### PR TITLE
Python: Fix inverted `subscriptUnknown` predicate.

### PR DESCRIPTION
**Pull request by tausbn**
This predicate is used to indicate whether we're likely to have full information
about subscripted values of the given kind of object. Thus, it doesn't hold for,
say, `SequenceObjectInternal`, but it _does_ hold for, say,
`UnknownInstanceInternal`.

For `BuiltinOpaqueObjectInternal`, we look at whether the underlying built-in
has items that can be accessed. Unfortunately, for whatever reason this check
was inverted: If there _were_ such items, we would say that subscripting was
unknown, and if there _weren't_, we would say that subscripting gave a known
result. The upshot of this was that subscripting would never work on these
objects.

Negating the body of the predicate was not a valid solution, as this would
induce a negative recursion, so I have split the getting of the built-in into
its own positive step, and the negation is only on the `getItem` call, which is
fine (it calls directly into the underlying extensional predicate).

I don't know whether anything has been affected by this bug -- most built-ins
aren't "opaque" by our definition, so probably this won't change much in terms
of results.

### CODE REVIEW

**Comment by RasmusWL** [comment]
Are we still awaiting evaluation on this one? :blush:

**Comment by tausbn** [comment]
Evaluation is up an running now.

**Comment by RasmusWL** [comment]
> It might be useful to add a comment inline about why the original implementation was subtly wrong, given that it was added without that error being obvious to the author or previous reviewers.

For _me_, it was clear what was wrong when looking at the code. How did you feel about it? If you had no problem, I don't think we need a comment. If you had to spend a bit of time understand why the old one was broken and the new one wasn't, that's totally fine, and a great argument for adding a comment! Just say so :wink:

**Comment by tausbn** [comment]
I'm not sure adding a comment saying "there used to be a missing `not` here, and this broke the predicate" is terribly useful.

What _would_ probably be useful, however, is a comment explaining why it's not simply `not exists(this.getBuiltin().getItem(_))`, in case someone feels like "cleaning up" this bit of code in the future.

I'll add that comment. :slightly_smiling_face:

**Comment by tausbn** [comment]
Dist-compare report here: https://git.semmle.com/gist/taus/a79a401c849d9bceae19316359507ec6

**Comment by RasmusWL** [comment]
Can you explain the results that are shown as removed in the dist-compare? To me they look like real alerts. A common pattern is that they all use `sys.argv[1]`.

I think it's a bit curious that no tests were affected by this, and I'm starting to wonder if this change will change the results of any query _for the better_?

Not saying we should never merge this, but would be great to fully understand what's going on here :smile: maybe you can add some tests with `sys.argv` and see the results before/after adding this change? (uh, that sounds like rebasing and force pushing, which I think is fine in this instance).

**Comment by tausbn** [comment]
Hmm... Yeah, some of the results look a bit curious, but none of them strike me as true positives. Am I misreading them somehow?
(I guess the real question is: why are they not still false negatives. I'll have to investigate that further before I can answer it.)

**Comment by RasmusWL** [comment]
They all looked like TPs from my point of view. 

For [the first one](https://github.com/python/cpython/blob/8ec7cb53f0705509bac20c96d19fdbd9baec0cb2/Tools/freeze/makeconfig.py#L47), if `outfp = open(sys.argv[2], 'w')` (line 51) fails due to the file not being found (or not having the correct permissions), the file `infp` will not be closed. I (as a human), can see that this code is probably only used for testing locally, so this is probably not the most important alert ever, but I think it's still a TP?

**Comment by tausbn** [comment]
Ah, you're right, and I understand the nature of the TP now. I wonder if what we're seeing here is the limited nature of our modelling of exceptions. (After all, absolutely _anything_ may end up throwing an exception.) In particular, we may not consider `open` to be a potential source of exceptions.

**Pull request closed without merging**
