### PR TITLE
Java/C#: Introduce kind for neutrals.

### PR DESCRIPTION
**Pull request by michaelnebel**
In this PR we introduce a *kind* for neutrals.

The *kind* of a neutral is used to describe, whether the neutral is neutral with respect to
- `summary`: They neutral does not have flow through it (ie. no summary flow).
- `source`: The neutral is not a source (of any source kind).
- `sink`: The neutral is not a sink (of any sink kind).

### CODE REVIEW

**Comment by michaelnebel** [comment]
DCA looks good.

**Review by jcogs33 — COMMENTED** [review]
I added a few minor suggestions about updating comments, otherwise looks reasonable to me.

**Comment by michaelnebel** [comment]
> I added a few minor suggestions about updating comments, otherwise looks reasonable to me.
Thank you very much!!

**Review by hvitved — DISMISSED** [review]
LGTM

**Review by hvitved — APPROVED** [review]

**Pull request merged**
