### PR TITLE
QL: allow getURL as an acronym

### PR DESCRIPTION
**Pull request by erik-krogh**
`getURL` is a language feature, so it should be allowed as an upper-case acronym.

### CODE REVIEW

**Review by nickrolfe — APPROVED** [review]
Makes sense.

**Review by kaeluka — APPROVED** [review]
Strictly speaking, that change means that users can write their own `getURL` methods (right?), but this implementation still seems to strike a good balance between precision and complexity.

**Comment by MathiasVP** [comment]
> Strictly speaking, that change means that users can write their own `getURL` methods (right?), but this implementation still seems to strike a good balance between precision and complexity.

People _can_ write their own getURL predicate, yes. See https://codeql.github.com/docs/writing-codeql-queries/providing-locations-in-codeql-queries/#providing-urls.

**Comment by erik-krogh** [comment]
> Strictly speaking, that change means that users can write their own `getURL` methods (right?), but this implementation still seems to strike a good balance between precision and complexity.

Yes, and that was always the case, now they just don't get a warning when they do it.  

[The `getURL` predicate is special at the language level](https://codeql.github.com/docs/writing-codeql-queries/providing-locations-in-codeql-queries/#providing-urls).  
So sometimes it's the right name to use, even if the name doesn't follow our style-guide.  

I got some FPs due to that in [another PR](https://github.com/github/codeql/pull/10592), so that's why I'm doing this PR.

**Pull request merged**
