### PR TITLE
Python: Mention more sanitisation options in py/url-redirection qhelp.

### PR DESCRIPTION
**Pull request by max-schaefer**
/cc @erik-krogh

### CODE REVIEW

**Review by erik-krogh — COMMENTED** [review]
LGTM.  

But we could use a non-django example for how to check for missing hostname.

**Comment by max-schaefer** [comment]
Agreed in principle, but (as far as I can see) at the moment the query only recognises this one particular sanitiser, so if we suggest another one it wouldn't actually make the alert go away. I have raised https://github.com/github/codeql/issues/15178 to discuss this further.

**Review by tausbn — APPROVED** [review]
Looks reasonable to me. 👍

**Review by felicitymay — APPROVED** [review]
Thanks for taking the time to expand the documentation. Nothing to suggest here 💖

**Pull request merged**
