### PR TITLE
Python: Force read- and store steps to add nodes.

### PR DESCRIPTION
**Pull request by yoff**
This gives much nicer path explanations on some snapshots (all examples from sql injection):
[`g/owid/owid-grapher`](https://lgtm.com/projects/g/owid/owid-grapher)
before (note the direct jump from line 145 to line 253):
Screenshot 2020-11-27 at 11 10 39
after:
Screenshot 2020-11-27 at 11 10 27
[`g/sergiodctest/ex5`](https://lgtm.com/projects/g/sergiodctest/ex5)
before (first path goes `request` parameter -> use of `name`):
Screenshot 2020-11-27 at 11 12 15
after (`request` -> `name = request.POST.get('name', False)` -> use of `name`):
Screenshot 2020-11-27 at 11 10 08
It also makes a slight change to the "proper model" test, which looks fine in my opinion (from stepping through the paths, it is not that easy to see the changes from these screen shots):
before:
Screenshot 2020-11-27 at 11 47 23
after:
Screenshot 2020-11-27 at 11 49 51
It is achieved by making stepped-to nodes `CastNode`s. This seems somewhat reasonable as types then to change when we move between content and container. We could probably refine it, though.

### CODE REVIEW

**Comment by aschackmull** [comment]
This looks weird. Are your store steps and read steps also additional steps? Because they shouldn't be.

**Comment by yoff** [comment]
@aschackmull Thanks for looking, store steps are added to `defaultAdditionalTaintStep`, is that problematic?

**Comment by aschackmull** [comment]
It's not problematic as such, but I wouldn't expect that you'd want that by default. Maybe in an ad-hoc test query where you can tolerate more noise, but for default flow I'd expect that you'd want store-steps to line up with matching read-steps.

**Comment by RasmusWL** [comment]
I'm the one who added read and store steps to `defaultAdditionalTaintStep`, back when I just wanted taint-tracking to give results, and wasn't quite sure how anything worked. It was originally inspired by [this bit](https://github.com/github/codeql/blob/94deed39a2b44555af570e1b970d09b9f4e53b9b/csharp/ql/src/semmle/code/csharp/dataflow/internal/TaintTrackingPrivate.qll#L153-L159) from C#.

From @aschackmull it does sound like it's a bit of a hack :sweat_smile: 

While this PR does look to improve readability of our path explanations, it sounds a bit like we're paying the price for my hack (read/store steps in `defaultAdditionalTaintStep`) by using an other hack (considering read/store steps to be type-casts). 

@yoff how do you want to deal with this? is now a good time to clean up my hack? or is it more important to get this in now, and deal with the consequences later?

**Comment by aschackmull** [comment]
The C# snippet only includes read steps, and it doesn't even include all of them - only a suitably curated subset. There's a case to be made for adding some read steps as taint steps (if an entire object is tainted, then you may argue that its fields are also tainted), but if you include both read and store steps as taint steps then you will be certain to get false positives like this:
```
obj.foo = source()
sink(obj.bar)
```
with a false-positive flow sequence from `obj.foo` to `obj.bar`.

**Comment by yoff** [comment]
To be fair, it is accompanied with a comment suggesting the author was not entirely comfortable.

I would probably prefer to clean things up properly, we are out of rush-mode after all. But I would like to understand how this leads to nicer path explanations.

**Comment by aschackmull** [comment]
> how this leads to nicer path explanations

Read steps and store steps are not compressed, whereas ordinary local steps are compressed. What you see currently is a sequence of compressed local value steps and local taint steps, which happens because you've defined read and store steps to also be taint steps.

**Comment by yoff** [comment]
> Read steps and store steps are not compressed, whereas ordinary local steps are compressed. What you see currently is a sequence of compressed local value steps and local taint steps, which happens because you've defined read and store steps to also be taint steps.

Ah! Then it also makes sense why you would immediately think this PR weird :-)

**Comment by yoff** [comment]
Converting this to draft as we are currently pursuing a different route.

**Comment by yoff** [comment]
Converting from draft, as we are currently leaning towards this as a stop-gap measure.

**Review by RasmusWL — CHANGES_REQUESTED** [review]
I would like a comment explaining _why_ we need this, and the fact that this is sort of a hack.
It should also mention when we expect to be able to remove it again (when we are doing proper flow-summary taint modeling).

**Comment by yoff** [comment]
I added the no-change-note-required label. While this is a reasonably big user-experience change, I am not sure how much we want to commit to it yet, due to its wacky nature...

**Review by tausbn — APPROVED** [review]
Let's get it in for now, as agreed.

**Review by RasmusWL — APPROVED** [review]
Thanks for adding that comment... now, let the merge conflicts commence! (since expected output of a ported data-flow query currently in a PR won't be correct anymore)

**Pull request merged**
