### PR TITLE
C++: For unnamed local variable declaration entries consider the name of the variable

### PR DESCRIPTION
**Pull request by jketema**

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
So happy that, for once, this wasn't a dataflow issue 😂

**Comment by jketema** [comment]
> So happy that, for once, this wasn't a dataflow issue 😂

It's technically an extractor issue, but also very hard to fix in the extractor.

**Comment by jketema** [comment]
I've opened an internal PR to fix the remaining test.

**Review by MathiasVP — APPROVED** [review]
LGTM if DCA is happy!

**Pull request merged**
