### PR TITLE
JS: Cache moduleImport and simplify PathExpr hierarchy

### PR DESCRIPTION
**Pull request by asgerf**
This fixes another join ordering issue I encountered in the `SharedTaintStep` work, but is beneficial on its own.

Evaluations:
- [Security/smoke-test](https://git.semmle.com/asger/dist-compare-reports/tree/js/cache-module-import_1589392195566)
- [XSS/big-apps](https://git.semmle.com/asger/dist-compare-reports/tree/js/cache-module-import_1589442550086)
- Update: [XSS/nightly](https://git.semmle.com/asger/dist-compare-reports/tree/js/cache-module-import_1589471570321)

### CODE REVIEW

**Comment by asgerf** [comment]
> I suppose PathExprInModule will be made private after being deprecated for a while, or is it entirely redundant?

There are no internal uses of it if that's what you mean. It can be removed after a few cycles.

**Comment by esbena** [comment]
I mean that is still contributes to `PathExpr`, so my question is if that contribution is redundant.

**Comment by asgerf** [comment]
> I mean that is still contributes to PathExpr, so my question is if that contribution is redundant.

Ah, `PathExprInModule` is (still) abstract, and without any subclasses of its own, it contributes nothing.

**Comment by esbena** [comment]
Doh. I missed that keyword. All good then.

**Pull request merged**
