### PR TITLE
Python: Use `LocalSourceNode` in `StepSummary::step`

### PR DESCRIPTION
**Pull request by tausbn**
Does what it says above. We now step directly between `LocalSourceNode`s in type tracking. This should result in a smaller `step` relation, and better performance.

Reviewing per-commit is highly recommended.

### CODE REVIEW

**Review by yoff — COMMENTED** [review]
Great to see the fruits of the refactor. Happy to merge once performance is confirmed.

**Comment by tausbn** [comment]
Surprisingly, this didn't have a _huge_ impact on performance, but it seems to be an improvement nonetheless: https://github.com/dsp-testing/tausbn-dca/issues/19

**Comment by yoff** [comment]
Hm, interesting, I would have hoped for more. In any case, the improvement in readability _is_ huge.. :)

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
