### PR TITLE
Shared: Do not use `@kind graph` for CFG test output

### PR DESCRIPTION
**Pull request by hvitved**
The original motivation for using `@kind graph` was to be able to visualize CFGs in VS Code. However, now that we have `View CFG`, this is no longer needed. Moreover, `@kind graph` often has spurious reorderings of the output, and there are some known limitations (such as missing multi-edges, IIRC), so it is not well suited for qltest.

### CODE REVIEW

**Review by michaelnebel — APPROVED** [review]
C# LGTM!

**Review by redsun82 — APPROVED** [review]
Seems reasonable, thanks for jumping on that!

The only comment I have is that the expected files remain somewhat hard to check for a human (more or less as before). But small diffs (as will usually be the case in a PR) are probably manageable.

**Comment by hvitved** [comment]
> The only comment I have is that the expected files remain somewhat hard to check for a human (more or less as before). But small diffs (as will usually be the case in a PR) are probably manageable.

Diffs are, IMO, easier to check in the non-`@kind graph` format.

**Comment by redsun82** [comment]
> > The only comment I have is that the expected files remain somewhat hard to check for a human (more or less as before). But small diffs (as will usually be the case in a PR) are probably manageable.
> 
> Diffs are, IMO, easier to check in the non-`@kind graph` format.

I agree that typical PRs are probably easier to review now. The full expected file though remains pretty much imperscrutable :sweat_smile:

**Pull request merged**
