### PR TITLE
C++: Update auto-builder nuget packages

### PR DESCRIPTION
**Pull request by hvitved**
https://github.com/github/codeql/pull/11266 follow-up.

### CODE REVIEW

**Review by michaelnebel — APPROVED** [review]
Looks good to me!

**Review by michaelnebel — APPROVED** [review]
LGTM

**Comment by michaelnebel** [comment]
@hvitved : Was it technically required to downgrade the `Microsoft.Build` NuGet package?

**Comment by hvitved** [comment]
> Was it technically required to downgrade the `Microsoft.Build` NuGet package?

17.4.0 does not officially support .NET 6 (it supports .NET 7), so I downgraded it to avoid warnings.

**Pull request merged**
