### PR TITLE
Data flow: Performance tuning

### PR DESCRIPTION
**Pull request by aschackmull**
This is a sequence of smaller performance tweaks (commit-by-commit review is encouraged). All of them relate to reducing work by avoiding splits of the tuple stream in the main recursive pipelines. Either by making sure negations are simple anti-joins (thereby also avoiding materialisation) or by avoiding tuple duplication arising from disjunctive filters.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM if DCA is happy! I'm curious about the performance implications of removing disjunction-induced tuple duplication. (Could we have a ql-for-ql query for this?)

**Review by hvitved — APPROVED** [review]
LGTM

**Review by atorralba — APPROVED** [review]
FWIW, LGTM

**Review by RasmusWL — APPROVED** [review]
:+1: from Python (after also talking through what some of the changes do :+1:)

**Pull request merged**
