### PR TITLE
Python: Fix a few performance issues.

### PR DESCRIPTION
**Pull request by tausbn**
See commit messages for more information. 

Needs performance evaluation (obviously).

Does not need a change note.

### CODE REVIEW

**Comment by tausbn** [comment]
Performance is looking promising: https://github.com/dsp-testing/tausbn-dca/issues/45

**Comment by tausbn** [comment]
And here's a different performance comparison that really shows the improvement for the queries surrounding sensitive data: https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/619/

**Review by RasmusWL — COMMENTED** [review]
I think it would be nice to highlight what the alternative to the new performance optimized `sensitiveString` would have been, but otherwise LGTM :+1:

**Comment by tausbn** [comment]
Good suggestion! :+1:

**Review by RasmusWL — APPROVED** [review]

**Pull request merged**
