### PR TITLE
C++: Taint flow to formatting function return values.

### PR DESCRIPTION
**Pull request by geoffw0**
Strictly speaking, taint should flow from a tainted argument to a formatting function such as `sprintf` to the return value (the number of characters written / error code).  This is much less important than the existing flow to the output parameter, but could conceivably come up as allowing a user to control the size of an allocation or something like that.

This is consistent with how we handle `strftime` (the only similar case I could find) and is the final part of https://jira.semmle.com/browse/CPP-466 (which I am keen to close).

The new test results in `format.cpp` are on lines that look like this:
```
sink(mysprintf(buffer, 256, "%s", string::source()));
```

### CODE REVIEW

**Comment by jbj** [comment]
Isn't the return value of `sprintf` very similar to the return value of `strlen`? And problematic for the same reasons. We might want this taint step in `DefaultTaintTracking` for the sake of backwards compatibility, but I'm less keen on adding it to `models` so all taint libraries have it.

I know I change my opinion about what _taint_ means about once per month, but it's currently this: _a tainted expression can be influenced by an attacker to have unusual values._ An unusual value for an integer is almost never the length of a string.

**Comment by geoffw0** [comment]
> a tainted expression can be influenced by an attacker to have unusual values.

I like this definition.  'unusual' is a bit open to interpretation, but it captures the idea that booleans and things like string lengths don't necessarily need to be considered tainted just because they're computed from things that are.

The old security taint tracking library did consider these return values tainted, but I don't think it was an important detail in practice (real world or samate tests, for example).  The change was motivated by consistency with the old code and our handling of `strftime`.  I'll:
 - close this PR
 - open another one to deal with `strftime` instead
 - close https://jira.semmle.com/browse/CPP-466 (all other parts already resolved)
 - look for somewhere suitable in our QLDoc to state your definition of taint (at least until someone comes up with a better one)

**Comment by geoffw0** [comment]
Do you think taint should flow through `strlen` in the models library?  (it currently does)

**Comment by geoffw0** [comment]
Closed in favour of https://github.com/github/codeql/pull/3569.

**Comment by jbj** [comment]
> Do you think taint should flow through `strlen` in the models library? (it currently does)

No, I don't think it should. Right now it's excluded in `DefaultTaintTracking.qll`, but I'd rather have it excluded in `PureStrFunction.hasTaintFlow` so the exclusion also reaches `semmle.code.cpp.ir.dataflow.TaintTracking`.

**Comment by geoffw0** [comment]
I'm slightly cautious because I don't want to port every hack from the old taint tracking library to the new one, but I agree.  I'll make a PR for that change as well.

**Comment by geoffw0** [comment]
The `strlen` PR: https://github.com/github/codeql/pull/3592

**Pull request closed without merging**
