### PR TITLE
C++: Add `cpp/invalid-pointer-deref` FP test case

### PR DESCRIPTION
**Pull request by jketema**
Test case shows that the store may occur before the pointer update, and the number of indirections still seem to be off-by-one 😕 

Also make the formatting in the test file more uniform while we're here.

### CODE REVIEW

**Comment by jketema** [comment]
I've added a second test case. The first is cut down from the asn1 library we've had more issues with (the gift that keeps on giving it seems). The second test case is reduced from redis and is the cause of about 500 FPs on that project alone.

For the second test case it looks like we're not handling `++` correctly when it occurs as a suffix? I'll have a look at the IR for it.

**Comment by jketema** [comment]
>  I'll have a look at the IR for it.

IR definitely looks wrong, doing the addition before the load.

```
# 1920|     r1920_1(glval<int>)    = VariableAddress[val] : 
# 1920|     r1920_2(glval<char *>) = VariableAddress[xs]  : 
# 1920|     r1920_3(char *)        = Load[xs]             : &:r1920_2, ~m?
# 1920|     r1920_4(int)           = Constant[1]          : 
# 1920|     r1920_5(char *)        = PointerAdd[1]        : r1920_3, r1920_4
# 1920|     mu1920_6(char *)       = Store[xs]            : &:r1920_2, r1920_5
# 1920|     r1920_7(char *)        = CopyValue            : r1920_3
# 1920|     r1920_8(char)          = Load[?]              : &:r1920_7, ~m?
# 1920|     r1920_9(int)           = Convert              : r1920_8
# 1920|     mu1920_10(int)         = Store[val]           : &:r1920_1, r1920_9
```

**Comment by MathiasVP** [comment]
Hmm, yeah that's weird. I can't quite see how post-fix increments should throw anything off, but it looks like it is 🤔.

**Review by MathiasVP — APPROVED** [review]
LGTM!

**Pull request merged**
