### PR TITLE
various QL-for-QL fixes

### PR DESCRIPTION
**Pull request by erik-krogh**
The first 4 commits were written automatically by my patching tool

### CODE REVIEW

**Review by aschackmull — DISMISSED** [review]
LGTM. Although I wonder whether the import-removals are based on the import being unused or merely superfluous due to being transitively imported. In the latter case the proper fix was probably to remove the transitive import by making more imports private.

**Review by geoffw0 — APPROVED** [review]
C/C++ LGTM.

**Review by RasmusWL — DISMISSED** [review]
Python :+1:

**Comment by erik-krogh** [comment]
> LGTM. Although I wonder whether the import-removals are based on the import being unused or merely superfluous due to being transitively imported. In the latter case the proper fix was probably to remove the transitive import by making more imports private.

It's the latter. The query looks for imports that have already been transitively imported by an earlier import  (only 1 level down).

**Comment by aschackmull** [comment]
> It's the latter. The query looks for imports that have already been transitively imported by an earlier import (only 1 level down).

Then I think I mildly disagree with the QL style that that query pushes towards. I'd rather have a QL-for-QL query that made those imports relevant by making the transitive imports private.

**Comment by erik-krogh** [comment]
> Then I think I mildly disagree with the QL style that that query pushes towards. I'd rather have a QL-for-QL query that made those imports relevant by making the transitive imports private.

I'll look into that and update this PR.

**Review by aschackmull — DISMISSED** [review]

**Review by smowton — DISMISSED** [review]
Go lgtm

**Comment by erik-krogh** [comment]
> > Then I think I mildly disagree with the QL style that that query pushes towards. I'd rather have a QL-for-QL query that made those imports relevant by making the transitive imports private.
> 
> I'll look into that and update this PR.

@aschackmull: Making the transitive imports private changes behaviour because some code relied on those imports being public.   
The [last commit](https://github.com/github/codeql/pull/10076/commits/4bc10f9b5c9489c5d7b19503468afc91af0eafd3) was required to things to compile again.  
I don't think there's a way to make those public imports deprecated without introducing a deprecation warning.   
This change will definitely require a change-note.   

But do you want this? Or should I just revert the changing of imports in `java/`?  
I'm leaning towards the latter.

**Comment by aschackmull** [comment]
> Or should I just revert the changing of imports in `java/`?

That's fine (do leave the changes+revert in the commit history, though). Cc @atorralba in case you want to cherry-pick some of these changes into a separate PR.

**Review by aschackmull — APPROVED** [review]

**Pull request merged**
