### PR TITLE
Packaging: Refactor cpp libraries

### PR DESCRIPTION
**Pull request by aeisenberg**
This PR separates the core cpp packs into `codeql/cpp-queries` and
`codeql/cpp-all`.

There are very few lines of code changed. Almost all changes are moving
files around.

### CODE REVIEW

**Comment by rdmarsh2** [comment]
It looks like a handful of files under  csharp/ql/lib/semmle/code/csharp/frameworks/system/data/ were accidentally committed

**Comment by aeisenberg** [comment]
Thanks. You're right. Let me remove them.

**Review by dbartol — DISMISSED** [review]
LGTM.

Once we have all languages refactored, we should probably make a sweep through the whole repo to ensure that all uses of the old pack names (`codeql-cpp`, etc.) are gone, as well as all uses of `libraryPathDependencies`.

**Comment by aeisenberg** [comment]
Yes, I was trying to make the smallest change possible at first. And we can complete the changes later.

**Review by dbartol — APPROVED** [review]
Still LGTM

**Comment by adityasharad** [comment]
All checks have passed on this PR except `Checks` (known bug when using non-`main` branches) and `QLDoc Checks` (expected to fail since we are moving libraries around). The tests have all passed on the corresponding internal PR. Merging.

**Pull request merged**
