### PR TITLE
Go: extractor/objecttypes consistency generics

### PR DESCRIPTION
**Pull request by owen-mc**

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Looks plausible

**Comment by smowton** [comment]
Recommend DCA including some projects known to use generics to check for alert differences

**Comment by owen-mc** [comment]
Yes, we definitely need to make sure that the checks won't just cause us to stop in the middle of extraction. I did MRVA on `go/ql/test/library-tests/semmle/go/Function/GenericFunctionInstantiationExpr.ql` to get a list of repos for DCA. Unfortunately DCA is down at the moment.

**Comment by owen-mc** [comment]
DCA looked fine.

**Pull request merged**
