### PR TITLE
Python: Port `py/request-without-cert-validation` to use API graphs

### PR DESCRIPTION
**Pull request by RasmusWL**
For my reviewer: I'm don't feel like this should require adding a change note, but happy to do so if you think that's better :blush: (so didn't add the `no-change-note-required` label to the PR yet)

### CODE REVIEW

**Comment by RasmusWL** [comment]
I started a performance run on our usual set of projects for this PR. I could have looked at projects that had results for this query, but I really think the part that would have had the highest risk of causing problems is the type tracker of falsey values, which is tested fine on other projects. I guess I could have made that a back-tracker instead of a forwards tracker, but it felt more easy to do it this way :shrug: (let me know if you think that needs to be changed)

**Comment by RasmusWL** [comment]
Performance looked a bit worrysome, so trying to use backtracker instead :+1:

**Comment by RasmusWL** [comment]
> Performance looked a bit worrysome, so trying to use backtracker instead

As we discussed offline, I confused myself on this bit. Since I only ran the old/new version of this query, for the new query we also have to pay the price for the all of the stages involving the new data-flow library, type-tracking, and api-graphs. So that's probably where the extra time is spent, and not because of bad implementation of this query.

That also explains why using a back-tracker did not yield substantial performance gains (although it should help with performance, and is the right approach overall... and also ended up looking nicer)

**Review by yoff — APPROVED** [review]
Code looks great, I agree about no change note needed. Do you want to run a performance test with more queries to check performance? I am not sure that we can force another query to be evaluated before this one, but the order is largely consistent, so you could add one that usually gets evaluated first?

**Comment by RasmusWL** [comment]
> Code looks great, I agree about no change note needed. Do you want to run a performance test with more queries to check performance? I am not sure that we can force another query to be evaluated before this one, but the order is largely consistent, so you could add one that usually gets evaluated first?

No, I'm feel very confident that nothing is wrong here. Will try to remember to run such queries _in addition_ some other query next time.

**Pull request merged**
