### PR TITLE
Move upgrades into standard library packs

### PR DESCRIPTION
**Pull request by dbartol**
This PR moves the upgrade scripts for C#, C++, Java, JavaScript, and Python into the corresponding standard library packs (the same pack that contains the dbscheme).

Having upgrades in a separate pack gives us little or no advantage, and increases the overhead of package management. We wind up with the standard library (say, `codeql/cpp-all`) depending on another library pack (`codeql/cpp-upgrades`), but the version number of that dependency always needs to be kept in sync with the version number of the upgrade pack. In addition, no other pack for that language would have any reason to declare a dependency on the upgrade pack, so no query pack would ever have a reason to depend on a version of the upgrade pack other than the one that was published at the same time as that version of the library pack. By simply merging the packs we ensure that the right upgrade scripts are always available without having to keep two package versions in sync.

The actual changes were as follows:
- Moved contents of `<lang>/upgrades` to `<lang>/ql/lib/upgrades` verbatim.
- Added `upgrades: upgrades` property to `qlpack.yml` for each standard library pack.
- Deleted `qlpack*.yml` for upgrade packs.
- Removed from each standard library pack the declared dependency on the now-deleted upgrade pack.

The corresponding internal PR fixes up the build system to handle the change.

Note that Ruby already put its upgrades in its standard library.

I have not yet applied the same change to Go. I'll do that in a follow-up PR to avoid having three PRs that need to be merged simultaneously.

### CODE REVIEW

**Comment by aeisenberg** [comment]
This looks fine by me, though I think we need to get some eyes from the languages team on this before merging. 

It would be very nice if we could avoid having the language server try to reconcile any `.ql` files in upgrades folders since they will fail compilation anyway. This was always the case, but because upgrades were in a separate pack before, it was less tempting to click on them. Not sure the best way we can implement this.

**Comment by asgerf** [comment]
> It would be very nice if we could avoid having the language server try to reconcile any .ql files in upgrades folders since they will fail compilation anyway. This was always the case, but because upgrades were in a separate pack before, it was less tempting to click on them. Not sure the best way we can implement this.

@aeisenberg  Could the language server simply treat `upgrade.properties` as a qlpack file with the contents:
```
database: old.dbscheme
```

**Comment by dbartol** [comment]
Does the language server issue only happen if the user opens a `.ql` file from an upgrade, or does it cause a problem if the user opens any file in the pack that contains upgrades?

**Comment by aeisenberg** [comment]
It only happens in the specific file you open.

**Comment by aeisenberg** [comment]
@asgerf 

> Could the language server simply treat upgrade.properties as a qlpack file with the contents:

I'm sure it's possible to do this. I'm not sure how much effort would be involved or if it would be worth it since these scripts are usually write-only. From your perspective how often do you find that you have to interact with upgrade scripts?

**Comment by dbartol** [comment]
If the issue only happens when opening an upgrade file, I'd prefer that it not block this PR.

**Comment by aeisenberg** [comment]
It will have to be implemented separately. This requires a change to the language server.

**Comment by dbartol** [comment]
> It will have to be implemented separately. This requires a change to the language server.

Right, I meant "not block this PR or the `semmle-code` PR that goes with it, the latter in which we could conceivably change the language server to fix the issue."

**Review by asgerf — COMMENTED** [review]
I'm not sure who is expected to review this; but I just want to say that it LGTM from my perspective, and I don't think the language server issue is a problem if it only happens when you open the file.

**Comment by aeisenberg** [comment]
Thanks for the review, @asgerf. I think having buy-in from the static or dynamic languages teams is important. And I will make sure to do any subsequent reviews.

**Comment by aeisenberg** [comment]
I'm taking over this PR.

**Comment by aeisenberg** [comment]
Closing this PR in favour of https://github.com/github/codeql/pull/7355, since it's harder for me to work with a fork.

**Pull request closed without merging**
