### PR TITLE
C#: CIL and Dotnet cleanup (removal).

### PR DESCRIPTION
**Pull request by michaelnebel**
This is the *last* PR related to CIL deprecation/deletion.
In this PR we remove all CIL related tables and CIL related parts of the QL library.

### CODE REVIEW

**Comment by michaelnebel** [comment]
DCA looks good!

**Comment by michaelnebel** [comment]
@hvitved @tamasvajk : How long do you we have to wait before deleting all the CIL tables and deprecated predicates (I will add a reminder to revive this PR at that point in time)?

**Comment by hvitved** [comment]
> @hvitved @tamasvajk : How long do you we have to wait before deleting all the CIL tables and deprecated predicates (I will add a reminder to revive this PR at that point in time)?

I find it extremely unlikely that anybody uses the `Dotnet`/`Cil` QL layer, so 6 months should be sufficient.

**Comment by michaelnebel** [comment]
DCA looks good!

**Review by hvitved — APPROVED** [review]
Yay 🎉

**Pull request merged**
