### PR TITLE
Added Workflow.getName and Step.GetId

### PR DESCRIPTION
**Pull request by henti**
Resolves https://github.com/github/codeql-core/issues/2528 and extends for future work.

### CODE REVIEW

**Review by asgerf — DISMISSED** [review]
LGTM from JS

**Review by henrymercer — APPROVED** [review]
LGTM.  Couple of very minor QLDoc suggestions.

**Comment by henti** [comment]
> LGTM. Couple of very minor QLDoc suggestions.

I've applied the suggestions. 

Thank you both :)

**Review by henrymercer — APPROVED** [review]
Reapproving per audit requirements

**Pull request merged**
