### PR TITLE
Dataflow: Add support for not skipping configuration-specific nodes in big-step

### PR DESCRIPTION
**Pull request by aschackmull**
fixes https://github.com/github/codeql-team/issues/2191

### CODE REVIEW

**Comment by owen-mc** [comment]
For a flow config using the new API (ConfigSig and so on) that does what I was expecting. I was a bit surprised that it didn’t do anything for old-style configuration classes. I guess it’s not important, as everything will move over to the new API in time.

**Comment by aschackmull** [comment]
The C/C++ XXE query gets a bunch of additional steps due to its
```
  predicate isAdditionalFlowStep(
    DataFlow::Node node1, FlowState state1, DataFlow::Node node2, FlowState state2
  ) {
    // create additional flow steps for `XxeFlowStateTransformer`s
    state2 = node2.asIndirectExpr().(XxeFlowStateTransformer).transform(state1) and
    DataFlow::simpleLocalFlowStep(node1, node2)
  }
```
Is that desirable? Or should we add a `predicate neverSkip(Node node) { none() }` in the XXE config?

**Review by owen-mc — DISMISSED** [review]
Go 👍🏻

**Review by MathiasVP — APPROVED** [review]
C++/Swift 👍

**Comment by MathiasVP** [comment]
> The C/C++ XXE query gets a bunch of additional steps due to its
> 
> ```
>   predicate isAdditionalFlowStep(
>     DataFlow::Node node1, FlowState state1, DataFlow::Node node2, FlowState state2
>   ) {
>     // create additional flow steps for `XxeFlowStateTransformer`s
>     state2 = node2.asIndirectExpr().(XxeFlowStateTransformer).transform(state1) and
>     DataFlow::simpleLocalFlowStep(node1, node2)
>   }
> ```
> 
> Is that desirable? Or should we add a `predicate neverSkip(Node node) { none() }` in the XXE config?
> 
> Edit: There are also a bunch of other queries with additional steps where we might also want to consider whether or not to use the new default that this PR introduces.

We resolved this on Slack and decided to add a `neverSkip` override (see 8a71408b60d4607f490042fca14cc13c70fb3e08).

**Review by owen-mc — APPROVED** [review]
Go 👍🏻 (but I think you should add a change note to let users know about the new feature)

**Review by yoff — DISMISSED** [review]
Python 👍

**Review by MathiasVP — DISMISSED** [review]

**Review by owen-mc — APPROVED** [review]
Go 👍🏻

**Comment by aschackmull** [comment]
One C/C++ query changed on main, so I had to rebase and add a commit to update its `.expected` file.

**Review by owen-mc — APPROVED** [review]
Go 👍🏻

**Review by MathiasVP — APPROVED** [review]
Still LGTM!

**Comment by aschackmull** [comment]
🚀

**Pull request merged**
