### PR TITLE
C++: Add IR test that shows dataflow regression after frontend update

### PR DESCRIPTION
**Pull request by jketema**

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
This LGTM! But should we maybe put this into the dataflow test folder as well?

**Comment by jketema** [comment]
> This LGTM! But should we maybe put this into the dataflow test folder as well?

This is literally one of the dataflow tests 😄

**Comment by jketema** [comment]
For reference https://github.com/github/codeql/blob/2b3cab355dd79b15f0ba9239a296baab65606ccd/cpp/ql/test/library-tests/dataflow/dataflow-tests/example.c#L24-L26

**Comment by MathiasVP** [comment]
Oh! I thought this was a new and evil test that you somehow crafted 😂. Yay for our tests then!

**Pull request merged**
