### PR TITLE
Update all pack versions to `1.0.0`

### PR DESCRIPTION
**Pull request by dbartol**
This PR updates the version numbers of all of our packs to `1.0.0`, in preparation for the CodeQL Packaging GA in CLI release 2.17.4.

### CODE REVIEW

**Comment by dbartol** [comment]
Test run of release prep [here](https://github.com/github/codeql/pull/16565). Everything looks good. The `codeql pack release` command correctly handles the manual version bump by setting the release version to the maximum of (current pack version) and (previous release version plus bump).

**Comment by aeisenberg** [comment]
I forgot where we came down on this, but do we want to add a changelog note to each pack describing why we are bumping to 1.0.0?

**Comment by dbartol** [comment]
Updated to add a change note to each pack explaining the bump to `1.0.0`. Sample release prep [here](https://github.com/github/codeql/pull/16583/files).

**Comment by aeisenberg** [comment]
Thanks. With the `category: breaking` metadata, would this make the next release step bump all versions to 2.0.0?

**Comment by dbartol** [comment]
@aeisenberg
>With the category: breaking metadata, would this make the next release step bump all versions to 2.0.0?

No (although that's exactly what I was worried about). `codeql pack release` computes the new version number by bumping the version number of the _previous_ release, and then uses either that or the _current_ version number, whichever is higher. So, for a pack that was last released as `0.9.1`, we get:

```
previousVersion = 0.9.1
bumpedVersion = 0.10.0  // 0.9.1, bumped for a breaking change, which bumps the minor version number because the major version number is 0
currentVersion = 1.0.0  // We removed the '-dev' suffix already
newVersion = 1.0.0  // max(0.10.0, 1.0.0)
```


`

**Review by aeisenberg — APPROVED** [review]
Awesome. LGTM. 

Since there's no rush, maybe keep this open for a couple of days to see if anyone on the languages team has any comments.

**Comment by dbartol** [comment]
I went ahead and merged it. The corresponding issue has been open for a week, and publicized on Slack, so I think we've had adequate opportunity for discussion.

**Pull request merged**
