### PR TITLE
Update CodeQL CLI docs articles and links to point to new location on GitHub Docs site

### PR DESCRIPTION
**Pull request by saritai**
Docs-content issue: https://github.com/github/docs-content/issues/6930

These updates are a follow up to migrating all the articles under "[Using the CodeQL CLI](https://codeql.github.com/docs/codeql-cli/using-the-codeql-cli/)" and "[CodeQL CLI reference](https://codeql.github.com/docs/codeql-cli/codeql-cli-reference/)" to the [GitHub Docs site](https://docs.github.com/en/code-security/codeql-cli). 

Changes in this PR: 
1. I've removed the content from these articles on the microsite that were migrated - and replaced it with a note that lets people know the article has been migrated and provides a link to the new location of the article. Also added mini-TOCs to each page that includes all the subsections and links to the new version of them. This allows users to quickly find a subsection they may have bookmarked! We can remove this eventually, especially once we start making changes to these articles. 
2. I have updated any links in other articles that linked to these CodeQL CLI articles to just point directly the new location of the article on the GitHub Docs site
3. Also ended up updating the CONTRIBUTING.md file and the READMEs from the `swift` and `go` directories to update some links in there to point to the new location on GitHub Docs, for convenience.

Looks like a number of reviewing groups will be pinged on this - but just know that all of the changes (outside the `codeql-cli` directory) are just updating links to point to GitHub Docs. 

cc @felicitymay @adityasharad

### CODE REVIEW

**Comment by adityasharad** [comment]
How will anchor links be handled? We sometimes provide customers with specific links to anchors/sections within the docs pages. As I understand this PR, following one of those anchored links will now take the reader to the overall page with a redirect notice, but no guidance on how to find the equivalent section in the new page.

**Comment by saritai** [comment]
@adityasharad Ah looks like I missed some of those that didn't have the path of the page they were from! We can definitely update that link to point directly to that anchor in the new article, as we kept the same headings as were in the original articles! Let me sweep through and try to find the rest of these anchor links I didn't get 👍

**Comment by saritai** [comment]
@adityasharad I think I got all the anchor links - there were only a few! I found all the anchor links in these migrated articles and searched for them across this repo. Thanks for the question, great catch! 🙇‍♀️

**Comment by adityasharad** [comment]
> @adityasharad I think I got all the anchor links - there were only a few! I found all the anchor links in these migrated articles and searched for them across this repo. Thanks for the question, great catch! 🙇‍♀️

Thanks, that looks like it covers the anchor links within the existing docs. Can we do anything more about existing anchor links that users attempt to access directly (e.g. if they recorded links in their own internal docs for reference)? Perhaps by keeping the table-of-contents list in the redirect pages, with redirect links to each section, rather than just a redirect link to the page as a whole?

**Review by owen-mc — APPROVED** [review]

**Review by felicitymay — COMMENTED** [review]
Thanks for finding and replacing all those links @saritai. I found one more that we should probably update.

Regarding the point about anchors that we've given to users that @adityasharad raises, I think it would be quite a lot of work to update each article with a "fake" TOC. I wonder if this is necessary because the articles on the docs site each have a mini-TOC so users ought to be able to identify the section they need fairly easily, assuming that the heading is an H2.

image

image

If we do decide that we need to do something for anchors that you use frequently, perhaps we can make a list of them so that we only add links for headings that are needed?

**Review by felicitymay — APPROVED** [review]
@saritai - thank you for taking the time to add the links to all the anchors in the new location. Hopefully that'll help users find their place easily.

I spot checked some of the TOC links and they all worked perfectly 👍🏻

**Review by adityasharad — APPROVED** [review]
Thank you!

**Comment by jketema** [comment]
I think this needs a merge back to main, as the post-release merge back has already happened.

**Pull request merged**
