### PR TITLE
C++: add some more range analysis tests

### PR DESCRIPTION
**Pull request by redsun82**
Add more covering for integer conversions and some unsigned bit manipulation.

### CODE REVIEW

**Comment by redsun82** [comment]
this is some more tests I wanted to add before I start work on github/codeql-c-team#751, guess it's small and self contained enough to already be merged

**Review by MathiasVP — DISMISSED** [review]
LGTM!

**Comment by redsun82** [comment]
sorry @MathiasVP , can you approve again? I fonud out I had forgot the `C++` tag in the commit :sweat_smile:

**Review by MathiasVP — APPROVED** [review]
Sure!

**Pull request merged**
