### PR TITLE
Add updated framework support for JS/Java

### PR DESCRIPTION
**Pull request by turbo**
This PR adds the newly supported JavaScript and Java libraries/frameworks to the documentation.

### CODE REVIEW

**Review by smowton — COMMENTED** [review]
Re: Java, there's also at least some support for:

Android 
Apache Camel
Gigaspaces
Google HTTP Client Library for Java
GSON
Google Web Toolkit
OCNI
JSF
Google Play
Ratpack
Castor
Cucumber
FastJson
Flexjson
Guice
HessianBurlap
JAXB
JYaml
Jabsorb
Jakarta JSON
Jodd JSON
Jakarta Mail
YamlBeans
jOOQ
Selenium

Probably among others, this is just from a quick run down the https://github.com/github/codeql/tree/main/java/ql/lib/semmle/code/java/frameworks directory

What's the threshold for mentioning something in this list? Are we deliberately sticking to only the best-known frameworks here, or only specifying frameworks where we have comprehensive support?

(cc @aschackmull @yo-h)

**Comment by turbo** [comment]
I've for now included the list explicitly mentioned in the (internal) release planning for GHES. IMO updating the list itself can/should be done in a separate PR that isn't an upstream requirement for the release, like this one 🙂

**Review by esbena — APPROVED** [review]
JS :+1:

**Comment by yo-h** [comment]
> What's the threshold for mentioning something in this list? Are we deliberately sticking to only the best-known frameworks here, or only specifying frameworks where we have comprehensive support?

I believe the intention was to only list the latter, but this list of supported frameworks is effectively deprecated and intended to be replaced by [the new generated list](https://github.com/github/codeql/blob/main/java/documentation/library-coverage/coverage.rst).

**Pull request merged**
