### PR TITLE
python: remove library annotation to clean up QL warnings.

### PR DESCRIPTION
**Pull request by yoff**
Should put these functions in a private module instead, as indicated by the documentation for `library`?

### CODE REVIEW

**Comment by RasmusWL** [comment]
Maybe this should be obvious, but what warnings are we getting for these? (and why?)

**Comment by tausbn** [comment]
> Maybe this should be obvious, but what warnings are we getting for these? (and why?)

There's a QL-for-QL query that checks for this presence of this annotation. The annotation itself is deprecated (though not to the degree that it actually emits a compiler warning).

**Comment by yoff** [comment]
I made it also remove the auto-generated annotations. There is a PR to not auto-generate those.

**Review by tausbn — APPROVED** [review]
Looks good to me. We might want to also fix up the QLDoc to get rid of those warnings.

**Pull request merged**
