### PR TITLE
Dataflow: add language-specific hook for breaking up big step relation

### PR DESCRIPTION
**Pull request by owen-mc**
Python and Ruby have been (ab)using `CastNode` to do this. Go now has a use-case as well, so I have made a proper language-specific hook.

### CODE REVIEW

**Review by aschackmull — COMMENTED** [review]
Looks reasonable to me. Only minor comment is that `flowCheckNodeSpecific` isn't a very good predicate name, I think. Perhaps `neverSkip`, `neverSuppress`, `neverHide`, or something like that would be better. The qldoc is also a little off since `FlowCheckNode` is a rather internal name and not really a good name to mean anything outside its small private context. Here's my alternative take on the qldoc:
```
Holds if `n` should never be skipped over in the `PathGraph` and in path explanations.
```
(And having just written that qldoc, I think I'm leaning towards `neverSkip` as the predicate name unless someone has a better suggestion.)

**Comment by smowton** [comment]
`neverSkip` is pretty vague if you don't know this has to do with path explanations. I don't have a good answer right now though.

**Comment by aschackmull** [comment]
> `neverSkip` is pretty vague if you don't know this has to do with path explanations. I don't have a good answer right now though.

`neverSkipInPath`, `neverSkipInPathGraph`, `includeInPath`, `includeInPathGraph`?

**Comment by owen-mc** [comment]
I've gone for `neverSkipInPathGraph`.

**Review by hvitved — APPROVED** [review]
LGTM

**Review by aschackmull — APPROVED** [review]

**Review by MathiasVP — APPROVED** [review]

**Review by yoff — APPROVED** [review]
Nice, thanks for doing this. Abused semantics is always a liability, so getting rid of that feels very good to me 👍

**Pull request merged**
