### PR TITLE
Move `tree-sitter-extrator` project to `ruby/extractor/codeql-extractor`.

### PR DESCRIPTION
**Pull request by criemen**
I investigated porting our ruby extractor build to bazel, and unfortunately, bazels `rules_rust` only support local dependencies inside a workspace, c.f. https://github.com/bazelbuild/rules_rust/issues/1525.

Therefore, to be able to build the ruby extractor with bazel, I had to move the `tree-sitter-extractor` project out of `shared/`, where it morally belongs, into the ruby extractor workspace. Alternatives considered:
- Provide a symlink from inside the workspace into `shared/`. This is possible, but due to the poor symlink support on Windows, it'd make working with the entire codeql repo on Windows more difficult. Our internal developers all (have to) have developer mode enabled, so that we can use symlinks in Bazel, but all external contributers on Windows would presumably run into trouble while cloning the repo. Imo, that's not acceptable.
- Fake an environment that looks like it's a workspace using advanced bazel magic. That's possible, but would make the build much harder to understand. In particular, bazel doesn't (easily) allow writing to the source tree, so this is not an easy/quick hack. It's important to me that the build system can be understood by non-bazel experts, so this isn't acceptable either.
- Fix the upstream issue. I don't have a good enough understanding of the issue or the code to do that.
- Drop the `Cargo.toml` for the ruby extractor, and model all dependencies only on the bazel side. This'd break IDE support, and the bazel<->cargo integration is actually quite good (besides its limitations), so I don't want to do that.

Out of all these alternatives, moving the shared code into the ruby workspace seemed the least bad option.
Note that this works, because we want to build the ruby language pack with bazel, but not the ql-for-ql one - for now, I don't see an advantage of porting that to bazel anyways, so it's okay that it's blocked from being ported to bazel right now.

I'm happy to discuss this change and alternatives further. If we agree that this is the way forward, then this needs to be merged together with a simple corresponding change in the internal repo.

### CODE REVIEW

**Comment by hmac** [comment]
Another alternative is presumably to publish `tree-sitter-extractor` on crates.io? Then it would be a normal dependency.

**Comment by aibaars** [comment]
What about other users of the shared extractor?

**Review by aibaars — CHANGES_REQUESTED** [review]
I don't think this is a good idea.

**Comment by criemen** [comment]
@hmac Ah yes, publishing it, or moving it to another public repo are other options.
I don't know about publishing at all, and moving it to another repo would presumably increase friction in the development process, and we'd have to go through another open-source procss (although light-weight).

@aibaars There are no other uses of the shared code so far, python doesn't use it, and we have (as of now) no other tree-sitter extractors.

**Comment by criemen** [comment]
After a long slack conversation with @aibaars , he came up with the idea of specifying the dependency on the shared extractor as `git` repo. Initial testing seems that this is working (it's just extremely slow, re-pinning the dependencies in bazel takes 5+min on my computer), but as this only has to happen on lockfile updates, I think that's acceptable.

I'll investigate this further, and if it doesn't work out, look at the crates.io and separate repo options instead of moving the extractor.
Thanks all for your input!

**Comment by tausbn** [comment]
> `@aibaars` There are no other uses of the shared code so far, python doesn't use it, and we have (as of now) no other tree-sitter extractors.

For future reference, QL-for-QL also uses it: https://github.com/github/codeql/blob/main/ql/extractor/Cargo.toml#L20

**Pull request closed without merging**
