### PR TITLE
Remove VulnerablePackage.ql

### PR DESCRIPTION
**Pull request by rneatherway**
This query seems to be made redundant by dependabot.

### CODE REVIEW

**Comment by calumgrant** [comment]
I agree that we certainly don't want to be running this query by default on GitHub as it just duplicates what we already have.

**Comment by calumgrant** [comment]
However, wouldn't it be better to turn the query off rather than to delete it entirely?

We could also think about improving the query by for example checking for uses of the vulnerable API in conjunction with the package version?

We also need a change note for lgtm.

**Comment by max-schaefer** [comment]
> We could also think about improving the query by for example checking for uses of the vulnerable API in conjunction with the package version?

We have an example of such a query for the special case of prototype pollution in JavaScript (https://github.com/github/codeql/blob/master/javascript/ql/src/Security/CWE-400/PrototypePollution.ql) and it is apparently massively popular with customers.

**Comment by rneatherway** [comment]
So it seems like adding an exclusion filter like https://github.com/github/codeql/blob/master/cpp/ql/src/codeql-suites/exclude-slow-queries.yml might be a good place to start? Would you prefer that?

**Comment by rneatherway** [comment]
As the less disruptive option I have opened https://github.com/github/codeql/pull/3736

**Pull request closed without merging**
