### PR TITLE
JS: recognize access to a req.query object through function calls

### PR DESCRIPTION
**Pull request by erik-krogh**
[Motivation one](https://github.com/iamhosseindhv/Rentaly/blob/c9193ac36f90236b8bd913228bb1d7186941ee09/routes/api.js#L181) and [motivation two](https://github.com/netbeast/dashboard/blob/a8690eb1ae1959ce3b339315d0559fea3fc4365c/src/helpers/resource.js#L41) (found using ATM). 

[Here are some new `RemoteFlowSource` we recognize](https://lgtm.com/query/8082025528011051369/). 

TODO:
 - [x] Add test
 - [x] Evaluation
 - [x] Check that [this](https://lgtm.com/query/8342915628539377335/) is empty.

### CODE REVIEW

**Comment by asgerf** [comment]
Two quick comments:
- `req.query` is also recognized `isUserControlledObject` predicate, where it differs from `params`. It's quite an important source for NoSQL injection so it seems worth handling as well.
- Maybe we should just treat `req.query` as the source, instead of `req.query.prop`? I'm not actually sure why we don't do that. (Feel free to ignore for this PR)

**Comment by erik-krogh** [comment]
> Maybe we should just treat req.query as the source, instead of req.query.prop? I'm not actually sure why we don't do that. (Feel free to ignore for this PR)

If we also do that for `"params"`, then there is no need for the type-tracking I introduced.

**Comment by erik-krogh** [comment]
> LGTM given a good evaluation. I'd be interesting to see `--metric TaintSources` for this.

[Evaluation](https://git.semmle.com/erik/dist-compare-reports/tree/profiling-js-asger.northeurope.cloudapp.azure.com_1593770201630).   
I think the performance gains are spurious.   
But it looks like there is no performance regression.

**Comment by erik-krogh** [comment]
@esbena  
This could use a review.

**Comment by esbena** [comment]
>  I'd be interesting to see --metric TaintSources for this.

That was a quite disappointing improvement. Happy to merge regardless.

**Pull request merged**
