### PR TITLE
Updated vulnerable XSS.java version

### PR DESCRIPTION
**Pull request by giper45**
According to @atorralba suggestion in issue #10395 , this PR updates the vulnerable XSS source code that works with the current query.

### CODE REVIEW

**Review by atorralba — COMMENTED** [review]
Hey @giper45 thank you for going ahead and fixing this! I added one minor suggestion (no need to use the expectation comment from the tests in the example).

**Comment by intrigus-lgtm** [comment]
Should https://github.com/github/codeql/blob/1c4488e7c854069cfd00a8604a63897d0a57ea2c/java/ql/src/Security/CWE/CWE-079/XSS.qhelp#L21 also be adjusted?

**Comment by giper45** [comment]
Yes, the response is written in the printStream, just remove the  "error"
string:

error page -> page


Il Mar 13 Set 2022, 16:21 intrigus-lgtm ***@***.***> ha
scritto:

**Comment by atorralba** [comment]
> Should
> 
> https://github.com/github/codeql/blob/1c4488e7c854069cfd00a8604a63897d0a57ea2c/java/ql/src/Security/CWE/CWE-079/XSS.qhelp#L21
>
> also be adjusted?

Good point @intrigus-lgtm, thanks! Fixed.

**Review by atorralba — APPROVED** [review]

**Pull request merged**
