### PR TITLE
C#: Update the Microsoft.NETCore.App stub

### PR DESCRIPTION
**Pull request by michaelnebel**
Before making any changes to the stub generator, we update the existing Microsoft.NETCore.App stub.

### CODE REVIEW

**Comment by michaelnebel** [comment]
@tamasvajk : Before making any other updates, I have just recreated the stubs using the python stub generator script.
All tests seems to pass and it almost looks like the only change is just some ordering of declarations.
Furthermore, I have tried to add the Microsoft.NETCore.App project reference in the options file in the FlowSummaries directory, but unfortunately there is compilation error (the first one is const declaration using System.Byte type not allowed). That is, it seems that the generated stub won't compile due to errors in the generated code (and not due to missing dependencies).
Is this anything you have played around with and know something about?  :-) All help and info is highly appreciated.

**Comment by tamasvajk** [comment]
@michaelnebel The member ordering change is a bit unfortunate. We have spent some time on making a stable order, but maybe that was introduces after this project was added.

Regarding the compilation error, could you please check if it still comes up if you add `semmle-extractor-options: /nostdlib /noconfig` to the options file, like [here](https://github.com/github/codeql/blob/main/csharp/ql/test/library-tests/frameworks/ServiceStack/options)?

**Comment by michaelnebel** [comment]
It turned out that there was a problem with mixing the use of stubs and referring explicitly to assemblies - so there was no problem with the stub itself.
Thank you for the suggestion 👍

**Comment by michaelnebel** [comment]
In any case, I would really like to merge this update of the stub as we might change the generator slightly and then it would be nice to see the changes of changing the generator without the noise of the rearrangement of the declarations.

**Review by tamasvajk — APPROVED** [review]
I haven't checked this line by line, but it LGTM.

**Pull request merged**
