### PR TITLE
C++: Further improvements to experimental query cpp/memory-leak-on-failed-call-to-realloc

### PR DESCRIPTION
**Pull request by geoffw0**
There's been some discussion on https://github.com/github/codeql/pull/4881 following https://github.com/github/codeql/pull/4979.  I said:

> I see what you mean, p_malloc contains a call to i_panic (which seems to call abort or exit) in the case of an allocation failure, but it's very different to the conditional termination of, say, an assert. I'll look into reintroducing some more of your constraints (but we're not very keen on keeping getStartLine and toString as in your original solution, both are problematic).

This PR narrows the exclusion, requiring that program termination be guarded by a condition that references the buffer.  For example:
```
buffer = realloc(buffer, ...); // realloc buffer
if (!buffer) // guard that references buffer
  abort(); // terminate
```
I believe this improves accuracy in the kinds of cases that have been discussed - see the two new test cases, and an LGTM query exploring when the three versions of this code differ: https://lgtm.com/query/5221953584618553467/ .

Thanks to @ihsinme for pointing out the weaknesses I'd introduced in my last iteration.

### CODE REVIEW

**Comment by ihsinme** [comment]
1.guard does a very good job of limiting the search. in subsequent PRs I will use it.
2. Analysis of your evaluator's performance shows. triggering of both scripts for example here. https://lgtm.com/projects/g/vim/vim/snapshot/46d19547ba6bc6b06ff1d5bf56a81869814e7444/files/src/misc1.c?sort=name&dir=ASC&mode=heatmap#L802
2.1. The first thing that catches your eye is the test cases you have already added to https://github.com/github/codeql/pull/4979 (using an old variable for intermediate storage of a pointer to the t_buf buffer), which I skipped when designing my request. Hopefully in the future you will add processing to them.
2.2. the second is a call to the function `vim_free (t_buf);`. which looks odd since it doesn't have calls to `abort()`  `exit()`.

**Comment by geoffw0** [comment]
> using an old variable for intermediate storage of a pointer to the t_buf buffer

We don't currently detect this pattern, that could be a future improvement.

> the second is a call to the function vim_free (t_buf);. which looks odd since it doesn't have calls to abort() exit().

I don't think the call to `vim_free` is causing the exclusion in this case, I think it's the call to `do_outofmem_msg` a few lines below.

**Comment by ihsinme** [comment]
> I don't think the call to `vim_free` is causing the exclusion in this case, I think it's the call to `do_outofmem_msg` a few lines below.

if so. then this solution is very good.

**Review by MathiasVP — APPROVED** [review]
LGTM!

**Pull request merged**
