### PR TITLE
C++: Use range analysis for maximum lengths of `%x` formats

### PR DESCRIPTION
**Pull request by rdmarsh2**

### CODE REVIEW

**Review by MathiasVP — COMMENTED** [review]
LGTM! I'd appreciate a DCA run on this before we merge it, though. This change will probably also conflict with https://github.com/github/codeql/pull/7386, but it shouldn't be difficult to fixup, I guess.

**Comment by redsun82** [comment]
I don't mind this getting merged before https://github.com/github/codeql/pull/7386, I can easily update that :+1:

Should we maybe open another issue to do the same for octal as well?

**Comment by MathiasVP** [comment]
We might as well. Then we can fix it once we find someone actually using octal formats 😄.

**Comment by MathiasVP** [comment]
> LGTM. I think this deserves a change note.

We didn't add one for the [base-10 case](https://github.com/github/codeql/pull/7063), though. But I guess we can add a change note saying "we did this for both base-10 and base-16".

**Review by redsun82 — APPROVED** [review]
:ship:

**Pull request merged**
