### PR TITLE
Data flow: Further pruning based on `read` column of `nodeCand2()` predicate

### PR DESCRIPTION
**Pull request by hvitved**
We were missing out on additional pruning in `flowCandFwd()`, because we ignored the `read` column of `nodeCand2()`. 

### C# tuple counts

Ran [this](https://gist.github.com/hvitved/ac1e68269d9d0dd4dc1c7a0a43a61b04#file-csharpdataflowtuplecounts-qll) on `mono`:

  | fwd1 | nc1 | fwd2 | nc2 | ff1 | fb1 | ff2 | fb2 | f | fwd3 | lbs | nc3 | fwd3t | nc3t | ccfwd | cc | fwd4 | nc4 | fwd4t | nc4t | pn
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Before | 3163944 | 1830102 | 928649 | 110442 | 32513 | 24077 | 11395 | 1448 | 1159 | 39147 | 79804 | 23209 | 67287 | 23658 | 1004 | 77 | 22041 | 21967 | 23001 | 22032 | 28565
After | 3163944 | 1830102 | 928649 | 110442 | 32513 | 24077 | 11395 | 1448 | 1159 | 38547 | 93237 | 23139 | 64595 | 23556 | 975 | 77 | 22020 | 21946 | 22972 | 22009 | 28536
Increase | 0% | 0% | 0% | 0% | 0% | 0% | 0% | 0% | 0% | -2% | 17% | 0% | -4% | 0% | -3% | 0% | 0% | 0% | 0% | 0% | 0%

### Java tuple counts

Ran [this](https://gist.github.com/hvitved/ac1e68269d9d0dd4dc1c7a0a43a61b04#file-javadataflowtuplecounts-qll) on JDK:

  | fwd1 | nc1 | fwd2 | nc2 | ff1 | fb1 | ff2 | fb2 | f | fwd3 | lbs | nc3 | fwd3t | nc3t | ccfwd | cc | fwd4 | nc4 | fwd4t | nc4t | pn
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Before | 2604206 | 1555243 | 920416 | 565520 | 30417 | 22434 | 14298 | 8872 | 7884 | 208534 | 813190 | 127783 | 976581 | 346054 | 11750 | 3955 | 113281 | 108944 | 403062 | 322831 | 313277
After | 2604206 | 1555243 | 920416 | 565520 | 30417 | 22434 | 14298 | 8872 | 7884 | 195284 | 846259 | 125882 | 851799 | 341831 | 10322 | 3946 | 111649 | 107336 | 395717 | 317363 | 307376
Increase | 0% | 0% | 0% | 0% | 0% | 0% | 0% | 0% | 0% | -6% | 4% | -1% | -13% | -1% | -12% | 0% | -1% | -1% | -2% | -2% | -2%

### Differences jobs:
- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/538/
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1499/
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/960/

### CODE REVIEW

**Comment by hvitved** [comment]
The failing `Distro-Tests/CPP-Linux` job appears to be caused by the recent Jenkins outage.

**Comment by hvitved** [comment]
Rebased to resolve merge conflict, and updated difference job links in the PR description.

**Comment by jbj** [comment]
No objections from me. The 7% time increase on torvalds/linux C/C++ seems to be just noise: the two queries with the biggest increase don't use data flow.

**Comment by hvitved** [comment]
Rebased again. I have updated the PR description with new tuple counts and links to new Differences jobs.

**Pull request closed without merging**
