### PR TITLE
Dataflow: Content-aware simple steps

### PR DESCRIPTION
**Pull request by MathiasVP**
For C++ we often have a tainted indirection  (i.e., `*p`) that requires a dereference to be reached. We want to model this using field flow, where the node for `p` is tainted with `ArrayContent` on the access path if `*p` is tainted.

However, when `p` is tainted and the access path is `[ArrayContent]` we don't get to use non-value preserving steps, which means that we don't get flow in cases such as: `int* q = p + 1; sink(*q)` since the step from `p` to `p + 1` isn't value preserving.

This PR implements a new feature in the shared dataflow library, where each language can define a step relation that is parameterized by a `Content`, and this relation is included in the value-preserving step-relation. The `Content` column of the relation represents the content that must be at the head of the access path in order to perform this flow step.

Currently this is implemented as `none()` in all languages (including the C++ IR where I want to use this). Eventually, the implementation in the C++ IR's `DataFlowUtil.qll` will be something along the lines of:

```codeql
predicate simpleLocalFlowContentStep(Content c, Node nodeFrom, Node nodeTo) {
  c instanceof ArrayContent and
  nodeFrom.asOperand() = nodeTo.asInstruction().(PointerArithmeticInstruction).getAnOperand()
}
```

meaning that, when the head of the access path is an `ArrayContent`, we will have flow from `p` to `p + 1`.

I'm curious to hear if this is something that would be feasible to include in the shared library, and if anyone else would find this useful.

[This CPP-difference](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1744/) compares https://github.com/github/codeql/pull/5127 to https://github.com/github/codeql/pull/5127 + this PR (with the above implementation of `simpleLocalFlowContentStep`). The slowdown looks like noise: The query with the most slowdown is one that doesn't use dataflow.

### CODE REVIEW

**Comment by hvitved** [comment]
Is there a good reason why this can't just be defined as a read step followed by a store step, with a synthesized node in between (which can be hidden using the `nodeIsHidden` predicate)? This is what we currently do for C# flow summaries; for example in `x.Reverse()` there is flow from elements of `x` to elements of the call, which under-the-hood compiles down to a read step followed by a store step.

**Comment by MathiasVP** [comment]
I suppose that might work, yes. Thanks for that suggestion!

My immediate concern is that the read step + store step approach does require an access path that is one longer than the approach implemented in this PR. This might be an issue because https://github.com/github/codeql/pull/5127 already forced me to increase the `accessPathLimit` by 2 to pass many of our tests.

**Comment by hvitved** [comment]
> My immediate concern is that the read step + store step approach does require an access path that is one longer than the approach implemented in this PR

Why is that? First you read, which reduces the existing length by one, and then store to bring the length back to what it was before.

**Comment by MathiasVP** [comment]
> Why is that? First you read, which reduces the existing length by one, and then store to bring the length back to what it was before.

Oh, right! I kept thinking that I had to push another content to the access path, and then have the intermediate node pop it. But you're right! That's not needed. I'll give that a try!

**Comment by aschackmull** [comment]
Right, what Tom said (because at first glance this seems like a lot of complexity in the shared implementation for something that's already possible). A second comment is that if we do want to consider something like this, then perhaps a more general "clone" step would make sense, i.e. a step that's valid only for non-empty access paths.

(Also, another minor point about the structure of DataFlowImpl: The stage 2-3-4 parts are intended to be textual expansions of a hypothetical parameterised module so their bodies (the parts indicated by `/* Begin: Stage 2 logic. */`, etc.) should be kept identical.)

**Pull request closed without merging**
