### PR TITLE
Swift: generate raw helpers in synthesized stubs

### PR DESCRIPTION
**Pull request by redsun82**
This will add helpers to get the underlying raw entities or constructor arguments on stubs for synthesized classes.

For example a schema like:

```python
@synth.from_class(A)
class B:
    pass

@synth.on_arguments(base=A, index=int)
class C:
    pass
```

will generate

```codeql
cached
private Raw::A getUnderlyingEntity() { this = Synth::TB(result) }
```
in the `B.qll` stub and
```codeql
cached
private Raw::A getUnderlyingBase() { this = Synth::TC(result, _) }

cached
private int getUnderlyingIndex() { this = Synth::TC(_, result) }
```
in the `C.qll` stub.

As stubs these can be freely changed later on.

### CODE REVIEW

**Review by AlexDenisov — APPROVED** [review]

**Comment by MathiasVP** [comment]
Out of curiosity: What is the end goal that we're trying to get to with this?

**Comment by redsun82** [comment]
> Out of curiosity: What is the end goal that we're trying to get to with this?

It's a small QoL improvement. Until now, we would write such predicates by hand, see [this example](https://github.com/github/codeql/blob/29c826000448c8382c9465896a2a3b71b1c96d90/swift/ql/lib/codeql/swift/elements/expr/MethodLookupExpr.qll#L29-L30). Now, it will be given to us from the get go.

For me the prompt for this was to give a leaner live demo later today :slightly_smiling_face:

**Comment by MathiasVP** [comment]
Alright, that's fair. I'm not sure we want to `cache` all of these predicates. I'd expect them to be called _once_ the first time we need the cached user-facing AST layer. But for the purposes of your demo that's probably irrelevant. We need to investigate this, though.

**Comment by redsun82** [comment]
> Alright, that's fair. I'm not sure we want to `cache` all of these predicates. I'd expect them to be called _once_ the first time we need the cached user-facing AST layer. But for the purposes of your demo that's probably irrelevant. We need to investigate this, though.

Good point, I only cached those predicates because the hand-written example I had did that.

**Pull request merged**
