### PR TITLE
C++: Improve cpp/unsigned-difference-expression-compared-zero using IR Range Analysis

### PR DESCRIPTION
**Pull request by geoffw0**
Changes on top of https://github.com/github/codeql/pull/5616, that enhance the query further using IR Range Analysis.  That library is currently in experimental so we should be cautious about using it, in particular it needs significant performance testing before this can be merged.  I have made this PR so that we can discuss both the IR Range Analysis library and its possible use in this query.

LGTM run comparing three versions of this query: https://lgtm.com/query/228593669197855836/

@rdmarsh2 @MathiasVP @criemen @jbj

### CODE REVIEW

**Comment by criemen** [comment]
Can you add a fourth version to the LGTM run with
```
import semmle.code.cpp.ir.implementation.UsesoundEscapeAnalysis
```
?

**Comment by geoffw0** [comment]
LGTM run: there are a small number of changes, all of which are false positives resolved by this version of the query (but nowhere near as many as @criemen described in the motivating ticket).  Several projects timed out, though being a diff query it isn't clear which versions (if any) are actually responsible for that.

I will try the sound escape analysis suggestion, and also look into the timeouts at some point.

**Comment by geoffw0** [comment]
Original query vs sound IR range analysis: https://lgtm.com/query/3167181963200267748/

**Comment by geoffw0** [comment]
Results with sound IR range analysis are identical to unsound (on the LGTM run above and in the tests).  Some slightly different projects time out on LGTM but that probably doesn't mean much.  I therefore don't think the soundness flag is an issue either way for this query.

**Comment by geoffw0** [comment]
Note: we merged https://github.com/github/codeql/pull/5616 instead of this PR.  This branch still potentially improves results further, so I'm leaving it open with the hope we might resurrect it when IR Range Analysis is ready (but not before).  It will need to be merged with the changes from the other branch (now on `main`), and the improvement to results will need to be re-checked at that time.

**Comment by geoffw0** [comment]
I just had a brief and unsuccessful go at updating this very old PR.  IMO the changes are too old to have value, due to divergence of the base commit from `main`.  We could resurrect this change via a rewrite, if desired.

The improvements to test results in this PR are already accomplished by https://github.com/github/codeql/pull/5616/ .  I *believe* based on the discussion about that the (no longer available) LGTM run above this version was expected to be slightly superior in a few niche cases.

The new test cases added in this PR have also been added to `main` by https://github.com/github/codeql/pull/5616/ .

Closing.

**Pull request closed without merging**
