### PR TITLE
C++: Downgrade `cpp/uncontrolled-allocation-size` query precision.

### PR DESCRIPTION
**Pull request by geoffw0**
See discussion in https://github.com/github/codeql-c-analysis-team/issues/80.

This means the query will be run on LGTM, but no longer displayed by default.

When we port this query to the newer taint tracking (https://github.com/github/codeql-c-analysis-team/issues/49) we may be able to increase this again.

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
As the linked issue is not public, may I ask why the precision is lowered?

**Comment by jbj** [comment]
@intrigus-lgtm, the lower precision reflects that `cpp/uncontrolled-allocation-size` is the C/C++ query for which we get the most false-positive reports. Examples: #3016, #3437 and #2953, plus at least as many fixed or partially fixed reports. Many of the false positives are fundamentally hard to fix, and we haven't been able to prioritise it.

**Comment by jbj** [comment]
@geoffw0 please add a change note to say this query is now run but not displayed on LGTM by default.

**Comment by geoffw0** [comment]
I have added a change note.

Sorry for my initial description - for those without access to the links it was little better than no description at all!  As @jbj says there are quite a lot of known false positives for this query, and they appear to be caused by a range of deficiencies (not one common cause) so we expect it will take several rounds of (non-trivial) improvement to get the results of this query up to a good enough standard.  For the time being, we feel that the query precision should be downgraded so that the results are not as prominent.

**Comment by DanBloomberg** [comment]
It sounds like the 'cpp/uncontrolled-allocation-size' query is a new one, in the current version.

I'm surprised with all the false positives that you didn't revert that part of the analyzer 6 or 7 months ago when the issues surfaced.  I note that you have closed 3 of the bug reports on this issue.  Is that because those problems have been fixed, but there are other false-positives that are still outstanding?

**Comment by jbj** [comment]
> It sounds like the 'cpp/uncontrolled-allocation-size' query is a new one, in the current version.

It's not new, but we've made substantial changes to the underlying libraries it uses, which can lead to changes in which projects are seeing false positives.

> I'm surprised with all the false positives that you didn't revert that part of the analyzer 6 or 7 months ago when the issues surfaced. I note that you have closed 3 of the bug reports on this issue. Is that because those problems have been fixed, but there are other false-positives that are still outstanding?

I've closed the public issues because the bugs will no longer be user-visible. We are still keeping track of the bugs in internal issues.

**Pull request merged**
