### PR TITLE
C++: Remove flow from pointer indirection to pointer from DefaultTaintTracking

### PR DESCRIPTION
**Pull request by MathiasVP**
This is part 3 of https://github.com/github/codeql-c-analysis-team/issues/31. It removes the `*p -> p` flow from DefaultTaintTracking. This rule gives unintuitive "diamond-shaped" path-explanations and is generally not the direction we want taint to flow.

I discussed the current state of https://github.com/github/codeql-c-analysis-team/issues/31 this morning with Jonas, and we believe that part 2 is "solved" by the switch to unsound IR: When we had a sound IR, parameters would be conflated with `{all-aliased-memory}`, and we would not track its flow through `Chi` instructions. But now that we have an unsound IR we'll track updates to the indirection of the parameter.

All test results lost are true results we want to keep.  I suspect we lose them because most sinks are arguments, and AFAIK the instruction that has the result of `Call.getAnArgument` is the definition of the `ArgumentOperand`, and not the `ReadSideEffect` that contains the indirection that has actually been tainted.

Edit: 1dc4dc3 brings back all the previously lost results.

Fixes https://github.com/github/codeql-c-analysis-team/issues/31.

### CODE REVIEW

**Comment by jbj** [comment]
Before we can merge this, we'll certainly need a solution to the problem of losing flow at arguments. I think this is exactly what's discussed in https://github.com/github/codeql-c-analysis-team/issues/147, so it seems these issues will have to be solved together.

**Comment by MathiasVP** [comment]
> Before we can merge this, we'll certainly need a solution to the problem of losing flow at arguments. I think this is exactly what's discussed in [github/codeql-c-analysis-team#147](https://github.com/github/codeql-c-analysis-team/issues/147), so it seems these issues will have to be solved together.

Good point. I knew we had a discussion regarding this at some point. Thanks for the link! I will re-read that issue.

**Comment by MathiasVP** [comment]
1dc4dc3a07e13c2bd61dc6bbd7c875f56df5fbd9 brings back all the previously lost results. I think this PR is good to go!

**Comment by jbj** [comment]
Fantastic results! Please run CPP-Differences.

**Comment by MathiasVP** [comment]
> Fantastic results! Please run CPP-Differences.

I was positively surprised as well. It _does_ look like there's a slight cosmetic regression in https://github.com/github/codeql/pull/5089/commits/e93e49cbc90ae8fd3573a0f728824e931b7aadf1#diff-a66aea87fd1d4016afe8c1efe74c95bdd08a33bde0746e8e8e96839c20e5b1e0R96, though: There's flow to a sink, which then flows to another sink. It should be a simple fix involving an `isBarrierOut` override. Do you think it's worth doing in this PR?

I've started a CPP-differences that compares e93e49cbc90ae8fd3573a0f728824e931b7aadf1 to the current `main`: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1705/

**Comment by jbj** [comment]
> Do you think it's worth doing in this PR?

I'm happy to leave it for a follow-up.

**Comment by MathiasVP** [comment]
> I've started a CPP-differences that compares [e93e49c](https://github.com/github/codeql/commit/e93e49cbc90ae8fd3573a0f728824e931b7aadf1) to the current `main`: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1705/

Looks like we lose a bunch of results :( I'll look through them later today and see what's causing this.

**Comment by MathiasVP** [comment]
It looks like the missing results on `cpp/path-injection` on `OpenJDK` are due to a single missing flow step. Here's the relevant piece of code:

```cpp
static char * fgets_no_cr(char * buf, int n, FILE *fp)
{
   char * rslt = fgets(buf, n, fp);
   if (rslt && buf && *buf){
       char *p = strchr(buf, '\0');
       if (*--p=='\n') *p='\0';
   }
   return rslt;
}

static bool read_lib_info(struct ps_prochandle* ph) {
  char fname[32];
  char buf[PATH_MAX];
  FILE *fp = NULL;

  sprintf(fname, "/proc/%d/maps", ph->pid);
  fp = fopen(fname, "r");
  if (fp == NULL) {
    print_debug("can't open /proc/%d/maps file\n", ph->pid);
    return false;
  }

  while(fgets_no_cr(buf, PATH_MAX, fp)){
    char * word[7];
    int nwords = split_n_str(buf, 7, word, ' ', '\0');
    // ...
```

We have flow into `*buf` from the call to `fgets(buf, n, fp)`. We then pass `buf` into a function `split_n_str` here:

```
int nwords = split_n_str(buf, 7, word, ' ', '\0');
```

where the `*p -> p` taint step (which we're now removing) is then used to transfer flow to `buf`, so the `str` parameter (and not just the indirection) is tainted here:

```cpp
static int split_n_str(char * str, int n, char ** ptrs, char delim, char new_delim) {
  int i;
  for(i = 0; i < n; i++) ptrs[i] = NULL;
  if (str == NULL || n < 1 ) return 0;

  i = 0;

  // skipping leading blanks
  while(*str&&*str==delim) str++;

  while(*str&&i<n){
    ptrs[i++] = str;
    while(*str&&*str!=delim) str++;
    while(*str&&*str==delim) *(str++) = new_delim;
  }

  return i;
}
```
we then follow the flow through `str` through various phi nodes, until we get to the `Store` instruction here:
```
ptrs[i++] = str;
```
which triggers a `storeStep` with an `ArrayContent` that taints `*ptrs`, and the flow continues out of the function, eventually reaching a sink.

So without that `*str -> str` taint step we're not catching this flow because that step from `str` to `ptrs[i++]` doesn't mention the indirection at all.

**Comment by jbj** [comment]
Thanks for a very clearly explained diagnosis.

An even harder variant of this problem is (not tested):

```cpp
fgets(buf, ..., ...);
mystruct->myfield = buf;
sink(mystruct->myfield);
```

In this case we don't have a function call as a point where we can cheat and add object-to-pointer flow. If we want flow here at all, we'll have to taint the `buf` pointer at the `fgets` call. We can either taint the pointer but not the object, or we can taint the pointer with an `ArrayContent` and taint the object directly. I'm not sure how to best taint the pointer `buf`.

**Comment by MathiasVP** [comment]
> In this case we don't have a function call as a point where we can cheat and add object-to-pointer flow. If we want flow here at all, we'll have to taint the `buf` pointer at the `fgets` call.

Good point. I just tried this on `main` and It looks like we currently don't catch this flow (for the exact reason you mentioned).

> We can either taint the pointer but not the object, or we can taint the pointer with an `ArrayContent` and taint the object directly. I'm not sure how to best taint the pointer `buf`.

Indeed, I guess this is another good reason we should switch to field flow through addresses. When we have taint to the `WriteSideEffect` instruction for argument 0 in `fgets` we can do a `storeStep` to `buf ` that pushes an `ArrayContent` and track the taint on the pointed-to memory through the `buf` pointer.

**Comment by MathiasVP** [comment]
df016934b2a05e1b2d4583fa8f104a4e7733b193 brings back the lost results on OpenJDK when I tested it locally. I've started a new CPP-difference which should hopefully show that we preserve all results: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1750/

**Comment by MathiasVP** [comment]
CPP-differences came back. The good news: It looks like we got back the results we lost (we're still losing 2 and gaining 2 new ones. I'll look into that).

The bad news:
analysis_time
And unfortunately, it doesn't look like it's just a join-order issue.

**Comment by MathiasVP** [comment]
24b135337f119336f81c920b89f0dbed2652d575 seems to fix the `git/git` performance regression when I run it locally. Here's a new [CPP-differences](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1765/) that hopefully convinces us that:
1. We don't have any performance problems.
2. We don't lose too much flow now that we're doing `p -> *p` and `*p -> p` in a slightly more principled way.

This is starting to become a risky change - it's difficult to say whether this PR now adds or removes flow. I talked with @jbj about this today, and we're currently leaning towards delaying a merge of this PR until after the freeze. But this will only be a concern if the CPP-differences comes back with good results, so let's wait and see.

**Comment by MathiasVP** [comment]
CPP-differences has come back! Some good news: The performance problems has been fixed.

Some bad news: We're losing a couple of results. The reason is somewhat interesting. The lost results can be boiled down to the fact that we’re losing taint on this example:
```cpp
char *strip_ext(char *fname)
{
  char* ep = fname;
  // ...
  if (ep >= fname) --ep;
  return fname;
}
int main(int argc, char* argv[]) {
  const char *base = strip_ext(argv[0]);
  char fname[16];
  sprintf(fname,"%s",base);
}
```
It turns out that we’re losing taint because of the relational comparison in `strip_ext`. This makes `DefaultTaintTracking` block all taint coming out of any occurrence of `fname`, meaning that we're not getting taint out of `strip_ext`. This seems a little extreme to me.
There’s a large TODO comment on `hasUpperBoundsCheck` that mentions that this is a coarse overapproximation that has been ported from the old taint library.

Apparently we’re catching this flow currently on main because we can transfer taint from the argv[0] argument to its indirection before we enter strip_ext and thus avoid the barrier.

**Comment by jbj** [comment]
### g/openjdk/jdk

> Could we restrict `hasUpperBoundsCheck` to only block taint on non-pointer relational comparisons?

Sounds good to me. I believe `hasUpperBoundsCheck` is only intended for blocking taint through numbers that'll be used as allocation sizes.

### g/vim/vim

> This is basically the problem I described in #5225

If it doesn't cause a SAMATE regression I'm okay with losing these results for now and then restoring them later as part of solving #5225.

**Comment by MathiasVP** [comment]
> Sounds good to me. I believe `hasUpperBoundsCheck` is only intended for blocking taint through numbers that'll be used as allocation sizes.

Fixed in 1df0d9d0ab44dac37ac2721176ed177385e49ef7. I've started another CPP-differences for good measure: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1770/.

> If it doesn't cause a SAMATE regression I'm okay with losing these results for now and then restoring them later as part of solving #5225.

Sounds good. Depending on the state of https://github.com/github/codeql-c-analysis-team/issues/237 it sounds like it might be faster to just wait for that to be done instead of starting a long old-school SAMATE run.

**Comment by MathiasVP** [comment]
[CPP-differences](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1787/) finally came back without timeouts.

The 2 remaining results we lose are due to non-empty access paths resulting in missing taint-steps (i.e., the problem I talked about in the comment [above](https://github.com/github/codeql/pull/5089#issuecomment-787105182)). I've talked about one of the two results above. The other lost result happens because we're losing a `argument indirection -> argument` taint step when taint reaches `*buf` in this function:

```cpp
static const char *
json_find_attr(const char *buf, const jsmntok_t *tokens, int count, const char *attr)
{
	int i;

	for (i = 0; i < count; i += 2)
	{
		const char *tok_attr  = &buf[tokens[i + 0].start];
		const char *tok_value = &buf[tokens[i + 1].start];

		if (!strcmp(tok_attr, attr))
			return tok_value;
	}

	return NULL;
}
```
Previously, we proceeded with a taint step to `tok_value` and to the return value. Now, we can no longer perform this taint step, so we lose the flow here.

The new results on `cpp/unbounded-write` looks like true positives. The only remaining problem is the 20% regression on `vim/vim`.

**Comment by MathiasVP** [comment]
> The new results on `cpp/unbounded-write` looks like true positives. The only remaining problem is the 20% regression on `vim/vim`.

It looks like the 20% regression on vim/vim is caused by the same problems as the ones described in https://github.com/github/codeql-c-analysis-team/issues/177. We generate a factor ~100 more nodes in stage 3 of dataflow when we compute:
```codeql
exists(Ap argAp0 |
  fwdFlowOutFromArg(call, node, argAp0, ap, config) and
  fwdFlowIsEntered(call, cc, argAp, argAp0, config)
)
```

**Comment by MathiasVP** [comment]
Good news: I've figured out the performance regression that underlies both this PR and the related problems we've been having with IR field flow. We get a tuple explosion when the dataflow library calculates which access paths may follow an `Array Content` using the `consCand` predicates in stage 3 and 4.

The bad news: The only way to prevent this seems to be opting into the type pruning mechanism which we've historically avoided in C++. I did some experiments using naive `{isPointer, isPOD, isPrimitive}` (i.e., `compatibleTypes` holds if both types are pointers, or both types are PODs, or both types are primitives) type system on Friday, but it doesn't prune enough to solve the performance problems.

**Comment by MathiasVP** [comment]
I've tried adding an implementation of `compatibleTypes` in 84d85d51e8ded7e9cff08590779d4030b85680a9 that:
1. doesn't block any flow, and
2. does more pruning than the `{isPointer, isPOD, isPrimitive}` type system I alluded to above.

Locally it looks like it's fixing the performance on vim/vim. I'll start a CPP-difference to confirm this.

I've marked this PR as a WIP because I encountered a join-order issue in `DataFlowImplCommon` that I fixed using `only_bind_into`. Before we can merge this PR we need to sync this up with the other copies of the dataflow library.

**Comment by MathiasVP** [comment]
I'm closing this PR for now as my list of open PRs on https://github.com/pulls is about to overflow my tiny screen. We can revisit it once we start working on dataflow improvements again.

**Pull request closed without merging**
