### PR TITLE
JS: Remove local flow step from left operand of &&

### PR DESCRIPTION
**Pull request by asger-semmle**
Still waiting for evaluation, just uploading to run the tests

### CODE REVIEW

**Comment by xiemaisi** [comment]
Hm, no, that doesn't seem right. I probably didn't express myself clearly when we discussed this, but I feel pretty strongly that the _ data flow_ edge from `x` to `x && y` should stay. It's just the taint that should go, in my opinion. (Alternatively, perhaps we can fix the mismatch between type inference and data flow you mentioned and introduce a general-purpose sanitizer for non-string, non-object data; can you remind me what exactly the mismatch was?)

**Comment by xiemaisi** [comment]
Ah, is it because data flow doesn't go through guard nodes? (Do we even have enough guard nodes in this case?)

**Comment by asger-semmle** [comment]
For now I just wanted to give both approaches a try and see what works.

One problem that came up, which the other solution did not handle, is that `getALocalSource()` would still return both operands, so long chains like `e && e.f && e.f.g` would return _all_ of the operands as sources, which can cause FPs in most of our library models and also affect type tracking.

**Comment by xiemaisi** [comment]
That's an interesting point that would require further thought. I don't think that deliberately making local data flow unsound is the right way to fix that, though.

**Pull request closed without merging**
