### PR TITLE
HTTPS links in documentation

### LINKED ISSUE #5163: Use HTTPS links in documentation and comments
It appears there are quite a few HTTP links in the documentation and code comments of this project despite the target websites supporting HTTPS.
A quick search for `http:` yielded about 4000 findings, however I assume a lot are false positives (e.g. because they are part of an XML namespace declaration) and some target sites might not support HTTPS, or are not properly configured (outdated certificate, wrong domain name).

However, for the websites which do support HTTPS it would be good to update the links. Otherwise for HTTP links the browser will first send an HTTP request which an attacker in the same network is able to see and for which they can spoof a response.

Slightly related: #4379

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Resolved #5163

### CODE REVIEW

**Comment by jbj** [comment]
I think some of these changes could be valuable. Before any of us starts reviewing in detail, I'd like to check with you, @himanshu007-creator, whether you're prepared to rework the PR in response to review comments about removing unrelated changes or changes to files that should remain static.

**Comment by himanshu007-creator** [comment]
Yes, I can am able to rework on this PR

**Comment by esbena** [comment]
This PR touches 15000 lines, across 1200 files. Which is too much to review manually. Could you perhaps explain how you selected the files to change, and what you changed in them? I suppose you used some kind of script.

---

By the way, a quick look at the diff reveals the follow example changes that does not match the PR description "HTTPS links in documentation":

- [javascript/ql/src/semmle/javascript/security/dataflow/InsecureDownloadCustomizations.qll](https://github.com/github/codeql/pull/5965/commits/70b9dc7a18c7cfb077bf4b05e000af499197080b?#diff-b827e9e6a2a5ee1ba4fa76359a099ecb7f9226cf40e4c1781a0949c6aaaa006aL71): semantic change to query that specifically looks for http-URLs that should have been https-URLs
- [docs/codeql/ql-training/_static-training/end-slide.svg](https://github.com/github/codeql/pull/5965/commits/70b9dc7a18c7cfb077bf4b05e000af499197080b#diff-1fc59bb4ef30ae28d86786ebf6cce74a026c43c62bdb29606924a7af28a08c2bL3): changes to the content of an svg file
- [change-notes/1.20/analysis-javascript.md](https://github.com/github/codeql/pull/5965/commits/70b9dc7a18c7cfb077bf4b05e000af499197080b#diff-25f09a3c108ce84c315c240468747d673b61210087c6d3d1f59de382c9948b34L5): markdown changes to an old release note

**Comment by himanshu007-creator** [comment]
Yeah, i just searched for all instances of  <code>http:</code>  and replaced them with <code>https:</code>

**Comment by esbena** [comment]
As seen above, that approach is not precise enough. Do you want to refine your replacement strategy?

**Comment by himanshu007-creator** [comment]
Yes, I will make the changes as suggested and improve this PR.

**Comment by esbena** [comment]
Just to make it clear: the three undesired changes that I listed above is not an exhaustive list. 
I would prefer to see a description of how you selected the files to change, and what you changed in them, instead of having to spelunk for other undesired changes.

**Comment by esbena** [comment]
Closing the PR due to inactivity, but feel free to reopen if you wish to continue work on it.

You need to rerun the script in any case to get past the conflicts.

**Pull request closed without merging**
