### PR TITLE
C#: Add '-DisableParallelProcessing' flag to nuget restore in Autobuilder

### PR DESCRIPTION
**Pull request by tamasvajk**

### CODE REVIEW

**Comment by tamasvajk** [comment]
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/512/

**Comment by hvitved** [comment]
I have started auto-builder tests as well: https://jenkins.internal.semmle.com/job/LGTM/job/Autobuild-Tests-v2/job/CSharp/450/

**Comment by tamasvajk** [comment]
> I have started auto-builder tests as well: https://jenkins.internal.semmle.com/job/LGTM/job/Autobuild-Tests-v2/job/CSharp/450/

@hvitved This seems to be passing too.

**Comment by tamasvajk** [comment]
fixed in https://github.com/github/codeql/pull/4438

**Review by hvitved — APPROVED** [review]

**Pull request merged**
