### PR TITLE
Merge `rc/3.5` branch into `main`

### PR DESCRIPTION
**Pull request by edoardopirovano**
Merges back the `rc/3.5` branch into `main`.

@hvitved I fixed some conflicts in `ruby/ql/lib/codeql/ruby/ast/internal/Constant.qll`, `ruby/ql/lib/codeql/ruby/regexp/RegExpTreeView.qll` and `ruby/ql/test/library-tests/ast/ValueText.expected` by taking the versions of those files on `main`. I believe this is fine since the fixes you applied to those files on the RC branch in https://github.com/github/codeql/pull/8590 were already on `main` via the PRs you cherry-picked there. Please could you confirm this is correct and there was nothing on the RC branch in those files that needed to get to `main`?

@dbartol @aeisenberg We talked a few weeks ago in the releases channel about we should probably bump the minor version number of our QL packs after a GHES release. This time has now come, so I've gone ahead and done this in https://github.com/github/codeql/commit/f25618eed6ff1df80f496f4a33ea7520b7ec8689. Would you mind confirming that looks good to you?

### CODE REVIEW

**Comment by hvitved** [comment]
> @hvitved I fixed some conflicts in `ruby/ql/lib/codeql/ruby/ast/internal/Constant.qll`, `ruby/ql/lib/codeql/ruby/regexp/RegExpTreeView.qll` and `ruby/ql/test/library-tests/ast/ValueText.expected` by taking the versions of those files on `main`. I believe this is fine since the fixes you applied to those files on the RC branch in #8590 were already on `main` via the PRs you cherry-picked there. Please could you confirm this is correct and there was nothing on the RC branch in those files that needed to get to `main`?

Thanks; I forgot to merge back myself. You were right to resolve in favour of `main`.

**Review by hvitved — APPROVED** [review]

**Comment by dbartol** [comment]
I pushed a commit that bumps a couple version numbers in obscure packs that the original didn't touch. I also fixed several instances where a pack in the `codeql` repo declared a specific version range for a dependency on another pack in the same repo. Since we want these packs to automatically pick up whatever version is in the repo, I changed these version ranges to `"*"` like all of our other intra-workspace dependencies.

**Comment by edoardopirovano** [comment]
Thanks! The extra commit looks good to me. We should probably wait for at least one more set of eyes on this, though, just in case there's another obscure pack somewhere we've missed. (Should we have automation for this?)

**Comment by dbartol** [comment]
> Thanks! The extra commit looks good to me. We should probably wait for at least one more set of eyes on this, though, just in case there's another obscure pack somewhere we've missed. (Should we have automation for this?)

We might want a CLI command (or a switch to an existing one) to force a specific version bump across all packs in the workspace.

**Review by dbartol — APPROVED** [review]
LGTM

**Pull request merged**
