### PR TITLE
Codegen/Rust: allow renaming in QL

### PR DESCRIPTION
**Pull request by redsun82**
This adds a `ql.name` codegen pragma to change the name of a property on the QL side. This is useful to give more meaningful names than what we get from the generated rust AST.

This is used as an example for `MatchExpr.getExpr`, renamed to `MatchExpr.getMatchedExpr`.

### CODE REVIEW

**Review by geoffw0 — APPROVED** [review]
SGTM.

**Review by hvitved — COMMENTED** [review]
I believe Rust uses the terminology _scrutinee_, so perhaps `getScrutinee` instead?

**Comment by redsun82** [comment]
> I believe Rust uses the terminology _scrutinee_, so perhaps `getScrutinee` instead?

Ah, that is what @paldepind suggested in his request for this, I didn't know it was an official rust terminology. Matched expression seems more immediate to me, but I won't argue with established terminology! Will do

**Review by hvitved — APPROVED** [review]

**Comment by paldepind** [comment]
Thanks a lot @redsun82. This is great and I think this (and doing the same for other `getExpr` predicates) can make things quite a bit more readable and solve the problem I mentioned here https://github.com/github/codeql/pull/17918#issuecomment-2490784963 (where the `getExpr` in the CFG AST layer ends up getting shadowed by other `getExpr` predicates).

**Pull request merged**
