### PR TITLE
C++: fix join order in UsingExpiredStackAddress

### PR DESCRIPTION
**Pull request by rdmarsh2**

### CODE REVIEW

**Comment by jketema** [comment]
Before and after tuple counts on some database would be useful (as far as possible). Also can you run a DCA experiment?

**Comment by rdmarsh2** [comment]
Tuple counts before (canceled run):
```
3500      ~0%     {3} r15 = SCAN UsingExpiredStackAddress::TFieldAddress#38a029fe#fff#prev_delta OUTPUT In.1, In.0, In.2 'result'
770331500 ~0%     {3} r16 = JOIN r15 WITH Instruction::FieldInstruction#577b6a83#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'instr', Lhs.1, Lhs.2 'result'
770331000 ~4%     {4} r17 = JOIN r16 WITH Instruction::FieldAddressInstruction::getObjectAddress#dispred#f0820431#ff ON FIRST 1 OUTPUT Lhs.1, Rhs.1, Lhs.2 'result', Lhs.0 'instr'
16500     ~3%     {2} r18 = JOIN r17 WITH UsingExpiredStackAddress::globalAddress#38a029fe#ff#reorder_1_0#prev ON FIRST 2 OUTPUT Lhs.2 'result', Lhs.3 'instr'
```

Tuple counts after:
```
1273860 ~5%     {3} r15 = JOIN UsingExpiredStackAddress::TFieldAddress#38a029fe#fff#prev_delta WITH UsingExpiredStackAddress::globalAddress#38a029fe#ff#reorder_1_0#prev ON FIRST 1 OUTPUT Rhs.1 'instr', Lhs.1, Lhs.2 'result'
3955124 ~2%     {3} r16 = JOIN r15 WITH Instruction::FieldAddressInstruction::getObjectAddress#dispred#f0820431#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'instr', Lhs.1, Lhs.2 'result'
988886  ~3%     {2} r17 = JOIN r16 WITH Instruction::FieldInstruction#577b6a83#ff ON FIRST 2 OUTPUT Lhs.2 'result', Lhs.0 'instr'
```

I'll start a DCA run now.

**Comment by jketema** [comment]
Thanks for the counts and the DCA experiment!

**Review by jketema — APPROVED** [review]
Thanks again for the tuple counts. DCA looks good to me; the `--tuple-counts` option would have helped, but given the results I'm seeing I don't think it's not worth re-running with that option added.

**Pull request merged**
