### PR TITLE
Java: Switch helper flow from Global to SimpleGlobal in StaticInitializationVectorQuery.

### PR DESCRIPTION
**Pull request by aschackmull**
Using a full global data flow instance is overkill and prone to performance issues: In my fieldFlowBranchLimit experiments I noticed this particular configuration suddenly taking an additional 3.6 hours to compute in the dca run.
I expect that the SimpleGlobal flow will be mostly comparable for the level of precision needed here, so I don't expect much in the way of alert changes, but let's see if dca finds something.

### CODE REVIEW

**Review by atorralba — DISMISSED** [review]
LGTM if results don't significantly change.

**Comment by aschackmull** [comment]
> LGTM if results don't significantly change.

openjdk goes from 148 to 165 results with -6 and +23, but the other projects in dca aren't affected. Although one project does have a noticable performance regression. I'll take a look and see what I can find out.

**Comment by aschackmull** [comment]
The lost results look like FPs, so that's fine, and it looks like at least some of the added results are attributable to the `TODO: support setters` in `SimpleGlobal`.

**Comment by aschackmull** [comment]
I've added a commit to fix the performance regression. There was a join-order problem, and specialising `getNode` allows the compiler to perform the `TPathNodeMid` joins on both columns. I'll run dca again to be safe.

**Review by atorralba — APPROVED** [review]
DCA looks much better re: performance.

**Pull request merged**
