### PR TITLE
Codespaces: initial configuration

### PR DESCRIPTION
**Pull request by jbj**
This was adapted from https://github.com/github/vscode-codeql-starter.

### CODE REVIEW

**Comment by jbj** [comment]
This almost works, but for some reason I didn't get syntax highlighting on QL files until I invoked "Developer: Reload Window".

@jcreedcmu or @aeisenberg, maybe you can advise.

**Comment by jcreedcmu** [comment]
Is it reproducible that every time you create a new codespace syntax highlighting doesn't work until you reload? I think that we had seen this phenomenon reported nonreproducibly.

**Comment by aeisenberg** [comment]
@jbj This is a known issue in codespaces. See: https://github.com/github/codespaces/issues/541 and https://github.com/github/codespaces/issues/333

Great to hear that it's working for you.

**Comment by jbj** [comment]
I got syntax highlighting on the second attempt, so it apparently doesn't happen every time. Let's hope it's a rare issue.

**Comment by aeisenberg** [comment]
In my experience, simply refreshing the page once (or twice) will get the syntax highlighting to work again.

**Pull request merged**
