### PR TITLE
Python: Fix too many results from DataFlow::importNode

### PR DESCRIPTION
**Pull request by RasmusWL**

### CODE REVIEW

**Review by yoff — COMMENTED** [review]
Does this rely on the user (so far just ourselves) using `startInAttr` to track `foo.bar` in `import foo.bar`?

**Comment by RasmusWL** [comment]
> Does this rely on the user (so far just ourselves) using `startInAttr` to track `foo.bar` in `import foo.bar`?

I don't understand your question. The problem is that `import foo.bar` will result in `foo` being added to the current scope (and now you can access the `bar` attribute of the `foo` module`. With the previous modeling, we said that `foo` was also a reference to `foo.bar`, which is obviously wrong :grimacing:

**Comment by yoff** [comment]
Ah, I see, I did not read the code properly. This seems fine :-)

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
