### PR TITLE
Rust: make the cli flags override automatic

### PR DESCRIPTION
**Pull request by redsun82**
This makes the clap flags overlay over `Config` entirely derived via an attribute macro. Also, the `--intputs-file` option is replaced by a more standard and versatile `@` parameter file mechanism.

### CODE REVIEW

**Comment by aibaars** [comment]
This looks great. Have you checked that the `CODEQL_EXTRACTOR_RUST_OPTION` prefix overrides ``CODEQL_EXTRACTOR_RUST_` ? We may also want to add `CODEQL_` as a lower priority prefix, so that things like `CODEQL_VERBOSITY` is picked up, but can be overridden by setting `CODEQL_EXTRACTOR_VERBOSITY`.

**Comment by redsun82** [comment]
> This looks great. Have you checked that the `CODEQL_EXTRACTOR_RUST_OPTION` prefix overrides ``CODEQL_EXTRACTOR_RUST_`? We may also want to add `CODEQL_` as a lower priority prefix, so that things like `CODEQL_VERBOSITY` is picked up, but can be overridden by setting `CODEQL_EXTRACTOR_VERBOSITY`.

Yes, `Figment` merge gives an ordering of source priority, which means that `CODEQL_EXTRACTOR_RUST_OPTION_*` has precedence over `CODEQL_EXTRACTOR_RUST_*` (and now over `CODEQL_*` as you suggested). And CLI flags (when passed) have priority over all else. The tricky part solved by the macro is to not have CLI flag defaults override env variables (which is what the `skip_serializing_if` are for).

**Review by aibaars — DISMISSED** [review]
Looks good to me. Any idea why Python tests would be failing for this pull request?

**Review by aibaars — APPROVED** [review]

**Comment by redsun82** [comment]
> Looks good to me. Any idea why Python tests would be failing for this pull request?

Discussing it on slack, but in the meantime a rerun worked :shrug:

**Pull request merged**
