### PR TITLE
JS: Handle calls to accessor functions

### PR DESCRIPTION
**Pull request by asgerf**
Revival of https://github.com/github/codeql/pull/2524, which has finally worked out performance-wise, thanks to the new `pragma[only_bind_into]`.

Adds flow in and out of property accessors (actual getters/setters, not to be confused with methods named `getX`/`setX` which we already handle).

This PR attempts to treat such accessor-calls with the same infrastructure that handles regular calls, to avoid duplicating things like summarization, inheritance-based dispatch, and exceptional returns.

[Evaluation](https://github.com/dsp-testing/asgerf-dca/tree/run/flow-through-accessors6/reports) shows acceptable performance, and 3,374 new call edges from accessor calls.
- vscode and ChakraCore took a minor hit, but I think we can live with it considering the value of the feature.

/cc @max-schaefer who reviewed the original PR

### CODE REVIEW

**Review by max-schaefer — COMMENTED** [review]
:100: Looks very promising, and not a painful as I would have expected!

Would it be easy to also support accessors on object literals, or do you think that's not worth it?

**Comment by asgerf** [comment]
[Another evaluation](https://github.com/dsp-testing/asgerf-dca/tree/run/js/flow-through-accessors2/reports) shows slightly worse performance but 4,565 new call edges in total (up from 3,374).

**Comment by asgerf** [comment]
I did a quick investigation into the slowdown in the last evaluation, but it doesn't seem to be bad join orders, just more tuples coming through the pipeline due to the new data flow.

**Review by max-schaefer — APPROVED** [review]

**Review by erik-krogh — APPROVED** [review]
I suppose getters/setters defined by `Object.defineProperty` is out of scope for now.   
(But could be interesting in a followup :thinking:)

LGTM :+1:

**Comment by asgerf** [comment]
A [quick evaluation](https://github.com/dsp-testing/asgerf-dca/tree/run/js/flow-through-accessors3/reports) after rebasing on #5478 shows good performance, so I'll go ahead and merge.

**Pull request merged**
