### PR TITLE
Java/C#: exclude parameterless constructors from `DataFlowTargetApi`

### PR DESCRIPTION
**Pull request by jcogs33**
### Description
This PR updates `DataFlowTargetApi` to exclude parameterless constructors.

### Consideration
Same as for https://github.com/github/codeql/pull/11623: 
> - Please let me know if the exclusion for C# is correct as I don't have much experience with C#.
> - Are there existing library tests for `DataFlowTargetApi` where I could add a test case for this scenario? I couldn't find any existing tests in the `library-tests` directory, but I may have missed them.
> - Does a change like this need a DCA run?
> - Is this change minor enough that I can add the `no-change-note-required` label?

(cc @michaelnebel)

### CODE REVIEW

**Comment by michaelnebel** [comment]
- For both Java and C# consider introducing a member predicate in the `Constructor` class named `isParamterless` to avoid the duplicate implementation.
- The implementation for C# looks correct. Are you up for adding a unit test for C# as well that would cover not creating neutral models for parameterless constructors?

**Review by michaelnebel — CHANGES_REQUESTED** [review]
The changes looks good, but I have added some comments for refactoring and testing.

**Comment by jcogs33** [comment]
Thanks again for the review! 🙂 I've addressed your comments, let me know if anything else needs to be adjusted.
I've also started DCA runs for this one as well.

**Review by michaelnebel — APPROVED** [review]
Yes, this is excellent!

**Comment by michaelnebel** [comment]
@jcogs33 : I have just merged some renaming including the renaming of some of the testcases, which has lead to some merge conflicts in this PR.
Also, we need to run DCA again with the *uninterpreted-queries* (I had forgotten about that initially). There is a short guide in the documentation section of: https://github.com/github/codeql-csharp-team/issues/223

**Review by michaelnebel — APPROVED** [review]
Excellent work!

**Comment by michaelnebel** [comment]
DCA looks good. Both Java and C# shows a good reduction in the number of generated neutral models!

**Pull request merged**
