### PR TITLE
Add support for C++20's char8_t type.

### PR DESCRIPTION
**Pull request by matt-gretton-dann**
Internal extractor PR: https://git.semmle.com/Semmle/code/pull/36459
GH issue: https://github.com/github/codeql-c-extractor-team/issues/50

This adds support for `char8_t` a new type supported by C++20.  I have added basic support to the extractor and C++ QL libraries to treat it like `char16_t`

I have not attempted to write a complex upgrade script which converts non-builtin `char8_t` types to builtin ones because we run the risk of breaking databases where `char8_t` is not a builtin type (because they're not C++20).

### CODE REVIEW

**Comment by matt-gretton-dann** [comment]
Language-Tests/CPP failures are those we expect to fail because this is using an extractor which doesn't support `char8_t`.  See [internal extractor PR](https://git.semmle.com/Semmle/code/pull/36459) which shows the tests passing.

**Comment by jbj** [comment]
I git-grepped for `Char16Type` and `\<43\>` in this repo and found two more places where the support for `Char16Type` could be copied and adapted to support `Char8Type` as well: two occurrences in `Padding.qll` and one in `integralTypeMapping` in `Type.qll`.

**Comment by jbj** [comment]
Note that if you add a commit to this PR with the changes I suggested, you don't have to update the internal PR to bump the submodule. It should be fine to leave the submodule pointing at a commit that's not the head of this PR as long as the changes past that point aren't crucial to correctness.

**Comment by matt-gretton-dann** [comment]
> I git-grepped for `Char16Type` and `\<43\>` in this repo and found two more places where the support for `Char16Type` could be copied and adapted to support `Char8Type` as well: two occurrences in `Padding.qll` and one in `integralTypeMapping` in `Type.qll`.

https://github.com/Semmle/ql/pull/3074/commits/7b0539c4fd075a128f6932b89e27e2033d4493f8 should cover these changes.

**Pull request merged**
