### PR TITLE
JS: Reintroduce js/resource-exhaustion

### PR DESCRIPTION
**Pull request by esbena**
This reintroduces the reverted js/resource-exhaustion - see [original PR](<https://github.com/github/codeql/pull/3702>) and its [revert](<https://github.com/github/codeql/pull/3756/commits/9a0bbb31f4493e6c59a2167c163fb9b3009fad1a>).

This is a bit of a sad PR. The first commit contains a query with flow labels, the second commit removes the use of the flow labels completely. The flow labels were used to distinguish between numbers and other types, since some sinks only works with numbers. I do not think the overhead of the flow labels is worth the potential results (which I expect to be very rare). The result is a faster query with fewer sinks.

I think the likelihood that the remaining sink `setTimeout(SINK)` will be hit in the wild is high enough that I want to merge the query in this restricted version instead of shelving the full query among the queries that are not run by default. We can add flow labels later to regain the remaining sinks.

Sample run: <https://lgtm.com/query/2428900331474891062/>

Can I get a proper dist-compare run? With the security suite or another RemoteFlow taint query for establishing the baseline?

### CODE REVIEW

**Comment by esbena** [comment]
I have removed the `documentation` label since the documentation has been reviewed in https://github.com/github/codeql/pull/3702 already.

**Comment by esbena** [comment]
(the check failure is just the usual one for missing qldoc on the `Customization` module pattern)

**Comment by erik-krogh** [comment]
It all looks good to me (assuming that an evaluation looks ok).

**Comment by erik-krogh** [comment]
I made [an evaluation against a `where none()` edition of the query](https://git.semmle.com/erik/dist-compare-reports/tree/eriks-profile-machine_1611090638654).  

Definitely shows a slowdown.  
I'm not sure if the slowdown is acceptable.

**Comment by esbena** [comment]
Thanks for checking. Lets shelve this in /experimental for now then (I have moved all files there).

**Review by erik-krogh — APPROVED** [review]

**Pull request merged**
