### PR TITLE
Python: Understand multiple parse mode flags specified in a regular expression string

### PR DESCRIPTION
**Pull request by geoffw0**
Understand / correctly parse multiple parse mode flags specified in a regular expression string, for example `i` and `s` in:
```
(?is)abc.*
```
Previously we were only recognizing the first flag (`i`).

This is a backport of part of the Swift PR https://github.com/github/codeql/pull/13715 .

### CODE REVIEW

**Review by yoff — DISMISSED** [review]
Very nice PR, good choice of tests. Also, thanks for doing this 🙏

**Comment by yoff** [comment]
The test failures can be explained by `flag_group_start` now only matching `(?` and not also the first mode character.
They do pose the question if mode characters should not be considered normal characters. They do not seem like good candidates for first and last items to be matched...

**Comment by yoff** [comment]
In summary, I think you can just fix the test expectations and then we can merge :-)

**Comment by geoffw0** [comment]
Sorry, my notification on this got lost somewhere.  Thank you for reviewing.

There's some related investigation / discussion going on in the Java version of this PR (https://github.com/github/codeql/pull/13778), so I'll wait until everything's settled and port any fixes that arise back to here.

**Comment by geoffw0** [comment]
I've added a commit accepting the test changes.  @yoff it's my understanding that https://github.com/github/codeql/pull/13975 will fix these?

**Comment by yoff** [comment]
> I've added a commit accepting the test changes. @yoff it's my understanding that #13975 will fix these?

Yes. I will rebase, then we shall see :-)

**Comment by yoff** [comment]
> > I've added a commit accepting the test changes. @yoff it's my understanding that #13975 will fix these?
> 
> Yes. I will rebase, then we shall see :-)

Scratch that, no need to rebase. We have a PR on top where these tests pass without change.

**Review by yoff — APPROVED** [review]
Let us merge this now, and then let us merge #13975 soon.

**Pull request merged**
