### PR TITLE
C++: Don't produce partial CFGs when using VLAs

### PR DESCRIPTION
**Pull request by MathiasVP**
We were missing cases for `VlaDimensionStmt` and `VlaDeclStmt` when constructing IR for a variable-length array. This meant that the IR-based CFG on:
```cpp
void foo(int n) {
  ...
  int buf[n];
  ...
}
```
would hit a dead end when reaching the `int buf[n];` declaration, which resulted in missing IR for the remaining part of the function.

This PR doesn't _quite_ generate the right IR for VLAs since (I think) we'd need a new kind of instruction that represents an initialisation of a non-constant sized stack array (i.e., something like an `UninitializedInstruction`, but with a number of operands that specify the size of the indices).

### CODE REVIEW

**Comment by jketema** [comment]
An IR test would be very useful 😄

**Comment by MathiasVP** [comment]
> An IR test would be very useful 😄

That's a very good point! Let me force-push a proper test failure and a fix.

**Review by jketema — DISMISSED** [review]
LGTM if DCA is happy.

**Review by jketema — APPROVED** [review]

**Comment by MathiasVP** [comment]
> There seem to be some syntax zoo failures (you fixed some inconsistencies).

Should be fixed by 65c7a504b224081a60cd2185e914790d8cce9874 🤞.

**Comment by jketema** [comment]
Could you re-run DCA with uninterpreted queries enabled. That'll give some info on the IR changes (as it'll report the number of inconsistencies).

**Comment by MathiasVP** [comment]
> Could you re-run DCA with uninterpreted queries enabled. That'll give some info on the IR changes (as it'll report the number of inconsistencies).

Oh, right. I'll do that.

**Comment by MathiasVP** [comment]
#### Result changes:

Some new results. I've looked through some of the new `cpp/path-injection` results and they all look like TPs 🎉.

#### IR inconsistencies:

`instructionWithoutSuccessor` has gone down from 41 to 25 on a single projected (which is consistent with what we're seeing in our tests). Interestingly, some of the other inconsistency checks has an increased number of results. I think this is due to the fact that we now have _more_ IR than before (i.e., missing phi operands increases from 6209 to 6216, and missing operand types increased from 35461 to 35526). Overall, it's a very small number of increases, so I'm not worried about it.

**Comment by jketema** [comment]
Yeah, DCA results look ok to me too.

**Pull request merged**
