### PR TITLE
Swift: Taint through arithmetic

### PR DESCRIPTION
**Pull request by geoffw0**
Adds tests and taint flow through arithmetic.  Before this PR we had flow through `+` on `String`s only, a rather conservative position.  We want taint through other types such as `Integer`s, and through other arithmetic operators such as `-`.

After this PR I will create a follow-up for taint through `+=` and friends, which builds on the changes here but is a separate chunk of work with a bit of its own complexity.  More of the tests will pass after that.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM!

I remember for C/C++ we only taint the result of an arithmetic operation when one of the operands is _predictable_ (which pretty much translates to constant). I fully support the decision to not go this route for Swift (since no other CodeQL-support language does it this way), and just provide taint through all arithmetic operations.

**Comment by geoffw0** [comment]
Yes, I'm not sure why that was.  Perhaps there was a problematic pattern involving subtraction???

**Comment by MathiasVP** [comment]
> Yes, I'm not sure why that was. Perhaps there was a problematic pattern involving subtraction???

I'm not sure of the history either. What I am sure of is that C/C++ probably has a lot more queries that involve arithmetic operations (and thus a lot more flow through arithmetic operations), so the potential for FPs were probably just a lot more relevant.

**Comment by geoffw0** [comment]
We are paying a lot of attention to new results (at least at the DCA scale) and have plans to do a wide review of query false positives later in the year.  So we don't have to worry about non-obvious FPs too much at this early stage.

Merging.

**Pull request merged**
