### PR TITLE
DataFlow - SummarizedCallable refactor

### PR DESCRIPTION
**Pull request by michaelnebel**
Avoid duplicate implementations of SummarizedCallable.

### CODE REVIEW

**Comment by michaelnebel** [comment]
@hvitved: 
DCA investigation.
C#: Looks good. All workflows executed and no performance regression.
Ruby: Looks good. All workflows executed and no performance regression.
Java: Unsure. All workflows except for apache-geode executed (query execution failure). Not sure, if this is a general flakiness issue with that project.

**Comment by michaelnebel** [comment]
> @hvitved: DCA investigation. C#: Looks good. All workflows executed and no performance regression. Ruby: Looks good. All workflows executed and no performance regression. Java: Unsure. All workflows except for apache-geode executed (query execution failure). Not sure, if this is a general flakiness issue with that project.

Looks like the apache geode is a flaky project.
Workflow also fails on other PRs (eg this one: https://github.com/github/codeql/pull/9134).
So we should probably accept the result.
The other java projects did not exhibit any performance regressions.

Setting ready for review.

**Comment by aschackmull** [comment]
> apache-geode

This project currently has a known performance problem.

**Review by hvitved — APPROVED** [review]

**Comment by hvitved** [comment]
We can ignore the failing Integration tests, it is unrelated to this PR.

**Comment by michaelnebel** [comment]
> We can ignore the failing Integration tests, it is unrelated to this PR.

Excellent!

**Pull request merged**
