### PR TITLE
C++: Ensure we can round trip between (forward) class declarations

### PR DESCRIPTION
**Pull request by jketema**
This was already possible when the forward class declaration and the class definition occurred in the same scope. However, there is a common C++ usage pattern in which this is not the case (when only a pointer to the class is needed). In this latter scenario we could not round trip between the (forward) `DeclarationEntry` and the `Declaration`.
    
Effectively this changes the code to:
```
if exists(TypeDeclarationEntry e | e.getType() = this)
then result.getType() = this
else ...
```
We use `type_decls` instead to stay close to the original code.

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
Nice find! LGTM is DCA is happy 🤞.

**Comment by jketema** [comment]
Yeah, this confused me quite a lot yesterday. Indeed let's see what DCA has to say.

**Comment by jketema** [comment]
@MathiasVP DCA completed. Would you mind having a look at the results? I ran with tuple counting enabled, and I'm not sure if there's anything concerning int there.

**Comment by MathiasVP** [comment]
> @MathiasVP DCA completed. Would you mind having a look at the results? I ran with tuple counting enabled, and I'm not sure if there's anything concerning in there.

I think it all looks good 👍. It's a bit difficult to read the tuple-count tables since this PR changes a fundamental AST class that most higher-level predicates depend on (which means all dependent predicates get a different hash).

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
