### PR TITLE
C++: Repair swap taint tests

### PR DESCRIPTION
**Pull request by geoffw0**
This is a follow-up to https://github.com/github/codeql/pull/3733, requested by @jbj in https://github.com/github/codeql-c-analysis-team/issues/90, adding taint tests for `swap` that work like they did originally (i.e. where taint flow has to be deduced from the function bodies and can't just from their constructor/assignment operator signatures).

@MathiasVP my changes seem to have had a non-local effect on the result for `swap2.cpp` line 87 (look at the second commit on its own to see this).  I'd like to know your thoughts on this result and whether it is well understood?

### CODE REVIEW

**Comment by MathiasVP** [comment]
> @MathiasVP my changes seem to have had a non-local effect on the result for `swap2.cpp` line 87 (look at the second commit on its own to see this). I'd like to know your thoughts on this result and whether it is well understood?

I'm not quite sure why we lose that result all of a sudden. I'll investigate it later today.

**Comment by geoffw0** [comment]
Thanks.

I believe it comes back if you comment out either the call `y.move_assign(std::move(x))`, or `swap(that)` inside `move_assign`.  And it only disappeared in the `swap2` test despite the changes being the same.

**Comment by jbj** [comment]
I'll merge this now and investigate the mysterious non-local effect later.

**Comment by jbj** [comment]
I attempted to investigate the mysterious non-local effect in this test last week, but I wasn't able to isolate it in a few hours. I can't justify spending more time on it, given that we've never seen other instances of this bug. It only affects AST data flow.

**Pull request merged**
