### PR TITLE
Python: Add type-tracking consistency query

### PR DESCRIPTION
**Pull request by RasmusWL**
Like [Ruby](https://github.com/github/codeql/blob/6ce8e0510f9e58bfa55e305ccafd354d1468950c/ruby/ql/consistency-queries/TypeTrackingConsistency.ql#L4-L6) we need to exclude nodes related to post-update

(created as draft to ensure I didn't overlook anything important)

### CODE REVIEW

**Comment by RasmusWL** [comment]
@yoff I would like your input in regards to the match exclusions (specifically the ones from adf5a4b). The internal match tests had quite a few failures not found when running against [dataflow/match/](https://github.com/github/codeql/tree/5433907c331a1dd0d7bb7a28df7114cd1ccf9c91/python/ql/test/experimental/dataflow/match) tests. I think that indicates we should expand the dataflow `match` tests.

I looked at constructs such as `case ("foo" | "bar") as thing:` and found it strange that the flow was `"foo" | "bar" -> "foo"` and not the other way around :shrug: Having some tests would at least highlight why the modeling is working the way it is :blush:

<details>

<summary>internal match consistency failures</summary>

```
unreachableNode
| motivation.py:42:15:42:28 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:42:16:42:22 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:42:28:42:28 | ControlFlowNode for l | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:42:38:42:51 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:42:39:42:45 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:42:51:42:51 | ControlFlowNode for r | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:44:18:44:32 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:44:19:44:25 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:44:31:44:32 | ControlFlowNode for op | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:15:46:51 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:16:46:30 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:16:46:38 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:35:46:38 | ControlFlowNode for left | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:59:46:97 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:60:46:74 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:60:46:83 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:46:79:46:83 | ControlFlowNode for right | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:48:15:48:40 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:48:16:48:30 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:48:36:48:40 | ControlFlowNode for value | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:55:15:55:21 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:57:15:57:21 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:57:61:57:67 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:65:15:65:23 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| motivation.py:113:26:113:42 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| tutorial.py:48:18:48:52 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| tutorial.py:53:17:53:66 | ControlFlowNode for MatchAsPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| tutorial.py:53:18:53:52 | ControlFlowNode for MatchOrPattern | Unreachable node in step of kind simpleLocalSmallStep. |
| tutorial.py:53:58:53:66 | ControlFlowNode for direction | Unreachable node in step of kind simpleLocalSmallStep. |
```

</details>

**Comment by yoff** [comment]
I had to read what is actually being tested, and it seems that all local sources should be excluded?
I had a look at the first case in https://github.com/github/codeql/pull/15776/commits/5d212514c63ae288371b3878d64f6ed01d7e543b where the code is
```python
@expects(2)
def test_sequence_pattern_tuple():
    match (NONSOURCE, SOURCE):
        case (x, y):   <--- consistency failure here (for x, y and their two match-patterns)
            SINK_F(x)
            SINK(y) #$ flow="SOURCE, l:-3 -> y"
```
and here it seems that the pattern for `x` is only the target of a read step and so should indeed be excluded. I would have expected flow from that pattern to the variable `x` via `matchCaptureFlowStep`, though...

**Comment by RasmusWL** [comment]
> I had to read what is actually being tested, and it seems that all local sources should be excluded?

For anyone following along, the check is implemented here: https://github.com/github/codeql/blob/5a348a5048675223807f168fee5b4080cb1cfb1b/shared/typetracking/codeql/typetracking/internal/TypeTrackingImpl.qll#L44-L51

I don't understand your question though. I don't think `unreachableNode` will have any results for LocalSourceNodes, since that would require that `not flowsTo(_, n)` holds. Consider that `flowsTo(_, n)` holds when:

* [`nonStandardFlowsTo(localSource, n)` holds](https://github.com/github/codeql/blob/5a348a5048675223807f168fee5b4080cb1cfb1b/shared/typetracking/codeql/typetracking/internal/TypeTrackingImpl.qll#L283)
* which is the case when [`localSource.flowsTo(n)`](https://github.com/github/codeql/blob/169d7a3c9827684e5a888503a3adaa0c1bbc4294/python/ql/lib/semmle/python/dataflow/new/internal/TypeTrackingImpl.qll#L271) holds
* which is forwarded to [`Cached::hasLocalSource`](https://github.com/github/codeql/blob/169d7a3c9827684e5a888503a3adaa0c1bbc4294/python/ql/lib/semmle/python/dataflow/new/internal/LocalSources.qll#L81)
* which holds when [`source = sink`](https://github.com/github/codeql/blob/169d7a3c9827684e5a888503a3adaa0c1bbc4294/python/ql/lib/semmle/python/dataflow/new/internal/LocalSources.qll#L231)

**Comment by yoff** [comment]
> So there will be no `n` where the following can hold: `n instanceof LocalSourceNode and not flowsTo(_, n)`

Ah, right, because all `LocalSourceNode`s flow to themselves.

**Comment by RasmusWL** [comment]
> Ah, right, because all `LocalSourceNode`s flow to themselves.

exactly

**Comment by yoff** [comment]
Ok, so there is probably something to investigate here, but I do not see a reason to block this PR..

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
