### PR TITLE
JS: remove the second argument of findByIdAndUpdate as a NoSQL sink

### PR DESCRIPTION
**Pull request by erik-krogh**
2 things:  

1) I was looking at `findByIdAndUpdate`, and I was surprised we flag the second argument as a NoSQL sink.   
See doc: https://mongoosejs.com/docs/tutorials/findoneandupdate.html. The second argument is the data given to the update function, so I'm unsure how that could be unsafe? 

2) A friend of mine likes to use `mongoose.Types.ObjectId.isValid` as a sanitizer for NoSQL injection.  
The function checks if an input is a string of a certain length, so it is a nice sanitizer for object-injection in general.  
I therefore decided to put it in `TaintedObject.qll`, let me know if you want it somewhere else.    
[The function is used a decent amount in the wild.](https://github.com/search?type=code&q=mongoose.Types.ObjectId.isValid)

[Evaluation looks good](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-13381-d504c9__nightly-old__code-scanning/reports).  
There is one lost result, where we no longer flag the second argument on a call to `update`.  
(We still flag the first argument to that same call).

### CODE REVIEW

**Comment by asgerf** [comment]
> I was looking at findByIdAndUpdate, and I was surprised we flag the second argument as a NoSQL sink.

I remember also being surprised at this when porting the SQL models to MaD. As far as I understand, Mongoose lets you [use MongoDB update operators](https://mongoosejs.com/docs/documents.html#updating-using-queries) in updates, so they are sinks for the same reason they are sinks in MongoDB.

**Comment by erik-krogh** [comment]
> I remember also being surprised at this when porting the SQL models to MaD. As far as I understand, Mongoose lets you [use MongoDB update operators](https://mongoosejs.com/docs/documents.html#updating-using-queries) in updates, so they are sinks for the same reason they are sinks in MongoDB.

The documentation states: `Note that update(), updateMany(), findOneAndUpdate(), etc. do not execute save() middleware. If you need save middleware and full validation, first query for the document and then save() it.`

So should the second argument just be removed for those methods?

**Comment by asgerf** [comment]
The issue with `save()` and middlewares is not important. What matters is that these functions treat their second argument as update operators.

**Comment by erik-krogh** [comment]
I see. I get it now.  

I rebased away the part about removing the second argument of `findByIdAndUpdate` etc. as a sink.

**Review by asgerf — APPROVED** [review]
👍

**Pull request merged**
