### PR TITLE
JS: add CWE-1333 to the JS ReDoS queries

### PR DESCRIPTION
**Pull request by erik-krogh**
[CWE-1333](https://cwe.mitre.org/data/definitions/1333.html) sounds like a perfect fit. 

Inspired by Nicks comment here: https://github.com/github/codeql/pull/6038#issuecomment-864909171

### CODE REVIEW

**Comment by esbena** [comment]
Historically (as in: this used to be in the Semmle-wiki), we have tried to only make use of the `Class` `Research Roncept` for CWEs. CWE-1333 uses the `Base` concept. I am not sure if that guideline still is in effect.

@calumgrant you have recently worked with the CWEs. Do you know what the guidelines are these days for query/CWE combinations?

**Comment by calumgrant** [comment]
There are no established guidelines yet, but the tooling is still a work in progress. However, it should be fairly safe to just add  CWE to an existing query as this will in theory just refine the severity score. In theory you should also rerun the cwe scoring tool as part of the PR but the exact workflow has not been established.

**Comment by esbena** [comment]
Thanks.
I vote for making use of this CWE then.

**Review by esbena — APPROVED** [review]

**Review by duongxuantuan154 — COMMENTED** [review]
- [ ]

**Pull request merged**
