### PR TITLE
Fix CSV timeseries script to create DB with scheme from correct git SHA

### PR DESCRIPTION
**Pull request by tamasvajk**
This PR fixes the CSV timeseries coverage report generator to handle earlier DB versions. The `--dbscheme` parameter is specified on the `codeql database finalize` call.

The following files were generated on my machine. They contain the latest stats:
[framework-coverage-timeseries-csharp-packages.csv](https://github.com/github/codeql/files/7135109/framework-coverage-timeseries-csharp-packages.csv)
[framework-coverage-timeseries-csharp.csv](https://github.com/github/codeql/files/7135110/framework-coverage-timeseries-csharp.csv)
[framework-coverage-timeseries-java-packages.csv](https://github.com/github/codeql/files/7135111/framework-coverage-timeseries-java-packages.csv)
[framework-coverage-timeseries-java.csv](https://github.com/github/codeql/files/7135113/framework-coverage-timeseries-java.csv)

The second commit changes the aggregate report to only include days when the values changed. (Requested by @turbo) See the changed files below:
[framework-coverage-timeseries-csharp.csv](https://github.com/github/codeql/files/7135360/framework-coverage-timeseries-csharp.csv)
[framework-coverage-timeseries-java.csv](https://github.com/github/codeql/files/7135362/framework-coverage-timeseries-java.csv)

### CODE REVIEW

**Comment by turbo** [comment]
I noticed that the packages column values are sometimes separated by a space, sometimes by a `, `:

```text
com.esotericsoftware.kryo.io, com.esotericsoftware.kryo5.io, com.fasterxml.jackson.core, com.fasterxml.jackson.databind, com.opensymphony.xwork2.ognl, com.unboundid.ldap.sdk, ...
```

vs:

```text
org.apache.hc.core5.* org.apache.http
```

The latter seems to happen for everything with exactly two packages.

**Comment by tamasvajk** [comment]
> I noticed that the packages column values are sometimes separated by a space, sometimes by a `, `

Thanks for reporting it, I fixed this too in a 3rd commit.

**Comment by adityasharad** [comment]
Code changes look fine. Can you explain the problem you're solving? Is it that creating a database with a stable release of CodeQL may use a dbscheme older than the dbscheme currently on `main`?

**Comment by tamasvajk** [comment]
> Code changes look fine. Can you explain the problem you're solving? Is it that creating a database with a stable release of CodeQL may use a dbscheme older than the dbscheme currently on `main`?

No. The PR fixes the opposite case, when the stable release of CodeQL has newer DB scheme than the one used by the query that we run.

This workflow is starting with the latest `github/codeql:main` and goes back in the git history to generate some statistics at selected SHAs. At each selected SHA, we create an empty DB, and then run a QL query from that given SHA. The DB is generated with the latest released CLI, so the selected SHA that we are processing might be newer or older than the CLI. This PR fixes the latter case by creating the DB with the scheme in the selected SHA. This means that the DB scheme and the evaluated query belongs to the same SHA.

The case you mentioned (current DB newer than the released CLI) was already covered by having the `--search-path` in the `codeql query run` command, which would automatically upgrade the DB if needed.

**Comment by turbo** [comment]
@adityasharad I requested the fix because previous runs [had been silently failing](https://github.com/github/codeql/runs/3545196034?check_suite_focus=true#step:7:1122) and omitting data, for the reasons Tamás highlighted above :)

**Comment by adityasharad** [comment]
> No. The PR fixes the opposite case, when the stable release of CodeQL has newer DB scheme than the one used by the query that we run.

Makes sense, thanks for explaining. A good candidate for downgrade scripts, but we haven't written any yet :) I'm glad the opposite direction is correctly handled by the automatic upgrades.

**Review by adityasharad — APPROVED** [review]

**Comment by tamasvajk** [comment]
@turbo You can find the latest run of this job (which includes these fixes) [here](https://github.com/github/codeql/actions/runs/1228620245).

**Pull request merged**
