### PR TITLE
Dataflow: Fix getLocalCc join order

### PR DESCRIPTION
**Pull request by MathiasVP**
On the C++ IR we would get this join order: `getLocalContext -> getEnclosingCallable -> localFlowEntry`, while Java got a different (and much better!) join order: `localFlowEntry -> getEnclosingCallable -> getLocalContext`.

Before (on Wireshark):
```
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/2@ae700a:
371826   ~3%     {2} r1 = SCAN DataFlowImplCommon::getLocalCallContext#cpe#12#ff AS I OUTPUT I.<1>, I.<0> 'arg1'
80607395 ~0%     {2} r2 = JOIN r1 WITH DataFlowUtil::Node::getEnclosingCallable_dispred#ff_10#join_rhs AS R ON FIRST 1 OUTPUT R.<1> 'arg0', r1.<1> 'arg1'
                  return r2
...
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#2/3@b18565:
282      ~0%     {3} r1 = JOIN DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff AS L WITH DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1 AS R ON FIRST 1 OUTPUT R.<0>, R.<1> 'arg1', L.<1> 'arg2'
                  return r1
```

After:
```
Tuple counts for DataFlowImpl3::Stage4::getLocalCc0#fff/3@2d9f53:
  143      ~0%     {3} r1 = JOIN DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff AS L WITH DataFlowUtil::Node::getEnclosingCallable_dispred#ff AS R ON FIRST 1 OUTPUT R.<1> 'callable', R.<0>, L.<1> 'config'
                    return r1
...
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@5e88d7:
  371826 ~3%     {2} r1 = SCAN DataFlowImplCommon::getLocalCallContext#cpe#12#ff AS I OUTPUT I.<1>, I.<0> 'arg1'
  282    ~1%     {3} r2 = JOIN r1 WITH DataFlowImpl3::Stage4::getLocalCc0#fff AS R ON FIRST 1 OUTPUT R.<1> 'arg0', r1.<1> 'arg1', R.<2> 'arg2'
                  return r2
```

Differences:
C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1712/
Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1176/
C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/862/
Python: https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/408/

### CODE REVIEW

**Comment by aschackmull** [comment]
Does the compiler know that `node.getEnclosingCallable()` is functional? Because otherwise that might be a simpler fix.

**Comment by MathiasVP** [comment]
> Does the compiler know that `node.getEnclosingCallable()` is functional? Because otherwise that might be a simpler fix.

It has the same unfortunate join order both on `main` and https://github.com/github/codeql/pull/5127 (which uses a `getEnclosingCallableImpl` here: https://github.com/github/codeql/pull/5127/files?file-filters%5B%5D=.qll#diff-73001a3b1f9949f0a0dbbc5653e9620fccf5d376f8709e0c960d2551d68da849R44)

**Comment by aschackmull** [comment]
Let's try `pragma[only_bind_into]` for this. That should be our default mechanism for solving join-order issues like this as it won't incur a runtime cost (adding extra predicates means more materialisation).

**Comment by MathiasVP** [comment]
> Let's try `pragma[only_bind_into]` for this. That should be our default mechanism for solving join-order issues like this as it won't incur a runtime cost (adding extra predicates means more materialisation).

Sure. I was looking for an excuse to try it anyway!

**Comment by MathiasVP** [comment]
Indeed, I was able to solve it with this using the new pragma like this:
```codeql
bindingset[node, cc, config]
private LocalCc getLocalCc(Node node, Cc cc, Configuration config) {
  localFlowEntry(pragma[only_bind_into](node), config) and
  result = getLocalCallContext(cc, node.getEnclosingCallable())
}
```
Looking forward to getting these fixes into the dataflow library!

**Comment by aschackmull** [comment]
Indeed that seems like exactly the right place to put the pragma, as that conveys the information that we want to use `localFlowEntry` to constrain `node` before joining on `getEnclosingCallable` (as the latter has a large fanout in the callable-to-node direction).

**Comment by aschackmull** [comment]
> Is this change independent of #5338?

Good question. It probably isn't, so this might indeed be fixed by #5338.

**Comment by MathiasVP** [comment]
> Good question. It probably isn't, so this might indeed be fixed by #5338.

It doesn't look like it, unfortunately. Here's the result on the current `main`:

```
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@000ba5:
  110814  ~0%     {2} r1 = SCAN DataFlowImplCommon::getLocalCallContext#2#cpe#12#ff OUTPUT In.1, In.0 'arg1'
  7139996 ~0%     {2} r2 = JOIN r1 WITH DataFlowUtil::Node::getEnclosingCallable_dispred#2#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg0', Lhs.1 'arg1'
  2062    ~0%     {3} r3 = JOIN r2 WITH DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff ON FIRST 1 OUTPUT Lhs.0 'arg0', Lhs.1 'arg1', Rhs.1 'arg2'
                  return r3
```

and on this PR:
```
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@e05d28:
  3719583 ~0%     {2} r1 = SCAN DataFlowUtil::Node::getEnclosingCallable_dispred#2#ff OUTPUT In.1, In.0 'arg0'
  7139996 ~2%     {2} r2 = JOIN r1 WITH DataFlowImplCommon::getLocalCallContext#2#cpe#12#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1 'arg0', Rhs.1 'arg1'
  2062    ~0%     {3} r3 = JOIN r2 WITH DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff ON FIRST 1 OUTPUT Lhs.0 'arg0', Lhs.1 'arg1', Rhs.1 'arg2'
                  return r3
```

**Comment by aschackmull** [comment]
> It doesn't look like it, unfortunately. Here's the result on the current `main`

Oh, but the other PR hasn't been merged to main yet.

**Comment by MathiasVP** [comment]
> Oh, but the other PR hasn't been merged to main yet.

Sorry! I meant to say that this is the current main:
```
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@000ba5:
  110814  ~0%     {2} r1 = SCAN DataFlowImplCommon::getLocalCallContext#2#cpe#12#ff OUTPUT In.1, In.0 'arg1'
  7139996 ~0%     {2} r2 = JOIN r1 WITH DataFlowUtil::Node::getEnclosingCallable_dispred#2#ff_10#join_rhs ON FIRST 1 OUTPUT Rhs.1 'arg0', Lhs.1 'arg1'
  2062    ~0%     {3} r3 = JOIN r2 WITH DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff ON FIRST 1 OUTPUT Lhs.0 'arg0', Lhs.1 'arg1', Rhs.1 'arg2'
                  return r3

```

and this is on https://github.com/github/codeql/pull/5338:

```
Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@e05d28:
  3719583 ~0%     {2} r1 = SCAN DataFlowUtil::Node::getEnclosingCallable_dispred#2#ff OUTPUT In.1, In.0 'arg0'
  7139996 ~2%     {2} r2 = JOIN r1 WITH DataFlowImplCommon::getLocalCallContext#2#cpe#12#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1 'arg0', Rhs.1 'arg1'
  2062    ~0%     {3} r3 = JOIN r2 WITH DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff ON FIRST 1 OUTPUT Lhs.0 'arg0', Lhs.1 'arg1', Rhs.1 'arg2'
                  return r3
```

**Comment by aschackmull** [comment]
Right, so we do in fact need to pragma the `node`-join. I guess we might as well fold that into `DataFlowCallable getNodeEnclosingCallable(Node n)`.

**Comment by aschackmull** [comment]
Could you try that comparison again? The head of #5338 has been changed to hopefully take this join into account.

**Comment by MathiasVP** [comment]
> Could you try that comparison again? The head of #5338 has been changed to hopefully take this join into account.

Indeed, now we get the correct join order in #5338 🎉:

```
Tuple counts for DataFlowImpl3::LocalFlowBigStep::localFlowStepPlus#ffffff#shared/3@e9ca8c:
                      1031    ~4%     {3} r1 = SCAN DataFlowImpl3::LocalFlowBigStep::localFlowEntry#ff OUTPUT In.0 'arg1', In.0 'arg1', In.1 'arg2'
                      1031    ~0%     {3} r2 = JOIN r1 WITH DataFlowUtil::Node::getEnclosingCallable_dispred#2#ff ON FIRST 1 OUTPUT Rhs.1 'arg0', Lhs.1 'arg1', Lhs.2 'arg2'
                                      return r2

Tuple counts for DataFlowImpl3::Stage4::fwdFlow0#fffff#join_rhs#1/3@72cbff:
                      2062   ~0%     {3} r1 = JOIN DataFlowImpl3::LocalFlowBigStep::localFlowStepPlus#ffffff#shared WITH DataFlowImplCommon::getLocalCallContext#2#cpe#12#ff_10#join_rhs ON FIRST 1 OUTPUT Lhs.1 'arg0', Rhs.1 'arg1', Lhs.2 'arg2'
                                     return r1
```

**Comment by MathiasVP** [comment]
Superseded by https://github.com/github/codeql/pull/5338.

**Pull request closed without merging**
