### PR TITLE
Model Spring `web.multipart`

### PR DESCRIPTION
**Pull request by sauyon**
I've skipped the `getFile` methods of `MultipartRequest`, as I assume that that's very rarely used.

### CODE REVIEW

**Comment by smowton** [comment]
Why skip them? Uploading files is reasonably common?

**Comment by sauyon** [comment]
I'd thought that was for a client request for some reason, I'll fix that...

**Comment by aschackmull** [comment]
Currently fails Java Language Tests.

**Comment by sauyon** [comment]
Ah, this was failing because I autoformatted and pushed to the wrong branch; fixed.

**Review by aschackmull — APPROVED** [review]

**Pull request merged**
