### PR TITLE
Python: Two fixes regarding annotated assignments

### LINKED ISSUE #2652: LGTM.com - false positive - unused python locals with typehints incorrectly
**Description of the false positive**

Adding a descriptive type-hint to an existing variable is treated as if it is redefining the variable, when it is not.

image

https://lgtm.com/projects/gl/nekokatt/hikari/snapshot/1a1a0346e6e0529199a5dd80a9bb8e42a761926f/files/hikari/orm/state/state_registry_impl.py#x4d28be86792861e0:1

Example:
```py
def do_something_with(foo: Eggs):
    ...

def do_something_else_with(foo: Spam):
    ...

foo = bar()  # `Value assigned to "foo" is never used' (yes it is!!!)

if baz:
    foo: Eggs
    do_something_with(foo)
else:
    foo: Spam
    do_something_else_with(foo)
```

### PR DESCRIPTION
**Pull request by tausbn**
Fixes #2652 and a bunch of other FPs seen in the wild.

Should not require a change note.

Will probably need performance testing, although I expect the number of new `DefinitionNode`s to be rather low.

### CODE REVIEW

**Review by RasmusWL — DISMISSED** [review]
Looks good to me.

Should we care to add a test-case such as

```py
def func():
    foo = 5
    foo: int
    return "foo is unused"
```

which I think should be marked by `py/unused-local-variable`, but probably won't since it now has a type-hint. I don't think it's **super** important, just thinking out loud.

**Comment by tausbn** [comment]
Sure, why not. :+1:

**Review by RasmusWL — COMMENTED** [review]
thanks :muscle: besides performance test, this looks good to me :+1:

**Review by RasmusWL — APPROVED** [review]
LGTM :+1: (performance also looks fine)

**Pull request merged**
