### PR TITLE
Swift: Correct a couple of FilePath models.

### PR DESCRIPTION
**Pull request by geoffw0**
Very minor fixes for the `FilePath` model.

The existing [tests for this](https://github.com/github/codeql/blob/main/swift/ql/test/library-tests/dataflow/taint/libraries/files.swift#L151) are unaffected.

### CODE REVIEW

**Review by MathiasVP — COMMENTED** [review]
Would it be possible to ... add a test that shows the difference?

**Comment by geoffw0** [comment]
> Would it be possible to ... add a test that shows the difference?

Will do.

Note that I don't in general write tests for every single MAD source or sink - particularly when there are many similar ones, I feel that testing one of a set of near identical rows is often sufficient.

**Comment by MathiasVP** [comment]
> Note that I don't in general write tests for every single MAD source or sink - particularly when there are many similar ones, I feel that testing one of a set of near identical rows is often sufficient.

Good point. I just think it would be valuable as a justification for why this rewrite was necessary.

**Review by MathiasVP — APPROVED** [review]
Thank you 🙇!

**Pull request merged**
