### PR TITLE
Python: Enclosing callable for synthetic arguments

### PR DESCRIPTION
**Pull request by yoff**
We had consistency failures because synthetic arguments do not have enclosing callables.

### CODE REVIEW

**Review by RasmusWL — COMMENTED** [review]
Would it be possible to see this change in action with some tests? :blush:

**Comment by yoff** [comment]
Yes, that should be fairly easy. I split it out because my endeavours to fix all the inconsistencies I could find turned out to be a longer process. I should add a small function call to the inconsistency test files for each type of synthetic argument.

**Comment by yoff** [comment]
Added tests, rearranged history and made tests be run after each commit, and force-pushed. I realize that it would be even better to enable the three fixes on at a time and see the failures disappear, let me know if you want that.

It also exposed a new failure :-)

**Review by RasmusWL — APPROVED** [review]
Nice :+1:. Thanks for rearranging history to make things easy. For this case, it's simple enough that I don't need separate commits, but it's good to keep in mind for more tricky cases :+1: (that is, if each fix needed 100 lines of QL code, having 3 separate commits would be nice)

**Pull request merged**
