### PR TITLE
Swift: Models and tests for numeric conversions

### PR DESCRIPTION
**Pull request by geoffw0**
Add models and tests for (mostly) numeric conversions.

Fixed a flow issue with `OptionalSomePattern` I bumped into on the way.

TODO:
- [x] can we catch this one as well:
```
	sink(arg: [UInt8](sourceString().utf8)) // $ MISSING: tainted=
```
- [x] DCA run

### CODE REVIEW

**Review by d10c — COMMENTED** [review]
LGTM

**Comment by geoffw0** [comment]
Fixed merge conflicts.  Changes after the merge need a quick review.

There were a number of changes to various test results as a result of the merge.  One was a good change, the other two were undesirable.  I've addressed them by adding proper barriers for `Numeric` values (in particular `Int`) in five injection-like queries.  Previously we were depending on data flow not actually working through the constructs that were involved.

**Comment by geoffw0** [comment]
... I should probably add a second change note for the barriers ...

**Comment by geoffw0** [comment]
Second change note added (with no mention of the command injection query as it's still in experimental).

And added the numeric barrier to the regular expression injection query as well.

**Review by d10c — APPROVED** [review]
Looks good  :shipit:

**Pull request merged**
