### PR TITLE
Java: Use the instance argument type in call contexts.

### PR DESCRIPTION
**Pull request by aschackmull**
This improves the call contexts used in data flow by also considering the type of the instance argument. Recent experience from C# has shown this to be especially helpful when dealing with the visitor pattern.

### CODE REVIEW

**Comment by hvitved** [comment]
Curious to see what the effect is on performance and results.

**Comment by aschackmull** [comment]
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/866/

**Comment by aschackmull** [comment]
With a suitable test configuration in scope, quick-eval'ing the following on JDK11 yields:
```
    pn = count(PathNode pn_) and
    pnr = count(PathNode pn_ | reach(pn_))
```
| | pn | pnr |
| ---- | --- | --- |
| Before | 315048 | 238285 |
| After | 306711 | 206954 |

**Comment by aschackmull** [comment]
I've rebased and rerun the tuple counts since we now apply call contexts in the final pruning stage. Numbers are still looking good:
|  | fwd4 | nc4 | fwd4t | nc4t | pn | pnr |
| ---- | --- | --- | ---- | --- | --- | --- |
| Before | 113281 | 108944 | 403062 | 322831 | 313277 | 238199 |
| After | 108602 | 104193 | 392612 | 305260 | 303797 | 206388 |

**Comment by aschackmull** [comment]
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/877/

**Review by aibaars — APPROVED** [review]
Looks good to me.

**Comment by hvitved** [comment]
Seems like this had real impact 🎉 :
```
java/tainted-arithmetic                                                     +0 -99
java/uncontrolled-arithmetic                                                +0 -113
```

**Pull request merged**
