### PR TITLE
Python: Handle diagnostics writing for `BuiltinModuleExtractable`

### PR DESCRIPTION
**Pull request by RasmusWL**
In the hopes this will fix a problem encountered in the wild (that I couldn't reproduce locally).

I couldn't find any tests that I could easily extend to test the new behavior either, so what I did was to locally alter `BuiltinExtractor` to always throw an exception. I observed this causes us to generate `Exception: 'BuiltinModuleExtractable' object has no attribute 'path'` in the logs.

With the commits from this PR, we now properly log the failure reason:

```
[2024-07-09 14:07:25] [build-stdout] [ERROR] [15] Failed to extract module _datetime: <exception-reason>
[2024-07-09 14:07:25] [build-stdout] [TRACEBACK] [15] "semmle/worker.py", line 263, in _extract_loop
[2024-07-09 14:07:25] [build-stdout] [TRACEBACK] [15] "semmle/extractors/super_extractor.py", line 34, in process
[2024-07-09 14:07:25] [build-stdout] [TRACEBACK] [15] "semmle/extractors/builtin_extractor.py", line 24, in process
```

and generate diagnostics such as (EDIT: updated to not include location after 
354394d)

```
{"timestamp": "2024-07-12T13:40:41.728383", "source": {"id": "py/diagnostics/internal-error", "name": "Internal error in Python extractor", "extractorName": "python"}, "severity": "error", "plaintextMessage": "Internal error", "visibility": {"statusPage": false, "cliSummaryTable": false, "telemetry": true}, "attributes": {"traceback": ["\"semmle/worker.py\", line 263, in _extract_loop", "\"semmle/extractors/super_extractor.py\", line 34, in process", "\"semmle/extractors/builtin_extractor.py\", line 24, in process"], "args": ["<exception-reason>"]}}
```

I'm not 100% sure if the tooling will be happy with the fake "file" here, so want to confirm that before merging this PR.

EDIT: I forgot to mention I also tried inserting an exception in `internal_error_message` function, to verify _that_ error handling also works :+1:

```
[2024-07-09 14:15:07] [build-stdout] [WARN] [7] Failed to write diagnostics: <exception-reason>
[2024-07-09 14:15:07] [build-stdout] [TRACEBACK] [7] "semmle/worker.py", line 263, in _extract_loop
[2024-07-09 14:15:07] [build-stdout] [TRACEBACK] [7] "semmle/extractors/super_extractor.py", line 34, in process
[2024-07-09 14:15:07] [build-stdout] [TRACEBACK] [7] "semmle/extractors/builtin_extractor.py", line 24, in process
[2024-07-09 14:15:07] [build-stdout] [TRACEBACK] [7] "semmle/worker.py", line 290, in _extract_loop
[2024-07-09 14:15:07] [build-stdout] [TRACEBACK] [7] "semmle/logging.py", line 387, in internal_error_message
```

### CODE REVIEW

**Review by sidshank — DISMISSED** [review]
LGTM! I like the extra information being logged, and presumably the shift from unhandled exception to warning should allow extraction to continue (and not fail).

**Review by tausbn — DISMISSED** [review]
Looks good to me. 👍 
I'm still somewhat surprised that this error is occurring at all, but I think this should fix it.

**Comment by molson504x** [comment]
Hey @RasmusWL - chiming in because you'd commented you weren't sure how to test this out and couldn't reproduce locally.  I've got a way you can test this (this is an example of how we found this in the wild).  This client is using AmazonLinux to build their runner images, and AmazonLinux handles cryptography functions in a weird way because of FIPS compliance.  I targeted the python `hashlib` library because of that (and because of finding this in the debug output of CodeQL:

> [2024-07-09 15:42:05] [build-stdout] [DEBUG] [24] Trying built-in extractor on module _blake2
> Error: 7-09 15:42:05] [build-stdout] [ERROR] [24] Exception: 'BuiltinModuleExtractable' object has no attribute 'path'

I wrote a small python script which would try to create a blake2 hash, and ran it in python 3.9 in AL2, AL2023, and Ubuntu (Ubuntu was running 3.10).  Here's the script:

``` py
from hashlib import blake2b
h = blake2b()
h.update(b'Hello world')
print(h.hexdigest())
```

On AmazonLinux, it failed because blake2b (and blake2s) don't exist in hashlib.  On Ubuntu, it works fine and produced a hex digest.

In theory, running this same python script through CodeQL's Python Extractor on AmazonLinux and on Ubuntu should be a good sanity check to test this.  AmazonLinux is available from dockerhub, so in theory you should be able to spin up a AL2 or AL2023 container locally and just run the CodeQL CLI there to reproduce the error.

**Review by tausbn — APPROVED** [review]

**Comment by RasmusWL** [comment]
Thanks @molson504x, that's really valuable context :+1: When the change from this PR is applied, we will still have the same underlying problem with `blake2`, it just wont cause the extractor to crash. (and we'll investigate the underlying problem separately :+1:)

_oh, I forgot to actually submit this comment :see_no_evil:_

**Pull request merged**
