### PR TITLE
QL Language specification. Fix multiple spec bugs.

### PR DESCRIPTION
**Pull request by alexet**
There fixes a mixture of mistakes, missing parts and also changes that have been made over the years that never made it into the spec. The main changes are

- Fields have a runtime spec
- Predicate resolution is fixed to handle primitives and certain calls correctly.
- Overriding and member-predicate resolution now handles "side overriding" correctly (when inherit both a predicate and an one that overrides it it is not ambiguous).
- Qldoc is parsed rather than being a special type of comment.

This fixes many of the most glaring issues I noticed when reading through. This was orginally a few small fixes that got a bit out of hand as I realised how broken the spec had become. There are still some major omissions from the spec but I have made issues for them.

### CODE REVIEW

**Comment by shati-patel** [comment]
Thanks for tidying up some of this stuff, @alexet 🎉  I'll take a look shortly! (I might raise a PR against your branch to fix some of the Sphinx warnings.)

**Comment by shati-patel** [comment]
See https://github.com/alexet/ql/pull/1!

**Comment by alexet** [comment]
Thanks, I have incorporated your suggestions. For future reference is there a way I can build this locally easily. I was building it with the vscode extension to check but it looks like we check things in a stricter way.

**Review by shati-patel — APPROVED** [review]
LGTM, assuming the tests now pass!

> Thanks, I have incorporated your suggestions. For future reference is there a way I can build this locally easily. I was building it with the vscode extension to check but it looks like we check things in a stricter way.

If you have sphinx installed, you can run:

```
sphinx-build -W -b html  <path-to-codeql-repo>/docs/codeql  <output-dir>
```

(The `-W` flag makes sure any warnings are treated as errors.)

**Pull request merged**
