### PR TITLE
C++: Test and improve cpp/improper-null-termination

### PR DESCRIPTION
**Pull request by geoffw0**
Add tests for `cpp/improper-null-termination`, and make several improvements to the `readlink` case.

It currently lacks an `@precision` tag, I'm aiming to give it `@precision high` at some point in future, but I need to spend more time looking at results (and perhaps making further improvements) first.

### CODE REVIEW

**Comment by geoffw0** [comment]
Looks like an internal test has failed (just one case).  I'll fix it after this PR is reviewed, to avoid having to update the fix over and over.

**Review by MathiasVP — COMMENTED** [review]
LGTM!

**Comment by geoffw0** [comment]
Internal PR: https://github.com/github/semmle-code/pull/39892

**Comment by MathiasVP** [comment]
Should we provide a change note for this PR, @geoffw0? Or should we wait until we bring its precision to `high`?

**Review by MathiasVP — APPROVED** [review]
Merging to avoid internal submodule conflict. We can always add a change note later.

**Comment by geoffw0** [comment]
Yep, I'll add a note to the ticket about writing a proper change note when we increase the precision.

**Pull request merged**
