### PR TITLE
C++: Use heuristic allocation functions in `cpp/overrun-write`

### PR DESCRIPTION
**Pull request by MathiasVP**
This expands the set of sources for `cpp/overrun-write` by including heuristic allocation sources. On MRVA this gives about 40 new results - all of which look like good results 🎉.

As an extra bonus I expanded the heuristic to also consider function names including `"Alloc"` (instead of just `"alloc"`). This makes us catch allocations such as these ones: https://github.com/tianocore/edk2/blob/5215cd5baf6609e54050c69909273b7f5161c59e/BaseTools/Source/C/DevicePath/DevicePathUtilities.c#L729-L729 and https://github.com/NVIDIA/open-gpu-kernel-modules/blob/6dd092ddb7c165fb1ec48b937fa6b33daa37f9c1/src/nvidia/src/kernel/platform/nbsi/nbsi_init.c#L2656-L2656

### CODE REVIEW

**Review by geoffw0 — APPROVED** [review]
This seems like a sensible change.  There's a risk that `HeuristicAllocationExpr.getSizeExpr()` may match the wrong parameter or a parameter with slightly different meaning that wouldn't happen with `AllocationExpr.getSizeExpr()`.  But if the MRVA results look good and DCA doesn't throw anything up either, I'm happy that this is quite unlikely.

**Comment by MathiasVP** [comment]
> This seems like a sensible change. There's a risk that HeuristicAllocationExpr.getSizeExpr() may match the wrong parameter or a parameter with slightly different meaning that wouldn't happen with AllocationExpr.getSizeExpr(). But if the MRVA results look good and DCA doesn't throw anything up either, I'm happy that this is quite unlikely.

There's actually no such risk. The heuristic allocation implementation is defined with the following charpred:
```ql
HeuristicAllocationFunctionByName() {
  Function.super.getName().matches(["%alloc%", "%Alloc%"]) and
  Function.super.getUnspecifiedType() instanceof PointerType and
  sizeArg = unique( | | getAnUnsignedParameter(this))
}
```
meaning that there's only one parameter with an unsigned integer type, and we pick that one as the size.

**Comment by geoffw0** [comment]
Yeah, I agree that `unique` is an excellent countermeasure, but there is still some remaining risk.  For example you could reasonably have:
```
void *myAllocateForStringWithLength(unsigned int length) {
  return malloc(length + 1); // leave room for terminator
}

char *str = (char *)myAllocateForStringWithLength(5);
strcpy(str, "12345"); // GOOD (6 bytes allocated, 6 bytes copied)
```
To be clear I don't think we need to address this, just keep an open mind when we're reviewing new results.

**Comment by MathiasVP** [comment]
Yeah, that's a good point. I think we've worked around issues like that in the past by excluding heuristic allocation functions that wrapped an _actual_ allocation function.

In any case, there are a few new results on `cpp/overrun-write` (because of the switch to heuristic allocation), and on some of the other queries that use heuristic allocation functions (because we now also include `Alloc` as a substring).

**Comment by geoffw0** [comment]
Let me know if you'd like help looking through any of the results.

**Comment by MathiasVP** [comment]
Will do - thanks 🙇! None of the results were super difficult so I've looked at them all already.

**Comment by MathiasVP** [comment]
I have a performance fix locally that I'll open in as a follow-up to this PR. Merging this!

**Pull request merged**
