### PR TITLE
Util: Use end line instead of start line for actual results

### PR DESCRIPTION
**Pull request by hvitved**
This PR changes the semantics of the inline test expectations framework, from using start-line to using end-line for actual results (we still use start-line for expected results).

The motivation for this is that two entities may share start line, which makes it impossible to add unambiguous test expectations. For example, for chained calls
```csharp
M1().
M2()
```
both calls have the same start-line (the output of the call to `M1` is an argument of the call to `M2`), but they have different end lines. By using end-line instead of start-line, we can meaningfully add expectations such as
```csharp
M1(). // $ calls=M1
M2() // $ calls=M2
```

### CODE REVIEW

**Review by tausbn — APPROVED** [review]
Python bits look good to me. 👍

**Review by owen-mc — APPROVED** [review]
I think it looks slightly worse, but maybe I'm just used to the old way, and you do give at least one advantage. Approved for go.

**Review by MathiasVP — APPROVED** [review]

**Review by atorralba — APPROVED** [review]
Java 👍

**Review by geoffw0 — APPROVED** [review]
Swift :+1:.  We're adding a lot of tests and models at the moment, I would appreciate if you merge in latest `main` and re-run the checks just before merging.

**Review by erik-krogh — APPROVED** [review]

**Pull request merged**
