### PR TITLE
Java: Fix taint-step handling for untrusted-data-external-api

### PR DESCRIPTION
**Pull request by RasmusWL**
The previous implementation would not handle any `AdditionalTaintStep` subclasses.

/cc @lcartey (since I'm not able to put your as assigned or reviewer)

### CODE REVIEW

**Comment by aschackmull** [comment]
I don't think this is the right fix. Instead `localTaintStep` ought to use `defaultAdditionalTaintStep` instead of `localAdditionalTaintStep`.

**Comment by aschackmull** [comment]
On second thought, this is fine (modulo keeping both `localTaintStep` and `defaultAdditionalTaintStep` instead of replacing one with the other).

**Comment by RasmusWL** [comment]
:+1: done @aschackmull

**Review by aschackmull — APPROVED** [review]
LGTM.

**Pull request merged**
