### PR TITLE
C++/C#: Allow memory operands to lack a definition

### PR DESCRIPTION
**Pull request by dbartol**
Another step toward https://github.com/github/codeql-c-analysis-team/issues/69

We want to reuse `TOperand` objects across IR phases. Before we can do this, we have to ensure that the parameters to the IPA constructors for those shared operands do not contain data that changes between phases. `RegisterOperand`s will always keep the same definition across all phases, but `NonPhiMemoryOperand`s may wind up with different definitions in different phases, depending on how precise SSA's alias analysis is. Furthermore, in order to remove all `UnmodeledDefinition` instructions, we have to allow for the possibility that a `NonPhiMemoryOperand` will not have a definition at all.

This change first refactors `Operand.qll` into a form closer to what we will want once the `TOperand` IPA type is shared across phases. I've wrapped each branch of the IPA type in a private class, and `Operand` and subclasses now extend one or more of those private classes, rather than extending an IPA type or branch directly. Once we actually have IPA branch union type support, we can implement the IPA branches in a single shared file, expose the base operand types as union types with the right names, and we shouldn't have to change the rest of `Operand.qll`.

I looked at the RA diffs from this refactoring, and other than predicate names, the only thing that changed was that the optimizer was able to replace a use of `Operand::PositionalArgumentOperand#class#fffff` with a use of `Operand::PositionalArgumentOperand::getIndex_dispred#ff`, which has the same RA body except that it uses two fewer columns.

The second commit removes the `defInstr` and `overlap` parameters from `TNonPhiMemoryOperand`. The `TNonPhiMemoryOperand` objects are now created by simply asking the `Opcode` if it expects an operand with that tag. The actual lookup of definitions for those operands now happens in `NonPhiMemoryOperand::hasDefinition()`, which has essentially the same implementation as the old constructor for `TNonPhiMemoryOperand`. Other than introducing a dedupe operation to cope with the potential for an operand having multiple overlap values, the RA for the important `Operand::getAnyDef()` predicate is pretty much the same as before.

As a useful side effect, this change partially fixed an existing bug where we would create two `Operand`s with the same use instruction and tag because SSA construction was giving two different `Overlap` values for the operand's definition. The SSA bug is still there, but now we only create one `Operand` with two values for `getDefinitionOverlap()`, rather than two `Operand`s each with a single value for `getDefinitionOverlap()`. The `.expected` file that I fixed still has one consistency failure caused by that SSA bug, because one of the two `Overlap` values is `MayPartiallyOverlap`, which is invalid.

### CODE REVIEW

**Comment by MathiasVP** [comment]
While looking for something completely different I noticed that, on `master`, the tuple counts for `AliasAnalysis::addressOperandAllocationAndOffset#fff#antijoin_rhs` on `ffmpeg` is:

```
Tuple counts for AliasAnalysis::addressOperandAllocationAndOffset#fff#antijoin_rhs:
4473570 ~3%     {3} r1 = SCAN AliasAnalysis::hasBaseAndOffset#fff AS I OUTPUT I.<1>, I.<0>, I.<2>
4394757 ~8%     {4} r2 = JOIN r1 WITH Operand::Operand::getUse_dispred#ff_10#join_rhs AS R ON FIRST 1 OUTPUT R.<1>, r1.<1>, r1.<0>, r1.<2>
4170332 ~0%     {4} r3 = JOIN r2 WITH Operand::Operand::getDef_dispred#2#ff AS R ON FIRST 1 OUTPUT r2.<1>, R.<1>, r2.<2>, r2.<3>
2147396 ~2%     {3} r4 = JOIN r3 WITH project#AliasAnalysis::hasBaseAndOffset#fff AS R ON FIRST 2 OUTPUT r3.<0>, r3.<2>, r3.<3>
                return r4
```

and with this PR it is:
```
Tuple counts for AliasAnalysis::addressOperandAllocationAndOffset#fff#antijoin_rhs:
4473570  ~3%     {3} r1 = SCAN AliasAnalysis::hasBaseAndOffset#fff AS I OUTPUT I.<1>, I.<0>, I.<2>
4394771  ~0%     {4} r2 = JOIN r1 WITH Operand::Operand::getUse_dispred#ff_10#join_rhs AS R ON FIRST 1 OUTPUT r1.<1>, r1.<0>, r1.<2>, R.<1>
20309491 ~0%     {5} r3 = JOIN r2 WITH project#AliasAnalysis::hasBaseAndOffset#fff AS R ON FIRST 1 OUTPUT r2.<3>, R.<1>, r2.<0>, r2.<1>, r2.<2>
2147396  ~2%     {3} r4 = JOIN r3 WITH Operand::Operand::getDef_dispred#2#ff AS R ON FIRST 2 OUTPUT r3.<2>, r3.<3>, r3.<4>
                 return r4
```

**Comment by dbartol** [comment]
😔

**Comment by dbartol** [comment]
@MathiasVP Which of the several `ffmpeg` projects from lgtm.com were you testing?

**Comment by MathiasVP** [comment]
> @MathiasVP Which of the several `ffmpeg` projects from lgtm.com were you testing?

https://lgtm.com/projects/g/FFmpeg/FFmpeg/ci/. It should be commit `876cfa67f37e944b0f42cb67b2de4e2e06f52e82`

**Comment by dbartol** [comment]
`unique` FTW!

**Pull request merged**
