### PR TITLE
C++: Operands as dataflow nodes

### PR DESCRIPTION
**Pull request by MathiasVP**
This PR introduces operands as dataflow nodes, which should hopefully fix a [long list of problems](https://github.com/github/codeql-c-analysis-team/issues/104).

Commit 7530dc2 hides operands from path-explanations using the `nodeIsHidden` predicate introduced in https://github.com/github/codeql/pull/3657. I don't know if this is actually what we want to do, but it's at least nice to have when reviewing the accepted test changes.

I've started a CPP-differences: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1234/

If that looks alright I'll take the PR out of draft mode.

### CODE REVIEW

**Comment by rdmarsh2** [comment]
There are a few more cases where flow needs to go through operands, mostly where we may want to put a barrier on an operand rather than either the defining instruction or the use instruction. I think that mostly applies to operands that are used in a different block than their definition.

**Comment by MathiasVP** [comment]
> There are a few more cases where flow needs to go through operands, mostly where we may want to put a barrier on an operand rather than either the defining instruction or the use instruction. I think that mostly applies to operands that are used in a different block than their definition.

I agree there are more cases that needs flow through operands, but maybe it makes sense to keep the changes in this PR small and have separate PRs that add flow through operands in the cases where we need it?

**Comment by jbj** [comment]
How is performance now?

> There are a few more cases where flow needs to go through operands, mostly where we may want to put a barrier on an operand rather than either the defining instruction or the use instruction. I think that mostly applies to operands that are used in a different block than their definition.

I thought it wasn't just a few more cases but every single case. I imagine that from now on our data-flow paths (before the big-step transformation) will always be of the form ... -> Instruction -> Operand -> Instruction -> Operand -> ... . Data will flow through all operands with exact overlap. Our existing `simpleInstructionLocalFlowStep` rules will change to specify flow from operands to instructions.

I'm fine with delaying those changes to a follow-up PR.

**Comment by MathiasVP** [comment]
> How is performance now?

This is the performance of the current state of the PR: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1234/

> I thought it wasn't just a few more cases but every single case. I imagine that from now on our data-flow paths (before the big-step transformation) will always be of the form ... -> Instruction -> Operand -> Instruction -> Operand -> ... . Data will flow through all operands with exact overlap. Our existing simpleInstructionLocalFlowStep rules will change to specify flow from operands to instructions.

This is what I did in a0bfbda51cd2ed6aa3338859b9e97713e19d94e4: I modified `simpleInstructionLocalFlowStep` to be operand -> instruction flow, and included all instruction -> operand flow.

I ran a CPP-differences for this: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1229/. It shows a 10% performance regression due to a larger `simpleLocalFlowStep` relation (since the instruction -> operand flow adds quite a number of tuples).

**Comment by jbj** [comment]
Thanks for clarifying. I had not been following the previous iterations of this PR.

I'll leave the final review/merge to @rdmarsh2.

**Pull request merged**
