### PR TITLE
Java: pick an arbitrary representative location when an entity has many candidate locations.

### PR DESCRIPTION
**Pull request by smowton**

### CODE REVIEW

**Review by aschackmull — DISMISSED** [review]
LGTM.

**Comment by smowton** [comment]
@aschackmull I needed to do some join-order engineering after this perturbed InlineExpectationsTest into a bad enough order that tests were timing out.

**Review by michaelnebel — APPROVED** [review]
Looks plausible to me!

**Review by erik-krogh — APPROVED** [review]
QL-for-QL 👍

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
