### PR TITLE
Dataflow: Fix a couple of join-orders.

### PR DESCRIPTION
**Pull request by aschackmull**
Easy wins.

### CODE REVIEW

**Review by geoffw0 — COMMENTED** [review]
Changes seem reasonable to me.  Do you have any performance data / can you run DCA on this?

**Review by tausbn — DISMISSED** [review]
Looks reasonable to me. 

Is `assume_small_delta` available in a currently-released version of the CodeQL CLI? If not, we might want to hold off on merging this until that is the case, so we don't suddenly break things for our users.

**Comment by aschackmull** [comment]
> can you run DCA on this

Will do.



> Is `assume_small_delta` available in a currently-released version of the CodeQL CLI

It's currently bleeding edge, so you have to compile your own CLI to try it out, but it'll be in the next release. So yes, we should hold the merge until then.

**Comment by aschackmull** [comment]
This should btw. be a noop in most common case (because the standard order won't be chosen), but it should measurably improve performance for queries with very large data flow graphs, i.e. on large databases or other otherwise poorly performing cases.

**Review by hvitved — DISMISSED** [review]
Let's see what DCA says.

**Comment by aschackmull** [comment]
Can't get dca for swift to work, but all other languages look uneventful, so I'd say LGTM from dca.

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
