### PR TITLE
Data flow: Add consistency checks for parameter positions

### PR DESCRIPTION
**Pull request by hvitved**
Adds two new consistency checks:
- No two parameters (in the same callable) with overlapping parameter positions, and
- No parameters with multiple parameter positions.

### CODE REVIEW

**Comment by hvitved** [comment]
@MathiasVP : Note that one of the consistency checks fails for C++.

**Review by aschackmull — APPROVED** [review]
LGTM!

**Comment by MathiasVP** [comment]
> @MathiasVP : Note that one of the consistency checks fails for C++.

Thanks for the heads up 👍.

**Comment by THEWZRD23** [comment]
no

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
