### PR TITLE
Dataflow: Add empty provenance column to PathGraph.

### PR DESCRIPTION
**Pull request by aschackmull**
This adds a column for provenance information to the PathGraph as preparation for alert provenance. In this PR the column is just added without any actual provenance information - that will be filled in a subsequent PR.

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
C++/Swift(/dataflow) LGTM!

**Review by michaelnebel — APPROVED** [review]
C# LGTM!

**Review by atorralba — DISMISSED** [review]
Java 👍 (aside from some tests failing that'll need an internal PR)

**Review by hvitved — APPROVED** [review]

**Comment by aschackmull** [comment]
Rebased to resolve conflicts.

**Review by hvitved — APPROVED** [review]

**Pull request merged**
