### PR TITLE
All: delete outdated deprecations

### PR DESCRIPTION
**Pull request by erik-krogh**
Similar to last time: https://github.com/github/codeql/pull/14403

### CODE REVIEW

**Review by michaelnebel — APPROVED** [review]
C#: LGTM!

**Review by jketema — APPROVED** [review]
C++ 👍

**Review by hvitved — APPROVED** [review]

**Review by atorralba — APPROVED** [review]
Java 👍

**Review by smowton — APPROVED** [review]
Go 👍

**Review by aibaars — APPROVED** [review]

**Review by tausbn — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
