### PR TITLE
C++: QLDoc Pure.qll

### PR DESCRIPTION
**Pull request by geoffw0**
Another old QLDoc improvement branch I found on my machine.  There isn't a lot here and the classes affected are (now?) private, but this is still an improvement.

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
Should it be `side-effect-free` or `side effect-free`?

**Comment by geoffw0** [comment]
> Should it be side-effect-free or side effect-free?

I think it should be the secret third option, `side-effect free`.  I don't mine `side-effect-free`.  But `side effect-free` looks wrong to me now.

**Review by criemen — DISMISSED** [review]
LGTM, feel free to merge with the `side-effect free` in the wording.

Restarted PR tests, the distro-test failure doesnt' come from this PR.

**Comment by geoffw0** [comment]
I've made the `side-effect free` change.

**Review by criemen — APPROVED** [review]
LGTM, please merge when the CI is green.

**Comment by criemen** [comment]
Ha, seems your search-and-replace hit the JS library as well.
I guess we can merge the PR as low-impact without their approval.

**Comment by geoffw0** [comment]
> Ha, seems your search-and-replace hit the JS library as well.

Whoops - I was aware it went beyond the original file this PR was about, but didn't mean to escape cpp.

We _should_ have cross-language consistency for these kinds of things, so in that way it's good - but if anyone doesn't like my chosen solution, I'll be happy to discuss and implement another way.

**Pull request merged**
