### PR TITLE
small refactorizations across CodeQL

### PR DESCRIPTION
**Pull request by erik-krogh**
I applied all my automatic patches to all the code in `github/codeql`.  
The result wasn't overwhelming, so I opened this PR with the result.  

This PR reduce the number code-scanning warnings by about 200.

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Java :+1:

**Review by hvitved — COMMENTED** [review]
C# and Ruby 👍

**Review by esbena — COMMENTED** [review]
JS :+1:

**Review by aschackmull — APPROVED** [review]

**Review by MathiasVP — APPROVED** [review]

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
