### PR TITLE
Java: Non-Production interface

### PR DESCRIPTION
**Pull request by haby0**
Attackers can use the legacy test interface in the production system to collect information or use functions that were otherwise unavailable. Non-production interfaces are insecure by default, and should not reside on the production system because they may leak sensitive information or functions of the system.

In addition, because many non-production interfaces are not intended to be used in a production environment, they do not have sufficient security controls or may not have undergone rigorous testing. Therefore, they may contain many flaws and loopholes, which may cause the adversary to seriously damage the target.

### CODE REVIEW

**Comment by haby0** [comment]
@tamasvajk Sorry, Non-Production interface ql I need to modify, after modifying, I will ping you.

**Comment by haby0** [comment]
@tamasvajk 

Hi friend, I made some changes to ql:
- Now supports the detection of `pom.xml`;
- Because `CodeQL` does not support the analysis of `build.gradle`, it does not support the detection of `build.gradle` for the time being

Please review, look forward to reply,Thanks!

**Comment by haby0** [comment]
hi @tamasvajk, Do you have any suggestions about this pr?

**Comment by m-y-mo** [comment]
@haby0 
Unfortunately, after reviewing the results, we have decided to reject this submission due to the high false positive rate and that there isn't much that can be done to improve the query. The query tries to identify test code in a production code base. However, it is normal for a repository to include test code and code that is included in a repository does not necessarily get deployed in production. As there is no clear way to determine which code gets deployed for production from inspecting the source code alone, we believe there is not much that can be done to improve the false positive rate of the query and hence decided to reject it. Thank you very much for your submission and sorry about the disappointment.

**Comment by haby0** [comment]
> @haby0
> Unfortunately, after reviewing the results, we have decided to reject this submission due to the high false positive rate and that there isn't much that can be done to improve the query. The query tries to identify test code in a production code base. However, it is normal for a repository to include test code and code that is included in a repository does not necessarily get deployed in production. As there is no clear way to determine which code gets deployed for production from inspecting the source code alone, we believe there is not much that can be done to improve the false positive rate of the query and hence decided to reject it. Thank you very much for your submission and sorry about the disappointment.

I don't quite understand what you mean.
- This query is for the test interface in the non-test directory, not the test code.
- The code contained in the repository may not necessarily be deployed in a production environment. I think there is a doubt in the statement. The repository code does not guarantee that it is only stored.

**Pull request closed without merging**
