### PR TITLE
Go: Enable GoKit module into the default list

### PR DESCRIPTION
**Pull request by tunnelshade**
### Changes

Enable GoKit framework by default in `go.qll`

### CODE REVIEW

**Comment by owen-mc** [comment]
Is there a particular reason you think we should include it in the default list now? The reasoning behind the current situation is [here](https://github.com/github/codeql-go/pull/451#issuecomment-760351924).

**Comment by smowton** [comment]
Presumably when adding this in https://github.com/github/codeql/commit/3ed9e66c7a43e93749a8598971ceae4dadc29e24 the idea must have been that it's common for gokit to be used in a scenario where "remote" data is actually coming from another microservice under our control and the data is in fact trusted. What makes you think it ought to be enabled by default?

**Comment by tunnelshade** [comment]
Thanks for the context around why this is an opt-in and not a default. My reasoning is two fold:

- `GoKit` is also used by externally exposed applications as well ([an api gateway example](https://github.com/go-kit/examples/blob/master/apigateway/main.go) existed since long time), as it can support different transports and serialisation including JSON over HTTP. Even if it used for inter service calls, security issues often arise due to the differing assumptions around data sanitisation across service boundaries.
- `GoKit` is very similar in abstractions for when compared to `GoMicro`, which is [included](https://github.com/github/codeql/blob/e9e58d97be1b60b8975419e899a9a7323af8bd62/go/ql/lib/go.qll#L43C34-L43C34) by default.

I do not have enough large enough dataset around usage types of `GoKit` library, but if the team strongly feels that this should remain an opt-in due to known data/usage patterns; it makes sense.

**Comment by owen-mc** [comment]
After some internal discussion we agree with you.

Please remove the line `import semmle.go.frameworks.GoKit` from `go/ql/test/library-tests/semmle/go/frameworks/GoKit/untrustedflowsource.ql`.

**Comment by tunnelshade** [comment]
Ping @owen-mc

**Review by owen-mc — APPROVED** [review]
Thank you for this contribution.

**Pull request merged**
