### PR TITLE
Swift: Add Unsafe Unpacking Query (CWE-022)

### PR DESCRIPTION
**Pull request by maikypedia**
This pull request adds a query for Unsafe Unpacking covering [Zip](https://github.com/marmelroy/Zip) and [ZIPFoundation](https://github.com/weichsel/ZIPFoundation).

Looking forward to your suggestions.

### CODE REVIEW

**Comment by ghsecuritylab** [comment]
Hello maikypedia 👋
You have submitted this pull request as a bug bounty report in the [github/securitylab](https://github.com/github/securitylab) repository and therefore this pull request has been put into draft state to give time for the GitHub Security Lab to assess the PR. When GitHub Security Lab has finished assessing your pull request, it will be marked automatically as `Ready for review`. Until then, please don't change the draft state.

In the meantime, feel free to make changes to the pull request. If you'd like to maximize payout for your this and future submissions, here are a few general guidelines, that we might take into consideration when reviewing a submission.

- the submission models widely-used frameworks/libraries
- the vulnerability modeled in the submission is impactful
- the submission finds new true positive vulnerabilities
- the submission finds very few false positives
- code in the submission is easy to read and will be easy to maintain
- documentation is written clearly, highlighting the impact of the issue it finds and is written without grammatical or other errors. The code samples clearly show the vulnerability
- the submission includes tests, change note etc.

Please note that these are guidelines, not rules. Since we have a lot of different types of submissions, the guidelines might vary for each submission.

Happy hacking!

**Comment by geoffw0** [comment]
Hi @maikypedia,

Thank you for this contribution.  The QL appears to be to a high standard and I'm interested to see what this query can find.  After the Security Lab team have taken a look I'll be happy to give a more detailed review.  Feel free to `@mention` me if you have any questions before then.

**Review by geoffw0 — COMMENTED** [review]
Hi, sorry for the long wait.  The query looks great, I've suggested a few minor fixes and changes.

**Comment by geoffw0** [comment]
Thanks for addressing the comments.

CI has noticed that we're missing a change note.  This will be a new file in `cpp\ql\src\change-notes` with contents along the lines of:
```
---
category: newQuery
---
* Added a new query, `swift/unsafe-unpacking`, that detects unpacking user controlled zips without validating the destination file path is within the destination directory.
```

**Review by geoffw0 — APPROVED** [review]
Great, I think this is ready to merge.

Thank you for your contribution!  ✨

**Comment by geoffw0** [comment]
@maikypedia you should be able to hit "Merge pull request" now if you're also satisfied that this is finished.

**Comment by maikypedia** [comment]
> @maikypedia you should be able to hit "Merge pull request" now if you're also satisfied that this is finished.

image

I can't  😅

**Comment by geoffw0** [comment]
Ah, sorry, I didn't know that was a thing.  Merging now.

**Pull request merged**
