### PR TITLE
Add a PR check to ensure query IDs are unique

### PR DESCRIPTION
**Pull request by henrymercer**
We distinguish queries in Code scanning by their ID, so it's important that each query has a unique ID.  This PR adds a PR check to ensure that query IDs are unique, and fixes up duplicate query IDs for Java and Python.

For now, we limit our scope to just the duplicate IDs in `src` directories, which correspond to query packs.  In the future, we may want to extend this to eliminate duplicate IDs in test packs too, but the changes involved there are more widespread, so let's break that out into a separate PR.

### CODE REVIEW

**Comment by henrymercer** [comment]
@github/codeql-python The QHelp changes are failing for `TarSlipImprov.ql` with the following:

```
./python/ql/src/experimental/Security/CWE-022bis/TarSlipImprov.qhelp: Could not find sample examples/TarSlip_1.py
./python/ql/src/experimental/Security/CWE-022bis/TarSlipImprov.qhelp: Could not find sample examples/NoHIT_TarSlip_1.py
```

This seems genuine since the examples don't exist.  Do we have some other examples we can use here?

**Comment by henrymercer** [comment]
@tausbn I've renamed the Qhelp file as you suggested

**Review by tausbn — APPROVED** [review]
Python looks reasonable to me. 👍

**Review by aschackmull — APPROVED** [review]
Java 👍

**Comment by henrymercer** [comment]
Thanks both!

**Pull request merged**
