### PR TITLE
Adding C++20 Beta support.rst

### PR DESCRIPTION
**Pull request by AlonaHlobina**

### CODE REVIEW

**Comment by jbj** [comment]
Shouldn't the word "beta" be in there?

**Comment by AlonaHlobina** [comment]
`Beta` is added

**Review by jbj — DISMISSED** [review]
LGTM. I'll also give @igfoo a chance to weigh in.

**Comment by igfoo** [comment]
Is `extractor` a word we use much when talking to customers? I think we can actually just remove that word, i.e. something like:
`C++20 beta support for GCC on Linux; modules are *not* supported.`

Although now I look at that, it could be read as "C++20 is supported [everywhere]" with a footnote that the gcc/Linux support is /worse/ than elsewhere, and only in beta. Perhaps this would be better?:

`C++20 support is currently in beta. Supported for GCC on Linux only. Modules are *not* supported.`

**Comment by AlonaHlobina** [comment]
@igfoo, I changed it as you suggested.

**Review by jbj — DISMISSED** [review]

**Comment by intrigus-lgtm** [comment]
Maybe I'm missing something, but didn't <a href="https://github.com/github/codeql/pull/6101/commits/281a6196460e4d80661efe1314f407ef5bb0d823">281a6196460e4d80661efe1314f407ef5bb0d823</a> un-do a part of your work?

Note that there is no reference to C++20 anymore and the footnote `[2]` appears to be unused.

**Review by jbj — APPROVED** [review]

**Pull request merged**
