### PR TITLE
C#: Move ASP extraction from auto builder to `pre-finalize.{sh,cmd}`

### PR DESCRIPTION
**Pull request by hvitved**
In addition to moving the call to the ASP extractor, the call to the XML extractor has also been removed from the auto-builder, as that already happens in `pre-finalize.{sh,cmd}`.

It was also possible to remove the `CODEQL_AUTOBUILDER_CSHARP_NO_INDEXING` environment variable, as it was set iff `SEMMLE_DIST` was not set.

### CODE REVIEW

**Review by tamasvajk — DISMISSED** [review]
I didn't run this locally, but the changes seem reasonable.

**Review by tamasvajk — APPROVED** [review]

**Comment by hvitved** [comment]
Here is a successful run: https://jenkins.internal.semmle.com/job/LGTM/job/Autobuild-Tests-v2/job/CSharp/404/

**Comment by aibaars** [comment]
@hvitved Would this still run the ASP and XML extractors from the autobuilders when invoked from ODASA? We're about to switch to CodeQL on LGTM, but haven't done so yet.

**Comment by hvitved** [comment]
> @hvitved Would this still run the ASP and XML extractors from the autobuilders when invoked from ODASA? We're about to switch to CodeQL on LGTM, but haven't done so yet.

Oh, I though we had made the switch already. Do you know if that will happen before the next dist upgrade?

**Comment by aibaars** [comment]
> > @hvitved Would this still run the ASP and XML extractors from the autobuilders when invoked from ODASA? We're about to switch to CodeQL on LGTM, but haven't done so yet.
> 
> Oh, I though we had made the switch already. Do you know if that will happen before the next dist upgrade?

It cannot happen before the next dist upgrade, because switching is done by updating the dist.

**Comment by hvitved** [comment]
> It cannot happen before the next dist upgrade, because switching is done by updating the dist.

Right. What I meant was whether it will happen with the next dist upgrade?

**Pull request merged**
