### PR TITLE
Kotlin: Respect `override` modifier in useless parameter query

### PR DESCRIPTION
**Pull request by tamasvajk**

### CODE REVIEW

**Review by atorralba — APPROVED** [review]
LGTM. OOC, why isn't this covered by `not this.(Method).overridesOrInstantiates(_)` in the charpred?

**Comment by tamasvajk** [comment]
> LGTM. OOC, why isn't this covered by `not this.(Method).overridesOrInstantiates(_)` in the charpred?

Good question, I haven't investigated this now, I just added the modifier check next to the java equivalent: `this.getAnAnnotation() instanceof OverrideAnnotation`. Also, I added two commits to show that the change does fix the issue. I vaguely remember that the `overridesOrInstantiates` check the signature of candidate methods, and for generics it doesn't always match.

**Comment by smowton** [comment]
Does the signature mismatching inhibit dataflow from spotting a possible callee of an overridden method? If so we should fix that

**Comment by tamasvajk** [comment]
@smowton I've added an internal issue for this.

**Review by atorralba — APPROVED** [review]
Approving under the assumption that we'll investigate and, if necessary, handle the dataflow issue in a separate PR.

**Review by atorralba — APPROVED** [review]

**Pull request merged**
