### PR TITLE
Golang: add `rsync` as a program capable of arbitrary shell command execution

### PR DESCRIPTION
**Pull request by pwntester**
Add rsync since both --rsh and --rsync-path admit commands

### CODE REVIEW

**Comment by smowton** [comment]
@pwntester please rebase so we only get one commit instead of a big merge. I think this would also be sensible to add to `override predicate doubleDashIsSanitizing()` in `SystemCommandExecutors.qll`, since I think `"rsync ... -- " + userData` would be as safe as letting someone control an rsync could ever be?

**Comment by smowton** [comment]
Please add a test case to https://github.com/github/codeql/tree/main/go/ql/test/query-tests/Security/CWE-078 too

**Comment by pwntester** [comment]
@smowton let me know if it looks better now. Would it make sense to share these lists of commands with other languages in a shared qlpack or similar?

**Review by smowton — DISMISSED** [review]

**Comment by smowton** [comment]
Wants a change-note, otherwise looks good

**Comment by owen-mc** [comment]
@pwntester The tests are failing because it doesn't like your declaration of  a function named`handler` - there's already one in another file in the same folder. Also you need to rebase your branch onto `main`.

**Review by owen-mc — APPROVED** [review]

**Comment by pwntester** [comment]
@owen-mc sure! I cant merge it though

**Comment by owen-mc** [comment]
@pwntester Ah, I didn't realise. I've done it now. Feel free to prod us if it looks like we've forgotten a PR, especially if it's ready to be merged.

**Pull request merged**
