### PR TITLE
Java: get tainttracking3/TaintTrackingImpl.qll in sync

### PR DESCRIPTION
**Pull request by erik-krogh**
https://github.com/github/codeql/pull/8748 added a copy of `TaintTrackingImpl.qll`.  

But the shared implementation changed in the meantime.   
So now we got the sync files check failing on main.

### CODE REVIEW

**Review by nickrolfe — APPROVED** [review]

**Review by aibaars — APPROVED** [review]

**Comment by aibaars** [comment]
The error message from QLDoc seems genuine:
```
A fatal error occurred: Errors during binding:
ERROR: This predicate does not override another predicate (/home/runner/work/codeql/codeql/java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingImpl.qll:118,3-120,4)
ERROR: This predicate does not override another predicate (/home/runner/work/codeql/codeql/java/ql/lib/semmle/code/java/dataflow/internal/tainttracking3/TaintTrackingImpl.qll:135,3-137,4)
```

**Comment by erik-krogh** [comment]
> The error message from QLDoc seems genuine:

Yes. I'm confused about which file is actually the latest.

**Review by aschackmull — APPROVED** [review]

**Comment by aschackmull** [comment]
> > The error message from QLDoc seems genuine:
> 
> Yes. I'm confused about which file is actually the latest.

Presumably that error is from main, and a side-effect of the files being out-of-sync. The change in this PR looks like the right fix to me.

**Comment by erik-krogh** [comment]
> Presumably that error is from main, and a side-effect of the files being out-of-sync. The change in this PR looks like the right fix to me.

Yes. Parts of the failing CI check is: `HEAD is now at d309e150 Merge pull request #8748 from smowton/smowton/admin/dependent-dataflow-configs`, which suggests that it is trying to compare against the failing `main`.

**Pull request merged**
