### PR TITLE
C# 12: Experimental attribute.

### PR DESCRIPTION
**Pull request by michaelnebel**

### CODE REVIEW

**Review by mbg — APPROVED** [review]
Makes sense. Question: the change notes highlight that

> All types included in an assembly marked with the Experimental attribute are experimental

Is that something we already handle for assembly attributes more generally or is this something we should handle for this attribute?

**Comment by michaelnebel** [comment]
> Makes sense. Question: the change notes highlight that
> 
> > All types included in an assembly marked with the Experimental attribute are experimental
> 
> Is that something we already handle for assembly attributes more generally or is this something we should handle for this attribute?

As far as I understand this just states that if you add an attribute like below and compile the project into an assembly, you will get a compiler warning (error) when using anything from that particular assembly.
```csharp
[assembly: Experimental("MyID")]
```
In general we extract *assembly* attributes from the source code and there shouldn't be anything special about the extraction of the Experimental attribute.

**Comment by mbg** [comment]
Sorry, what I was wondering was if we should expose that same behaviour in the QL library somehow. I.e., if an _assembly_ has the `Experimental` attribute, should we do one of the following:

1. Return the `Experimental` attribute when a user queries the attributes of a _type_ in that assembly, even if the type doesn't explicitly have that attribute.
2. Have a flag in the database that marks assemblies/types as experimental and a predicate on C# types in QL which returns whether a given type is experimental.

Either way, I can't imagine that knowing whether a type is experimental or not would be particularly relevant for any queries so it's not something that needs to be addressed in this PR -- it was just something I noticed when I was reviewing the change notes!

**Comment by michaelnebel** [comment]
> Sorry, what I was wondering was if we should expose that same behaviour in the QL library somehow. I.e., if an _assembly_ has the `Experimental` attribute, should we do one of the following:
> 
> 1. Return the `Experimental` attribute when a user queries the attributes of a _type_ in that assembly, even if the type doesn't explicitly have that attribute.
> 2. Have a flag in the database that marks assemblies/types as experimental and a predicate on C# types in QL which returns whether a given type is experimental.
> 
> Either way, I can't imagine that knowing whether a type is experimental or not would be particularly relevant for any queries so it's not something that needs to be addressed in this PR -- it was just something I noticed when I was reviewing the change notes!

Ah ok, now I understand.
If something like that is needed, it should probably be a query instead of incorporated directly in the library.
You are probably thinking about something in the line of
```
import csharp
import semmle.code.csharp.commons.Compilation

class ExperimentalAttribute extends Attribute {
  ExperimentalAttribute() {
    this.getType().hasFullyQualifiedName("System.Diagnostics.CodeAnalysis", "ExperimentalAttribute")
  }
}

from Attributable att
where
  att.getAnAttribute() instanceof ExperimentalAttribute
  or
  exists(Compilation c, Assembly a |
    c.getAFileCompiled() = att.(Element).getFile() and
    a = c.getOutputAssembly() and
    a.getAnAttribute() instanceof ExperimentalAttribute
  )
select att
```
where we then need to narrow the `attributables` to the exact list of attribute targets allowed for the experimental attribute.
In any case, I think it is a good idea to add the `ExperimentalAttribute` class.

Is this ok with you?

**Review by mbg — APPROVED** [review]
Yes, that's exactly what I had in mind -- thank you for turning that into a query and adding the `ExperimentalAttribute` class to the library as well. I think that alone will be very helpful if someone requires this functionality since it should be possible to stumble across this discussion.

**Pull request merged**
