### PR TITLE
ExponentialBackTracking: Speedup `concretise`

### PR DESCRIPTION
**Pull request by hvitved**

### CODE REVIEW

**Review by erik-krogh — COMMENTED** [review]
You've achieved the same thing as I did in https://github.com/github/codeql/pull/8522, but much more concisely :clap: 

Could `SuperlinearBackTracking.qll` get the same treatment?

**Review by erik-krogh — DISMISSED** [review]
:+1: (Assuming the new evaluations work out)

**Comment by hvitved** [comment]
There was some slowdown on `facebookarchive__nuclide`. The latest commit tries to reduce the slowdown.

**Comment by erik-krogh** [comment]
I think you need a merge with `main` to include https://github.com/github/codeql/pull/8532 (I think that's why Ruby is failing).

**Comment by hvitved** [comment]
> I think you need a merge with `main` to include #8532 (I think that's why Ruby is failing).

Turns out that this was already broken on `main`: https://github.com/github/codeql/pull/8624.

**Comment by hvitved** [comment]
Rebased onto latest `main` without changes.

**Review by erik-krogh — APPROVED** [review]
:+1: (assuming a new evaluation works out).

**Comment by hvitved** [comment]
There is still a bit of a slowdown on `facebookarchive__nuclide`, but less than before. I would argue that it is an evaluator bug that `strictconcat` is not faster than the old recursive computation (I have made @alexet aware). @erik-krogh is it acceptable to merge?

**Comment by erik-krogh** [comment]
> I would argue that it is an evaluator bug that `strictconcat` is not faster than the old recursive computation.  

I read your comments about that, and I agree. It sounds like there are some unnecessary sorting when `language[monotonicAggregates]` is enabled.  

> @erik-krogh is it acceptable to merge? 

Your solution is faster and more elegant than [the solution I was planning](https://github.com/github/codeql/pull/8522), it massively improves the worst-case performance, and if the evaluator is fixed then the performance should be better in all cases.   
So yeah, big :+1: from me.

**Pull request merged**
