### PR TITLE
Go: mass-convert taint-flow models to models-as-data format (with `viableParamArgSpecific` hook)

### PR DESCRIPTION
**Pull request by smowton**
This is a variation on https://github.com/github/codeql/pull/12562 that uses a new data-flow library language-specific hook instead of trying to achieve the golang QL lib's prior behaviour by trickery using argument/parameter numbering as that PR does. See https://github.com/github/codeql/pull/12562 for background and details.

### CODE REVIEW

**Comment by aschackmull** [comment]
> filter out receiver argument flow to Golang interface dispatch candidates

I'm confused about why you want to do this. And also wondering why this needs a hook into the dataflow library. I looked briefly at the referenced PR, but didn't find explanation/motivation there either (although I didn't dig deep into that PR and all of its comments).

**Comment by smowton** [comment]
Why: maintain current behaviour, which I didn't write but I guess is there because of flows like

```go
tainted := getInterfaceTypedTaint()
tainted.Method()

...

func (derived *DerivedType) Method() {
  sink(derived.field)
}
```

So the hypothesis is "if the source ever made a DerivedType then we'd have taint flow", contrast `tainted := getParameterTypedTaint(); dispatch := getInterfaceTypedThing(); dispatch.Method(tainted)`, where at least it isn't the source itself that is hypothesised to create a `DerivedType` object (it is non-source `getInterfaceTypedThing`, though).

I agree it's not very principled, and to get full detail we'd have to grill Max on the original decision-making, but my guess is that Go's simple handling of low-confidence dispatch + the absence of data-flow type pruning (not that that would help us in this particular example) meant we saw too many FPs resembling this example.

Why do it via a data-flow lib hook: because this is currently implemented by suppressing argument nodes entirely for interface dispatch receivers, but that no longer works once summaries are implemented by synthetic callables, and therefore we do need an argument node, *but that argument node must flow only to the interface summary, not to derived-type synthetic or concrete implementatons*. Note this can't be done by eliminating a parameter node either, because the implementations should accept flow from high-confidence dispatch.

**Comment by Happiness-n** [comment]
> > تصفية حجة م المتلقي تدفق إلى مرشحي إرسال واجهة جولانغ مبيد > المهاب > أنا مرتبك بشأن سبب رغبتك في القيام بذلك. وأتساءل أيضا لماذا هذا يحتاج إلى ربط تدفق البيانات بمكتبة. نظرت بإيجاز إلى العلاقات العامة المشار إليها، ولكن لم أجد تفسيرا/تحفيزا هناك أيضا (على الرغم من أنني لم أتعمق في تلك العلاقات العامة وجميع تعليقاتها). 


مرحبا.. انا لا اعرف عن ماذا تتحدث لعلي وضعت ملفات هنا شخصيه بدون ادراك مني فهي غير واضحه لي ولم انتبه انني وضعتها على العام ايضا ارجو المساعده ان كانت شخصيه او غير لائقه باخباري كيف حذفها وعدم انتشاره واعتذر للجميع وشكرا

**Review by aschackmull — COMMENTED** [review]
Data flow hook LGTM.

**Review by owen-mc — APPROVED** [review]

**Pull request merged**
