### PR TITLE
Python: Add cookie security-related queries

### PR DESCRIPTION
**Pull request by jorgectf**
This PR adds:

* Modeling of:
* * Adding cookies in `flask`.
* * Adding cookies in `django`.

* Queries:
* * Cookie without `(secure|httponly|samesite)` flag properly set.
* * Cookie constructed from user-supplied input.

### CODE REVIEW

**Review by RasmusWL — COMMENTED** [review]
I have not looked at this PR in depth, but just noted that this deals with setting cookies in HTTP responses. Would be great if you could integrate this with the existing `HTTP::Server::CookieWrite` concept implemented here:
https://github.com/github/codeql/blob/main/python/ql/lib/semmle/python/Concepts.qll#L759-L784

You can do this by creating your own experimental concepts that extend the existing concept, for an exmaple, see https://github.com/github/codeql/blob/85f00fda1960590e833bc1c9064243d1281869d6/python/ql/lib/semmle/python/Concepts.qll#L75-L106

I would base my modeling in Django/Flask on the existing modeling (that is, copy-paste it), such that it is easy to just override the existing modeling when promoting this query :+1:

**Comment by jorgectf** [comment]
I haven't been able to find any CVE for this specific security issue, so the bounty submission has been closed.

**Comment by RasmusWL** [comment]
Thanks for the update @jorgectf. Will take a look on this PR soon :+1:

**Review by RasmusWL — APPROVED** [review]
I took forever to review this, sorry :grimacing:

For reference when promoting this, JS adopted an approach with multiple queries for each of these flags, so we should consider doing the same

- `js/samesite-none-cookie` (precision medium)
- `js/client-exposed-cookie` (precision high) -- for `httpOnly` flag
- `js/clear-text-cookie` (precision high) -- for 'secure' flag

See https://github.com/github/codeql/pull/6855 and https://github.com/github/codeql/pull/7721

**Review by RasmusWL — DISMISSED** [review]

**Review by RasmusWL — APPROVED** [review]

**Pull request merged**
