### PR TITLE
Java: Add comments about use of sink kind `regex-use`

### PR DESCRIPTION
**Pull request by owen-mc**
The sink kind `regex-use` doesn't match [the code which parses regex-use sink kinds](https://github.com/github/codeql/blob/4c8da54b64d67aa958ed8875492f962bb1c5c5af/java/ql/lib/semmle/code/java/regex/RegexFlowConfigs.qll#L20-L49) for regex injection. It turns out this is intentional, but not clearly documented. This PR adds comments explaining that.

### CODE REVIEW

**Review by jcogs33 — COMMENTED** [review]
@owen-mc The `regex-use` sink kind intentionally does not match the regex-use parsing code in order to avoid excess FPs in the `java/regex-injection` query. Some prior discussion [here](https://github.com/github/codeql/pull/11070#discussion_r1015494987). Changing this kind to `regex-use[0]` will break `java/regex-injection` test cases.

There is an existing issue about adjusting the `regex-use%` kind to resolve this situation, which I'll send you a link to. `@atorralba` and I had previously discussed that the appropriate adjustment would not be simple and that is why we left it as an issue.

Perhaps it would be best to simply add a comment in the `org.apache.commons.lang3.model.yml` file for now to avoid future confusion?

**Comment by owen-mc** [comment]
@jcogs33 Thanks for explaining that. I've updated this PR to add comments in the two places that I think would be most useful.

**Review by jcogs33 — APPROVED** [review]

**Comment by joefarebrother** [comment]
Is it accurate to say that the rexex-use kind is "used for regular expression injection sinks that should not be used
 as polynomial ReDoS sinks."? 
 From my understanding, it would be nice to consider the regex injection sinks to also be redos sinks, but the difficulty in actually doing that would be that there are *redos* sinks that need to not be considered as *injection* sinks.

**Comment by jcogs33** [comment]
ah sorry, @owen-mc I misread the comments when I reviewed this. Joe is correct.
Thanks for catching @joefarebrother! 🙏 

I'll open a PR to fix.

**Pull request merged**
