### PR TITLE
C++: ignore iterators that are their own value type

### PR DESCRIPTION
**Pull request by rdmarsh2**
This fixes a rare case where IR-based data flow won't have appropriate edges for these types.

### CODE REVIEW

**Comment by rdmarsh2** [comment]
cc @bdrodes who originally reported this

**Comment by MathiasVP** [comment]
Hmmm... The comment added here seems relevant: https://github.com/github/codeql/blob/ea97c3ea8301fa278bed547a7c4b99f43183aad7/cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowUtil.qll#L873

I wonder if there's a better fix somewhere lurking here 🤔

**Comment by MathiasVP** [comment]
I've opened up an alternative fix that doesn't limit our iterator model: https://github.com/github/codeql/pull/13515.

**Comment by rdmarsh2** [comment]
Closing in favor of https://github.com/github/codeql/pull/13515

**Pull request closed without merging**
