### PR TITLE
Codegen: mark generated checked in files as such

### PR DESCRIPTION
**Pull request by redsun82**
codegen will now generate a `.gitattributes` file marking all generated files as `linguist-generated`, that will then [stay hidden by default in github UI diffs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github). This relies on the work already done to maintain a `generated.list` file holding contents hashes of generated files. That list was just modified so that files in it appear relative to the directory containing `generated.list` rather than to the language pack root directory, to mimic how `.gitattributes` works.

### CODE REVIEW

**Comment by redsun82** [comment]
Here's a test difference showing the effect:
https://github.com/github/codeql/compare/redsun82/swift-mark-generated-files...redsun82/test?expand=1

**Comment by geoffw0** [comment]
The test looks good!

**Comment by sashabu** [comment]
> Here's a test difference showing the effect: #13057

What does it look like if we manually modify a generated file? I understand `.generated.list` keeps track of that via hashes, but wanted to double-check we're not accidentally hiding useful diffs.

**Review by sashabu — APPROVED** [review]
Thanks!

**Comment by redsun82** [comment]
> > Here's a test difference showing the effect: #13057
> 
> What does it look like if we manually modify a generated file? I understand `.generated.list` keeps track of that via hashes, but wanted to double-check we're not accidentally hiding useful diffs.

@sashabu 
If it's a file that is meant to be generated (a non-stub file, or a stub file whose "generated" header comment was not removed) then CI will fail ([here's the step checking that](https://github.com/github/codeql/actions/runs/4891323540/jobs/8731696680?pr=13056#step:7:92)). After modifying a stub file (also removing its header), running codegen again will update both `.generated.list` and `.gitattributes` removing the file from the list and therefore showing the diff in the PR. Once again if you modify a stub file but forget to run codegen (thus forgetting to update the two list files), CI will remind you :slightly_smiling_face:

**Pull request merged**
