### PR TITLE
Data flow: Support hidden return nodes in subpaths predicate

### PR DESCRIPTION
**Pull request by aschackmull**
Alternative to https://github.com/github/codeql/pull/6824

### CODE REVIEW

**Comment by aschackmull** [comment]
Cherry-picked two of the three additional commits from the other PR. I skipped https://github.com/github/codeql/pull/6824/commits/b9869ea7b9aa76e324fb1de1c68b7b2c97eac793 as that would conflict with https://github.com/github/codeql/pull/7002, so I'd rather postpone that commit.

**Review by hvitved — APPROVED** [review]
LGTM. But let's wait for the performance numbers before merging.

**Comment by aschackmull** [comment]
Timings look fine. There are a few result changes, though.

**Comment by hvitved** [comment]
The C# result changes appear to be due to some wobbliness, so LGTM.

**Pull request merged**
