### PR TITLE
QL for QL: add autobuilder that respects LGTM_INDEX_FILTERS

### PR DESCRIPTION
**Pull request by nickrolfe**
A fairly trivial modification of the Ruby autobuilder.

Closes https://github.com/github/codeql-ql/issues/141

### CODE REVIEW

**Review by erik-krogh — APPROVED** [review]
LGTM :tada:

**Comment by erik-krogh** [comment]
Something seems to be wrong.  
When I try to use `LGTM_INDEX_FILTERS` the extractor tries to extract every file in the folder, not just the files with the right extension: https://github.com/github/codeql/runs/4562952843?check_suite_focus=true  
@nickrolfe ?

**Comment by nickrolfe** [comment]
I see you have this config:

```
paths:
  - ruby
paths-ignore:
  - ql/ql/test
```

And I guess that gets translated somehow to something like `LGTM_INDEX_FILTERS=include:ruby/**\nexclude:ql/ql/test/**`.

The autobuilder will then run

```
codeql database index-files --include-extension=.ql --include-extension=.qll --include-extension=.dbscheme --include=**/qlpack.yml --size-limit=5m --language=ql --working-dir=. $CODEQL_EXTRACTOR_QL_WIP_DATABASE --include=ruby/** --exclude=ql/ql/test/**
```

And I suppose the `--include=ruby/**` argument tells `index-files` to include everything in the `ruby` directory, ignoring the extension filter.

@aibaars do we need to make the Ruby/QL autobuilder smarter at expanding the `include:` options, or is there a better way of handling this?

**Comment by erik-krogh** [comment]
Could it be `codeql database index-files` bug.  
It seems like `--include-extension` is pretty much ignored if `--include` is used?

**Comment by erik-krogh** [comment]
I did a little experiment.  
And apparently `codeql database index-files --include-extension=.ql --include=somefolder` means to include every file `.ql` reachable from the current working folder, and every file inside `somefolder`.   

So the autobuilder is broken both for QL-for-QL and Ruby right now.

**Pull request merged**
