### PR TITLE
Data flow: Track precise types during field flow

### PR DESCRIPTION
**Pull request by hvitved**
### Overview
This PR factors type information out of the language-specific `Content` entities, and instead uses the actual stores to record type information. That is, when tracking flow through a field-write, `x.f = y`, we use the type of `x` during the subsequent flow calculations, rather than the result of `getContainerType()` on the content entity corresponding to `f`.

This means that we are now able to eliminate flow like in the example below:
```csharp
class FieldA
{
    public object Field;

    public virtual void M() { }

    public void CallM() => this.M();

    static void M1(FieldB b, FieldC c)
    {
        b.Field = new object();
        b.CallM(); // no flow            <- NEW
        c.Field = new object();
        c.CallM(); // flow
    }
}

class FieldB : FieldA { }

class FieldC : FieldA
{
    public override void M() => Sink(this.Field);
}
```

While this change may not have a big impact on field flow, it is crucial in the implementation of (typed) collection flow: If we kept type information in the `Content` class:
```ql
newtype TContent = ... or TCollectionContent(DataFlowType elementType)
```
then a generic element read such as
```csharp
T GetFirstElement<T>(IList<T> l) => l[0];
```
would have to match _all_ `TCollectionContent(t)` entities, which does not scale.

### Performance

I have started Difference jobs for
- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/165/.
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1133/.
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/746/.

I also ran @aschackmull 's [tuple counting benchmark](https://gist.github.com/hvitved/ac1e68269d9d0dd4dc1c7a0a43a61b04) on JDK, which revealed that most relations had similar sizes; most notably, `flowCandFwdConsCand` increased by 56%, but from a mere 10711 tuples to 16710 tuples.

### Notes for review
Commit-by-commit review is encouraged. The actual work happens in f1cd53507d3482de760384565ed560760bd9e57d; the other PRs deal with syncing, renaming, and follow-up changes.

### CODE REVIEW

**Comment by jbj** [comment]
I haven't looked at the code, but I note that the CPP-Differences job shows only one result change, which is caused by build-system wobble, and mostly unchanged performance. The slowdown on Wireshark may be significant, but it's not large enough to block this PR.

**Comment by hvitved** [comment]
> I haven't looked at the code, but I note that the CPP-Differences job shows only one result change, which is caused by build-system wobble, and mostly unchanged performance. The slowdown on Wireshark may be significant, but it's not large enough to block this PR.

👍 FYI, the C++ specific parts are in https://github.com/github/codeql/pull/3456/commits/2d7470fc3ae1f69c393f28c79669d53e631d2bfc.

**Comment by hvitved** [comment]
Ping @aschackmull.

**Comment by hvitved** [comment]
Ping.

**Comment by aschackmull** [comment]
I'm looking at this, but it's slow going, sorry.  Found a bug in `flowCandFwdConsCand` to possibly explain the tuple explosion though, but I'll investigate further before reviewing in full.

**Comment by aschackmull** [comment]
PR against this PR: https://github.com/hvitved/ql/pull/2

**Comment by hvitved** [comment]
Updated Differences jobs:
C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/222/
C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1200/
Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/785/

C++ and Java have completed, and they still show now change in neither performance nor results, as expected.

**Comment by hvitved** [comment]
I had to restart the C# job (https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/224/), which also shows no change in performance nor results.

**Pull request merged**
