### PR TITLE
Java: Understand multiple parse mode flags specified in a regular expression string

### PR DESCRIPTION
**Pull request by geoffw0**
Understand / correctly parse multiple parse mode flags specified in a regular expression string, for example `i` and `s` in:
```
(?is)abc.*
```
Previously we were only recognizing the first flag (`i`).

This is a backport of part of the Swift PR https://github.com/github/codeql/pull/13715 .

### CODE REVIEW

**Comment by atorralba** [comment]
Changes look plausible to me.

However, there's this test expectation diff:

```diff
--- expected
+++ actual
@@ -118,8 +118,9 @@
 | Test.java:16:95:16:101 | t{,15}+ | [RegExpQuantifier] |
 | Test.java:16:102:16:102 | u | [RegExpConstant,RegExpNormalChar] |
 | Test.java:16:102:16:108 | u{16,}+ | [RegExpQuantifier] |
-| Test.java:17:10:17:13 | (?i) | [RegExpZeroWidthMatch] |
+| Test.java:17:10:17:13 | (?i) | [RegExpGroup] |
 | Test.java:17:10:17:36 | (?i)(?=a)(?!b)(?<=c)(?<!d)+ | [RegExpSequence] |
+| Test.java:17:12:17:12 | i | [RegExpConstant,RegExpNormalChar] |
 | Test.java:17:14:17:18 | (?=a) | [RegExpPositiveLookahead] |
 | Test.java:17:17:17:17 | a | [RegExpConstant,RegExpNormalChar] |
 | Test.java:17:19:17:23 | (?!b) | [RegExpNegativeLookahead] |
```

I get the change from `RegExpZeroWidthMatch` to `RegExpGroup`,  but the fact that the `i` gets classified as a `RegExpConstant`/`RegExpNormalChar` kind of bugs me. Happy to accept the changes if they look good to you though, just wanted to double check.

**Comment by geoffw0** [comment]
> the fact that the `i` gets classified as a `RegExpConstant`/`RegExpNormalChar` kind of bugs me.

I'm not sure of the right way to fix this.  Add `flagGroup` to the `zeroWidthMatch` predicate???

**Comment by atorralba** [comment]
> I'm not sure of the right way to fix this. Add `flagGroup` to the `zeroWidthMatch` predicate???

🤷 not sure if it's even a problem. @erik-krogh any insight? Can we safely merge this?

**Comment by erik-krogh** [comment]
> 🤷 not sure if it's even a problem. @erik-krogh any insight? Can we safely merge this?

I think it's safe enough to merge. 
I think the worst that can happen is that the alert-message spuriously mentions the flags in the "prefix" string.  
Can you check what alert-message we get for a regex like `"(?is)(a|aa?)*b"`? 

If the alert-message mentions `i` or `s`, then we should probably do something about it. 
I don't think adding something to the `zeroWidthMatch` predicate will work, because that predicate isn't really used by the shared regex library.

**Comment by yoff** [comment]
I suspect that fixing https://github.com/github/codeql-team/issues/2209 will fix the issue.

**Comment by yoff** [comment]
> I suspect that fixing [github/codeql-team#2209](https://github.com/github/codeql-team/issues/2209) will fix the issue.

I made a branch on top of the Python PR [here](https://github.com/github/codeql/pull/13975) to test this hypothesis.

**Comment by yoff** [comment]
So
- the current PR here (and the one for Python) changes the parser so that all mode characters are now considered. They are also now group content for the flag group.
- [my PR](https://github.com/github/codeql/pull/13975) on top of the Python PR changes this so that the mode characters are not content, the flag group is instead empty.
- This makes the NFA utility deal with a new empty group causing problems, so I added a potential fix for that
- Tests on the PR on top the Python PR now [look good](https://github.com/github/codeql/pull/13975#pullrequestreview-1580433058).

Does this sound like a good way forward?

**Comment by geoffw0** [comment]
Sounds good to me.  What do we need to merge first?

**Comment by yoff** [comment]
> Sounds good to me. What do we need to merge first?

My PR includes a revert that we do not want (it enabled debugging the AST). So we do not want to merge that directly, but I could clean it up (rebase the revert away). Alternatively, you could take the approach from that PR and apply it to your own. How many PRs are in flight? We would probably want these for all the regex parsers, together with the change to the shared component, so another possible alternative is to make a big PR that does that...

**Comment by geoffw0** [comment]
I much prefer the multiple small PRs strategy - I have reviewed https://github.com/github/codeql/pull/13975 and am happy to back-port it to Swift after it's merged.

**Comment by yoff** [comment]
Ok, I will clean that up up, then. Thanks for the review :-)

**Comment by geoffw0** [comment]
It might make sense to merge my Python PR first since you're already using the commits from it.

**Comment by geoffw0** [comment]
... except it's failing PR checks.  I'll look into that.

**Comment by yoff** [comment]
Did this become unblocked now or are there still considerations?

**Comment by yoff** [comment]
> Assuming I haven't made any mistakes...

Looks to me like you did not :-) LGTM

**Review by atorralba — APPROVED** [review]

**Pull request merged**
