### PR TITLE
Java: Update the Model Difference workflow to use the `gh api`.

### PR DESCRIPTION
**Pull request by michaelnebel**

### CODE REVIEW

**Review by aeisenberg — APPROVED** [review]
LGTM

**Review by tamasvajk — APPROVED** [review]
LGTM

Unrelated to your changes, there are some missing artifacts mentioned on the workflow summary page: https://github.com/github/codeql/actions/runs/3905134834.

**Comment by michaelnebel** [comment]
> LGTM
> 
> Unrelated to your changes, there are some missing artifacts mentioned on the workflow summary page: https://github.com/github/codeql/actions/runs/3905134834.

Yes, that is because there are no differences in the models produced with the code in main and in this PR. If the diff is empty there is not produced an html file.
I have tested the PR with changes that *should* produce a diff and in that case the html artifacts will be uploaded.
Were you thinking about that we should look into avoiding the message when the diff is empty?

**Comment by tamasvajk** [comment]
> Were you thinking about that we should look into avoiding the message when the diff is empty?

If this is the expected behaviour and generally everybody know this, we can leave it as it is.

**Comment by michaelnebel** [comment]
> > Were you thinking about that we should look into avoiding the message when the diff is empty?
> 
> If this is the expected behaviour and generally everybody know this, we can leave it as it is.

Then we should probably do something :-)
PR is up: https://github.com/github/codeql/pull/11881

**Pull request merged**
