### PR TITLE
[WIP] Java : Add support for detecting Template Injections in Java.

### PR DESCRIPTION
**Pull request by porcupineyhairs**
This is a WIP. Please don't merge.

-- EDIT -- 
I have only included files for Velocity and Freemarker but I am trying to add Pebble too.

### CODE REVIEW

**Comment by pwntester** [comment]
Hey @porcupineyhairs, it is great you are working on a SSTI query. I wrote this [query](https://gist.github.com/pwntester/486fc423503d222d0afb1b32a4c6a159) that I used for some research but didnt get the time to make a proper PR. Since you are already working in this query you may want to consider the sinks in my query.

**Comment by porcupineyhairs** [comment]
@pwntester Your query is definitely useful. I will include it with my PR and push the changes over the weekend.

**Comment by porcupineyhairs** [comment]
@aschackmull @pwntester Does java have something like `debstubber` or I am to manually stub the dependencies?

**Comment by aschackmull** [comment]
Not to my knowledge, unfortunately.  So far, we've been adding stubs manually.

**Comment by porcupineyhairs** [comment]
I am closing this as the main has moved during the time this was pending.

Instead I am have opened a new PR #5935 with the necessary changes.

**Pull request closed without merging**
