### PR TITLE
Python: Use API graphs in `Stdlib.qll`

### PR DESCRIPTION
**Pull request by tausbn**
Eliminates _almost_ all of the bespoke type trackers found here. The
ones that remain do not fit easily inside the framework of API graphs
(at least, not yet), and I did not see any easy ways to clean them up.
They have, however, been rewritten to use `LocalSourceNode` internally,
which was the primary goal of this exercise.

I'm sure we could also clean up many of the inner modules given the more
lean presentation we have now, but this can wait for a different PR.

--- 
No change note required. This only affects internal stuff.

### CODE REVIEW

**Review by yoff — DISMISSED** [review]
Nice, I will be happy to have this.
One change, which I think we want to do and which might be small enough to be in scope, is to inline `XXX_attr`; that is replace `XXX_attr(yyy)` with `XXX().getMember(yyy)`.

**Review by yoff — APPROVED** [review]
Nice, good use also of `CallCfgNode`.
We are deleting some very small deprecated functions. They really are small and internal and only expressing "intermediate results", so I think this is fine.
We should probably run performance evaluation just to push this behaviour, but otherwise I am happy to merge as is.

**Comment by tausbn** [comment]
> We are deleting some very small deprecated functions. They really are small and internal and only expressing "intermediate results", so I think this is fine.

Actually, this doesn't delete any deprecated functions after all, because it introduced them in the first place. :sweat_smile: 
This is because I initially saw a bunch of non-`private` predicates and thought "welp, better keep this around for now", but then I realised that the entire `Stdlib` module is private, so it should be safe to just change things freely.

> We should probably run performance evaluation just to push this behaviour, but otherwise I am happy to merge as is.

Agreed. I'm also curious as to whether performance will improve through the reuse of the API-graph typetracker.

**Review by RasmusWL — APPROVED** [review]
Very nice :muscle: 

I think we still want to do a bit more refactoring on this, such as 

```diff
-os::path().getMember("normpath").getACall()
+API::moduleImport("os").getMember("path").getMember("normpath").getACall()
```

like we did for [flask](https://github.com/github/codeql/blob/3dc0c2081e733c11a3186133770e0bff13601052/python/ql/src/semmle/python/frameworks/Flask.qll) -- (which makes reading this code super easy, since it's very transparent what is going on)

But I'm all for getting this in as-is, since it's still a major improvement :+1:

**Comment by tausbn** [comment]
> Agreed. I'm also curious as to whether performance will improve through the reuse of the API-graph typetracker.

No real change in performance: https://github.com/dsp-testing/tausbn-dca/issues/9

I guess the conclusion may just be that additional type trackers aren't very expensive at all.

**Comment by tausbn** [comment]
:shipit:

**Pull request merged**
