### PR TITLE
JS: Add support for TypeScript 5.2

### PR DESCRIPTION
**Pull request by erik-krogh**
No real surprises. 
Some new syntax, where I also added support for the corresponding JS proposal. 

Lots of things we get for free from better type-checks in the TS compiler.

### CODE REVIEW

**Comment by asgerf** [comment]
There's also `await using` statements. Otherwise looks reasonable

**Comment by asgerf** [comment]
Thanks. Could you do a DCA run? Mainly to check the extractor changes don't misbehave on ordinary code.

**Comment by erik-krogh** [comment]
> Thanks. Could you do a DCA run? Mainly to check the extractor changes don't misbehave on ordinary code. 

It does misbehave.  
Functions named `using` are not parsed correctly, and result in parse errors.

**Comment by erik-krogh** [comment]
New evaluations (see the two latest backrefs) look good.  

There is a single new extraction error, which is benign and comes from this file: 
 https://github.com/babel/babel/blob/4013c5460f687e4b96e31bddc314c450f30e130d/packages/babel-parser/test/fixtures/typescript/type-alias/declare-new-line/input.ts 
Where TypeScript now complains that `Line break not permitted here.`.

**Review by asgerf — APPROVED** [review]
👍

**Comment by Sashane969** [comment]
blockchains/kava/info/logo.png

**Pull request merged**
