### PR TITLE
JS: Fix Bad join orders in UnsafeJQueryPlugin

### PR DESCRIPTION
**Pull request by erik-krogh**
My [recent PR](https://github.com/github/codeql/pull/4206) caused a bad join order - in a seemingly unrelated location. 

Here are some tuple counts from the bad join-order: 

```
131770      ~1%     {2} r73 = SCAN AsyncPackage::AsyncPackage::getLastParameter#ff AS I OUTPUT I.<1>, I.<0>
69902       ~4%     {2} r74 = JOIN r73 WITH Sources::SourceNode::getACall_dispred#ff AS R ON FIRST 1 OUTPUT R.<1>, r73.<1>
92999       ~4%     {3} r75 = JOIN r74 WITH Nodes::InvokeNode::getArgument_dispred#fff AS R ON FIRST 1 OUTPUT R.<1>, r74.<1>, R.<2>
10799433111 ~6%     {4} r76 = JOIN r75 WITH Nodes::FunctionNode::getParameter_dispred#fff_102#join_rhs AS R ON FIRST 1 OUTPUT R.<1>, r75.<1>, r75.<2>, R.<2>
274380      ~0%     {5} r77 = JOIN r76 WITH AsyncPackage::AsyncPackage::IterationCall::getFinalCallback_dispred#fb_10#join_rhs AS R ON FIRST 1 OUTPUT R.<1>, R.<1>, r76.<1>, r76.<2>, r76.<3>
```

Adding a `pragma[noinline]` fixes the join-order. 

I also did a drive-by change to `aliasPropertyPresenceStep` to improve the performance of that.   
(On `azure-sdk-for-node` the time taken goes from ~55s to ~10s for that predicate).

### CODE REVIEW

**Review by esbena — APPROVED** [review]
Can you attach an evaluation link for reference?

**Comment by erik-krogh** [comment]
> Can you attach an evaluation link for reference?

I've only done small local tests for now. But I got a dist-compare running `UnsafeJQueryPlugin.ql` on `nightly`.

**Comment by erik-krogh** [comment]
My databases had broken `.stats` after upgrades, so my local performance measurements were invalid. 

The performance regression turned out to be somewhere else. 
The `improve join-order for aliasPropertyPresenceStep`-commit is still the same. 

I'm starting a nightly/UnsafeJqueryPlugin.ql evaluation.

**Comment by erik-krogh** [comment]
An [evaluation on nightly](https://git.semmle.com/erik/dist-compare-reports/tree/profiling-erik-krogh.northeurope.cloudapp.azure.com_1600120682332) finished.  
The first column is `main` - the second column is the bad join order - and the third column is the good join-order (this PR).  
(Look at `azure-sdk-for-node`).

**Comment by esbena** [comment]
Great. I take it that the warning about the missing sarif file is an artifact of how you made the three-column comparison?

**Comment by erik-krogh** [comment]
> Great. I take it that the warning about the missing sarif file is an artifact of how you made the three-column comparison?

Yes.  
`azure-sdk-for-node` timed out with the bad join order (middle column).

**Review by esbena — APPROVED** [review]

**Pull request merged**
