### PR TITLE
C++: Rewrite `cpp/cgi-xss` to not use default taint tracking

### PR DESCRIPTION
**Pull request by jketema**
Also add a test that demonstrates that we need to look at inidrect expressions and not direct ones.

New attempt at this, now using indirect expressions. MRVA and DCA still don't show anything interesting.

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
LGTM!

**Comment by jketema** [comment]
Fixed the barrier. MRVA looks good; will rerun DCA.

**Review by MathiasVP — APPROVED** [review]
LGTM if DCA is happy!

**Comment by jketema** [comment]
DCA looks good.

**Comment by Horvathbarbara1219** [comment]
Recovery support code

**Pull request merged**
