### PR TITLE
Python: Disregard unused imports in `pytest` tests

### PR DESCRIPTION
**Pull request by tausbn**
These may have an effect on the test framework even if the import itself is apparently unused.

For @redsun82. 🙂

### CODE REVIEW

**Review by redsun82 — COMMENTED** [review]
Thanks for trying this! :heart:

Unfortunately, I could test that this doesn't help not flagging the FP I reported and actually hides some TPs in our own repository.

* on the FP side, my problem is a fixture being imported in a module (`root_conftest.py`) which is then explicitly imported into `conftest.py`, which then pytest _implicitly_ imports into all actual tests. I'm not sure this change here covers transitive imports, but anyway I also doubt it covers the implicit import of `conftest.py`, so my unusued imports remain. AFAIK this might actually be the most common way in which fixtures are imported in tests
* on the TP side, we lose all properly unused imports on test files, but we might argue we might accept that.

I wonder whether we couldn't shift the logic on _what_ is imported, rather than _by whom_. Could we maybe have a `imported_alias_is_pytest_fixture` predicate, for anything decorated by `@pytest.fixture` or `@pytest.fixture(**some_kwargs)`?

Just to be clear, an answer "it's too complicated/we don't have capacity for this now" would be totally acceptable for me :slightly_smiling_face: :heart_hands:

**Comment by tausbn** [comment]
Thanks for the additional context. I ended up implementing essentially what you suggested, and as far as I can tell it works as intended. 🙂

**Comment by redsun82** [comment]
@tausbn So close, but still a tiny detail missing! Sorry for having nerd-sniped you :sweat_smile: 

The issue is that the `pytest.fixture` is both a decorator and a decorator factory. So you can do
```python
@pytest.fixture
def foo(...):
    ...
```
which will create a fixture with default parameters (and which I think your changes cover), but you can also do
```python
@pytest.fixture(scope='session', autouse=True)
def bar(...):
    ...
```
where, so that in this case what we're interested in is the return value of the call of the return value of `pytest.fixture`. This I don't think is covered here (and is the case for many of my fixtures).

The signature of `pytest.fixture` is
```python
def fixture(
    fixture_function: Optional[FixtureFunction] = None,
    *,
    scope: "Union[_ScopeName, Callable[[str, Config], _ScopeName]]" = "function",
    ...
```
and whether it returns the decorated function or a factory to be applied depends on having the first positional argument or not

**Review by RasmusWL — APPROVED** [review]

**Comment by tausbn** [comment]
Performance looks good (no change). Merging.

**Pull request merged**
