### PR TITLE
C++: Add field to object taint tests

### PR DESCRIPTION
**Pull request by MathiasVP**
Part of https://github.com/github/codeql-c-analysis-team/issues/103.

### CODE REVIEW

**Review by jbj — COMMENTED** [review]
I'd like to see some opinions in the test file comments on whether the library taints the correct elements.

**Comment by MathiasVP** [comment]
> I'd like to see some opinions in the test file comments on whether the library taints the correct elements.

Good point. I'll add those

**Comment by MathiasVP** [comment]
> > I'd like to see some opinions in the test file comments on whether the library taints the correct elements.

Done in a4890ef99c6c310875fa662c8832a6533e19874d. I didn't go with the usual `[FALSE POSITIVE]` annotation since I think it's in a different category than "there's too much flow here". But I'll happily accept a bikeshed challenge on the exact phrasing.

**Review by jbj — APPROVED** [review]
Thanks!

**Pull request merged**
