### PR TITLE
Release change notes for 2.15.4

### PR DESCRIPTION
**Pull request by coadaflorin**
Update the change notes for the release of CodeQl 2.15.4 documentation.

### CODE REVIEW

**Review by felicitymay — CHANGES_REQUESTED** [review]
@coadaflorin - I'm wondering if you intended to include the `dox-out` folder in this pull request. Could you take a look?

**Comment by coadaflorin** [comment]
@felicitymay most likely that should not be there. Let me correct!

**Comment by coadaflorin** [comment]
@felicitymay thanks for catching that. Let me know how it looks now!

**Comment by turbo** [comment]
I reviewed the changes on 2.15.3 and 2.15.2 and verified all the changes are OK - they're expected based on typos and other fixes that landed between releases on old changenotes.

I'll leave the review of 2.15.4's CL to the docs team 🙂

**Review by felicitymay — APPROVED** [review]
Thanks for fixing up the content of the PR ✨ 

The new change log looks reasonable to me. 

Going forwards, we might want to suggest people include links to the query help on the CodeQL docs site for new and revised queries. If we don't have a style guide for change log entries, we should probably create one.

**Pull request merged**
