### PR TITLE
Bump all qlpacks major versions

### PR DESCRIPTION
**Pull request by alexet**

### CODE REVIEW

**Comment by jketema** [comment]
Won't this conflict with https://github.com/github/codeql/pull/12819 once that gets merged back into main?

**Comment by alexrford** [comment]
> Won't this conflict with #12819 once that gets merged back into main?

`codeql-cli-2.13.0` is going to be recreated after this is merged.

**Comment by jketema** [comment]
> > Won't this conflict with #12819 once that gets merged back into main?
> 
> `codeql-cli-2.13.0` is going to be recreated after this is merged.

Great, that clarifies things.

**Review by alexrford — APPROVED** [review]
LGTM

**Pull request merged**
