### PR TITLE
Rust: rename `TypeRef` and `*Type` to `*TypeRepr`, `ty` to `type_repr`, and expand some abbreviations in generated docs

### PR DESCRIPTION
**Pull request by redsun82**
We were already renaming the tip of the type reference hierarchy from `Type` to `TypeRef` but weren't doing so with all its descendants.

Additionally, the `pat` and `ty` abbreviations are now expanded in generated documentation.

### CODE REVIEW

**Comment by paldepind** [comment]
Why do we want to rename `*Type` to `*TypeRef`? Why are they type references and not just types?

**Comment by redsun82** [comment]
> Why do we want to rename `*Type` to `*TypeRef`? Why are they type references and not just types?

These are all instances of types written in the code (they are `AstNode`s, they have a location), and especially they can be optional. "Real" types are semantic, unique despite all the different references to them, and also present for terms that don't have a type spelled out in the code, so they really are a different thing from what I changed here.

**Comment by redsun82** [comment]
> so they really are a different thing from what I changed here

(a thing we don't have, yet)

**Comment by paldepind** [comment]
Thanks for the explanation @redsun82 👍  🙏 . I guess the name "Ref" isn't very intuitive to me, but aside from that it makes sense. It's the distinction between syntax or notation representing a type and the actual type itself.

**Review by paldepind — DISMISSED** [review]

**Comment by redsun82** [comment]
@paldepind I went with the rename to `TypeRepr`, I also find it more intuitive. I've also changed all the `getTy` predicates to more explicit `getTypeRepr` (which will also cause less confusion when we start to have `getType` for actual semantic types), and went for a more specific `getElementTypeRepr` for `ArrayTypeRepr`.

**Review by paldepind — APPROVED** [review]
Really great changes 🤩

**Comment by redsun82** [comment]
@paldepind I had to merge in main, can you reapprove please?

**Review by paldepind — APPROVED** [review]

**Pull request merged**
