### PR TITLE
Java: Fix overrides to not be transitive.

### PR DESCRIPTION
**Pull request by aschackmull**
The `Method.overrides(Method)` relation was accidentally transitive. This has been a minor bit of technical debt for a long time, but isn't expected to have much impact as uses are mostly of the transitive form `a.overrides*(b)` and the qldoc has been claiming that only direct overrides were being included.

### CODE REVIEW

**Review by atorralba — COMMENTED** [review]
So, this is now expected to only return the directly (i.e. first) overridden method in the hierarchy, instead of all the methods with the same signature in all supertypes, and because of that it allows to skip intermediate types that don't declare a method with that signature, right?

If I understood that correctly, it LGTM. Some test expectations need fixing, though:

```
FAILED: ql/java/ql/test/library-tests/overrides/ConstructedOverrides2.ql
FAILED: ql/java/ql/test/query-tests/dead-code/DeadMethod/DeadMethod.qlref
```

**Comment by aschackmull** [comment]
> and because of that it allows to skip intermediate types that don't declare a method with that signature, right?

It already allowed that. The following equation holds `new_overrides = old_overrides+`. I.e. all the places that mention `Method.overrides*` or `Method.overrides+` should see the exact same tuples.

**Comment by atorralba** [comment]
Yes, I was just trying to write down what I understood about the block after the `or` in the new `overridesCandidateType` predicate.

> The following equation holds `new_overrides = old_overrides+`.

🤔 Isn't it `new_overrides+ = old_overrides`? As I understand it, `overrides` without the transitive closure should return less results now, right?

**Comment by aschackmull** [comment]
> Isn't it `new_overrides+ = old_overrides`?

Yes, you're right. I wrote that a bit too quickly.

**Review by atorralba — APPROVED** [review]

**Comment by aschackmull** [comment]
The queries `java/missing-override-annotation` and `java/non-overriding-package-private` produce fewer results. The removed results were essentially duplicates, so this is fine.

**Comment by aschackmull** [comment]
Timings look good now.

**Review by atorralba — APPROVED** [review]

**Pull request merged**
