### PR TITLE
QL4QL: catch behaviour/behavior in ql/non-us-spelling

### PR DESCRIPTION
**Pull request by nickrolfe**

### CODE REVIEW

**Review by owen-mc — APPROVED** [review]
I don't understand the Code scanning warning, but this PR is obviously good.

**Comment by erik-krogh** [comment]
> I don't understand the Code scanning warning, but this PR is obviously good.

If you're talking about the `Consistency predicate that should be empty`-warning, then it's caused by the QL-for-QL parser being confused about trailing commas in set literals.  
We know about it, and it will get fixed (after Taus has reworked the Tree-sitter grammars).

**Review by erik-krogh — APPROVED** [review]
JS and QL-for-QL :+1:

**Review by hvitved — APPROVED** [review]
C# 👍

**Review by MathiasVP — APPROVED** [review]
C++ 👍

**Comment by nickrolfe** [comment]
I haven't had a review from the Python team, but this seems like such an uncontroversial change that I'm sure they won't mind.

**Pull request merged**
