### PR TITLE
Swift: Expand models for UnsafePointer and friends

### PR DESCRIPTION
**Pull request by geoffw0**
Expand the models for the 8 core Swift pointer classes (`UnsafePointer` and friends), plus `Slice`.  These models were very fragmented and mostly just consisted of the 'closure methods' we've made an effort on + a few things we happened to use in tests of other functionality.  Now they're now more-or-less completely modelled.

There are quite a large number of MAD rows in this PR because, as far as I can tell, there's not much class hierarchy between the 8 pointer classes.  There are lots of similarities / duplication, but also lots of (possibly justified) minor differences.  I've only created a random scatter of test cases, we'll just have to trust that the documentation + my models are accurate ... or alternatively, trust that the impact of any mistakes is likely to be quite low compared to the impact of not having these models at all!

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
The changes LGTM, but let's have a DCA run to be on the safe side 🙂

**Comment by geoffw0** [comment]
There's also a test failure in a test I hadn't run locally.  I'll fix that, then start a DCA run...

**Comment by geoffw0** [comment]
... we lose a result in the path injection test because we're modelling collection content in these pointers correctly now, but the `TaintInheritingContent` for `NSString.utf8String` isn't adding collection content to the access path.  I've added a commit to accept the test regression, and created an issue to fix the problem - but this is not a trivial issue.

I could fix _this instance_ of the problem now by creating duplicate pointer models that don't specify `.CollectionElement`.  We're already have duplicate models in some cases (highly abstract protocols where the content could be one of several different things), but that case is more principled than this case.  So I'm reluctant to go down this route.

**Comment by MathiasVP** [comment]
> I could fix _this instance_ of the problem now by creating duplicate pointer models that don't specify `.CollectionElement`. We're already have duplicate models in some cases (highly abstract protocols where the content could be one of several different things), but that case is more principled than this case. So I'm reluctant to go down this route.

Yeah, I agree. Let's just accept this regression for now and come up with a better plan for how to address this.

**Comment by geoffw0** [comment]
DCA LGTM.

I was seeing consistency check failures in one test on CI for Linux (only).  Tried merging in latest main, now there are two tests with consistency check failures.  Hmm.  :(

**Comment by geoffw0** [comment]
Right - it appears this branch has been the victim of some kind of extractor bug, which causes it to fail on some swift code (we don't know what yet) on Linux.  An issue has been created for that.

The consistency failure in the `CWE-327` test should go away with a merge of latest `main`, because that test was only added recently and has been reverted (for now) to get `main` working.

The consistency failure in the `dataflow/taint/libraries` test on the other hand must be "caused" (triggered) by some of the `.swift` code I've added in this PR.  It only occurs on Linux and I don't have easy access to a Linux machine for testing, so I'm going to do a couple of experiments on this branch and will be adding and deleting commits for a bit.  Please ignore.

**Comment by geoffw0** [comment]
I've narrowed down the lines of tests that trigger the extractor issue and commented them out.  CI now passes.  I have created an issue to repair the test after the underlying extractor issue is fixed.

**Review by MathiasVP — APPROVED** [review]
Still LGTM!

**Pull request merged**
