### PR TITLE
ATM: New function parameters features

### PR DESCRIPTION
**Pull request by kaeluka**
This depends on the currently open PR #8586.

The PR adds two new features.

| Name | Description |
|-----|----|
| `contextSurroundingFunctionParameters` | contains the parameters of all surrounding functions |
| `contextFunctionInterfacesInFile` | contains the interfaces (eg., `name(param1, param2, param3)`) of all functions in the same file |

See `test.js` and `FeatureValue.expected` for the exact values of those features.

The features are disabled for now to avoid performance regressions.

The first *new* commit in this PR is the one called "add functionInterfacesInFile and surroundingFunctionParameters features"

### CODE REVIEW

**Comment by annarailton** [comment]
FYI base test failures have been fixed in https://github.com/github/codeql/pull/8597

**Comment by kaeluka** [comment]
Thanks, @annarailton! I think it's best to wait for @esbena to rebase #8586 first and then I'll get the change in here as well.

**Comment by tiferet** [comment]
Relevant conversation about newlines (logging this here so we remember to revisit it before merging this PR): https://github.slack.com/archives/CP9127VUK/p1648799123641439

**Comment by kaeluka** [comment]
I'm closing this PR and will merge it into #8740 as it's getting a bit tedious to maintain both separately when they won't be merged that soon

**Pull request closed without merging**
