### PR TITLE
Show lines of code data in debug mode only

### PR DESCRIPTION
**Pull request by henrymercer**
The new file coverage metrics are available in all supported GHES versions. This PR tags lines of code queries as `debug`.  This means that lines of code information will only be shown in the logging output of the CLI when running at higher verbosities (including the CodeQL Action debug mode).  Lines of code information will also still be available in the SARIF file.

The one exception is the metric queries for Java/Kotlin that provides separate lines of code information for Java and Kotlin. I've left these as non-debug level since separate file coverage information for languages like Java and Kotlin is only available for GHES 3.12 and later.

### CODE REVIEW

**Review by mbg — DISMISSED** [review]

**Comment by henrymercer** [comment]
I've added a changenote on the CLI side.

**Review by geoffw0 — APPROVED** [review]
:+1: (CPP and Swift; though I don't really see a need for sign off from every language here)

**Review by RasmusWL — DISMISSED** [review]
LGTM (I agree that you can just merge without more approvals)

**Comment by henrymercer** [comment]
Based on some internal feedback, I'm going to implement a "debug" level for metric queries that means they will only show up in the analysis summary at higher verbosities, for example when running in the CodeQL Action debug mode.

This lets advanced users see the lines of code information more easily, while we display only the improved and less flawed file-based coverage information by default.

**Review by michaelnebel — APPROVED** [review]
LGTM

**Pull request merged**
