### PR TITLE
Python: Restructure query file layout

### PR DESCRIPTION
**Pull request by RasmusWL**
Since I can never remember the CWE numbers

### CODE REVIEW

**Review by tausbn — APPROVED** [review]
... Shouldn't that be `SshMissingHostKeyValidation`? :trollface: 
(Ditto everything API. And HTTPS.)

Apart from that it looks good!

**Comment by tausbn** [comment]
A few test errors popped up:
- A bunch of new results (or at least path edges) in `ql/python/ql/test/query-tests/Security/Injection/TarSlip/PathInjection/PathInjection.qlref`
- Also, `PathInjection` tests appear to have been deposited inside the `TarSlip` directory, causing the latter to fail to extract.

My guess is that the underlying cause is the same.

**Comment by yoff** [comment]
A few inconsistencies in the line ending in qlrefs. I think they have simply been preserved, which is fine. I just wondered if those files are run through a pipeline that could just as easily fix it. If not, I am fine with just leaving it.

**Comment by yoff** [comment]
I think my only question is why two queries are put under `POI` rather than `Security`, are they not actually security related?

**Comment by RasmusWL** [comment]
@felicitymay I've removed you as a reviewer. This PR only moves files around, so I don't think it's meaningful for you to review it :blush:

**Comment by RasmusWL** [comment]
> ... Shouldn't that be `SshMissingHostKeyValidation`? :trollface:
> (Ditto everything API. And HTTPS.)

:laughing: well... I guess that's true (or soon will be). Let's do that change later down the line? :wink:

**Comment by RasmusWL** [comment]
> I think my only question is why two queries are put under POI rather than Security, are they not actually security related?

Fair point. I thought of them more as "manual debugging related" queries than security queries... but what the hell, they are still security related, so I moved them back :+1:

**Review by tausbn — APPROVED** [review]

**Pull request merged**
