### PR TITLE
Remove pragma[assume_small_delta]

### PR DESCRIPTION
**Pull request by cklin**
This PR removes `pragma[assume_small_delta]`, which has no effect and is no longer needed.

See referenced issue for details.

### CODE REVIEW

**Review by owen-mc — APPROVED** [review]

**Comment by owen-mc** [comment]
Go 👍🏻

**Review by jketema — APPROVED** [review]

**Review by hvitved — APPROVED** [review]
I assume you are confident that DCA runs are not needed :-)

**Review by geoffw0 — APPROVED** [review]
> I assume you are confident that DCA runs are not needed

If I understand correctly `pragma[assume_small_delta]` already has no effect on `main`, so this change seems very safe.  The changes that led up to this _would_ have been quite risky and I assume were heavily tested.

**Comment by cklin** [comment]
> > I assume you are confident that DCA runs are not needed
> 
> If I understand correctly `pragma[assume_small_delta]` already has no effect on `main`, so this change seems very safe. The changes that led up to this _would_ have been quite risky and I assume were heavily tested.

That is correct.  Compiler support for handling `pragma[assume_small_delta]` was removed almost 2 months ago.  Yes, it was a risky change.  And yes, it was very heavily tested 🙂

**Review by atorralba — APPROVED** [review]

**Pull request merged**
