### PR TITLE
Go: fix multiple anonymous type parameters

### PR DESCRIPTION
**Pull request by owen-mc**
#### All query authors

- [x] A change note is added if necessary. See [the documentation](https://github.com/github/codeql/blob/main/docs/change-notes.md) in this repository.
- [ ] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.
- [x] QL tests are added if necessary. See [Testing custom queries](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/testing-custom-queries) in the GitHub documentation.
- [ ] New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.

#### Internal query authors only

- [ ] Autofixes generated based on these changes are valid, only needed if this PR makes significant changes to `.ql`, `.qll`, or `.qhelp` files. See [the documentation](https://github.com/github/codeql-team/blob/main/docs/best-practices/validating-autofix-for-query-changes.md) (internal access required).
- [ ] Changes are validated [at scale](https://github.com/github/codeql-dca/) (internal access required).

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Change looks right (pleasantly surprising to find they can tell you their own param-list indices... but still not which param list that is?) -- test changes are a bit surprising though, and don't seem to be passing.

**Comment by owen-mc** [comment]
The test changes seem to be related to functions introduced in Go 1.23, which I have installed locally. The CI runners [seem to be](https://github.com/github/codeql/actions/runs/10796264464/job/29944862119?pr=17429#step:3:21) installing Go ~1.22.0. Which surprises me.

**Comment by owen-mc** [comment]
Ah, it's because we haven't done the mergeback to get 1.23 in `main` yet. The tests are passing now, so please re-review @smowton .

**Comment by mbg** [comment]
If the test output was different because you were running with Go 1.23, then I don't think it makes sense to undo those changes to get the CI to pass. If we merge this PR with expected test output for Go 1.22, then the tests will suddenly fail again as soon as the mergeback with the Go 1.23 has happened.

**Comment by owen-mc** [comment]
I think this could be merged straight away, since it was approved modulo that one test failing. If the mergeback happens then I will remove the commit fixing the tests. The expected value of that test will have to be fixed for the mergeback anyway.

**Comment by owen-mc** [comment]
DCA uneventful

**Pull request merged**
