### PR TITLE
Python: Ensure first type-tracking predicate is private

### PR DESCRIPTION
**Pull request by RasmusWL**
Updating the tests might not have been too important, but ensures we have a consistent use throughout our codebase :blush:

### CODE REVIEW

**Review by yoff — DISMISSED** [review]
LGTM
(we can do this, right? No deprecation needed..?)

**Comment by RasmusWL** [comment]
> (we can do this, right? No deprecation needed..?)

Hmm :thinking: I think if you want to follow our deprecation policies to the letter, I guess you could argue that these predicates have been public for long enough that you can't just remove them...

From my point of view, that is too pedantic, since none of these predicates offers any additional value compared with their variants without TypeTracking parameter.

In this situation, I think our ability to fix our code-base outweighs the downside from not following our deprecation policy to the letter.

**Comment by tausbn** [comment]
I agree. Each of these is an internal helper predicate used to define an external predicate of the same name. It makes little sense to use them directly.

**Review by yoff — APPROVED** [review]
LGTM

**Comment by yoff** [comment]
Ship to learn, then..

**Pull request merged**
