### PR TITLE
Python: Add precision to NoSQL query

### PR DESCRIPTION
**Pull request by RasmusWL**
Due to this, it was not part of any query suite :O

@yoff do you agree it should be `high`, or should it be `medium`? I don't have the details from when you did the promotion of this query, so just took a guess.

### CODE REVIEW

**Comment by yoff** [comment]
> @yoff do you agree it should be `high`, or should it be `medium`? I don't have the details from when you did the promotion of this query, so just took a guess.

Yes. I read through the old PR to jog my memory. I think 'high' should be defensible.

**Review by yoff — DISMISSED** [review]
LGTM

**Comment by yoff** [comment]
Do we need a change note about this query now being included by default? Thanks for cleaning up this mess!

**Comment by RasmusWL** [comment]
> Do we need a change note about this query now being included by default? Thanks for cleaning up this mess!

sure, I made one :+1: I based it on the following, but put emphasis on the fact that it's run by default now :sweat_smile:  https://github.com/github/codeql/blob/9fe993bec34d4ffe177f8bec3206b3e6019baef7/python/ql/src/change-notes/released/0.9.0.md#L5

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
