### PR TITLE
JS/ATM: Various compilation fixes and performance improvements

### PR DESCRIPTION
**Pull request by adityasharad**
This PR attempts to improve the evaluation performance of the ATM queries and libraries, focused on slow bottlenecks that take 10s or more on a moderately large database.

Semantics should be largely unchanged, with the exception of a few places where I've used the strict version of aggregates, which will now have no results (rather than the unit of the aggregation operation) if there are no tuples satisfying the aggregation expressions.

Commit-wise review highly recommended. See commit descriptions and inline comments for further explanation of each change. Careful testing with the actual models against some candidate databases highly recommended, to make sure I haven't changed how features are represented.

### CODE REVIEW

**Comment by erik-krogh** [comment]
LGTM :+1: 

[An evaluation](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7307-nightly-lgtm-full/reports) looks great :+1:  

But you need to run the autoformatter on `EndpointFeatures.qll`.

**Comment by esbena** [comment]
> An evaluation looks great +1

While impressive, the evaluation is not representative since it does not make use of the ml-model. A small DCA change is required to download the model on the fly. 
I'm about to look into fixing ATM FPs so I might just add DCA ml-model support immediately.

**Comment by henrymercer** [comment]
https://github.com/github/codeql/pull/7307/commits/0e31439b7e4075d2c2dedd0d45ab3d7c811ec866 appears to some small side effects where we duplicate some tokens in the function body feature.  I've pushed a couple of commits: the first removes that side effect, and the second autoformats `EndpointFeatures.qll` so that the language tests should start passing.

**Review by henrymercer — COMMENTED** [review]
Will do some final testing of this internally, but LGTM otherwise.

**Comment by henrymercer** [comment]
End-to-end evaluations: https://github.com/github/ml-ql-adaptive-threat-modeling-backend/actions/workflows/evaluate-boosted-query.yml?query=branch%3Ahenrymercer%2Fupdate-for-ql-optimizations

**Review by henrymercer — APPROVED** [review]
LGTM for the ATM changes.  There look to be a couple of failing tests in the standard JS library.

**Comment by adityasharad** [comment]
Looks like the regex-combining wasn't actually behaviour-preserving. Will see if I can fix that so it has no diffs, otherwise back out that change.

**Review by henrymercer — APPROVED** [review]
LGTM.  Could I get a signoff from @github/codeql-javascript on the standard library changes?

**Review by erik-krogh — APPROVED** [review]
> LGTM. Could I get a signoff from @github/codeql-javascript on the standard library changes? 

Yes you can :+1: 
I got [an evaluation running of the stdlib changes](https://github.com/github/codeql-dca-main/tree/data/erik-krogh/pr-7307-nightly-lgtm-full-2/reports), and that looks good.  

I have tried to fix the performance of `FrameworkLibraries.qll` a few times myself, but without success. 
So it's great to see that someone was finally able to do it :tada:

**Pull request merged**
