### PR TITLE
C++: Remove `pragma[noinline]` from `ResolveGlobalVariable.ql`

### PR DESCRIPTION
**Pull request by jketema**

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
The changes in 5e2baef8ce31cf448eabd450874484f4a7c6511a LGTM! Feel free to merge that once https://github.com/github/codeql/pull/9700 has gone in.

**Comment by geoffw0** [comment]
New DCA run LGTM (there is only query flagged as slowed down, but its a very fast query and looks like wobble to me).

**Review by geoffw0 — APPROVED** [review]
Re-approving. :+1:

**Comment by jketema** [comment]
> New DCA run LGTM (there is only query flagged as slowed down, but its a very fast query and looks like wobble to me).

Yeah, I did see that exact same one wobble in a nightly last week, and also on some other of my draft PRs.

**Pull request merged**
