### PR TITLE
C++: Deprecate AST dataflow

### PR DESCRIPTION
**Pull request by MathiasVP**
All of our queries use IR dataflow now (hopefully!).

### CODE REVIEW

**Comment by jketema** [comment]
This needs a change note, and I think the micro-site docs need to be updated as part to this to say that the library is deprecated (not that we're going to deprecate it at some point). Also some tests will probably fail, because they'll now include a deprecation warning.

**Comment by jketema** [comment]
> > I think the micro-site docs need to be updated as part to this to say that the library is deprecated (not that we're going to deprecate it at some point).
> 
> Good point. I guess we'll simply change the wording in https://github.com/github/codeql/blob/main/docs/codeql/codeql-language-guides/analyzing-data-flow-in-cpp.rst, right?

Yes.

> > Also some tests will probably fail, because they'll now include a deprecation warning.
> 
> Yeah, I think it's fine to just accept these. Then we can delete those annotations completely once we delete the library.

Agreed.

**Comment by jketema** [comment]
Oh yeah, coding standards 😭

**Comment by MathiasVP** [comment]
😭

**Comment by rvermeulen** [comment]
Coding standards is pinned to a CodeQL CLI and standard library version.

**Comment by jketema** [comment]
> Coding standards is pinned to a CodeQL CLI and standard library version. 

Indeed, but the `next` branch which we test against isn't, and that's causing problems here. Of course that branch exists to catch these kinds of problems early.

**Comment by MathiasVP** [comment]
> Last time it was around a year I believe.

Correct 🙂

**Comment by jketema** [comment]
I believe we can move forward with this, and we just have to update the test results on the coding standards `next` branch to include the deprecation warnings.

**Comment by MathiasVP** [comment]
This PR is ready for a docs review. Documentation friends: Would you please review the changes to the `analyzing-data-flow-in-cpp.rst` file?

**Review by jhosman — APPROVED** [review]
The text changes in `analyzing-data-flow-in-cpp.rst` look good! 👍

**Review by jketema — APPROVED** [review]

**Pull request merged**
