### PR TITLE
Dataflow: small fixes for naming in taint tracking

### PR DESCRIPTION
**Pull request by RasmusWL**

### CODE REVIEW

**Review by hvitved — APPROVED** [review]
C# + share code 👍

**Comment by calumgrant** [comment]
Can I double-check that we are using inclusive language? Sanity/sanitizer could be problematic as it could refer to mental health.

Since the word "barrier" is used commonly in the code, why are we reintroducing the word "sanitizer"?

**Comment by aschackmull** [comment]
> Sanity/sanitizer

Is that even the same word stem? Sanitization means cleaning, so I guess they might be entirely separate words that merely share the same first couple of letters? Or am I missing some etymology here?

**Review by aschackmull — APPROVED** [review]

**Comment by RasmusWL** [comment]
> Since the word "barrier" is used commonly in the code, why are we reintroducing the word "sanitizer"?

This PR simply cleans up the dataflow library to use the two terms consistently. From [Analyzing data flow in C#](https://help.semmle.com/QL/learn-ql/csharp/dataflow.html):

- `isBarrier` - optionally, restricts the data flow.
- `isSanitizer` - optionally, restricts the taint flow.

> Can I double-check that we are using inclusive language? Sanity/sanitizer could be problematic as it could refer to mental health.

Sure :+1: if we need to stop using the term "sanitizer", we need to change _lots_ of things, and I don't think this wouldn't be the right PR to do so.

_Disclaimer: I had a 1-1 with Calum anyway just now, and as I understood, we agreed that this concern should not block this PR_

**Comment by aschackmull** [comment]
> > Sanity/sanitizer
> 
> Is that even the same word stem? Sanitization means cleaning, so I guess they might be entirely separate words that merely share the same first couple of letters? Or am I missing some etymology here?

I think we're good. I did a little bit of research. As far as I know the issue with the word "sanity" (usually in the context "sanity check") is due to it meaning "mental health". "Sanitization" on the other hand merely means cleaning and comes from "sanitary" meaning "relating to the preservation of health".  The only shared origin between the two words that I could find is tracing back to the latin origin "sanitas" meaning "health".

**Review by jbj — APPROVED** [review]

**Review by tausbn — APPROVED** [review]
I agree with the above comments regarding the suitability of (variants of) the word "sanitizer".

Given the role hand sanitizer plays in the world currently, I'm sure most people would associate it with cleanliness.

(I will also add that I think some care must be taken in arguing by means of etymology. Even if the etymology of a term is entirely innocuous, it can still have harmful connotations.)

**Pull request merged**
