### PR TITLE
Python: Prevent potentially bad join order

### PR DESCRIPTION
**Pull request by tausbn**
This has no effect on the current compilation (indeed,
`ssa_filter_definition_bool` is not currently inlined), but will
prevent this from ever occurring, should the heuristics for inlining
ever change...

### CODE REVIEW

**Comment by yoff** [comment]
It seems you have added some beneficial annotations, is it still true that this PR has no effect on the current compilation?

**Comment by tausbn** [comment]
Indeed, more of these changes were needed, as it turns out. [Here](https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/478/)'s a performance comparison (which, to my eyes, appears to show no real change in performance). So I think this is safe to merge.

Also, I would expect the additional changes to only ever _improve_ performance. The joins they are preventing are always bad, as far as I can tell.

**Comment by ginsbach** [comment]
I can confirm that this fixes things!

```
16:51:49  Runtime                              baseline         branch1       
16:51:49  --------------------------------------------------------------------
16:51:49  python-kivy-codingstars               375027    383141 +2.16% +0.096
16:51:49  python-letsencrypt-codingstars        165026    167587 +1.55% +0.153
16:51:49  python-openstack-cinder-codingstars  2485498   2468516 -0.68% -0.295
16:51:49  --------------------------------------------------------------------
16:51:49  TOTAL:                               3025551   3019244 -0.21% +0.165
```

**Review by yoff — APPROVED** [review]
There might be some cleanup to do later, but knowing that this fixes issues, I will merge this now.

**Pull request merged**
