### PR TITLE
CPP: delete the deprecated Container::getURL predicates

### PR DESCRIPTION
**Pull request by erik-krogh**
Depends on internal PR (see backref).

### CODE REVIEW

**Comment by jketema** [comment]
I'm somewhat concerned that this causes a regression in one of our internal tests. However, the test seems to generate TRAP that is not representative of what the C/C++ extractor will generate (which will always include an appropriate location). So I think this change is ok, but I'd like to hear the opinion of someone else in @github/codeql-c-analysis.

**Comment by MathiasVP** [comment]
If the test isn't representative of what the extractor actually generates I'm also totally okay with this. In fact, we should probably update the test to better reflect what the extractor does.

**Comment by jketema** [comment]
>  In fact, we should probably update the test to better reflect what the extractor does.

Not sure whether that's worth it. The test tests something funny with sizes of things, and locations/urls are not really relevant for that and the size part of the test doesn't break by this change.

**Comment by jketema** [comment]
@erik-krogh Can you add a change note? I think we can approve/merge this.

**Comment by jketema** [comment]
I think the date on the change note should be `2023-06-19`, not `2023-19-06`.

**Review by jketema — APPROVED** [review]

**Comment by erik-krogh** [comment]
Rebased on `main` to get around a submodule bump.

**Comment by erik-krogh** [comment]
And another rebase on `main` to get around a submodule bump.

**Pull request merged**
