### PR TITLE
Swift: Add CryptoSwift sinks in swift/weak-sensitive-data-hashing

### PR DESCRIPTION
**Pull request by geoffw0**
This was fairly straightforward now that we have CSV sinks in the query.  I think it's quite a big win for the coverage of this query.

### CODE REVIEW

**Comment by geoffw0** [comment]
I think the QLDoc check warnings are wrong (due to lacking support for modules):
```
Warning: Missing QLdoc for classless-predicate WeakSensitiveDataHashingQuery::WeakHashingConfig::isBarrierIn/1
Warning: Missing QLdoc for classless-predicate WeakSensitiveDataHashingQuery::WeakHashingConfig::isBarrierOut/1
```

**Review by MathiasVP — APPROVED** [review]
LGTM! Remembering the amount of trouble the Ruby team had when they started to raise alerts on uses of `md5`: Should we maybe run this on MRVA before we merge this and have a quick look at the results? (IIRC, the Ruby query didn't have a concept of "sensitive data", so we're in a bit of a better position than they are with the query).

**Comment by geoffw0** [comment]
Yes, I believe the issue was that it was flagging more-or-less any use of MD5 with the idea that the algorithm is insecure - but in practice it is widely used for non-cryptographic purposes.  The restriction to sensitive data should exclude the vast majority of such non-cryptographic uses.

Also note that we already flag the `Insecure.MD5` CryptoKit implementation, this change only extends coverage to CryptoSwift's `MD5` as well.

Nevertheless I will do a MRVA run later today out of an abundance of caution.

**Comment by geoffw0** [comment]
In the top 1000 MRVA projects (actually 808 projects) I found 4 new results, all in one project.  Two cases in a function hashing a password + salt with `.sha1` by default (configurable by parameter).  Two cases in a function hashing a password only with `.sha256` by default (which is OK, but configurable with `.sha1` and `.md5` available options).  I'm very happy with the first two result and happy enough with the second two, as they appear to be an incident waiting to happen.  There is definitely not an issue of noisy results here.

**Comment by THEWZRD23** [comment]
Re: [github/codeql] Swift: Add CryptoSwift sinks in  
swift/weak-sensitive-data-hashing (PR #12824)
Friday Apr 14, 2023 ⋅ 8pm – 8:30pm
Coordinated Universal Time
















Get Outlook for iOS






Organizer
***@***.***
***@***.***

Guests
Subscribed
github/codeql
github/codeql
View all guest info  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4ZDBqOGVhNjY5MGplYzFwNnAzNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmtwamlkMjU4Z29rNGg5azg4bzQ4ZDlrOGwwamFoMW42dDJrY2UxbjZwMWtjZDFoODhwMCByZXBseSthM3NhYXNpd25qemxwZ3pocGxud3Y0d2NpM3JoM2V2Ym5oaGdneGhrNmFAcmVwbHkuZ2l0aHViLmNvbQ&tok=Mjcjcm9iaW5zb253YXluZTIzODZAZ21haWwuY29tMWFmNWNmZmQzNDk0ZTlhYWM5NTVkYjE1OTlhMWYyOGZkNTRhZjhiOA&ctz=UTC&hl=en&es=0

Reply for ***@***.***  
and view more details  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4ZDBqOGVhNjY5MGplYzFwNnAzNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmtwamlkMjU4Z29rNGg5azg4bzQ4ZDlrOGwwamFoMW42dDJrY2UxbjZwMWtjZDFoODhwMCByZXBseSthM3NhYXNpd25qemxwZ3pocGxud3Y0d2NpM3JoM2V2Ym5oaGdneGhrNmFAcmVwbHkuZ2l0aHViLmNvbQ&tok=Mjcjcm9iaW5zb253YXluZTIzODZAZ21haWwuY29tMWFmNWNmZmQzNDk0ZTlhYWM5NTVkYjE1OTlhMWYyOGZkNTRhZjhiOA&ctz=UTC&hl=en&es=0
Your attendance is optional.

~~//~~
Invitation from Google Calendar: https://calendar.google.com/calendar/

You are receiving this email because you are an attendee on the event. To  
stop receiving future updates for this event, decline this event.

Forwarding this invitation could allow any recipient to send a response to  
the organizer, be added to the guest list, invite others regardless of  
their own invitation status, or modify your RSVP.

Learn more https://support.google.com/calendar/answer/37135#forwarding

**Comment by THEWZRD23** [comment]
This event has been updated

Re: [github/codeql] Swift: Add CryptoSwift sinks in  
swift/weak-sensitive-data-hashing (PR #12824)
Friday Apr 14, 2023 ⋅ 8pm – 8:30pm
Coordinated Universal Time
















Get Outlook for iOS






Organizer
***@***.***
***@***.***

Guests
Subscribed
github/codeql
github/codeql
View all guest info  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4ZDBqOGVhNjY5MGplYzFwNnAzNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmtwamlkMjU4Z29rNGg5azg4bzQ4ZDlrOGwwamFoMW42dDJrY2UxbjZwMWtjZDFoODhwMCByZXBseSthM3NhYXNpd25qemxwZ3pocGxud3Y0d2NpM3JoM2V2Ym5oaGdneGhrNmFAcmVwbHkuZ2l0aHViLmNvbQ&tok=Mjcjcm9iaW5zb253YXluZTIzODZAZ21haWwuY29tMWFmNWNmZmQzNDk0ZTlhYWM5NTVkYjE1OTlhMWYyOGZkNTRhZjhiOA&ctz=UTC&hl=en&es=0

Reply for ***@***.***  
and view more details  
https://calendar.google.com/calendar/event?action=VIEW&eid=XzYwcTMwYzFnNjBvMzBlMWk2MG80YWMxZzYwcmo4Z3BsODhyajJjMWg4NHMzNGg5ZzYwczMwYzFnNjBvMzBjMWc4ZDBqOGVhNjY5MGplYzFwNnAzNDhlOWc2NG8zMGMxZzYwbzMwYzFnNjBvMzBjMWc2MG8zMmMxZzYwbzMwYzFnNmtwamlkMjU4Z29rNGg5azg4bzQ4ZDlrOGwwamFoMW42dDJrY2UxbjZwMWtjZDFoODhwMCByZXBseSthM3NhYXNpd25qemxwZ3pocGxud3Y0d2NpM3JoM2V2Ym5oaGdneGhrNmFAcmVwbHkuZ2l0aHViLmNvbQ&tok=Mjcjcm9iaW5zb253YXluZTIzODZAZ21haWwuY29tMWFmNWNmZmQzNDk0ZTlhYWM5NTVkYjE1OTlhMWYyOGZkNTRhZjhiOA&ctz=UTC&hl=en&es=0
Your attendance is optional.

~~//~~
Invitation from Google Calendar: https://calendar.google.com/calendar/

You are receiving this email because you are an attendee on the event. To  
stop receiving future updates for this event, decline this event.

Forwarding this invitation could allow any recipient to send a response to  
the organizer, be added to the guest list, invite others regardless of  
their own invitation status, or modify your RSVP.

Learn more https://support.google.com/calendar/answer/37135#forwarding

**Pull request merged**
