### PR TITLE
ReDoS: stop spuriously matching everything when encountering an unsupported charclass

### PR DESCRIPTION
**Pull request by erik-krogh**
Fixes a performance problem in Ruby.

### CODE REVIEW

**Comment by aibaars** [comment]
@erik-krogh Could you target the `rc/3.10` branch with this fix.

**Comment by erik-krogh** [comment]
> @erik-krogh Could you target the `rc/3.10` branch with this fix.

I've done that as a separate PR: https://github.com/github/codeql/pull/13469

**Comment by erik-krogh** [comment]
@aibaars do you know when/if `rc/3.10` is merged back into `main`?  
I'm thinking if this PR should just be closed if `rc/3.10` makes it into `main` soon.

**Comment by erik-krogh** [comment]
This has been indirectly merged into main through the `rc/3.10` branch - closing.

**Pull request closed without merging**
