### PR TITLE
C++: SSA and range analysis for reference parameters

### PR DESCRIPTION
**Pull request by jbj**
This PR changes the AST-based SSA and RangeSSA libraries to make the same assumption about reference-typed parameters that the IR does: that they don't alias any value that'll be mutated from within the function body.

A further commit, authored by @lcartey, adds support for reference-typed parameters in `SimpleRangeAnalysis`.

### CODE REVIEW

**Comment by jbj** [comment]
Started https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1373/. I expect to see a lot of differences on real-world code.

**Review by MathiasVP — COMMENTED** [review]
I think this LGTM, but I'll wait with the formal approval until we've validated the CPP-difference.

**Comment by jbj** [comment]
The CPP-Differences LGTM. The only changes are three new results from `cpp/comparison-with-wider-type` similar to [this one](https://github.com/microsoft/ChakraCore/blob/9f762f08e09953cfb9d4aeb6b4e834137c4cecdb/lib/Runtime/Types/DictionaryTypeHandler.cpp#L116). The `index` variable on the LHS is of type `PropertyIndex&`, which [is a typedef for `unsigned short &`](https://github.com/microsoft/ChakraCore/blob/9f762f08e09953cfb9d4aeb6b4e834137c4cecdb/lib/Runtime/RuntimeCommon.h#L38).

I had expected to see changes in all the queries that use SSA, and I can't really explain why the impact is so small.

**Comment by jbj** [comment]
I'd be tempted to say that the _use_ of a reference-parameter `SsaDefinition` is actually the `ReferenceDereferenceExpr` conversion. With this PR, [the `SsaDefinition.getAUse` predicate](https://github.com/github/codeql/blob/813d14791d6bea399bc96fa9b7143603eef6e6c4/cpp/ql/src/semmle/code/cpp/controlflow/SSA.qll#L44-L45) still has a `VariableAccess` result since I think it would be too disruptive to relax that to `Expr`. Almost all our queries and libraries assume that variable uses are of type `VariableAccess`. Unfortunately, `getType()` on these variable accesses gives `T&` instead of `T`, and I don't know if all queries deal with that properly. The `cpp/comparison-with-wider-type` query already had support for reference types.

On balance, I think this change is the least disruptive thing we can do that fixes the range analysis. Queries that want more information about indirections will have to use IR.

**Review by MathiasVP — APPROVED** [review]
LGTM!

**Pull request merged**
