### PR TITLE
C++: `AssignPointerAddExpr` and `AssignPointerSubExpr` should not be bitwise operations

### PR DESCRIPTION
**Pull request by MathiasVP**
Apparently we've been considering `AssignPointerAddExpr` and `AssignPointerSubExpr` as bitwise operations for almost 4 years (since I introduced this bug in one of my very first GitHub good-first-issues: https://github.com/github/codeql/commit/11a545e08e8ccf7f9092a5ad21afcc476be1dce1 🙈)

### CODE REVIEW

**Review by jketema — COMMENTED** [review]
Should we add a library change note for this?

**Comment by MathiasVP** [comment]
> Should we add a library change note for this?

Yeah, I think that's a good idea.

> I think it would also make sense to run a DCA experiment with uninterpreted queries enabled.

Doh! Good point. I'll rerun DCA with uninterpreted queries enabled.

**Comment by jketema** [comment]
You might want to add data set check for full measure

**Comment by MathiasVP** [comment]
@jketema the DCA run with dataset checks have completed now. I think it LGTM. Can I get your 👀 on it as well?

**Comment by jketema** [comment]
3 hours seems suspiciously fast, and I'm missing the frontend timings for some reason.

**Comment by MathiasVP** [comment]
> 3 hours seems suspiciously fast, and I'm missing the frontend timings for some reason.

Oh wait. Does dataset measure require me to disable database caching? 🤔

**Comment by jketema** [comment]
You made a schema change, I you will need to run without caching.

**Comment by MathiasVP** [comment]
> You made a schema change, I you will need to run without caching.

That's ... a good point

**Comment by jketema** [comment]
Also, it's a bit suspect that we get a change in IR inconsistencies with caching enabled. That means the schema change somehow affects IR generation?

**Comment by MathiasVP** [comment]
> Also, it's a bit suspect that we get a change in IR inconsistencies with caching enabled. That means the schema change somehow affects IR generation?

Yeah, I was wondering about that as well. I wrote it off as noise, but let me just investigate this while waiting for this (hopefully) last DCA run anyway.

**Comment by MathiasVP** [comment]
Can't reproduce the IR inconsistencies locally. Running the "count IR inconsistencies" query locally on the cached `openzfs` DB (on the HEAD of this PR) yields:
| missingOperand | unexpectedOperand | duplicateOperand | missingPhiOperand | missingOperandType | duplicateChiOperand | sideEffectWithoutPrimary | instructionWithoutSuccessor | ambiguousSuccessors | unexplainedLoop | unnecessaryPhiInstruction | memoryOperandDefinitionIsUnmodeled | operandAcrossFunctions | containsLoopOfForwardEdges | lostReachability | backEdgeCountMismatch | useNotDominatedByDefinition | switchInstructionWithoutDefaultEdge | notMarkedAsConflated | wronglyMarkedAsConflated | invalidOverlap | nonUniqueEnclosingIRFunction | fieldAddressOnNonPointer | thisArgumentIsNonPointer | nonUniqueIRVariable
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
| 520 | 0 | 0 | 1 | 3,726 | 0 | 0 | 104 | 2,970 | 0 | 2 | 0 | 0 | 0 | 0 | 0 | 59,391 | 0 | 44 | 0 | 0 | 0 | 0 | 0 | 77,431

which is exactly what we have on the "before" side on DCA.

**Comment by MathiasVP** [comment]
DCA looks fine. The same `IR inconsistencies` are still present, but that may now be from nondeterministic extraction.

**Review by jketema — COMMENTED** [review]
LGTM, still needs a change note though.

**Comment by MathiasVP** [comment]
> LGTM, still needs a change note though.

Added in 6e385cabd8ee19b2806ca3c59171356a7bd8ca93.

**Review by jketema — APPROVED** [review]

**Pull request merged**
