### PR TITLE
C++: Accept test changes caused by new CLI version.

### PR DESCRIPTION
**Pull request by geoffw0**
Similar to https://github.com/github/codeql/pull/17139 but for C++.

### CODE REVIEW

**Comment by alexet** [comment]
Can you target the release branch as a hotfix please.

**Review by owen-mc — APPROVED** [review]

**Comment by geoffw0** [comment]
Is that `codeql-cli-2.18.2`???  Should I open a second PR or attempt to re-target this one?

**Comment by dbartol** [comment]
I've merged this one into `main` but I'm creating a hotfix PR right now.

**Comment by dbartol** [comment]
Hotfix PR: https://github.com/github/codeql/pull/17163

**Comment by geoffw0** [comment]
Thanks @dbartol

**Pull request merged**
