### PR TITLE
C#: Add kind tag to Capture model queries.

### PR DESCRIPTION
**Pull request by michaelnebel**

### CODE REVIEW

**Comment by michaelnebel** [comment]
This is just a wild shot in getting the queries to run on DCA, but the changes needs to be merged before we can run DCA properly (as it will otherwise fail on main).

**Comment by hvitved** [comment]
> This is just a wild shot in getting the queries to run on DCA, but the changes needs to be merged before we can run DCA properly (as it will otherwise fail on main).

I don't understand: Why can't we just run the queries against this branch only?

**Comment by michaelnebel** [comment]
> > This is just a wild shot in getting the queries to run on DCA, but the changes needs to be merged before we can run DCA properly (as it will otherwise fail on main).
> 
> I don't understand: Why can't we just run the queries against this branch only?

Oh right - something like this 
image

**Comment by michaelnebel** [comment]
It looks like this is working.
I will try and run at single threaded DCA as well and see what the numbers look like in that case.

**Comment by michaelnebel** [comment]
Looks like the analysis time is now reported correctly via DCA.
image

**Review by hvitved — APPROVED** [review]

**Pull request merged**
