### PR TITLE
JS: Ignore JSON-like files in js/useless-expression

### PR DESCRIPTION
**Pull request by erik-krogh**
The anomalous query results found [a project with a lot of useless-expressions](https://lgtm.com/projects/g/WizTeam/WizQTClient/alerts?id=js%2Fuseless-expression&mode=list). 

However, most of those results were from JSON-like files. And while the expressions are useless, the warning looks benign.  

I added a condition on the `js/useless-expression` so it doesn't report an expression if the containing file only contains that expression.   
That pattern is [somewhat common](https://lgtm.com/query/5675048218760086780/). 

I could possibly restrict it further, such that we still report a useless expression if the expression contains a function?

### CODE REVIEW

**Comment by esbena** [comment]
If the goal is to exclude json-like constructs only, then I think we should try a little harder to weed out illegal json. Some ideas: can we remove variable references, function literals, regexp literals, calls?

(We have previously tried to classify entire json-like files as generated, but we never found a scalable way to to that reliably.)

**Comment by asgerf** [comment]
Looking great! 👍

We should probably exclude `CodeInAttribute` top-levels from this check, otherwise LGTM.

**Comment by erik-krogh** [comment]
> Some ideas: can we remove variable references, function literals, regexp literals, calls?

I've removed function literals from the check for now. When I look at [the results we no longer flag](https://lgtm.com/query/5675048218760086780/) I only want to remove functions from those.   
The rest with e.g. binary expressions look like a benign parser-tests or something. 

> We should probably exclude `CodeInAttribute` top-levels from this check, otherwise LGTM.

I don't think there is any need for that. 
Code in an attribute is already not in a void-context, and thus something like `<div onclick="[1,2,3]"></div>` is already not flagged.

**Comment by erik-krogh** [comment]
[An evaluation](https://git.semmle.com/erik/dist-compare-reports/tree/profiling-erik-krogh.northeurope.cloudapp.azure.com_1588692289929) looks fine.   
Lots of parser tests are no longer flagged as useless.

**Pull request merged**
