### PR TITLE
 Go: Convert go-restful, Gin and Mux sources to MaD

### PR DESCRIPTION
**Pull request by owen-mc**
Convert go-restful, Gin and Mux sources to MaD

I don't believe this needs a change note.

### CODE REVIEW

**Review by egregius313 — COMMENTED** [review]
Mostly LGTM.

But question: what is the plan for the models marked with `# TODO: add .ArrayElement`/`.MapValue`, etc?

Is this just the initial change to make the MaD conversion, and adding the appropriate modifiers will be done subsequently. (Like to minimize changes in this PR?)

**Comment by owen-mc** [comment]
Good question. At the moment sources can't have access paths. This is mostly okay because default taint steps fill in the gaps, e.g. if an array is tainted then any element in it is tainted. Because of that, I don't think it is something that will be fixed soon. These comments are so that when sources can have access paths, I can easily find places where I can change the models to use them.

**Comment by egregius313** [comment]
> At the moment sources can't have access paths.

Ah ok that makes sense.

**Review by egregius313 — APPROVED** [review]
LGTM

**Pull request merged**
