### PR TITLE
Data flow: Remove deprecated predicates

### PR DESCRIPTION
**Pull request by hvitved**

### CODE REVIEW

**Comment by aschackmull** [comment]
These were only just deprecated in 1.22, do we feel comfortable removing them already? Normally I'd wait until 1.26.

**Comment by hvitved** [comment]
> These were only just deprecated in 1.22, do we feel comfortable removing them already? Normally I'd wait until 1.26.

Do we have an official policy on this? I am normally OK with removing deprecated entities after just one release.

**Comment by jbj** [comment]
The official policy is at https://github.com/github/codeql/blob/master/docs/supported-queries.md:

> Once a query or library has appeared in a stable release, a one-year deprecation period is required before we can remove it. There can be exceptions to this when it's not technically possible to mark it as deprecated.

**Comment by hvitved** [comment]
Thanks @jbj. 1.22 was released in [August last year](https://help.semmle.com/wiki/display/REL/Semmle+1.22+-+release+notes), and I guess 1.25 will be released around August, so I it should be fine to remove the predicates?

**Comment by jbj** [comment]
I've raised it at https://github.slack.com/archives/CP6990YTU/p1589988187483700

**Pull request merged**
