### PR TITLE
Java: Magnitude test of data extensions.

### PR DESCRIPTION
**Pull request by michaelnebel**
In this PR we try to add around 3M tuples to the `extSummaryModel` predicate to try and investigate the performance effect.
We do rely in a quite large set of re-usable string as we can to some degree expect the same for real world code examples. (where the largest set of different strings will come from the method names for the extSummaryModel predicate).

A dummy test case has been added that just projects the first column of the `extSummaryModel` predicate.
Locally on my machine the test execution times are as follows (measured by `time codeql test run dummymodels.ql`)
1. 15s on main.
2. 60s on this branch.

That is, locally I experience an extra overhead of around 45s for reading the extra 3M data extension rows (this can also be confirmed by turning up the verbosity level on the test execution).

- CI fails with Java heap allocation problem.

Furthermore, five extra query suites containing only dummy queries have been added including a dummy script that executes `codeql database analyze` on a basically empty Java database.
Each of extra query suites depends of `java/codeql-all` (which has 3M+ models) and each query suite has 1M models.
That is, a totalt of around 8M tuples will be loaded.

### How to reproduce
From the Code QL repo `java/ql` subfolder execute:
```bash
python3 lotsofmodels.py <path to your Code QL clone>
```
My local example:
image

### CODE REVIEW

**Comment by michaelnebel** [comment]
@aeisenberg : It looks like the test execution CI jobs runs into an out of heap space exception during query compilation, when adding 3M tuples. The YAML files takes up around 400 MB of disk space, but there are many identical strings (no extreme pressure on the string pool) in the YAML files (as this is also what we would expect in a real world usecase).
Do you have any idea on, what could be causing this?

We might need millions as the order or magnitude for MaD at some point in time.

**Comment by michaelnebel** [comment]
@aeisenberg : I have added some extra query packs (see description above). Will this be sufficient for debugging purposes?

**Comment by michaelnebel** [comment]
@aeisenberg : Do we still need this PR for experimental purposes or can it be closed?

**Comment by aeisenberg** [comment]
Thanks....I don't need this PR any more. No problem to close it.

**Pull request closed without merging**
