### PR TITLE
SSA: Turn consistency predicates into `query` predicates

### PR DESCRIPTION
**Pull request by hvitved**
Possible now that class signatures are supported.

### CODE REVIEW

**Review by aibaars — APPROVED** [review]
Nice! Do we need to update the version of codeql/ssa in the qlpack.yml files. At the very least we'd need to update the lock files, don't we?

**Comment by aibaars** [comment]
> Nice! Do we need to update the version of codeql/ssa in the qlpack.yml files. At the very least we'd need to update the lock files, don't we?

Although, perhaps we don't; see also https://github.com/github/codeql/pull/10668#pullrequestreview-1162986575 .

**Review by michaelnebel — APPROVED** [review]
Looks good to me!

**Comment by hvitved** [comment]
> Nice! Do we need to update the version of codeql/ssa in the qlpack.yml files. At the very least we'd need to update the lock files, don't we?

All versions bumps should be part of the release process, AFAIK.

**Pull request merged**
