### PR TITLE
Update supported Go frameworks

### PR DESCRIPTION
**Pull request by owen-mc**
Is it too late to update the documentation for release 1.26?

### CODE REVIEW

**Review by smowton — APPROVED** [review]
Have asked the question in #lgtm-distribution. Thanks for this!

**Comment by calumgrant** [comment]
It's too late for the 1.26 branch, but please create a PR against https://github.com/github/codeql-release-notes/pull/9 with the changes and I'll be able to merge it today.

**Comment by calumgrant** [comment]
I see that the changes are already mentioned in the release notes, so I don't think this needs to go into the release notes themselves.

**Comment by calumgrant** [comment]
But make sure this change gets merged back into `main` if you do decide to merge to the `1.26` branch.

**Review by jf205 — APPROVED** [review]

**Comment by smowton** [comment]
@calumgrant do you want me to make a merge-1.26-into-main PR?

**Comment by calumgrant** [comment]
Yes please!

**Pull request merged**
