### PR TITLE
C#: Relational patterns

### PR DESCRIPTION
**Pull request by tamasvajk**
Relational patterns were at one point merged before. Then reverted, and now this is the revert of the revert commit 998e2de2c653e3f66cdc7d7b093f40068721e8b1.

~~[Stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/11/)~~

Rebased on top of https://github.com/github/codeql/pull/4656

Still missing:

- [x] Stats https://jenkins.internal.semmle.com/job/Stats/job/CSharp/29/
- [x] DB upgrade folder
- [x] Differences job ~~https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/767/~~ https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/781/
- [x] Fix change note date

### CODE REVIEW

**Comment by tamasvajk** [comment]
> [Stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/11/)

Stats job only passed because the testsuite job was not started with the correct parameters. I'll adjust it to receive the submodule SHA too.

Otherwise the test fails because of BDD node limit is reached.

**Comment by tamasvajk** [comment]
[New stats job](https://jenkins.internal.semmle.com/job/Stats/job/CSharp/13/)

**Comment by tamasvajk** [comment]
@hvitved I think this is ready to be merged. There's a slight performance loss on `DisposeNotCalledOnException.ql`.

**Review by hvitved — APPROVED** [review]

**Comment by hvitved** [comment]
> There's a slight performance loss on `DisposeNotCalledOnException.ql`.

That is within the margin of error, so I don't think there is an actual slowdown.

**Pull request merged**
