### PR TITLE
C++: Clean up ConversionConstructor.

### PR DESCRIPTION
**Pull request by geoffw0**
See https://github.com/github/codeql/pull/3733#discussion_r443388037:
> We're not currently using ConversionConstructor in production, and I think it needs a bit of dusting off. Its charpred excludes copy constructors but not move constructors. That's been worked around by excluding move constructors in its getCanonicalQLClass override, but surely that exclusion should be moved to its charpred?

So I've done that here.

Compatible with https://github.com/github/codeql/pull/3733.

### CODE REVIEW

**Comment by MathiasVP** [comment]
I noticed that [cppreference](https://en.cppreference.com/w/cpp/language/converting_constructor) mentions that:

> Implicitly-declared and user-defined non-explicit copy constructors and move constructors are converting constructors.

So would it not be more standards-conforming to relax the charpred and allow `CopyConstructor` and `MoveConstructor` to be instances of `ConversionConstructor`?

**Comment by jbj** [comment]
Good point, Mathias. Then `CopyConstructor` and `MoveConstructor` should really inherit from `ConversionConstructor`, right? Then `getCanonicalQLClass` will do the right thing without any exclusions.

**Comment by MathiasVP** [comment]
> Good point, Mathias. Then `CopyConstructor` and `MoveConstructor` should really inherit from `ConversionConstructor`, right? Then `getCanonicalQLClass` will do the right thing without any exclusions.

That sounds like the right approach. While we're at it, cppreference also mentions this as a conversion constructor:

```cpp
A(int, int) { } // converting constructor (since C++11)
```

suggesting that we should remove the `strictcount` requirement as well?

**Comment by jbj** [comment]
> [...] suggesting that we should remove the `strictcount` requirement as well?

As I read cppreference, a constructor like `A(int, void *)` is not a converting constructor because those parameters are not similar enough to go into a `std::initializer_list` together. So the `strictcount` would have to be replaced with a type-list check. Seems like a can of worms.

If we change `ConvertingConstructor` to be C++11-conformant, then I think it will be too far removed from the application in #3733: a hint for where taint should be propagated.

After thinking about these complications I'm now more inclined to say we should deprecate `ConvertingConstructor` and just write the heuristics we want into the taint model implementation. If those heuristics don't correspond to any concept in the C++ standard, then so be it.

**Comment by geoffw0** [comment]
> So would it not be more standards-conforming to relax the charpred and allow CopyConstructor and MoveConstructor to be instances of ConversionConstructor? (But maybe still exclude them from getCanonicalQLClass.)

Done.

> we should deprecate ConvertingConstructor and just write the heuristics we want into the taint model implementation.

Assuming everyone's happy with this, I can't actually implement it until https://github.com/github/codeql/pull/3733 is merged.

**Comment by jbj** [comment]
I've merged #3733. But this cleanup is not urgent, of course.

**Comment by geoffw0** [comment]
Deprecated `ConversionConstructor`.  This PR should now be ready to merge.

**Comment by geoffw0** [comment]
Fixed tests.  Thank you for your patience.

**Comment by geoffw0** [comment]
There's a test failure in code, I've made a corresponding PR https://git.semmle.com/Semmle/code/pull/37307 where the tests should all pass.  That PR should be merged at the same time as this one.

**Comment by geoffw0** [comment]
CPP tests passed in the associated code PR.

**Comment by jbj** [comment]
The new internal PR is https://github.com/github/semmle-code/pull/37307.

**Comment by geoffw0** [comment]
Ready to merge (both PRs together; the tests are passing on the other one).

**Pull request merged**
