### PR TITLE
C++: Model std::vector emplace and emplace_back()

### PR DESCRIPTION
**Pull request by criemen**
Fixes https://github.com/github/codeql-c-analysis-team/issues/159.
I recommend commit-by-commit review for the test changes, as the addition to `stl.h` lead to some churn.

### CODE REVIEW

**Comment by geoffw0** [comment]
LGTM.

Do you think it will be valuable to extend this to `std::array`, `std::deque`, `std::list` and `std::forward_list` at some point (to the extent that they have similar `emplace` methods) - or is `vector::emplace` the vast majority of usage anyway?

@dbartol in our meeting last week you asked us to try and avoid merging changes to taint tracking while you finished getting a big PR merged.  Is that done, and if not is this change likely to conflict?

**Comment by criemen** [comment]
I haven't looked closer at the other classes that we don't have support for, but at lest for `std::set`, `std::vector` and `std::map` `emplace` has slightly different semantics (arguments, return value), so our implementation does not generalize.
The question about usage could be best answered by a query run across LGTM I guess?

Let's wait with merging this until #4432 lands, as we do touch the same test files.

**Comment by geoffw0** [comment]
It [looks like](https://lgtm.com/query/6081173645976738687/) there are a few uses of the others, particularly `list` and `deque`, but not as many as for `vector`.  There are also a lot of uses on a class `_Hashtable`, which appears to be a commonly occurring implementation class(?).  So modelling these is not as important as the `vector` and `map` work.

**Review by geoffw0 — APPROVED** [review]
#4432 is merged, so I will merge this as soon as I'm able.

**Pull request merged**
