### PR TITLE
Rust: Accept data flow inconsistencies

### PR DESCRIPTION
**Pull request by paldepind**

### CODE REVIEW

**Review by geoffw0 — APPROVED** [review]
LGTM, assuming CI passes.

**Comment by geoffw0** [comment]
Ah, I think https://github.com/github/codeql/pull/17943 beat us to it.

**Comment by geoffw0** [comment]
(my fault, I think I mentioned the underlying problem in two places without linking to each other)

**Comment by paldepind** [comment]
Oh, yeah. They did 😆

**Pull request closed without merging**
