### PR TITLE
C++: SimpleRangeAnalysis: Always normalize bounds after a computation

### LINKED ISSUE #4243: LGTM.com - false positive (integer negative 0)
**Description of the false positive**

negating integer 0 results in integer 0.

The analyzer seems to consider the integer val in expression `val = -val` to result in `-0`. This negative integer 0 is then considered *smaller* than 0, resulting in treating the condition `val == 0` as always false, because `val` is `-0` or smaller.

https://lgtm.com/projects/g/arvidn/libtorrent/snapshot/b9e5def6fe4855f710787c74e19123037fa5c5c3/files/src/entry.cpp?sort=name&dir=ASC&mode=heatmap#x468910299c931467:1

### PR DESCRIPTION
**Pull request by jbj**
Fixes #4243.

### CODE REVIEW

**Comment by jbj** [comment]
We might want to run a CPP-Differences job to validate this, but first I'll make sure the tests pass.

**Comment by jbj** [comment]
The checks have passed, except for a check that's broken on all PRs.

I've started https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1424.

**Review by geoffw0 — APPROVED** [review]
LGTM, will merge when the diff is complete.

**Comment by jbj** [comment]
[The CPP-Differences job](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1424) shows no result changes and no significant performance changes. There is a slight slowdown in `SignedOverflowCheck.ql`, which uses range analysis, but that same slowdown is present in `TaintedPath.ql`, which doesn't.

**Pull request merged**
