### PR TITLE
Automodel: Do not generate features for compiler-generated program elements.

### PR DESCRIPTION
**Pull request by max-schaefer**
These have dummy locations, which breaks certain invariants that break downstream processing.

Alternative to https://github.com/github/codeql/pull/15263; I think I prefer this approach since it's more targeted.

### CODE REVIEW

**Comment by max-schaefer** [comment]
I've been looking into writing a qltest to have a concrete example of this happening, and it looks like this is quite easy to do with Kotlin data classes. However, this obviously would require us to add Kotlin source files to the qltests for automodel, which in turn would mean that they can only be run using a custom-built CodeQL CLI (since Kotlin support is still in beta). Would that be acceptable, @kaeluka, or do you think it's too much faff?

**Comment by kaeluka** [comment]
> Would that be acceptable, @kaeluka, or do you think it's too much faff?

It's hard for me to say how tedious that would get.

Arguments against:
 - I think we could consider skipping such tests at least until Kotlin support is out of beta and then consider building them the simple way.
 - Even if untested, this seems to be the sort of feature that would be unlikely to break in the future.

Arguments in favour:
 - We usually try to test our changes here (but far from everything is tested!)

**Review by kaeluka — COMMENTED** [review]
Two high-level questions:
 1. how is this an alternative to removing Kotlin endpoints? Are those endpoints considered compiler generated somehow?
 1. I think there's a predicate in the standard libs that you might want to use instead of rolling your own: [`fromSource`](https://github.com/github/codeql/blob/1b9f59efa7b498e426d224b2c7615e5d9aefd557/java/ql/lib/semmle/code/java/Element.qll#L37). Have you considered using that?

**Comment by max-schaefer** [comment]
> how is this an alternative to removing Kotlin endpoints?

All problematic endpoints mentioned in the issue are from Kotlin code, but the converse is not true: many Kotlin endpoints are fine. The idea behind this PR is to not simply throw away all Kotlin endpoints, but only those that are problematic. We do this by excluding endpoints not based on them being from Kotlin code, but on the finer-grained criterion that actually makes them problematic, namely them having a dummy location.

> I think there's a predicate in the standard libs that you might want to use instead of rolling your own: [fromSource](https://github.com/github/codeql/blob/1b9f59efa7b498e426d224b2c7615e5d9aefd557/java/ql/lib/semmle/code/java/Element.qll#L37). Have you considered using that?

I have, but this does not do what I want: the compiler-generated calls in Kotlin I'm seeing are still associated with a source file, so `fromSource()` is true for these calls. I am certainly open to adding `not fromSource()` as an additional requirement here, but by itself it won't achieve what I want.

**Comment by kaeluka** [comment]
> All problematic endpoints mentioned in the issue are from Kotlin code, but the converse is not true: many Kotlin endpoints are fine. The idea behind this PR is to not simply throw away all Kotlin endpoints, but only those that are problematic. We do this by excluding endpoints not based on them being from Kotlin code, but on the finer-grained criterion that actually makes them problematic, namely them having a dummy location.

I see! That's a good insight, thanks for going the extra mile 🙂

> I have, but this does not do what I want: the compiler-generated calls in Kotlin I'm seeing are still associated with a source file, so fromSource() is true for these calls. I am certainly open to adding not fromSource() as an additional requirement here, but by itself it won't achieve what I want.

Perfect!

**Review by kaeluka — APPROVED** [review]
:shipit:

**Comment by max-schaefer** [comment]
> It's hard for me to say how tedious that would get.

I've added a simple Kotlin test on a [branch](https://github.com/github/codeql/tree/max-schaefer/automodel-exclude-generated-calls-kotlin-tests), but will leave it out of this PR. Adding Kotlin tests at this stage risks increasing friction for very little gain, but once support has stabilised we can merge them in from that branch.

I have also added a comment clarifying the relationship between the two "from source" concepts.

**Comment by max-schaefer** [comment]
@kaeluka, can you re-approve (assuming you are OK with the last commit)?

**Review by kaeluka — APPROVED** [review]
👍 thank you! :shipit:

**Pull request merged**
