### PR TITLE
Java: update paramsString

### PR DESCRIPTION
**Pull request by jcogs33**
This PR simplifies the `paramsString` code and fixes its QLDoc.

### CODE REVIEW

**Review by michaelnebel — APPROVED** [review]
LGTM!

**Comment by michaelnebel** [comment]
@jcogs33 : Most likely DCA will timeout on some of the projects unless there has been some performance improvements lately.
At the time of writing it seems like the project `apache__lucene` could be interesting to investigate manually as there is some discrepancy in the generated summaries!

**Comment by jcogs33** [comment]
> At the time of writing it seems like the project apache__lucene could be interesting to investigate manually as there is some discrepancy in the generated summaries!

The discrepancies in `apache__lucene` all seem to be caused by an issue similar to `ObjectString` where one of the parameter types for the models is `MemorySegment[]byte[]` when using the old version of `paramsString` and then it changes to `MemorySegment[],byte[]` when using the simplified version since a comma gets inserted. 
(Maybe the `apache__lucene` database can be used to debug the `ObjectString` issue further 🙂)

I checked `ktorio__ktor` as well, and the reason for the discrepancies there look potentially similar except it looks like an empty string is the first parameter type inserted. For example, `(boolean)` is a params string when using the old version and `(,boolean)` when using the simplified version.

**Comment by aschackmull** [comment]
The QL change looks fine to me. The simplified version makes a few more string pool operations since it's concatenating the parentheses outside the `concat`, so it's likely a little bit slower, but probably not enough to matter, so simplifying the code SGTM.

As for the changes to the results, then that shouldn't be possible under normal circumstances - I believe those are due to extractor errors, and I think we ought to see db check errors if we look for those.

@smowton You might want to have a look to see if the db inconsistencies can be easily fixed and/or guide @jcogs33 towards looking at the right places in the extractor, in case you, @jcogs33, are feeling adventurous and wants to have a look at the extractor code (recommended 😄 ).

**Pull request merged**
