### PR TITLE
Python: implement printAst for Python

### PR DESCRIPTION
**Pull request by erik-krogh**
_(Creating a Python PR feels weird)._ 

I recommend trying out the printAst feature (see next section) before reviewing the code.

This PR adds a `printAst.ql` query that can be used for viewing the AST of Python files.

--- 

Recommended usage instructions: 
- Enable AST viewer by adding `"codeQL.experimentalAstViewer": true` to your settings in VSCode 
  (Ctrl + Shift + P: `Open Settings (JSON)`). 
- Open some Python file from some database (this step is intentionally vague). 
- Open the CodeQL view in VSCode and click the new `View AST` button in the bottom. 
- Navigate the AST a bit to see what it looks like.

--- 

The printAst.ql query produces a tree, and there are 3 basic kinds of nodes in this tree (most of the other languages have more kinds of nodes, JS has 15): 
 - **`AstElementNode`**: This node represents an `AstNode`. The children of this node can be any kind of node. 
 - **`FunctionParamsNode`**: This node represents the parameters of a function. The children are always `AstElementNode`. 
 - **`StmtListNode`**: This node represents a `StmtList`, and is e.g. used as a child of an if-statement. The children of a `StmtListNode` are always `AstElementNode`.   
The `StmtList` that this node represents must be a result from `AstElementNode::getStmtList(...)`. This is used to figure out where the `StmtList` belongs and printing a label. 

I could have made a `CallArgumentsNode` for aggregating all the arguments in a call, but I decided against this, as the result already looks pretty good as it is. (I've done that differently in JavaScript. But JavaScript have both arguments and type-arguments, so not splitting them up would look bad). 

The `AstElementNode` implements some default behavior that works for `AstNodes`, and for some it actually looks OK (it determines children based on the `AstNode::getAChildNode()` predicate).   
This default behavior is overwritten in subclasses to get more specific/prettier behavior, for example: 
- Functions, where all the parameters are aggregated into a `FunctionParamsNode`.  
- If-statements, where each `StmtList` becomes a child, instead of each `Stmt` inside the `StmtList`s. 
- Parameters, where I've "moved" the type-annotation and default value to be children of the parameter instead of the function. 
--- 

The pretty-printing is quick and dirty and far from complete.   
But it looks pretty good to me. 

Maybe the `PrettyPrinting` module should be moved somewhere else?

### CODE REVIEW

**Comment by erik-krogh** [comment]
The tests failed in CI, but not on my machine.  

My best guess is that every `Str` is also a `Bytes` in Python 2.7.17 (used in CI), but not in Python 2.7.18 (on my machine).

**Comment by yoff** [comment]
Thank you very much! I hope one of us finds time to look at it soon :-)

**Comment by aeisenberg** [comment]
Thanks for looking into print AST support in Python. Trying it out now. I am using https://lgtm.com/projects/g/AtsushiSakai/PythonRobotics/. I mostly looked at the `/opt/src/ArmNavigation/arm_obstacle_navigation/arm_obstacle_navigation_2.py` file.

* `FunctionDef` source locations do not include the body of the function. Maybe this is intentional, but typically, a parent node would subsume the source locations of all its children.
* `Name` of a `FunctionDef` is the third child after the parameters and body.
* I see that `(StmtList)` is in parens, not square brackets. Real AST Nodes should be in square brackets and synthetic nodes in parens.
* Source location for the `(parameters)` synthetic node seems to cover the entire declaration expression eg `def main():`. Either, it should just cover what's inside the parens or it should not have a source location at all.
* Label for integer literals look like this: `[IntegerLiteral] IntegerLiteral`. Instead of having the second `IntegerLiteral`, maybe just print the number itself (same for other kinds of literals).
* Calls have no distinction between the function name and its arguments. I wonder if you could add a synthetic node for the arguments list, similar to what you do for FunctionDefs (See screenshot)

_Extension_Development_Host__-_arm_obstacle_navigation_2_py__read-only___read-only__—_vscode-codeql-starter__Workspace_

**Comment by erik-krogh** [comment]
> `FunctionDef` source locations do not include the body of the function. Maybe this is intentional, but typically, a parent node would subsume the source locations of all its children.

That is the location of `FunctionDef` from the extractor, so that seems intentional.   
Changing it would require an extractor change. 

> Name of a FunctionDef is the third child after the parameters and body.   

I changed the order :+1: 

> I see that `(StmtList)` is in parens, not square brackets. Real AST Nodes should be in square brackets and synthetic nodes in parens.   

`StmtList` is a weird middle child. It is a synthetic node made by the extractor, and it doesn't extend `AstNode` like all the other nodes. That is why I chose to put it in parens.   
I think I'll keep that unless you prefer square brackets.   

There is a bunch of those synthetic nodes made by the extractor. For example all the positional arguments of a call are aggregated into an `ExprList` (But we cannot use that as an `(arguments)` node, as it doesn't include the keyword arguments).   

`StmtList` was the only such synthetic node that was useful while printing the Ast.

> Source location for the `(parameters)` synthetic node seems to cover the entire declaration expression eg `def main()`:. Either, it should just cover what's inside the parens or it should not have a source location at all.    

I removed the location from `(parameters)` and `(StmtList)`, as I don't have their exact locations in the datebase.

> Label for integer literals look like this: [IntegerLiteral] IntegerLiteral. Instead of having the second IntegerLiteral, maybe just print the number itself (same for other kinds of literals).   

That was a bug, I had accidentally used the wrong method.   
Fixed now. 

> Calls have no distinction between the function name and its arguments. I wonder if you could add a synthetic node for the arguments list, similar to what you do for FunctionDefs (See screenshot)

:+1:

**Comment by aeisenberg** [comment]
Thanks for addressing everything. Ah...I see how `StmtList` isn't like other "real" AST Nodes. It's fine to keep it as it is. And everything else you mention makes sense. I hope to get a chance to try this out again later today.

**Comment by aeisenberg** [comment]
This looks great. Only issue is that I am seeing errors when I click on synthetic nodes like `(parameters)`. 

Similar to what I was seeing in JavaScript.

```
cannot open codeql-zip-archive://0-185/Users/andrew.eisenberg/Library/Application%20Support/Code/User/workspaceStorage/600c0c6f9b1cb74bf3beb8a937563b05/GitHub.vscode-codeql/python-4/AtsushiSakai_PythonRobotics_fa636b2/src.zip/. Detail: Unable to read file 'codeql-zip-archive://0-185/Users/andrew.eisenberg/Library/Application Support/Code/User/workspaceStorage/600c0c6f9b1cb74bf3beb8a937563b05/GitHub.vscode-codeql/python-4/AtsushiSakai_PythonRobotics_fa636b2/src.zip/' (EntryIsADirectory (FileSystemError): codeql-zip-archive://0-185/Users/andrew.eisenberg/Library/Application Support/Code/User/workspaceStorage/600c0c6f9b1cb74bf3beb8a937563b05/GitHub.vscode-codeql/python-4/AtsushiSakai_PythonRobotics_fa636b2/src.zip/)
```

**Comment by erik-krogh** [comment]
> Similar to what I was seeing in JavaScript.  

And similar to JavaScript I don't see what to do about it.   
Also, I can't replicate the error.   
When I click a synthetic node nothing happens.

**Comment by aeisenberg** [comment]
Will be fixed here: https://github.com/github/vscode-codeql/pull/620

Thanks for looking into this. I'm happy with the implementation, but someone on the python team should approve.

**Comment by erik-krogh** [comment]
> Will be fixed here: https://github.com/github/vscode-codeql/pull/620
> 
> Thanks for looking into this. I'm happy with the implementation, but someone on the python team should approve.

/cc @github/codeql-python

**Review by yoff — APPROVED** [review]
Thanks again for doing this.
There is some extractor-induced funkiness (like how decorators are represented, although it makes great semantic sense), but the feature is certainly useful.

**Review by tausbn — CHANGES_REQUESTED** [review]
Good stuff! Thank you for stepping out of your comfort zone and writing some Python. :wink:
I’ve made a couple of suggestions, all related to the documentation.

**Review by tausbn — APPROVED** [review]

**Comment by tausbn** [comment]
I'm somewhat surprised that you didn't just batch my suggestions and commit them directly, but who am I to argue. :slightly_smiling_face: 
I think this looks ready to merge.

**Pull request merged**
