### PR TITLE
C++: Reduce memory pressure from `getInstruction`

### PR DESCRIPTION
**Pull request by MathiasVP**
Since we merged https://github.com/github/codeql/pull/12900 the Foundations teams internal performance measurements have been OOM'ing when analyzing Wireshark because they're running their experiments with ~6GB of RAM (unlike our DCA analysis of Wireshark which uses a much larger runner).

The analysis was OOM'ing because of the use of the `shortestDistances` HOP. This use was introduced in https://github.com/github/codeql/commit/8368c37781d5fae810f856cf9b1e04f586225a9f to get around an issue where Eclipse was OOM'ing because the log file was too large 😅.

This PR reverts https://github.com/github/codeql/commit/8368c37781d5fae810f856cf9b1e04f586225a9f and replaces the transitive closure of `adjacentInBlock` (which also was OOM'ing when I tried it locally) with an `EquivalenceRelation`-based approach. This succeeds even with 5GB of memory 🎉.

We do, however, now have `148647` iterations of `getMemberIndex` 😱. So we need to run DCA (and maybe even MRVA?) to check if this is a change we want to make.

### CODE REVIEW

**Comment by MathiasVP** [comment]
Hmmm... Apparently, this breaks some of our tests 🤔. I'll investigate

**Comment by rdmarsh2** [comment]
Stage timings on DCA look pretty noisy. I'm OK with the code but we should look into that.

**Comment by MathiasVP** [comment]
> Stage timings on DCA look pretty noisy. I'm OK with the code but we should look into that.

Sure, we can do that. Note that the stage timings behavior is actually quite consistent with our observations. In all of the projects, the `CppType::CppType#1#IRConstruction::Raw#14#Operand#3#SSAConstruction::Cached#7#TOperand::Internal#3` stage is the one with the largest regression (which is most likely the stage that evaluates `getInstruction`).

**Comment by MathiasVP** [comment]
Yeah, the query-specific stage timing alerts flagged up here is just noise.

**Review by rdmarsh2 — APPROVED** [review]

**Pull request merged**
