### PR TITLE
C#/Java: Move the modelgenerator.

### PR DESCRIPTION
**Pull request by michaelnebel**
It turns out that we might need to reference some of the libraries and queries in the model generator directory, which is not possible when the directory name contains a dash.
In this PR we remove the dash from the model generator directory name and also adjust workflows, query names and tags accordingly.
A separate PR for DCA is also needed.

### CODE REVIEW

**Comment by michaelnebel** [comment]
It is expected that the Models as Data - Diff workflows fails at it is not compatible with moving around the related scripts.

**Comment by michaelnebel** [comment]
DCA looks good.

**Review by aeisenberg — APPROVED** [review]
LGTM from the CLI and CI side. Reviews from at least one of the language teams would be good as well.

It looks like the CI failures are due to flaky network requests. And please be sure to notify relevant people regarding query id changes (which I think you have).

**Comment by michaelnebel** [comment]
> LGTM from the CLI and CI side. Reviews from at least one of the language teams would be good as well.
> 
> It looks like the CI failures are due to flaky network requests. And please be sure to notify relevant people regarding query id changes (which I think you have).

Thank you for the review!
Yes, there is a another open PR that changes more query IDs and it is being discussed in the Code Scanning Team slack channel.
The one query that has a changed id here should to my knowledge not really be used anywhere ATM and it *should* not cause any harm to merge that.

**Review by atorralba — DISMISSED** [review]
Java looks plausible to me.

**Review by atorralba — DISMISSED** [review]

**Review by sidshank — DISMISSED** [review]
LGTM. I spent some time looking for import paths or directories constructed using string concatenation, that might have been missed, but found nothing.

**Comment by michaelnebel** [comment]
@atorralba or @tamasvajk : Sorry to bother you again, but I needed to rebase once more (was not able to merge yesterday due to issues with actions timeout). There are no changes since last time. Could one of you please rubber stamp the PR again?

**Review by atorralba — APPROVED** [review]
Done 😃

**Pull request merged**
