### PR TITLE
C#: Poor mans quoting.

### PR DESCRIPTION
**Pull request by michaelnebel**
If quoted arguments are used these will not be respected by the LUA tracer on windows.
In this PR we explicitly quote all compiler arguments containing whitespaces (windows only) in the dotnet matcher.
This is an initial fix. The full fix, which also depends on an internal PR will be merged here: https://github.com/github/codeql/pull/14150

### CODE REVIEW

**Review by Lizzyrobin4 — COMMENTED** [review]
Good and let it work perfectly on my device

**Comment by Lizzyrobin4** [comment]
> Good and let it work perfectly on my device

**Comment by michaelnebel** [comment]
@aibaars : Should we consider merging this PR instead of the full solution as an intermediate?
As far as I can tell we don't break any existing stuff as we are checking for the presence of a whitespace before quoting. We might still return garbage in some cases, but then it will be garbage in - garbage out.

**Comment by michaelnebel** [comment]
DCA looks good!

**Review by tamasvajk — APPROVED** [review]

**Pull request merged**
