### PR TITLE
Swift: Model assignment operators (+= etc)

### PR DESCRIPTION
**Pull request by geoffw0**
Model assignment operators such as `+=` (including tests, QL classes, taint flow).  It turns out Swift has a fairly wide range of these assignment operators including some exotic ones.  This should give us a fair improvement to taint flow, mostly due to basic `+=` on strings and integers I suspect.

As discussed elsewhere there is some redundancy due to a desire to not expose `abstract` classes in the public interface - the `Assign*Ex` classes (which are abstract but private) and are only used by `Ex`-tending to construct characteristic predicates for corresponding non-`Ex` interface classes.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM! We should probably do a DCA run on this before we merge it, though.

**Comment by geoffw0** [comment]
DCA: I'm marginally concerned about this line from stage timings:

<html>
<body>


source | query | a targets | b targets | weight | a_m | a_std | b_m | b_std | diff | relative
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
OWASP__MASTG-Hacking-Playground | ControlFlowGraphImplShared::Cached#1#DataFlowDispatch#6#DataFlowDispatch::Cached#7#DataFlowImplCommon::Cached#43#DataFlowPrivate::Cached#14(swift/path-injection[14], 20/20) | 3 | 3 | ❌ | 14.97 | 4.72 | 53.25 | 31.48 | 38.28 | 2.557


</body>
</html>
but I think it's probably not related to the PR.  I'll do a re-run to be sure.

**Comment by MathiasVP** [comment]
I guess we are expecting some slowdown from this since we're adding a lot of taint flow.

With that said, I'm not actually sure that stage should even be affected by changes to _taint_ flow (dataflow for sure, but not taint flow)

**Comment by geoffw0** [comment]
> I guess we are expecting some slowdown from this since we're adding a lot of taint flow.

True, though I can't see any evidence of that above the noise.

I don't see the (same) slowdown on the rerun.  In fact overall analysis time is faster on the rerun.

Merging.

**Pull request merged**
