### PR TITLE
C++: Report any extracted file as successfully extracted

### PR DESCRIPTION
**Pull request by geoffw0**
Change `cpp/diagnostics/successfully-extracted-files` to report any extracted file as successfully extracted, regardless of errors that might have been encountered during extraction.  This is part of a cross-language effort to make the tool status page more optimistic about successfully extracted files, as apparently it was causing some users undue concern.

I've also added some test cases for this and related queries so we can get a clearer idea of what's going on - though they're far from exhaustive (due to limitations in what we can easily do in tests + wide diversity of scenarios in the real world).

### CODE REVIEW

**Review by jketema — APPROVED** [review]

**Review by jketema — APPROVED** [review]
LGTM. It does seem there's an internal integration test that needs to be updated.

**Comment by geoffw0** [comment]
Yep, I'll make a PR for that.

**Comment by geoffw0** [comment]
I've made an internal PR.  I believe that means we can disregard the integration test failure here as long as it succeeds on the other branch.

**Comment by jketema** [comment]
> I believe that means we can disregard the integration test failure here as long as it succeeds on the other branch.

Correct.

**Pull request merged**
