### PR TITLE
Dataflow: Refactor call context check

### PR DESCRIPTION
**Pull request by aschackmull**
The first commit just moves some code around. The second commit contains the actual change.

### CODE REVIEW

**Comment by smowton** [comment]
Go is somewhat behind the dataflow lib right now, so go ahead and we'll deal with any problems async

**Comment by aschackmull** [comment]
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1500/
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/2144/
https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1189/
https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/614/

**Review by hvitved — APPROVED** [review]
LGTM. Let's see if the differences jobs are good.

**Comment by aschackmull** [comment]
All diff jobs are looking good!

**Review by tausbn — APPROVED** [review]

**Review by hvitved — APPROVED** [review]

**Pull request merged**
