### PR TITLE
Data flow: Precise access paths

### PR DESCRIPTION
**Pull request by hvitved**
Differences jobs:

- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/449/
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1445/
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/928/

Analysis times are practically unaffected, and no changes in results for all languages (if only https://github.com/github/semmle-code/pull/37230 had been merged, we probably would see changes in number of paths). The tuple count benchmark for `mono` showed no change, but the one for `jdk` is measurable:

  | pn | pnr
-- | -- | --
Before | 313277 | 238199
After | 462902 | 348371
Increase | 48% | 46%

Commit-by-commit review is encouraged.

### CODE REVIEW

**Comment by aschackmull** [comment]
We have tried precise access paths before - and while they work just fine for many cases, some code bases cause a tuple explosion. Test e.g. the java query `TaintedPath.ql` on geogebra/geogebra.

**Comment by hvitved** [comment]
> Test e.g. the java query `TaintedPath.ql` on geogebra/geogebra.

Perhaps that project should be added to Java-Differences?

**Comment by aschackmull** [comment]
Maybe I'm misremembering which query/database caused problems or maybe other things changed. But yeah, there are probably a couple of projects that would be good to include in the differences job - that one and apache/geode springs to mind.
A tricky pattern to deal with for precise access paths is something like binary trees - even with very accurate pruning it's easy to end up with access paths that are every combination of `.left` and `.right`. If you look back in the git history you'll see earlier versions that used precise access paths with a fancy compression scheme to handle this pattern (essentially self-referential fields like `.left` in a binary tree or `.next` in a list would get compacted to "some sequence of one or more self-referential fields").  All of this code was deleted when we found that imprecise access paths were much more performant and had almost the same precision.

**Comment by hvitved** [comment]
> Maybe I'm misremembering which query/database caused problems or maybe other things changed. But yeah, there are probably a couple of projects that would be good to include in the differences job - that one and apache/geode springs to mind.

The updated Java-Differences job includes geogebra/geogebra and apache/geode; both have unchanged performance.

**Comment by hvitved** [comment]
> A tricky pattern to deal with for precise access paths is something like binary trees - even with very accurate pruning it's easy to end up with access paths that are every combination of `.left` and `.right`. If you look back in the git history you'll see earlier versions that used precise access paths with a fancy compression scheme to handle this pattern (essentially self-referential fields like `.left` in a binary tree or `.next` in a list would get compacted to "some sequence of one or more self-referential fields"). All of this code was deleted when we found that imprecise access paths were much more performant and had almost the same precision.

Even if we get all combinations of left/right paths, each node is only replicated at most 2^6-1 times, which doesn't seem problematic to me.

**Comment by aschackmull** [comment]
I've made some changes as a PR against this PR here: https://github.com/hvitved/ql/pull/3

Also, with this, could we perhaps undo some of the changes to the path* predicates in the final SCC? I assume they're no longer needed when a lot of the mutual recursion is gone, and some of them have degenerate standard join-orders.

**Comment by hvitved** [comment]
> I've made some changes as a PR against this PR here: [hvitved#3](https://github.com/hvitved/ql/pull/3)
> 
> Also, with this, could we perhaps undo some of the changes to the path* predicates in the final SCC? I assume they're no longer needed when a lot of the mutual recursion is gone, and some of them have degenerate standard join-orders.

Thanks. I have merged in your changes, rebased, and simplified predicates as suggested. I have started new Differences jobs (links in PR description updated).

**Comment by hvitved** [comment]
Rebased to resolve merge conflicts in `.expected` files.

**Review by aschackmull — APPROVED** [review]

**Comment by aschackmull** [comment]
Looks good. Merging together with https://github.com/github/codeql/pull/4440.

**Pull request merged**
