### PR TITLE
[docs] Add GitHub favicon to CodeQL docs

### PR DESCRIPTION
**Pull request by jf205**
This PR adds the GitHub favicon to the CodeQL docs Sphinx project and the static docs homepage.

For the Sphinx project, I've simply set `html_favicon` in the configuration file to the path to `favicon.io`.
For the landing page, which is static HTML not built by Sphinx, I've set the path to the location of `favicon.io` in the built docs. (It's moved from `images/site/favicon.io` to `_static/favicon.io` during the build.)

### CODE REVIEW

**Review by hubwriter — APPROVED** [review]
This seems fine (although I can't really check it). 😄 
Approved ✅

**Comment by jf205** [comment]
> This seems fine (although I can't really check it). 😄
> Approved ✅

Good point @hubwriter 😸 

I've just push a commit which adds the favicon to two other projects (should have been included earlier) and added a [preview](http://docteam.internal.semmle.com/james/add-favicon/codeql-docs/codeql-overview/about-codeql/) for you. 🤞🏻 it should be a very quick re-review. Thanks!

**Review by hubwriter — APPROVED** [review]
Thanks for adding the preview James. 
I had a good old click around and the favicon is showing on all the pages I landed on within http://docteam.internal.semmle.com/james/add-favicon.
So this looks good to 🚢 
👍

**Comment by adityasharad** [comment]
Internal PR is green. Merging.

**Pull request merged**
