### PR TITLE
Track taint for String.valueOf(..)

### PR DESCRIPTION
**Pull request by bmuskalla**
Given `String.valueOf` preserves the value of the passed parameter, mark its return value as tainted as well.

### CODE REVIEW

**Comment by aschackmull** [comment]
This blanket inclusion of all the overloads deserve at least some investigation prior to merging. The `char[]` overloads are perfectly fine to include, but the ones for primitive types perhaps less so, and the one for `Object` should be considered together with general `toString()` and its impact on performance and FP-rates should be looked into prior to merging.

**Comment by bmuskalla** [comment]
Thanks for the feedback @aschackmull - updated the PR accordingly and left out the `valueOf(Object)` variant for now. If you think it we should look into this right away, I'd need some help to gauge the implications of doing that.

**Comment by bmuskalla** [comment]
And related to that: Do you think an addition like this is worth a change note?

**Comment by aschackmull** [comment]
> Do you think an addition like this is worth a change note?

No, this is too minor.

Also, the expected file needs an update.

**Comment by bmuskalla** [comment]
Thanks. And sorry for the missing expected file, that was still lurking in my unstaged changes :)

**Review by aschackmull — APPROVED** [review]

**Pull request merged**
