### PR TITLE
Dataflow: Move the shared library to a properly shared qlpack.

### PR DESCRIPTION
**Pull request by aschackmull**
🎉 This makes the data flow library into a proper qlpack!

Several small tweaks were needed for the individual languages to ensure that the predicate types matched the signature.

### CODE REVIEW

**Comment by aschackmull** [comment]
> I'd like to see DCA runs on this pull request.

I'll start those shortly - I just wanted to clear out the worst compilation errors with some quick CI first.

**Comment by aschackmull** [comment]
Dca looks uneventful.

**Review by atorralba — APPROVED** [review]
Java changes look plausible to me (aside from the QLDoc check failures, which I'm not sure whether you intend to address). 

Thanks for doing this!

**Comment by aschackmull** [comment]
> aside from the QLDoc check failures, which I'm not sure whether you intend to address

I don't 😄

**Review by MathiasVP — APPROVED** [review]
C/C++/Swift 👍

**Review by geoffw0 — APPROVED** [review]

**Review by smowton — APPROVED** [review]
Go LGTM

**Review by alexrford — APPROVED** [review]
Ruby 👍

**Review by alexrford — APPROVED** [review]
Python also 👍

**Review by michaelnebel — APPROVED** [review]
Looks plausible to me! 👍 
Thank you Anders!

**Pull request merged**
