### PR TITLE
Go: improve value flow through arrays

### PR DESCRIPTION
**Pull request by owen-mc**

### CODE REVIEW

**Review by smowton — APPROVED** [review]
To check: that all nodes written as an array base (i.e. matching writesElement(n, _, _)) have post-update nodes. Pretty sure they do.

**Comment by owen-mc** [comment]
I ran the following query on all the large real-world dbs I had handy and got no results for any of them.
```ql
import go

from DataFlow::Node n
where
  (
    n.getType() instanceof ArrayType or
    n.getType() instanceof SliceType
  ) and
  any(Write w).writesElement(n, _, _) and
  not exists(DataFlow::PostUpdateNode pun | n = pun.getPreUpdateNode())
select n
```

**Comment by owen-mc** [comment]
(I have included some documentation improvements to `SliceExpr` in this PR. They seem so small it isn't worth making a separate PR for them. They aren't really related, so I will take them out if you want.)

**Comment by owen-mc** [comment]
Also a performance evaluation showed no changes in performance and no change in results. This PR fixes some missing value flow but there was always taint flow in this case and that will be enough for almost all cases.

**Review by smowton — APPROVED** [review]

**Pull request merged**
