### PR TITLE
C++: Make exprMightOverflowPositively sound for unanalyzable expressions

### PR DESCRIPTION
**Pull request by MathiasVP**
(and similarly for the `exprMightOverflowNegatively` predicate.)

This hopefully means that expressions that do not satisfy these predicates will never overflow/underflow.

This _might_ Break Everything. But let's wait and see what CPP-differences says: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1917/

### CODE REVIEW

**Review by geoffw0 — DISMISSED** [review]
Change LGTM.

Surprisingly there's only one change in CPP differences - a heavily templated comparison in Boost that we lose, that looks like it was indeed a false positive (though I'm not sure the exact mechanics of it being ruled out by this change).

**Comment by MathiasVP** [comment]
I think the `exprMightOverFlow` predicates become a bit too noisy when we include all unanalyzable expressions. Consider this example from https://github.com/github/codeql/blob/main/cpp/ql/test/query-tests/Security/CWE/CWE-190/semmle/tainted/test2.cpp:

```cpp
typedef struct _myStruct {
	s64 val;
} MyStruct;

void test2_sink(s64 v, MyStruct s, MyStruct &s_r, MyStruct *s_p)
{
	s64 v1 = v * 2; // bad
	s64 v2 = s.val * 2; // bad
	s64 v3 = s_r.val * 2; // bad
	s64 v4 = s_p->val * 2; // bad
}
```

We now flag all of the field accesses in this function as possibly overflowing, which doesn't make a lot of sense.

**Comment by MathiasVP** [comment]
> Surprisingly there's only one change in CPP differences - a heavily templated comparison in Boost that we lose, that looks like it was indeed a false positive (though I'm not sure the exact mechanics of it being ruled out by this change).

Yeah, I agree that the CPP-differences change looks good (the query should probably filter out templates anyway). But I'm not sure i like the changes in the tests.

**Comment by geoffw0** [comment]
Should there be two versions of the predicates then?  It seems legitimate to only want cases where we're most confident an overflow can occur (even if accuracy is not guaranteed), but on the other hand this will clutter up the interface to this library and give users more opportunity to make the wrong choice.

**Comment by MathiasVP** [comment]
> Should there be two versions of the predicates then? It seems legitimate to only want cases where we're least / most confident an overflow can occur (even if accuracy is not guaranteed either way), but on the other hand this will clutter up the interface to this library and give users more opportunity to make the wrong choice.

Yeah, there seem to be situations where we want the old semantics and other situations that call for the new semantics of those predicates. I was hoping that we didn't have to add a whole new predicate to the public interface, though :( This seems to be a discussion that would be helpful to have for the future IR-based range analysis as well, so maybe we should bring the discussion to a team meeting (as a very low priority topic).

**Comment by MathiasVP** [comment]
Note to self if we end up merging a version of this: Use this PR to make https://github.com/github/codeql/pull/5667/commits/bb447d7174141dc518e6ce90367121280fec1d80 more aesthetically pleasing.

**Comment by MathiasVP** [comment]
New CPP-difference: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1938/

**Comment by MathiasVP** [comment]
> New CPP-difference: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1938/

CPP-differences looks good. There is one query result change, and it's in a query that doesn't actually use range analysis so it looks like wobble.

There was a single test change. This is fixed by https://github.com/github/codeql/pull/5678/commits/86822f6c6161dc22f369a1de8caadb82d3530c38 following a Slack discussion [here](https://github.slack.com/archives/CP75PA8Q1/p1619185745483000).

**Comment by jbj** [comment]
Why is no change note required? The range analysis library has external users, and they might be affected by this new behaviour.

**Comment by MathiasVP** [comment]
> Why is no change note required? The range analysis library has external users, and they might be affected by this new behaviour.

Good point. We should have a change note for this.

**Comment by jbj** [comment]
LGTM. I'll leave the merging to @geoffw0 when he's satisfied.

**Review by geoffw0 — APPROVED** [review]
LGTM.

It's a shame library changes like this are difficult to explore on LGTM, but the unit tests + CPP-Differences do cover us.

**Comment by geoffw0** [comment]
> Note to self if we end up merging a version of this: Use this PR to make bb447d7 more aesthetically pleasing.

^ reminder.

**Comment by MathiasVP** [comment]
> > Note to self if we end up merging a version of this: Use this PR to make [bb447d7](https://github.com/github/codeql/commit/bb447d7174141dc518e6ce90367121280fec1d80) more aesthetically pleasing.
> 
> ^ reminder.

Thanks for the reminder. That fix is now up: https://github.com/github/codeql/pull/5780

**Pull request merged**
