### PR TITLE
Minor updates to CodeQL for VS Code docs for expansion of support for model editing

### PR DESCRIPTION
**Pull request by felicitymay**
There are only minor changes needed to the docs for the VS Code extension.

Reviewers, it would be great to get this merged before the next release candidate branch is created.

### CODE REVIEW

**Review by shati-patel — DISMISSED** [review]
Updates look good! 📝 

(Minor side note—not from this PR, just looking at the preview: There's a `.. tip::` box on this page which isn't really styled correctly. Might be worth changing that to a `.. pull-quote::` to match the other boxes?)

**Review by subatoi — DISMISSED** [review]
Thank you, particularly for updating the screenshots ❤️

**Comment by felicitymay** [comment]
Thanks for the rapid reviews 💖 

I've made the change @shati-patel requested, so this is probably ready to merge when one of you has time to give it a 👍🏻

**Review by subatoi — APPROVED** [review]
No reason to think CI won't pass 👍

**Pull request merged**
