### PR TITLE
CPP: Improvements for cpp/uncontrolled-arithmetic

### PR DESCRIPTION
**Pull request by geoffw0**
There are three parts to this PR:
 - the first two commits add test cases around some issues I'm still seeing in the real world.  They are not fixed in this PR.
 - the third commit extends `Overflow.qll` to understand `*=`, widening query results a bit.

I also have some more improvements ready locally that add a `SimpleRangeAnalysisExpr` model to the random functions, encoding the fact that their results are always non-negative (even when the return type is signed).  This fixes several false positives and removes the need for a less effective special case elsewhere in the QL - but comes at the cost of importing an experimental library `experimental.semmle.code.cpp.models.interfaces.SimpleRangeAnalysisExpr` into non-experimental code.  I'd like to talk to someone who knows more about that library before making a decision on what to do with this bit.  I am happy to see this PR merged without it for now.

### CODE REVIEW

**Comment by MathiasVP** [comment]
> I also have some more improvements ready locally that add a `SimpleRangeAnalysisExpr` model to the random functions, encoding the fact that their results are always non-negative (even when the return type is signed). This fixes several false positives and removes the need for a less effective special case elsewhere in the QL - but comes at the cost of importing an experimental library `experimental.semmle.code.cpp.models.interfaces.SimpleRangeAnalysisExpr` into non-experimental code. I'd like to talk to someone who knows more about that library before making a decision on what to do with this bit. I am happy to see this PR merged without it for now.

`experimental.semmle.code.cpp.models.interfaces.SimpleRangeAnalysisExpr` has footgun capatibilites. If the abstract class is extended in a query it causes range analysis re-evaluation.

It would be super nice to have this modeling feature, but we'd need to put the models somewhere where we'd know it would always be imported when `SimpleRangeAnalysis` was imported (or change `SimpleRangeAnalysis` so that it looks more like the way we do interprocedural dataflow. I recently tried that here: https://github.com/github/codeql/pull/6481).

**Comment by geoffw0** [comment]
Thanks for that explanation.  I talked with @jbj about this last week (?) and we were leaning towards hardcoding support for `rand` etc into simple range analysis for the time being (possibly with a public model of `rand` etc just for the constructor).  Range analysis already has a lot of special cases like this.

**Comment by MathiasVP** [comment]
> Thanks for that explanation. I talked with @jbj about this last week (?) and we were leaning towards hardcoding support for `rand` etc into simple range analysis for the time being (possibly with a public model of `rand` etc just for the constructor). Range analysis already has a lot of special cases like this.

SGTM.

**Review by MathiasVP — APPROVED** [review]
LGTM!

**Pull request merged**
