### PR TITLE
Updated dotnet version to 8.0.101

### PR DESCRIPTION
**Pull request by henti**
This is a corresponding PR to https://github.com/github/semmle-code/pull/48786

### CODE REVIEW

**Comment by tamasvajk** [comment]
@henti I pushed an extra commit to this PR to fix the failing integration tests. Let's see the results of the new CI run...

**Comment by tamasvajk** [comment]
There are some `[build-stderr] Install the [8.0.101] .NET SDK or update [.../global.json] to match an installed SDK.` errors on MacOS and Windows.

**Comment by michaelnebel** [comment]
> There are some `[build-stderr] Install the [8.0.101] .NET SDK or update [.../global.json] to match an installed SDK.` errors on MacOS and Windows.

Yeah, I think we need to bump QL submodule on the internal PR to verify that the tests will pass when the PRs are merged.

**Review by michaelnebel — APPROVED** [review]
LGTM!

**Comment by tamasvajk** [comment]
I've merged https://github.com/github/codeql/pull/15472, which adds further integration tests that depend on 8.0.0.

**Review by michaelnebel — APPROVED** [review]
LGTM!

**Pull request merged**
