### PR TITLE
Update test expectations after extension numbering fix

### PR DESCRIPTION
**Pull request by dbartol**
This PR updates test expectations after a CLI fix to ensure that all extension ID values are unique.

### CODE REVIEW

**Comment by owen-mc** [comment]
Note that Go test expectations also need to be updated.

**Review by smowton — COMMENTED** [review]
This seems to result in some attributions disappearing rather than getting renumbered?

**Comment by dbartol** [comment]
> This seems to result in some attributions disappearing rather than getting renumbered?

Yes, but that's the expected behavior. Previously, one of the test-specific models would get the same ID as one of the standard library's models, so when the test output referenced the test-specific model, it accidentally pulled in whatever random standard model had the same ID as well. Now, since each model ID is unique, the hitchhiking standard model doesn't appear in the output at all.

**Review by adityasharad — APPROVED** [review]
Approving to unblock. Tests are passing on the internal PR containing a bump of the submodule to the head of this PR.

**Comment by hvitved** [comment]
Ruby fix here: https://github.com/github/codeql/pull/17156.

**Pull request merged**
