### PR TITLE
Swift: Improvements related to the swift/cleartext-logging query.

### PR DESCRIPTION
**Pull request by geoffw0**
Improvements related to the `swift/cleartext-logging` query:
- model flow through [`getVaList`](https://developer.apple.com/documentation/swift/getvalist(_:)) (so that we can pass the `NSLogv` test cases).
- add data flow through variadic arguments (this will have effects more widely than the `swift/cleartext-logging` query and is separately tested).
- add an `allowImplicitRead` for array content sinks in the `swift/cleartext-logging` query (so that, together with the previous bullet point, we can pass the `NSLog` and more of the `print` test cases).
- add more sinks for the `swift/cleartext-logging` query.

### CODE REVIEW

**Comment by geoffw0** [comment]
Fixed merge conflicts.

@mathiasvp possibly `VarargExpansionExpr` is yet another example of something that should be hidden from the AST instead of having a special case in data flow?  As far as I can tell where varargs are used a `VarargExpansionExpr` wraps the `ArrayExpr` entering the call.

**Comment by MathiasVP** [comment]
> Fixed merge conflicts.
> 
> @MathiasVP possibly `VarargExpansionExpr` is yet another example of something that should be hidden from the AST instead of having a special case in data flow? As far as I can tell where varargs are used a `VarargExpansionExpr` wraps the `ArrayExpr` entering the call.

Good point. Looking at https://github.com/apple/swift/blob/main/include/swift/AST/Expr.h#L3566 it looks like there are plans to have surface-level syntax for `VarargExpansionExpr`s. Once we have surface-syntax for it I don't think we want to hide it from the AST?

**Comment by geoffw0** [comment]
> Looking at https://github.com/apple/swift/blob/main/include/swift/AST/Expr.h#L3566 it looks like there are plans to have surface-level syntax for `VarargExpansionExprs`.

Sounds like I should probably leave it as a data flow solution then, at least, for now.

**Comment by geoffw0** [comment]
DCA LGTM.

Merge conflicts fixed (again).

**Comment by geoffw0** [comment]
Fixed merge conflicts again.

**Review by MathiasVP — DISMISSED** [review]
LGTM!

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
