### PR TITLE
Move test utilities to the query pack.

### PR DESCRIPTION
**Pull request by michaelnebel**
In this PR the test utilities are moved from the *test* QL packs into the `codeql/<language>-queries` QL packs.
We are in the process of moving the *experimental* queries from the Code QL repo to the [CodeQL-Community-Packs](https://github.com/GitHubSecurityLab/CodeQL-Community-Packs/) repo, and some of the tests for the experimental queries are relying on the test utilities, which currently aren't being published.

As a temporary workaround a copy of the test utilities are added to the CodeQL-Community-Pack, but we should publish the test utilities to enable sharing.

Moving the test utilities for all languages for consistency.

### CODE REVIEW

**Comment by michaelnebel** [comment]
DCA looks good.

**Comment by owen-mc** [comment]
Should this be done for Go as well? (Not necessarily in this PR.)

**Comment by michaelnebel** [comment]
> Should this be done for Go as well? (Not necessarily in this PR.)

Yes, we should do it for all languages, if we agree that this is an acceptable approach. I intend to do it for all languages in this PR, if there are no objections :-)

**Review by hvitved — DISMISSED** [review]
LGTM

**Comment by michaelnebel** [comment]
Putting in draft while making the corresponding changes for the other languages.

**Review by dbartol — DISMISSED** [review]
I think these utilities should be in the library pack, not the query pack. Any query pack in an external repo will already have a dependency on the language's library pack. An external query pack probably wouldn't (and shouldn't) need a dependency on the standard _query_ pack for the language.

**Review by egregius313 — DISMISSED** [review]
Static languages (Java/C#/Go) LGTM.

**Comment by michaelnebel** [comment]
> I think these utilities should be in the library pack, not the query pack. Any query pack in an external repo will already have a dependency on the language's library pack. An external query pack probably wouldn't (and shouldn't) need a dependency on the standard _query_ pack for the language.

Note that the utilities do contain queries (which are used for postprocessing of test output). I will make a commit which moves the "library" parts to each languages library pack. These queries are used as  "utilitity queries" for tests, so I don't expect that any external query pack will make a dependency to the corresponding standard  query pack for this reason (but the test pack in the external query pack will).
There already exist examples of external query packs with references to the corresponding language standard query pack (the CodeQL community pack is the example I know of).

**Comment by michaelnebel** [comment]
> Swift, CPP LGTM (aside from @dbartol s concern about the new location)
> 
> Rust is missing. It's test utils are in [`rust/ql/test/utils`](https://github.com/github/codeql/tree/main/rust/ql/test/utils). I'm not sure what `Cfg.ql` is doing there exactly.

I missed that. Will fix.

**Comment by michaelnebel** [comment]
Putting the PR in draft as I would like to use the CI to check that all references are adjusted correctly before anyone spends time reviewing.

**Comment by michaelnebel** [comment]
> > I think these utilities should be in the library pack, not the query pack. Any query pack in an external repo will already have a dependency on the language's library pack. An external query pack probably wouldn't (and shouldn't) need a dependency on the standard _query_ pack for the language.
> 
> Note that the utilities do contain queries (which are used for postprocessing of test output). I will make a commit which moves the "library" parts to each languages library pack. These queries are used as "utilitity queries" for tests, so I don't expect that any external query pack will make a dependency to the corresponding standard query pack for this reason (but the test pack in the external query pack will). There already exist examples of external query packs with references to the corresponding language standard query pack (the CodeQL community pack is the example I know of).

@hvitved recommended that we try and put the postprocessing queries in the library pack as well. Will add a commit for that as well. I suppose this only means that these queries are not compiled up front, which should be ok for queries only used for testing purposes.

**Comment by michaelnebel** [comment]
Setting ready for review again.
- All the modules including the post-processing queries have been moved to the language packs.
- Rust test utilities have been moved ad well.
- Ignoring the QL doc warnings.

**Review by geoffw0 — APPROVED** [review]
CPP, Swift, Rust LGTM.

**Comment by geoffw0** [comment]
> The failing C++ integration test looks unrelated.

Yes it's an issue that came up yesterday afternoon.  I believe it's fixed now on latest `semmle-code`.

**Review by egregius313 — APPROVED** [review]
Static languages LGTM

**Review by erik-krogh — APPROVED** [review]

**Review by hvitved — APPROVED** [review]

**Review by RasmusWL — APPROVED** [review]
Python :+1:

**Pull request merged**
