### PR TITLE
Java: Add predicates for sealed classes

### PR DESCRIPTION
**Pull request by Marcono1234**
Adds two predicates to `ClassOrInterface` to support sealed classes (Java 17 feature; previously a preview feature). This is based on #6178.

I have also restructured the type tests a bit to be all under the common `types` folder. Please let me know if I should revert that.

Feel free to close this pull request in case you have your own changes for this planned internally, or want to implement this yourself.

### CODE REVIEW

**Comment by smowton** [comment]
Please add a change note and remove the `(Java 17 feature)` parenthetical, otherwise lgtm

**Comment by Marcono1234** [comment]
> remove the `(Java 17 feature)` parenthetical

My intention with this was to make it a bit more obvious what these predicates do, because not everyone might be up to date with the latest Java features, and for users of older Java versions these predicates would be irrelevant. For `StringLiteral` I added "(Java 15 feature)" in the past for text blocks and it was merged. Should I remove it there as well?

**Comment by owen-mc** [comment]
(Note that the way we format change notes has recently changed. [The instructions are here](https://github.com/github/codeql/blob/main/docs/change-notes.md).)

**Comment by smowton** [comment]
I don't mind much either way re: the Java 17 feature text

**Pull request merged**
