### PR TITLE
Swift: Correct the behaviour of Type.getName

### PR DESCRIPTION
**Pull request by geoffw0**
Correct the behaviour of `Type.getName`.  For a type `B` declared inside a type `A`, `Type.getFullName` returns the string `"A.B"`.  `Type.getName` should return the string `"B"`, but prior to this pull request returned `"A.B"`.

Behaviour is now consistent with that for `TypeDecl`.

An open question is whether we want to redefine `Type.toString` to preserve the old behaviour.  I *think* we do ... but I'm going to let the tests run on this pull request first and see what it looks like if we don't...

### CODE REVIEW

**Comment by MathiasVP** [comment]
> An open question is whether we want to redefine Type.toString to preserve the old behaviour. I think we do ... but I'm going to let the tests run on this pull request first and see what it looks like if we don't...

As queries aren't supposed to depend on the behavior of `toString` this is really up to us:

> Compilation of the query and any associated libraries and tests must be resilient to future development of the [supported](https://github.com/github/codeql/blob/main/docs/supported-queries.md) libraries. This means that the functionality [...] cannot make use of regexp matching on `toString`.

(from [CONTRIBUTING](https://github.com/github/codeql/blob/main/CONTRIBUTING.md).)

**Comment by geoffw0** [comment]
Yep, so it comes down to whether query output looks better with the full or short type names.

There are surprisingly few failing tests (no query tests, just a few integration tests), with differences like these:
```
-| Builtin.BridgeObject | BuiltinBridgeObjectType |
+| BridgeObject | BuiltinBridgeObjectType |

-| Builtin.Executor | BuiltinExecutorType |
+| Executor | BuiltinExecutorType |

-| T.Type | MetatypeType | T |
+| Type | MetatypeType | T |
```
I think the full names were clearer in these cases, so I'll switch `Type.toString()` to use that (i.e. preserve the old `toString` behaviour).

**Comment by MathiasVP** [comment]
This also adds a fair number of new string operations to many pipelines so I think we should run DCA once we're happy with the output.

**Comment by geoffw0** [comment]
DCA LGTM (analysis time unaffected; stage timings OK as far as I can tell).

There are some test failures I need to fix though...

**Comment by geoffw0** [comment]
Test failures fixed - but I had to rewrite `getName()` to do it, now using a regex solution.  This is because we have a wider variety of type names including dots than I had anticipated, such as tuple types `(Int, A.B.C)`, and variadic sequence types `A...`.

In a couple of places we were using `getName()` when we should have been using `getFullName()` but it didn't show up as a problem until now.  This is now fixed as well.

I will do another DCA run after the tests pass, as the solution has fundamentally changed.

**Comment by geoffw0** [comment]
DCA still LGTM.  It's slightly less clear than last time (analysis time has gone up but not by enough I'm sure it's a real effect) so I'll do a couple of local tests tomorrow to confirm.

**Comment by geoffw0** [comment]
Tested:
```
swift/path-injection on DanielZSY__RxCommonKit (inspired by one of the stage timing regressions)
	main: 89s, 79s
	PR: 107s, 93s

from Type t select t, t.getName() on DanielZSY__RxCommonKit
	main: 10s, 7s
	PR: 18s, 15s

from Type t select t, t.getName() on KrauseFx__MajorKey (the most slowed down analysis on the DCA run)
	main: 7s, 7s
	PR: 8s, 8s
```
I'll see if I can make this better...

**Comment by MathiasVP** [comment]
Note that all this regex stuff may break in the future since we're fundamentally trying to parse the output of a function that's used for diagnostics only: https://github.com/apple/swift/blob/c2fc7ee9e72e9a39854548e3202c667e4934dc65/include/swift/AST/Types.h#L1429. Are we sure this is the direction we want to go in?

**Comment by geoffw0** [comment]
We use type names to match things like MAD models against things in the database - I think it's safe to say that if the underlying strings change, we will have to fix it somewhere.

**Comment by MathiasVP** [comment]
> We use type names to match things like MAD models against things in the database - I think it's safe to say that if the underlying strings change, we will have to fix it somewhere.

Yeah, but I'm wondering if the proper fix may be to change the extractor not not output this diagnostics name in the first place.

**Comment by geoffw0** [comment]
> I'm wondering if the proper fix may be to change the extractor not not output this diagnostics name in the first place.

If there's a formal short name available, yes that would be fantastic!  (and I believe we already do that for decls and perhaps other things)

**Comment by geoffw0** [comment]
FWIW the DCA run on the newer version shows no noticeable analysis slowdown any more.  An extractor solution might still be preferable for the reasons discussed above.

@redsun82 do you know how this could be done?  Does the extractor even have access to a proper short name?

**Comment by redsun82** [comment]
As far as I know no, there is no formal generic short name available. The only way I would see it behaving more robustly is by stopping to extract type names altogether at the `Type` level, and then painstakingly code the naming for each concrete type in QL, possibly extracting whatever information is still missing on specific types to get there...

On the other hand, extracting the debug name of types directly is the only way that will guarantee that the names we print always match how the compiler presents those names to the user.

**Comment by MathiasVP** [comment]
The problem is that a lot of our internal logic (i.e., all of our modeling in MaD) currently depends on the specific string's outputted by this function. So it's not _just_ for displaying the right string to users.

**Comment by geoffw0** [comment]
So it looks like we're leaning back towards the QL approach again (i.e. this PR).

We could create one or more issues for the extractor + QL improvements to do this the more robust / painstaking way in the long run.  I haven't seen much motivation to prioritize it, and I'm a little worried it might create more problems than it solves.

**Comment by MathiasVP** [comment]
> So it looks like we're leaning back towards the QL approach again (i.e. this PR).
> 
> We could create one or more issues for the extractor + QL improvements to do this the more robust / painstaking way in the long run. I haven't seen much motivation to prioritize it, and I'm a little worried it might create more problems than it solves.

Sounds good to me. I'm not a super big fan of using this complicated regex to parse the debug output from the extractor, but in the interest of not letting this PR go stale I'm happy with merging this. We do, however, need to fixup the tests. It looks like this is breaking parts of the CFG construction?

**Pull request merged**
