### PR TITLE
Python: Plaintext Password Information in Config/Xml files

### PR DESCRIPTION
**Pull request by dilanbhalla**
Queries to detect the storing of plaintext password(s) in both xml files and config files in general. The Python xml query added in this branch is already used as a C# query, where  xml files are more commonly used for configuration. However, config files are an essential component of all large projects and it would be very helpful if Python could also detect potential leaks of private, unencrypted information within these files.

### CODE REVIEW

**Comment by shtat00** [comment]
Thanks

**Comment by dilanbhalla** [comment]
Hello,

I just moved this query to experimental as I was told it is the standard to submit there first. Thank you again, and let me know if I need to include anything else or if it’s good to go.

Best,
Dilan

**Comment by dilanbhalla** [comment]
Hi @felicitymay, I am a bit unsure if I am following the correct process. Is there anything else I need to do to help move this towards getting merged as an experimental query? I am unsure what you mean by your most recent comment. Is there a way for me to not request review from the codeql-python team? I would love to get this moved towards getting merged as an experimental query. Thanks!

**Comment by dilanbhalla** [comment]
In fact @felicitymay , I am unsure if this is why some of my experimental queries have not been reviewed, but several of my PRs have review requests from codeql-python (from which I have not received any feedback). I do not want to waste time from the docs team for experimental queries so if I can have some guidance on how to remove their review request and instead get someone else to take a look so I can get them potentially merged as experimental queries, that would be great. 

These queries that I have written and currently are waiting upon review from codeql-python are:

Python: XML RPC Dotted Names
Python: Private Data Cleartext Storage/Logging
Python: Module not intended for production
Python: Open URL without Certificate Validation

Thank you again so much!

**Comment by felicitymay** [comment]
Hi @dilanbhalla - apologies for my unclear message.

All submissions to the CodeQL repository need to be approved by the relevant language team, but submissions to the core query set also need a review from the documentation team - we help to make sure that the query help is clear. So I was automatically added as a reviewer to your PR when you raised it. Now you've updated it to an `experimental` submission, it no longer needs my approval. 

The @github/codeql-python team will be able to check that your query uses efficient and effective CodeQL so I've re-added them as a reviewer. I'll check with them that this PR is on their project board for review.

**Comment by dilanbhalla** [comment]
HI @felicitymay, thanks for letting me know. Unfortunately I submitted a handful of PRs before I was told to default to `experimental` queries, so sorry if anyone on your team has been unnecessarily added to one of my submissions as well. And thank you for checking in with them!

**Comment by RasmusWL** [comment]
Closing this PR off now, instead of letting it sit open any longer.

Technically there is nothing wrong with having this query in Python, but it is not of particular interest since we don't extract XML files by default. In general we recommend using [secret scanning](https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning).

Thanks for taking the time to look into this back in 2020 @dilanbhalla :pray: and sorry for taking so long to properly react to this :flushed:

**Pull request closed without merging**
