### PR TITLE
C++: Detect more uses of `abs`

### PR DESCRIPTION
**Pull request by MathiasVP**
(Part of https://github.com/github/codeql-c-team/issues/272.)

The `semmle.code.cpp.security.Overflow` library recognizes uses of `abs` in relational comparisons, but it _only_ recognized `abs`. This doesn't match well with SAMATE, which apparently tends to use `imaxabs` for `CWE-190`.

This PR adds a couple more `abs`-like functions to the list. Locally, these are the changes I see for the queries that import `semmle.code.cpp.security.Overflow`:

| Query | TP/FP on `main` | TP/FP on this PR |
|--------|--------|--------|
| ArithmeticTainted.ql | 3472/228 | 3468/0 |
| ArithmeticUncontrolled.ql | 2177/232 | 2173/0 |
| ArithmeticWithExtremeValues.ql | 1714/114 | 1712/0 |

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
While you're at it, would it make sense to create a test for the case `tainted = INTMAX_MIN`?
Because in this case `abs(INTMAX_MIN) == INTMAX_MIN` holds and underflow/overflow is possible.

**Comment by MathiasVP** [comment]
> While you're at it, would it make sense to create a test for the case `tainted = INTMAX_MIN`?
> Because in this case `abs(INTMAX_MIN) == INTMAX_MIN` holds and underflow/overflow is possible.

Good point! We should definitely have such a test. (My immediate feeling is that this is currently is a false negative, but let's see what happens.)

**Comment by geoffw0** [comment]
Looks good, great to get rid of some FPs that show up on SAMATE!

**Review by geoffw0 — APPROVED** [review]
It's nice to have that case documented, but I feel it's outside the scope of this PR to fix it (unless it's an easy fix).

I'll merge this later if there are no objections.

**Comment by MathiasVP** [comment]
> It's nice to have that case documented, but I feel it's outside the scope of this PR to fix it (unless it's an easy fix).

Indeed, I don't think I want to fix this in this PR.

**Pull request merged**
