### PR TITLE
C++: Update the DB scheme stats file

### PR DESCRIPTION
**Pull request by jketema**

### CODE REVIEW

**Comment by MathiasVP** [comment]
This is quite a scary PR: 39,547 additions and 39,130 deletions. But we've verified that it behaves as expected on DCA. I'm wondering whether we should do a full test on all of LGTM, though before merging this, though.

**Comment by jketema** [comment]
> This is quite a scary PR: 39,547 additions and 39,130 deletions.

Because the formatting and order in the stats file changed. Also when I looked at the actual contents a lot if the numbers changed, because of the discussed difference between old and new set of projects we use to generate the stats file.

**Comment by MathiasVP** [comment]
Oh yeah, sorry. It wasn't meant as a criticism! I wasn't expecting the diff to be smaller than it is, at all.

**Comment by jketema** [comment]
> Oh yeah, sorry. It wasn't meant as a criticism! I wasn't expecting the diff to be smaller than it is, at all.

I did not see it as criticism at all, not worries. I was just stating the obvious reason why this happened.

**Comment by MathiasVP** [comment]
I'll do a test on all of LGTM for this PR.

**Review by MathiasVP — APPROVED** [review]
Everything looks fine on LGTM 🎉!

**Pull request merged**
