### PR TITLE
delete old deprecations

### PR DESCRIPTION
**Pull request by erik-krogh**
Not Python or C++ (except for files that are synchronized).  
Those have complications, so they get their own PRs after this one has been merged.  

---- 

Notes about change-notes: 
**C++:** All changes seems to be in `internal/` or `implementation/` folders, so I don't think those need change-notes?  
**All**: For most languages there were too many deleted classes/classes to reasonably list. So I went for a general note about using PascalCase instead of UPPERCASE.

### CODE REVIEW

**Comment by jketema** [comment]
> C++: All changes seems to be in internal/ or implementation/ folders, so I don't think those need change-notes?

Yeah, I think it's fine to not have a change note for these.

**Review by jketema — APPROVED** [review]
C++ 👍

**Review by hvitved — APPROVED** [review]
C# 👍

**Review by alexrford — APPROVED** [review]
Ruby 👍

**Review by atorralba — APPROVED** [review]
Java 👍

**Review by asgerf — APPROVED** [review]

**Pull request merged**
