### PR TITLE
Swift: 'ParsedSequence' lacks proper types and yields 'Unresolved' AST nodes

### PR DESCRIPTION
**Pull request by AlexDenisov**
Fixes at least one instance of `UnresolvedDotExpr`s.

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
LGTM once DCA is happy. I wonder if there are other instances where we've made a similar mistake when picking a getter from the Swift AST 🤔

**Comment by redsun82** [comment]
I guess we should beware of `Parsed` thing, it was the same issue with `KeyPathExpr` :sweat_smile:

**Review by MathiasVP — APPROVED** [review]
The code LGTM, but there's a new timeout on a DCA project. Is this something we need to investigate?

**Comment by AlexDenisov** [comment]
> The code LGTM, but there's a new timeout on a DCA project. Is this something we need to investigate?

The timeout is not really new, we still have them once in a while 😞

**Pull request merged**
