### PR TITLE
Swift: Work around some QHelp rendering issues.

### PR DESCRIPTION
**Pull request by geoffw0**
A few of the Swift `.qhelp` files have minor rendering issues now that we label the code snippets as Swift (and have syntax highlighting).  The issue is believed to be caused by an external component, so for now lets just work around it by rendering problematic snippets without syntax highlighting.

~(I'm not 100% sure I have the syntax correct for this, so lets wait for the previews to be sure)~ all good now.

### CODE REVIEW

**Comment by geoffw0** [comment]
We have two choices:
- remove syntax highlighting from these examples (first commit, my preference)
- adjust the examples to avoid the problematic syntax (second commit)

The first approach wasn't properly supported by the qhelp converter, hence the second approach, but an improvement to the qhelp converter is being made so that the first approach _will_ work - hence the revert of the second commit (in the third commit).

**Comment by geoffw0** [comment]
Previews now LGTM.  Ready to merge.

**Comment by calumgrant** [comment]
Is there a plan/issue to revert this PR once the rendering has been fixed?

**Comment by geoffw0** [comment]
> Is there a plan/issue to revert this PR once the rendering has been fixed?

No - it's done by an external tool, we're not really anticipating a fix, and we're not pushing for one if Swift docs are the only thing that's affected.

**Comment by geoffw0** [comment]
I can create an issue in the backlog if you'd like?

**Comment by calumgrant** [comment]
I'll leave it up to you. Approving.

**Review by calumgrant — APPROVED** [review]

**Comment by geoffw0** [comment]
Thanks!

**Pull request merged**
