### PR TITLE
Adapt to `sourceLocationPrefix` change in `qltest`

### PR DESCRIPTION
**Pull request by hvitved**
Previously, `sourceLocationPrefix` for databases created with `codeql test run` would be the path of the enclosing qlpack, which makes little sense. This PR adapts our QL code to changing `sourceLocationPrefix` to be the actual path of the test, similar to what would happen if one ran `codeql database create` on the test folder.

### CODE REVIEW

**Review by RasmusWL — DISMISSED** [review]
Python :+1:

**Review by aschackmull — DISMISSED** [review]
Java 👍

**Review by jketema — DISMISSED** [review]
C++ 👍

**Review by igfoo — DISMISSED** [review]
Kotlin changes look fine

**Comment by hvitved** [comment]
Rebased again, and updated some JS expected test output.

**Comment by asgerf** [comment]
JS 👍 once the tests pass

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
