### PR TITLE
C++: Fix `cpp/boost/tls-settings-misconfiguration` FPs

### PR DESCRIPTION
**Pull request by MathiasVP**
The query was using `asExpr` instead of `asIndirectExpr` in the sink, which meant we didn't find flow from the constructor call associated with:
```cpp
new boost::asio::ssl::context(boost::asio::ssl::context::sslv23);
```
to the qualifier `ctx` on the next line:
```cpp
ctx->set_options(boost::asio::ssl::context::no_tlsv1 | boost::asio::ssl::context::no_tlsv1_1 | boost::asio::ssl::context::no_sslv3);
```

### CODE REVIEW

**Review by jketema — APPROVED** [review]
LGTM (I don't think this is actually run in DCA, because there is no `@precision`)

**Comment by MathiasVP** [comment]
Yeah, I agree. I'm wondering why it doesn't actually have a precision 🤔 I'd think this could _at least_ be medium. But that's a job for another PR I guess 😄

**Comment by jketema** [comment]
Might have something to do with the origin of the query.

**Comment by jketema** [comment]
Origin: https://github.com/github/codeql/pull/2113

**Comment by MathiasVP** [comment]
Good point. I'll create an issue for investigating which precision the query should have

**Comment by jketema** [comment]
> Good point. I'll create an issue for investigating which precision the query should have

Please do, also include the `cpp/boost/use-of-deprecated-hardcoded-security-protocol` query in the same directory, which has the same problem.

**Pull request merged**
