### PR TITLE
C++: QLDoc Improvements

### PR DESCRIPTION
**Pull request by geoffw0**
I just found a whole branch of QLDoc improvements on my machine that never got PR'd.  This is from the 2019 push to add source code examples to the QLDoc for each QL class (which we never finished, though I believe we did get through 90% of the ones designated important).

### CODE REVIEW

**Comment by rdmarsh2** [comment]
Should we syntax-highlight all those code blocks? It shows up in VS Code mouseover, so I think it improves the UX a bit. Just needs `cpp` after the triple backticks.

**Review by jbj — APPROVED** [review]
LGTM. I can see the attraction in adding cpp to the triple backticks, but that applies to all our QLDoc and should therefore be better suited for a follow-up. I seem to recall we've discussed cpp highlighting once or twice before, but I don't remember the conclusion.

**Comment by jbj** [comment]
The autoformatter is unhappy about `cpp/ql/src/semmle/code/cpp/Specifier.qll`. Perhaps you have a trailing space or a tab in there.

**Comment by geoffw0** [comment]
Fixed (it's good being able to see the reasons for check failures so easily now!)

**Review by jbj — APPROVED** [review]

**Pull request merged**
