### PR TITLE
Brodes/wcharcharconversion false positives upstream2

### PR DESCRIPTION
**Pull request by bdrodes**
Addressing false positives with byte arrays. There was an existing check for byte arrays, but there were cases missed. Updated and cleaned up this logic and added test cases to expose the observed false positive. 

Also addressed false positives due to types whose with are set based on macro definitions, and then dynamic checks are used to determine if dangerous widening is performed at runtime. Test cases added to demonstrate the style of check.

### CODE REVIEW

**Comment by jketema** [comment]
I'm not too happy with how this PR is structured, which means that we are spending more time on reviewing this then is ideal. Preferably a pattern is followed where one commit adds a test that highlights a problem, and that commit is then followed by one or more commits that fix the problem. This pattern can then be repeated if multiple problems are solved.

Would it be possible to rework this PR in the above way?

**Comment by bdrodes** [comment]
> I'm not too happy with how this PR is structured, which means that we are spending more time on reviewing this then is ideal. Preferably a pattern is followed where one commit adds a test that highlights a problem, and that commit is then followed by one or more commits that fix the problem. This pattern can then be repeated if multiple problems are solved.
> 
> Would it be possible to rework this PR in the above way?

@jketema I'll work with @MathiasVP to get it in a form that works with your workflow better. In practice I can't guarantee a test case a priori. I can make one, but often it is updated and iterated upon as query updates are based on real-world code bases exposes misc. issues requiring a bit of back and forth, and dev's provide additional insight. @MathiasVP  suggests I can rework the commit history in a way to front load the tests. I'll see if I can do this moving forward.

**Comment by jketema** [comment]
Thanks. I agree with Mathias here that it makes sense to rewrite the commit history, also because that helps to tell the story as to why you want to make the prosed changes.

**Comment by bdrodes** [comment]
@jketema, in this case we found it was easier to just start from scratch with a new PR. I'm going to close this one and open a new one shortly.

**Comment by jketema** [comment]
Sounds good. Thanks!

**Pull request closed without merging**
