### PR TITLE
Java: Remove low confidence dispatch for which we have a manual summary.

### PR DESCRIPTION
**Pull request by aschackmull**
This introduces the concept of low confidence virtual dispatch. Dispatch is currently defined as low confidence if it is purely open-world type-based, and the dispatch type is either `Object`, a functional interface, or an interface from `java.util`. Furthermore, the common marker interfaces `Serializable` and `Clonable` do not count as improved type bounds for the purpose of improving confidence.
Low confidence dispatch is then ignored in data flow in those cases where we also have a manual MaD summary to dispatch to.
As a canonical example consider a call to `Map.put` - without better type bounds this is most likely just some standard map implementation and we will prefer to just use our MaD summary, and not dispatch to any and all custom map implementations that may happen to also exist in the source.

Accounting for the couple of points-to-like enhancements to virtual dispatch in the confidence level is ignored for now.

### CODE REVIEW

**Comment by aschackmull** [comment]
dca looks good

**Review by atorralba — DISMISSED** [review]
LGTM! This should help with a ton of spurious flow in certain projects.

**Comment by aschackmull** [comment]
Hmm, this does probably warrant a change note - let me just add one.

**Comment by aschackmull** [comment]
> Nice, this PR should fix parts of #9864 ([#9864 (comment)](https://github.com/github/codeql/issues/9864#issuecomment-1194126784)) I believe 🎉

Indeed!

**Review by atorralba — APPROVED** [review]

**Pull request merged**
