### PR TITLE
Ruby: Update supported languages and frameworks

### PR DESCRIPTION
**Pull request by calumgrant**
This was just copied from the other languages, with links updated and checked.

A minor question is whether we could specify the RoR version supported (7.0). None of the other languages do this so I decided to leave this out @hmac.

### CODE REVIEW

**Comment by aibaars** [comment]
Looks good to me. Do we want to mention that "one-line pattern matches" are not supported?

**Comment by calumgrant** [comment]
I would not mention that - it's a small limitation that does not block analysis.

**Review by aibaars — APPROVED** [review]
Looks good to me. Let's wait for @hmac to answer your question about Rails version.

**Comment by calumgrant** [comment]
Will merge this now. The idea listing these additional libraries is good and I can do this in a follow-up if we agree to do this.

**Pull request merged**
