### PR TITLE
Update `Change-note-check` workflow to detect changes in shared folder

### PR DESCRIPTION
**Pull request by owen-mc**

### CODE REVIEW

**Comment by owen-mc** [comment]
I can confirm that the "check change note" CI check failed when I made a change to `shared/dataflow/codeql/dataflow/internal/DataFlowImpl.qll`

**Review by henrymercer — APPROVED** [review]

**Review by MathiasVP — APPROVED** [review]
Thanks!

**Comment by owen-mc** [comment]
Hmm. Why is the "Check change note" CI check there? Is it because there was a file which needed that check, and even after I force-pushed to remove that file the check doesn't go away? I tried rerunning it and it still failed, which makes sense as it's just checking whether there's a change note.

**Comment by criemen** [comment]
The workflow has a (sensible) trigger on changes to itself:
`- ".github/workflows/check-change-note.yml"`

Jut add the label, and it should be okay I think?

**Pull request merged**
