### PR TITLE
Fix QL Doc typo.

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Squash commits when merging.

### CODE REVIEW

**Review by michaelnebel — DISMISSED** [review]
Looks good to me.
I can see that I also forgot to finish the comment with "."
Will fix as part of some other PR.

**Comment by intrigus-lgtm** [comment]
> Looks good to me. I can see that I also forgot to finish the comment with "." Will fix as part of some other PR.

Give me a second, I'll add it.

**Review by hvitved — APPROVED** [review]
Thanks!

**Review by michaelnebel — APPROVED** [review]
Great thank you!

**Pull request merged**
