### PR TITLE
Relocate Java CWE libraries to importable location 

### PR DESCRIPTION
**Pull request by rvermeulen**
Multiple Java CWE queries use libraries that define `source` and `sink` nodes or other abstract classes of interest.
However, customisations cannot extend the CWE queries by defining new `source` or `sink` nodes due to the location of these libraries (i.e., their location `CWE-` contains a hyphen and cannot be imported).

This PR tracks the effort of relocating these 'extension points' to a location that can be imported by customisations to extend these queries without having to resort to QL code duplication.

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
Part of this is similar to my PR https://github.com/github/codeql/pull/3881/

**Comment by rvermeulen** [comment]
> A little part of this is similar to my PR #3881
> (The `PathCreation` stuff)

Thanks for the update. Seems like your PR covers the `PathCreation` part so I will update this PR before a merge.

**Comment by aibaars** [comment]
This looks like a good approach. Could you make the naming of those new library files consistent? Some have a `Lib` suffix while others don't. Personally I'd drop the `Lib` bit.

**Comment by rvermeulen** [comment]
> This looks like a good approach. Could you make the naming of those new library files consistent? Some have a `Lib` suffix while others don't. Personally I'd drop the `Lib` bit.

I have dropped the `Lib` suffix from the new libraries.

**Comment by aschackmull** [comment]
`ResponseSplittingLocal.ql` and `UrlRedirectLocal.ql` don't compile, hence the PR check failure.

**Comment by rvermeulen** [comment]
> `ResponseSplittingLocal.ql` and `UrlRedirectLocal.ql` don't compile, hence the PR check failure.

Was just about the ask about the failing `Pull-Request-Check`. 
Will look into those.

**Comment by aschackmull** [comment]
Which parts of `LdapInjection[Lib].qll` are expected to be reusable?

**Comment by rvermeulen** [comment]
> The `SqlInjection[Lib].qll` file should not be exposed in its entirety. It should be split in two files with the configuration and the `queryTaintedBy` predicate kept in a `.qll` next to the queries. Furthermore, once the top half of the file becomes importable we should make sure that it starts with `import java` as the very first import (and remove the subsequently superfluous `import semmle.code.java.Expr`).

This what I would like to discover through this PR. In the other libraries there are also `private` predicates that I would like to split out, but haven't yet to validate the approach.

The end-goal would be to only have extensible elements in these libraries.

**Comment by rvermeulen** [comment]
> Which parts of `LdapInjection[Lib].qll` are expected to be reusable?

The goals was the `LdapInjectionSink`, but I have to reconsider my assessment because it is not an `abstract` class.

**Comment by aschackmull** [comment]
> The goal was the `LdapInjectionSink`, but I have to reconsider my assessment because it is not an `abstract` class.

In that case, consider splitting the file such that the query specific parts are moved to the query and the sink is refactored as an importable abstract class.

**Comment by aschackmull** [comment]
> This what I would like to discover through this PR. In the other libraries there are also `private` predicates that I would like to split out, but haven't yet because I wanted first to validate the approach.

The approach is fine, it just needs individual care and attention for each query, as we don't necessarily want to expose everything, and once we expose something the quality requirements to the QL code goes up.

**Comment by aschackmull** [comment]
(I've only reviewed a few of the files - I have a lot more review comments coming)

**Comment by rvermeulen** [comment]
> > This what I would like to discover through this PR. In the other libraries there are also `private` predicates that I would like to split out, but haven't yet because I wanted first to validate the approach.
> 
> The approach is fine, it just needs individual care and attention for each query, as we don't necessarily want to expose everything, and once we expose something the quality requirements to the QL code goes up.

Given that, I will continue and ensure that only the extensible parts remain in the libraries to prevent unnecessary exposure.

**Comment by aschackmull** [comment]
Given the scope of this, perhaps it would be easier to review and merge if we split this up into several PRs - with one PR for each CWE directory?

**Comment by rvermeulen** [comment]
> Given the scope of this, perhaps it would be easier to review and merge if we split this up into several PRs - with one PR for each CWE directory?

Sounds good. I will split it up in a PR per CWE directory.

**Comment by aschackmull** [comment]
> Sounds good. I will split it up in a PR per CWE directory.

Minor convenience thing: Please include "Java: " as a prefix in the PR titles.

**Comment by rvermeulen** [comment]
This PR will be split into one PR per CWE directory.

**Pull request closed without merging**
