### PR TITLE
C++: Remove big-step relation in flow-through code

### PR DESCRIPTION
**Pull request by jbj**
The first commit makes it feasible to run C++ IR data-flow queries on oneapi-src/oneDNN, and the second makes it fast.

The second commit works around a join order problem that I've reported as https://github.com/github/codeql-coreql-team/issues/453.

I'll take this PR out of draft mode if *-Differences show no performance regressions.

### CODE REVIEW

**Comment by jbj** [comment]
I've started Differences jobs for [C/C++](https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1243/), [C#](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/262/) and [Java](https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/810/).

**Comment by jbj** [comment]
Performance seems to be no worse than before. Are the results diffs for [Java](https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/810//artifact/summary.txt) and [C#](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/262//artifact/summary.txt) just noise? I'm not even sure they're in queries that would be affected by this PR.

**Comment by hvitved** [comment]
> Are the results diffs for [Java](https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/810//artifact/summary.txt) and [C#](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/262//artifact/summary.txt) just noise?

For C#: yes :-/

**Comment by aschackmull** [comment]
Java as well, those two results can for some reason not be matched, so they show up as removed and re-introduced in every single Java-Differences.

**Pull request merged**
