### PR TITLE
Swift: Permit data flow out through pointer arguments

### PR DESCRIPTION
**Pull request by geoffw0**
Permit data flow out through pointer arguments whose contents is modified in the function.  The main change is in `DataFlowPrivate.qll`.  The rest of the changes are adding a `PointerTypes.qll` library to identify pointer types, and lots of testing.

Questions:
- we could restrict `modifiable` to only include _mutable_ pointers, but I think this might introduce edge cases where there really is output through a non-mutable pointer??? (e.g. where the pointee is of immutable type but itself _refers_ to something mutable?)
- alternatively it might be right to widen `modifiable` to include `BoundGenericType`s, as these I think are very similar things to `NominalType`s.  All of the pointers I've modelled are either `NominalType` (which were already part of `modifiable`) or `BoundGenericType`, so the special case for pointers won't be needed if we do that.

Limitations:
 - `modifiable` should account for type aliases, as demonstrated by one of the missing test results.  I've added a note in an issue to address this after the type alias PR is in.
 - we get a spurious result after a pointer contents is cleared in a function; I don't think this is a high priority to fix, but if anyone has a good idea how to do it easily, please say so.
 - some of the `data.swift` and `nsstring.swift` results aren't quite spot on because the MaD models specify taint to the pointer, rather than the pointee.  I've created an issue to sort this out at: https://github.com/github/codeql-c-team/issues/1604
 - the models in `PointerTypes.qll` are *really* basic as they only identify pointers, without modelling any of their methods or consequent taint flow.  I expect we'll expand on this in https://github.com/github/codeql-c-team/issues/1578 .  This is probably why we don't get the results in `taintBuffer`.

### CODE REVIEW

**Comment by MathiasVP** [comment]
> we could restrict `modifiable` to only include mutable pointers, but I think this might introduce edge cases where there really is output through a non-mutable pointer??? (e.g. where the pointee is of immutable type but itself refers to something mutable?)

Yeah, since we don't distinquish between a pointer and a pointee in Swift I don't think we should try to restrict `modifiable` so much that we risk missing flow.

> alternatively it might be right to widen modifiable to include `BoundGenericTypes`, as these I think are very similar things to `NominalTypes`. All of the pointers I've modelled are either `NominalType` (which were already part of modifiable) or `BoundGenericType`, so the special case for pointers won't be needed if we do that.

I'd also be okay with this 👍. In fact, I think I like that solution more so than the `PointerType` approach since this doesn't rely on us keeping a hardcoded list of "pointer-like types".

**Comment by geoffw0** [comment]
I've hopefully fixed the tests now.  I think I will make the change over to `BoundGenericType` in `modifiable`, but I'd also like to write an extra test for that (I think this will affect cases other than pointers) so perhaps it will be best done as follow-up.

**Comment by geoffw0** [comment]
DCA LGTM.

**Comment by MathiasVP** [comment]
> I've hopefully fixed the tests now. I think I will make the change over to `BoundGenericType` in `modifiable`, but I'd also like to write an extra test for that (I think this will affect cases other than pointers) so perhaps it will be best done as follow-up.

I'm happy about this being done as a follow up. Once we do that, do you think the `PointerType` class you added in https://github.com/github/codeql/pull/12391/commits/3249cee1c9af480d1b6dbb136d37ffb76e19603e still serve a purpose?

**Comment by geoffw0** [comment]
> Once we do that, do you think the PointerType class you added in https://github.com/github/codeql/commit/3249cee1c9af480d1b6dbb136d37ffb76e19603e still serve a purpose?

I expect the `PointerType.qll` library as a whole to serve as a starting point for https://github.com/github/codeql-c-team/issues/1578 .  As for the `PointerType` class in particular, I'm not sure whether it will be needed to tie stuff together or if we'll just have a bunch of mostly separate models - but it seems like a sensible thing to have available.

If you don't like it I'll remove it and potentially re-add it if/when it's used?

**Comment by MathiasVP** [comment]
I'd like to avoid dead/unnecessary AST classes if we can, but if you think it's a useful class to have for future work then I'm totally okay with keeping it around 👍

**Comment by geoffw0** [comment]
> I'd like to avoid dead/unnecessary AST classes if we can

Then I will remove it in the follow-up, and make a note in https://github.com/github/codeql-c-team/issues/1578 to re-introduce it if it's useful.

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
