### PR TITLE
JS: cache more predicates

### PR DESCRIPTION
**Pull request by erik-krogh**
I looked at which predicates are often used in the last stage, and then I `cached` some of them. 

[An evaluation](https://github.com/dsp-testing/erik-krogh-dca/tree/run/moreCache-nightly-security/reports) shows ~4% improvement on the security suite.

### CODE REVIEW

**Comment by asgerf** [comment]
I'd feel a lot more confident about this if we had a way to measure cache size 😓 . `hasLocationInfo` is pretty big, but yeah, I've also been bothered by how much time it takes up.

**Comment by esbena** [comment]
> I'd feel a lot more confident about this if we had a way to measure cache size

Why don't we just do that with `du` or something similarly hacky on the workers?

**Comment by erik-krogh** [comment]
> Why don't we just do that with `du` or something similarly hacky on the workers?

Is that something you're planning on? Because I think that sounds like a good idea.

**Comment by erik-krogh** [comment]
The cache size grows from 17% of the DB size to 19% of the DB size according to [Esbens evaluation](https://github.com/dsp-testing/esbena-dca/tree/run/R-657387221/reports/db-sizes). 

So no dramatic increase in cache size.

**Review by asgerf — APPROVED** [review]
Thanks for the quick turnaround @esbena!

Let's do this 🚀

**Pull request merged**
