### PR TITLE
Docs: CodeQL pack compatibility

### PR DESCRIPTION
**Pull request by saritai**
This pull request adds docs for CodeQL pack compatibility as part of CodeQL CLI 2.12.0 release. 

cc @hmakholm @felicitymay

### CODE REVIEW

**Review by hmakholm — APPROVED** [review]
OK for content; I checked with #codeql-releases and they are okay with merging into the release branch too.

**Comment by saritai** [comment]
@hmakholm Thank you! I can merge it into the branch anytime - I might just wait till Monday morning during your working hours but let me know if it is preferred to do it today!

**Comment by hmakholm** [comment]
I think Monday is OK. We'll need to do a follow-up submodule bump in github/semmle-code afterwards, but that won't actually block the release.

**Comment by saritai** [comment]
@hmakholm Sounds good, thank you!! Apologies again for the inconvenience 🙇‍♀️ Once we finally get this migration shipped then this sort of situation shouldn't come up again 👍

**Review by felicitymay — APPROVED** [review]
The content looks as expected. Thanks 💖

**Pull request merged**
