### PR TITLE
Go: improve output of check formatting in makefile

### PR DESCRIPTION
**Pull request by owen-mc**
I tried to do this once before but my bash-scripting skills weren't up to it. This time I had copilot to do it for me 😄 .

### CODE REVIEW

**Comment by smowton** [comment]
Accidentally based on another PR?

**Comment by owen-mc** [comment]
@smowton Deliberately, to check what is printed when there are mis-formatted files. Hence why it's still a draft.

**Comment by owen-mc** [comment]
The output when based on a PR with files that need to be reformatted is like this (taken from CI):
```
The following files need to be reformatted using gofmt:
./ql/test/library-tests/semmle/go/frameworks/Beego/test.go ./ql/test/library-tests/semmle/go/frameworks/Echo/test.go ./ql/test/library-tests/semmle/go/frameworks/Afero/main.go ./ql/test/library-tests/semmle/go/frameworks/Fiber/test.go ./ql/test/library-tests/semmle/go/frameworks/Iris/test.go
Error: make: *** [Makefile:35: check-formatting] Error 1
```
It would be slightly nicer if they weren't all on one line, but I think this is acceptable. When there is also a file that can't be parsed then the error is included in the list, like this (taken from my local machine):
```
The following files need to be reformatted using gofmt:
./ql/test/library-tests/semmle/go/frameworks/Afero/main.go ./ql/test/library-tests/semmle/go/frameworks/Echo/test.go ./ql/test/library-tests/semmle/go/frameworks/Iris/test.go ./ql/test/library-tests/semmle/go/frameworks/Beego/test.go ./ql/test/library-tests/semmle/go/frameworks/Fiber/test.go ./ql/src/experimental/CWE-203/timingGood.go:8:60: missing ',' in parameter list ./ql/src/experimental/CWE-203/timingBad.go:8:59: missing ',' in parameter list ./ql/src/experimental/CWE-74/DsnBad.go:2:1: expected 'package', found 'func' ./ql/src/experimental/CWE-74/DsnGood.go:1:1: expected 'package', found 'func'
make: *** [check-formatting] Error 1
```
Again, I think this is confusing but acceptable.

**Comment by owen-mc** [comment]
@smowton I've rebased on `main` now that I've checked it gives the output I expected in CI.

**Review by smowton — COMMENTED** [review]
Not familiar with an `@` variable, but I'll take your word for it that this does what it ought to.

I don't think go files serving as qhelp examples should gain package declarations and imports; it's better that they are abbreviated snippets.

**Comment by owen-mc** [comment]
I don't know what the `@` means either, so I asked Copilot.

> The @ symbol in a Makefile is used to suppress the echoing of a command. By default, when a Makefile runs a command, it first prints the command to the standard output (usually the terminal), and then runs the command. If you prefix a command with @, Make will run the command without printing it first.

Not sure if we want that, actually.

**Comment by owen-mc** [comment]
> I don't think go files serving as qhelp examples should gain package declarations and imports; it's better that they are abbreviated snippets.

I think that should be dealt with separately. All but four qhelp examples already have package declarations and imports, so I think it's fine for this PR to fix the four that don't.

**Comment by owen-mc** [comment]
With Copilot's help again I have figured out how to preserve the line breaks when printing the output of gofmt, so the list of files that need to be reformatted is now more readable. I believe it will look like this:
```
The following files need to be reformatted using gofmt:
./ql/test/query-tests/AlertSuppression/tst.go
./ql/test/query-tests/AlertSuppression/tstWindows.go
./ql/test/query-tests/Diagnostics/bad.go:3:1: expected 'package', found avvu
./ql/test/query-tests/Diagnostics/bad.go:5:1: expected ';', found wnvwun
./ql/test/query-tests/InconsistentCode/WhitespaceContradictsPrecedence/WhitespaceContradictsPrecedenceGood.go
./ql/test/query-tests/InconsistentCode/WhitespaceContradictsPrecedence/WhitespaceContradictsPrecedence.go
./ql/test/query-tests/InconsistentCode/WhitespaceContradictsPrecedence/main.go
./ql/test/library-tests/semmle/go/Expr/literals.go
./ql/test/library-tests/semmle/go/PrintAst/input.go
./ql/test/library-tests/semmle/go/controlflow/ControlFlowGraph/stmts.go
./ql/test/extractor-tests/robustness/tst.go
./ql/test/extractor-tests/go1.13/tst.go
./ql/test/extractor-tests/diagnostics/broken/test.go:7:1: expected declaration, found This
./ql/test/extractor-tests/diagnostics/broken2/test.go:3:1: expected 'package', found pac
./ql/test/extractor-tests/empty-interface/tst.go
./ql/test/consistency/test.go:7:1: expected declaration, found This
make: *** [check-formatting] Error 1
```

**Review by smowton — DISMISSED** [review]
Change message to note that a file can be flagged due to compile errors as well as due to formatting problems; otherwise lgtm

**Review by smowton — APPROVED** [review]

**Pull request merged**
