### PR TITLE
C++: Add precision to `cpp/boost/tls-settings-misconfiguration` and `cpp/boost/use-of-deprecated-hardcoded-security-protocol`

### PR DESCRIPTION
**Pull request by jketema**
Also clean up the names of the queries while here.

### CODE REVIEW

**Comment by MathiasVP** [comment]
I can't comment on the unchanged lines, but there are a couple of small nits I think we should fix before merging this regarding this `forall`:
```ql
forall(Expr optionArgument, Expr optionArgumentSource |
  optionArgument = fcSetOptions.getArgument(0) and
  BoostorgAsio::SslOptionFlow::flow(DataFlow::exprNode(optionArgumentSource),
    DataFlow::exprNode(optionArgument))
|
  optionArgument.getValue().toInt().bitShiftRight(16).bitAnd(flag) = flag
)
```
first of all, it could be simplified to:
```ql
forall(Expr optionArgument |
  optionArgument = fcSetOptions.getArgument(0) and
  BoostorgAsio::SslOptionFlow::flowTo(DataFlow::exprNode(optionArgument))
|
  optionArgument.getValue().toInt().bitShiftRight(16).bitAnd(flag) = flag
)
```
since we don't care about the `optionArgumentSource` (it's not used anywhere else). This avoids computing the `fastTC` inside the dataflow library.

Second: Should this `forall` really be a `forex`? If there are no 0'th argument for `fcSetOptions` then the entire predicate will hold, which probably isn't meant to happen. Since `fcSetOptions` is a call to `boost::asio::ssl::context::set_options` it probably always has a 0'th argument, but in case we ever add more models here without a 0'th argument then this would give the wrong result.

**Comment by jketema** [comment]
Both those suggested changes make sense.

**Comment by jketema** [comment]
DCA looks good. Let me write a change note before I pull this out of draft.

**Review by MathiasVP — APPROVED** [review]
LGTM!

**Pull request merged**
