### PR TITLE
delete old deprecations

### PR DESCRIPTION
**Pull request by erik-krogh**
This time with change-notes.  

I deleted deprecations where the `deprecated` annotation is at least 14 months old according to `git blame`.

### CODE REVIEW

**Review by hvitved — APPROVED** [review]
C# 👍

**Review by geoffw0 — APPROVED** [review]
C++ LGTM.

**Review by tausbn — APPROVED** [review]
Python 👍

**Review by asgerf — APPROVED** [review]
JS 👍

**Review by aschackmull — APPROVED** [review]
Java 👍

**Pull request merged**
