### PR TITLE
Swift: SingleValueStmtExpr migration scripts

### PR DESCRIPTION
**Pull request by AlexDenisov**

### CODE REVIEW

**Comment by geoffw0** [comment]
Would you mind linking to the associated change that defines `single_value_stmt_exprs` in the `.dbscheme` and extracts it?

Do you think we need to populate `unspecified_element_parents` and/or `unspecified_element_indices` for the new `nspecified_elements`?

As ever with upgrade / downgrade scripts, this will need some manual testing.

**Comment by AlexDenisov** [comment]
> Would you mind linking to the associated change that defines `single_value_stmt_exprs` in the `.dbscheme` and extracts it?

They are in the [target branch/PR](https://github.com/github/codeql/pull/14261), here is [the commit](https://github.com/github/codeql/pull/14261/commits/04766390a3647c3b8271e6326b1eae476a91f07d).

> Do you think we need to populate `unspecified_element_parents` and/or `unspecified_element_indices` for the new `nspecified_elements`?

I don't think so as we are not attaching new `unspecified_elements` to anything? 🤔 

> As ever with upgrade / downgrade scripts, this will need some manual testing.

I did manual testing locally, but of course more testing in such cases is always a good idea.

**Comment by geoffw0** [comment]
> more testing in such cases is always a good idea.

I doubt I'll get around to this until Friday at best.  You can wait and perhaps remind me then.  Or someone else can review and merge - I have no concerns apart from wanting to build a bit higher confidence.

**Comment by MathiasVP** [comment]
FWIW, I think this LGTM as well 👍.

**Review by geoffw0 — APPROVED** [review]
In which case approved. :+1:

(though if you'd rather I did some additional testing, we can still wait and do that)

**Comment by AlexDenisov** [comment]
> In which case approved. 👍
> 
> (though if you'd rather I did some additional testing, we can still wait and do that)

It's going to be merged into another WIP branch, in which I want to start a DCA run. I think we can then still do more tests before merging into `main`.

**Comment by geoffw0** [comment]
Sounds good to me.

**Pull request merged**
