### PR TITLE
Data flow: Use pruning to reduce call contexts

### PR DESCRIPTION
**Pull request by hvitved**
~https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1232/
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/2186/
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1531/
https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/644/~

https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/1234/
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/2189/
https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/1533/
https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/647/

### CODE REVIEW

**Comment by aschackmull** [comment]
What's the motivation for this? The `if recordDataFlowCallSite(call, c) then` ought to be doing a two-column join acting as a filter and the same goes for `if reducedViableImplInReturn(c, call) then`, so that ought to be cheap. Or do we have a bad join-order lurking?

**Comment by aschackmull** [comment]
Is this motivated by lambda-dispatch in higher-order summaries? If so, then I have some other ideas.

**Comment by hvitved** [comment]
> I'm not sure I see the relation to "adding call contexts earlier in the pruning stages"? That should be orthogonal to this, right? (Might even be easier without this change?).

What I meant was to apply the same trick when adding call contexts earlier, to reduce tuple counts.

**Comment by aschackmull** [comment]
The Differences jobs don't really look convincing.

**Comment by hvitved** [comment]
> The Differences jobs don't really look convincing.

No, it looks like maybe there is a bad join-order in the newly introduced predicates.

**Comment by tausbn** [comment]
This PR appears to have gone stale, so I've taken the liberty of closing it (in lieu of asking "hey can I close this?" and waiting for someone else to take appropriate action).

Feel free to reopen it if it's still relevant! :slightly_smiling_face:

**Pull request closed without merging**
