### PR TITLE
C++: Handle bitwise copies in copy constructors

### PR DESCRIPTION
**Pull request by jketema**
Mostly test updates and removal of an IR generation exclusion that is no longer needed.

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
LGTM!

**Comment by jketema** [comment]
Does this need a change note? This is probably not actually visible to users unless they start digging into the IR.

**Comment by jketema** [comment]
And I missed that you added the not change note label 😄

**Comment by MathiasVP** [comment]
> And I missed that you added the not change note label 😄

Yeah, sorry. I was going to do a quick merge so I added the label. Only afterward did I see that the internal PR needed a bump. I don't think we need to add a change note. If we want to, we can add a change note once all the bitwise copy stuff has been fixed. I don't think we need to add one that says "we've fixed it in 1 out of 6 places".

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
