### PR TITLE
C++: qltest options

### PR DESCRIPTION
**Pull request by igfoo**
Migrate to the new way of specifying qltest options.

https://git.semmle.com/Semmle/code/pull/35603

### CODE REVIEW

**Comment by geoffw0** [comment]
The tests are failing though - does this need a submodule update?

**Comment by jbj** [comment]
@geoffw0 Notice the "depends on internal PR" label. The internal PR is https://git.semmle.com/Semmle/code/pull/35603

**Comment by geoffw0** [comment]
Ah yes, sorry, it's the other one we expect the tests to pass on.

**Comment by jbj** [comment]
This PR is very old now, so I'll close it. Feel free to reopen or create a new PR if this work becomes a priority again.

**Pull request closed without merging**
