### PR TITLE
QL: A few more improvements to `ql/alert-message-style-violation`

### PR DESCRIPTION
**Pull request by erik-krogh**
`don't repeat the alert-location as a link` is not currently part of the style guide, and I don't think it needs to be.  
(It's covered under: Keep the message concise).  

I tried to use GVN when I created [don't repeat the alert-location as a link](https://github.com/github/codeql/commit/76fef28c32eef22346f3c417ba55e9f45c5c8048).  
But that seemed to run into an infinite loop (I stopped it after ~100.000 iterations).  
/cc @MathiasVP

### CODE REVIEW

**Comment by MathiasVP** [comment]
> I tried to use GVN when I created [don't repeat the alert-location as a link](https://github.com/github/codeql/commit/76fef28c32eef22346f3c417ba55e9f45c5c8048).
> But that seemed to run into an infinite loop (I stopped it after ~100.000 iterations).
> /cc @MathiasVP

Yeah, 100.000 iterations definitely doesn't sound right. GVN tends to go bad if it's running on a database with unfortunate inconsistencies that results in multiple results for a predicate that's only expected to have a unique result (i.e., if a variable access has multiple types, or if a field has multiple qualifiers).

**Comment by erik-krogh** [comment]
> Yeah, 100.000 iterations definitely doesn't sound right. GVN tends to go bad if it's running on a database with unfortunate inconsistencies that results in multiple results for a predicate that's only expected to have a unique result (i.e., if a variable access has multiple types, or if a field has multiple qualifiers).

We definitely have some non-unique results for some predicates with how we support parameterized modules (collapse all the things into one).  
That might be it.  
It should be possible to get the GVN library to work around that 🤔

**Comment by MathiasVP** [comment]
> I'm thinking that GVN just ignores those cases, and document that behavior.

That sounds good to me, indeed.

**Comment by erik-krogh** [comment]
> That sounds good to me, indeed.

Removing string constants of length > 50 from the GVN computation fixed the infinite loop 😕 
I have no idea why, but it seems like a somewhat reasonable restriction.   
Why do we need GVN for literals anyway? 

Btw: It found more results, so your GVN library works 🎉

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
