### PR TITLE
Java: Add more type-based sanitizers.

### PR DESCRIPTION
**Pull request by aschackmull**
Looking through the data from my initial MRVA top 100 speculative taint run, these additional types came up as potentially relevant to sanitize. The temporals I've also seen pop up before. This should help guard against FP flow going too much off the rails.

I'll run dca before phrasing the change note.

### CODE REVIEW

**Comment by aschackmull** [comment]
> I'll run dca before phrasing the change note.

No actual alert differences in dca. I think we can skip the change note then.

**Comment by owen-mc** [comment]
It might be worth running QA, as this might have an effect in a more obscure case than the default DCA suite covers.

**Comment by aschackmull** [comment]
> It might be worth running QA, as this might have an effect in a more obscure case than the default DCA suite covers.

For what purpose? To determine that we need a change note after all? Or to find a few cases of FPs, which we now filter. I think that's a bit overkill.

**Comment by owen-mc** [comment]
If you're sure there definitely won't be any TPs that we lose, then there is no need to run QA.

**Comment by aschackmull** [comment]
> If you're sure there definitely won't be any TPs that we lose, then there is no need to run QA.

I'm pretty sure. Famous last words and all that, but really, if I see a flow path through one of these types, then that will generally be enough for me to deem it to be clearly FP flow.

**Review by owen-mc — APPROVED** [review]

**Pull request merged**
