### PR TITLE
Swift: Extract Closure Captures

### PR DESCRIPTION
**Pull request by d10c**
This PR extracts closure capture information as a set of `CapturedDecl`s for each `Callable`.

CFG, SSA and DataFlow work will be part of a separate PR.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM once DCA is happy!

**Comment by geoffw0** [comment]
Is this PR waiting for anything, or is it just that merge conflicts need fixing / upgrade scripts need updating?

**Comment by MathiasVP** [comment]
I think this PR is just waiting for those things, yes.

**Review by MathiasVP — APPROVED** [review]
LGTM once DCA comes back happy!

**Comment by d10c** [comment]
DCA looks quite good, except for calleluks/Tofu having 4x analysis time for some reason? I can't reproduce it locally or figure out why, since none of the existing queries exercise closure captures. I'll merge as-is and take a deeper look at this later.

**Pull request merged**
