### PR TITLE
Python: Fix `hasLocationInfo` for packages

### PR DESCRIPTION
**Pull request by tausbn**
@aibaars

### CODE REVIEW

**Comment by aibaars** [comment]
Looks good to me.

**Review by yoff — DISMISSED** [review]
LGTM

**Comment by yoff** [comment]
Happy to merge this, once the test expectations are updated.

**Comment by tausbn** [comment]
How curious, I ran all of the library tests before pushing, and I didn't see any failures, but indeed that one test does fail. Fixed now.

**Comment by tausbn** [comment]
The single test failure (on Actions) appears to be spurious. I think you can merge this now, @yoff.

**Review by aibaars — APPROVED** [review]

**Pull request merged**
