### PR TITLE
Java: Add command-injection sink kind and refactor command injection queries

### PR DESCRIPTION
**Pull request by atorralba**
Adds the `command-injection` sink kind in Models as Data. Uses it in the queries `java/command-line-injection` and `java/concatenated-command-line`.

Also refactors the queries related to command injection so that they are more extensible.

### CODE REVIEW

**Comment by atorralba** [comment]
DCA looks uneventful.

**Comment by atorralba** [comment]
Converted to draft until https://github.com/github/codeql/pull/12698 is merged.

**Comment by atorralba** [comment]
DCA still uneventful.

**Review by egregius313 — APPROVED** [review]
LGTM

**Pull request merged**
