### PR TITLE
C++: Only consider the maximum buffer size for badly bounded write

### PR DESCRIPTION
**Pull request by jketema**

### CODE REVIEW

**Comment by MathiasVP** [comment]
Does this need a change note?

**Comment by jketema** [comment]
> Does this need a change note?

Yes, I think so.

**Comment by jketema** [comment]
Change note added.

**Comment by geoffw0** [comment]
Are there any good projects for testing this on?  (I tried MRVA top 100 but didn't find much)

**Comment by jketema** [comment]
Let me run some MRVA top 1000.

**Comment by geoffw0** [comment]
> Let me run some MRVA top 1000.

I'm already on it (with a variant of the query that should reveal differences)...

**Comment by geoffw0** [comment]
I ran this variant, intended to spot cases where we would have a result with either version of the query and examine potentially multiple buffer sizes:
```
import semmle.code.cpp.security.BufferWrite

int candidateResult(BufferWrite bw) {
  bw.hasExplicitLimit() and // has an explicit size limit
  result = getBufferSize(bw.getDest(), _)
}

from BufferWrite bw
where
  bw.getExplicitLimit() > candidateResult(bw)
select bw, strictconcat(candidateResult(bw).toString(), ", "), bw.getExplicitLimit().toString()
```
I ran this on the MRVA top 1000.  It hasn't finished every single project yet, but I think it's about time I commented.
- 1 result in `gozfree/gear-lib`, buffer size 8192, explicit limit 16384.  It *looks* like it's deliberately overrunning the buffer into another variable on the stack!
- 1 result for `OpenXRay/xray-16`, buffer size 33, explicit limit 65.  Click through to code didn't work.
- 1 result for `libretro/RetroArch`, buffer size 32, explicit limit 45.  This appears to be a fairly simple case of hardcoding the limit not matching the actual buffer size.  The code is 'drm' related though, so it could be doing something very weird or deliberately surprising.

No results with multiple candidate results (i.e. multiple calculated buffer sizes), which is disappointing, but also reassuring.  The change in this PR is likely to fix the intended case but won't affect most other results.  :+1:

**Review by geoffw0 — APPROVED** [review]

**Comment by esbena** [comment]
FWIW, QA can do the "which projects have alerts for this and that query?" for you now:

image

[visit the recent QA experiment](https://dataexplorer.azure.com/dashboards/751779bb-c379-4cc4-8f09-0448e8c0cb39?p-tag_left=v-QA-2.14.1-2023-08-10&p-tag_right=v-QA-2.14.2-2023-08-10-db&p-languages=v-cpp&p-_measure=v-steps%3A+e2e&p-repoPattern=v-.*&p-queryPattern=v-cpp%2Fbadly-bounded-write#7570c609-d3df-4609-8555-4c18f2c60ebd), where I have already set the query filter parameter in the top to `cpp/badly-bounded-write`, then sort by the `alerts` column by clicking on its header a few times.

**Pull request merged**
