### PR TITLE
Update version numbers for LGTM Enterprise 1.28

### PR DESCRIPTION
**Pull request by felicitymay**
This PR makes a couple of small changes in preparation for the next release of LGTM Enterprise:

- Comment out `version` and `release` variables in the main `conf.py` file as they are not used in the main CodeQL microsite and it's confusing having outdated information in the config file.
- Ditto for the `conf.py` file for the QL training slides (also fix the QLlexer path which was broken when `global-sphinx-files` was removed and file structure changed) 
- Update the `version` and `release` variables in the `conf.py` file used by the LGTM Enterprise CodeQL support docs.
- Be explicit about which version of the CodeQL CLI we are talking about, to reduce confusion with the support information in the CodeQL microsite.

### CODE REVIEW

**Comment by felicitymay** [comment]
@jf205 - would you mind checking this is okay as it contains changes to the configuration for the training slides. The slides build locally and I think these changes are correct, but you know much more about them than I do.

**Comment by felicitymay** [comment]
I can't see any error reason in the failing test: https://github.com/github/semmle-code/runs/3564647906?check_suite_focus=true 😕

**Comment by adityasharad** [comment]
@felicitymay The error message is sneakily hidden within a log message group: if you click to expand `Run` and then click to expand `Executing check script: worker-job-tests-reminder.py` then you'll see the failure.
The failure itself is a bug in the CI check, and not related to this PR. It attempted to run a check script that only applies to internal PRs, and then failed because it couldn't work out the internal PR number. 😐  Will fix separately.

**Comment by jf205** [comment]
@felicitymay thanks for making these updates to the training material files. Looks fine to me, and since your local builds work i guess it's good to go 👍🏻

**Review by jf205 — APPROVED** [review]

**Pull request merged**
