### PR TITLE
QL for QL: generalise non-US spelling query

### PR DESCRIPTION
**Pull request by nickrolfe**
1. Catch common misspellings as well.
2. Also check names of classes, predicates, etc.

The old query matched against the entire QLDoc comment string, but now I break each comment string up into individual words (and do the same for node names). I was a bit worried about string pool pollution and performance, but they seem OK. We're talking about tens of thousands of strings for a db containing all of `github/codeql`, which is not that big a number.

### CODE REVIEW

**Comment by nickrolfe** [comment]
If @github/codeql-ql-for-ql-reviewers think this is ok, I'll add followup commits to fix some/many/all of the typos it finds.

**Review by erik-krogh — COMMENTED** [review]
> If https://github.com/orgs/github/teams/codeql-ql-for-ql-reviewers think this is ok, I'll add followup commits to fix some/many/all of the typos it finds. 

This looks good :+1:  

And there are plenty of typos to fix :see_no_evil:

**Comment by tausbn** [comment]
_Finally_ I won't be able to misspell "primordial" in my code. :muscle:

**Comment by nickrolfe** [comment]
I've pushed fixes to all the spelling errors in QLDoc comments, and a couple of small refinements to the QL-for-QL query. I'm inclined to leave the remaining misspelled predicate and class names as they are for now.

**Review by jketema — APPROVED** [review]
C++ 👍 

@geoffw0 You might want to have a look at the XXE transformer misspellings flagged up here. I think those are coming from the query you're currently working on?

**Review by tausbn — APPROVED** [review]
Python changes LGTM. :+1:

**Comment by nickrolfe** [comment]
@geoffw0 - the updated query also flags a few class names in [XXE.ql](https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-611/XXE.ql) that misspell 'transformer' as 'tranformer'.

**Comment by geoffw0** [comment]
> @geoffw0 - the updated query also flags a few class names in [XXE.ql](https://github.com/github/codeql/blob/main/cpp/ql/src/Security/CWE/CWE-611/XXE.ql) that misspell 'transformer' as 'tranformer'.

Oh I see, there are some issues flagged but not fixed here.  I can fix them in an upcoming PR?

Also: how did I not spot these myself...

**Comment by nickrolfe** [comment]
> Oh I see, there are some issues flagged but not fixed here. I can fix them in an upcoming PR?

Yeah, correcting spelling in comments is low-risk, so I just fixed them, but changing class and predicate names is a bit more involved, as I have to figure out whether I need to deprecate the old name and write a change-note.

So I've left that as a followup exercise, and I'd be more than happy for you to deal with those particular misspellings.

**Comment by geoffw0** [comment]
> I'd be more than happy for you to deal with those particular misspellings.

Will do.

**Review by hvitved — APPROVED** [review]
C# / Ruby 👍

**Pull request merged**
