### PR TITLE
Misc: Make `generate-code-scanning-query-list.py` fail on missing query pack

### PR DESCRIPTION
**Pull request by RasmusWL**
I was using the artifact from the [Build code scanning query list](https://github.com/github/codeql/actions/workflows/query-list.yml), and couldn't understand that it didn't contain any C++ queries at all :confused: Looking further into the problem, it turns out that `codeql resolve queries cpp-code-scanning.qls` [fails for some reason in that action](https://github.com/github/codeql/runs/3498601442?check_suite_focus=true#step:8:7), although it works fine for me locally (and aa week ago [all languages were failing](https://github.com/github/codeql/runs/3431753013?check_suite_focus=true#step:8:7)).

I'm thinking it would be better for this to fail if a query pack could not be found, instead of silently producing wrong data. I added an option to ignore these sorts of errors, but I do think failing by default is the right behavior: If you're building a list of supported queries, but have problems finding some of them, that should probably always be a problem worth investigating. (I'm sort of skeptical on whether it's even a good idea to add this option, but I didn't want to make a too intrusive change)

### CODE REVIEW

**Review by sj — APPROVED** [review]
LGTM! Probably good to have @adityasharad's opinion as well.

**Review by adityasharad — APPROVED** [review]

**Comment by adityasharad** [comment]
Hmm the error message is a bit misleading (it tells you the name of the query suite, not the query pack) but I agree with having it fail for this reason.

**Comment by aeisenberg** [comment]
I am looking into the failing test and the root causes are the `from: codeql-cpp` in the `cpp-code-scanning.qls` suites and others like it.

In the 2.6.0 release, these references are mapped to `codeql/cpp-all` (the library pack, with no queries). Post 2.6.0, we fixed this and for resolve queries commands these references are mapped to `codeql/cpp-queries` (the query pack). Running with a CLI built against the `semmle-code` main branch, the query list is built correctly.

We have two options here:

- Convert all `codeql-{lang}` references in query suites to `codeql/{lang}-queries`. This should happen anyway and I will make this change shortly.
- Run this script with a more recent version of the CLI.

**Comment by aeisenberg** [comment]
Running the script on https://github.com/github/codeql/pull/6605, and it passes.

**Pull request merged**
