### PR TITLE
ATM: make training data selection also select sinks that are NOT constants

### PR DESCRIPTION
**Pull request by kaeluka**
see discussion: https://github.com/github/ml-ql-adaptive-threat-modeling/issues/1874.

This greatly increases the amount of training data available to train the model, eg.:

| Project | From | To | % |
|--|--|--|--|
| `elastic/kibana` | 408352 | 520836 | +27% |
| `angular/angular` | 82256 | 113040 | +38% |
| `adobe/brackets` | 92332 | 162504 | +76% |

### CODE REVIEW

**Comment by kaeluka** [comment]
@henrymercer are you able to take a look?

**Review by henrymercer — COMMENTED** [review]
Thanks, this looks correct to me, though of course we'll want to hold off merging it until we've done the experiment 👍

**Comment by kaeluka** [comment]
Thanks for taking a look, @henrymercer! Yes, this shouldn't be merged without an experiment and a discussion.

**Comment by tiferet** [comment]
Experimentation being tracked [here](https://github.com/github/ml-ql-adaptive-threat-modeling-backend/pull/1327)

**Comment by tiferet** [comment]
I wrote up the results and some thoughts on next steps [here](https://github.com/github/ml-ql-adaptive-threat-modeling-backend/pull/1327#issue-1235548911).

**Pull request closed without merging**
