### PR TITLE
Java: CWE-079 Query to detect XSS with JavaServer Faces (JSF)

### PR DESCRIPTION
**Pull request by luchua-bc**
JavaServer Faces (JSF) is a Java-based MVC web application framework intended to simplify development integration of web-based user interfaces. JavaServer Faces is a standardized display technology for component-based UI development, which was formalized through the Java Community Process and is a part of the Java EE platform.

JSF UI components are rendered as markup languages such as HTML and XML through a JSF <code>renderer</code>. User inputs that don't have proper sanitization and are directly written to a JSF <code>renderer</code> make the website vulnerable to cross-site scripting.

The query detects unsafe usage of JSF <code>renderer</code> that are vulnerable to XSS attacks. Please consider to merge the PR. Thanks.

### CODE REVIEW

**Comment by smowton** [comment]
@luchua-bc I've polished this up to what I'd consider main query-pack standard -- you might want to take a look at the new commits to see what's changed which would be welcome in future for any query targeting the main (non-experimental) suite.

**Comment by luchua-bc** [comment]
Thanks @smowton a lot for refactoring the query into the main (non-experimental) suite. Those separate commits are crystal clear. I will make sure future queries follow the best practices:
- Only include stub methods and constants being used by the query
- Merge with configuration and test cases of the same kind, e.g. servlet and JSF
- Put <code>qll</code> libraries in <code>java/ql/lib</code> instead of <code>java/ql/src</code>
- Add reverse import from the external flow library
- Create a change note

**Review by aschackmull — COMMENTED** [review]
LGTM.

**Review by smowton — APPROVED** [review]
Proxying @aschackmull's approval

**Pull request merged**
