### PR TITLE
Go: extractor: do not store intermediate values in long string concatenations

### PR DESCRIPTION
**Pull request by owen-mc**
When we see "a" + "b" + "c" + "d", do not add a row to the constvalues table for the intermediate strings "ab" and "abc". We still have entries for the string literals ("a", "b", "c", and "d") and the whole string concatenation ("abcd").

This was inspired by `golang/go-frontend`, which is a somewhat pathological case with a concatenation of 7098 literals of 60 characters each. The db goes down from 2.5GB to 170MB.

### CODE REVIEW

**Comment by owen-mc** [comment]
I'm thinking about how to test this. Should I add a check that we don't have a string with value "ab" in a db for a go file containing "a" + "b" + "c"? I feel like that isn't quite testing the right thing. Or could we have a pathological example and check the db isn't too big?

**Comment by smowton** [comment]
The former sounds right to me

**Comment by owen-mc** [comment]
DCA shows nothing interesting, so I'll do a QA run to see if that turns up any other repos with this pathologically long string concatenations.

**Comment by owen-mc** [comment]
QA results looked broadly fine. I saw one case where "  Stringpool size measured as 271614442" was replaced by "Stringpool size measured as 11567514" (23 times smaller), which is obviously encouraging. There are three alert changes I should look into - they may just because the base for my comparison wasn't quite right.

**Comment by owen-mc** [comment]
I looked into one of the alert changes, which was two extra alerts for `go/incomplete-hostname-regex`. The short version is that they are TPs and there was a bug in the way that the query was written which was hiding them before. I've filed [this issue](https://github.com/github/codeql-go-team/issues/381) to fix it properly, but it shouldn't block this PR being merged.

I also started looking at the other alert change, which is a lost result for `go/incorrect-integer-conversion` in `evilsocket/opensnitch`. I've figured out where the problem is happening but not why. It seems to be that we don't follow flow into a particular function. I can't see how the changes in this PR would affect that, as there aren't any string concatenations in sight. It isn't caused by an incorrect base for the comparison as I can reproduce it with the base of the PR. When I have more time to investigate I will look into the predicate for viable callees.

**Comment by owen-mc** [comment]
I investigated the second alert change some more. It is intermittent, though it did happen on QA and the first time I ran locally. The flow doesn't follow a method call because there is no parameter node defined, which is because there is no link between the Function (object/entity) and its declaration. This must come from a problem during extraction. There was a problem extracting the method `Process.BuildTree`, defined in `daemon/procmon/details.go`. `Process` is defined in the sibling file `daemon/procmon/process.go`. It turns out that we need to have `protoc` installed when we run the makefile to generate some code which is then imported by these files. Not having that package available stops us from extracting the `Process` type correctly on the first pass.

I don't think this should block this PR, as it seems unrelated to the changes made here. At worst we have perturbed something non-determinimistic which causes this to be a problem more often.

**Review by smowton — DISMISSED** [review]

**Review by atorralba — APPROVED** [review]
Rubber-stamping @smowton's previous approval.

**Pull request merged**
