### PR TITLE
Python: Fix join order in type trackers

### PR DESCRIPTION
**Pull request by tausbn**
Improves performance by avoiding having to materialise the tuples in the `..._first_join` helper predicates.

### CODE REVIEW

**Comment by RasmusWL** [comment]
Nice :muscle: Just going to run a performance test on this (to make sure everything is still ok), then I'll approve and merge

https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/463/

**Review by RasmusWL — CHANGES_REQUESTED** [review]
Results from :point_up: show that `nova` takes twice as long to analyze, so we will need to fix that before merging this PR :cry:

**Comment by tausbn** [comment]
> Results from  show that `nova` takes twice as long to analyze, so we will need to fix that before merging this PR

Thanks for checking this. It appears that the culprits here are a few type trackers that _do not_ use `LocalSourceNode` internally. Rewriting to use `LocalSourceNode` and `flowsTo(result)` fixes this. I will push a commit that addresses this.

Ideally, though, we would endeavour to rewrite all of these type trackers, in order to avoid this issue entirely.

**Comment by RasmusWL** [comment]
Nice @tausbn :muscle: In the meantime, I have actually rewritten a few of the libraries to use API graphs instead, so there are a few merge conflicts. Let's rerun performance tests to make sure all is ok once you've merged in main :blush:

**Comment by RasmusWL** [comment]
Started new performance test in https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/472/

**Comment by yoff** [comment]
> Started new performance test in https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/472/

Not the big win we were hoping for...

**Comment by tausbn** [comment]
This PR is quickly being superseded by the move to API graphs (e.g. #5642). Closing.

**Pull request closed without merging**
