### PR TITLE
C++: New query for SSL result conflation

### PR DESCRIPTION
**Pull request by geoffw0**
This is the first of two new queries for [CWE-295: Improper Certificate Validation](https://cwe.mitre.org/data/definitions/295.html).

Results:
 - [on all LGTM C/C++ projects](https://lgtm.com/query/1243915003686309152/); very thin (only 1 result).
 - this is disappointing, but the query does cover 2 of the 5 examples given in the CWE definition.

Precision:
 - provisionally set to `@medium`, it's difficult to judge without seeing more real world results.

Performance:
 - tested locally on `kamailio_kamailio` and `chakra-core` (performance is great with a warmed up cache)
 - no timeouts on the above LGTM run.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM! Could we upgrade this query to precision `high` right away? It's certainly not very noisy!

**Comment by MathiasVP** [comment]
Actually. Do you mind running DCA to make sure we don't get any re-evaluation in the suite @geoffw0?

**Comment by geoffw0** [comment]
> It's certainly not very noisy!

I'd like to tune it to detect a bit more (support more libraries and more variants of logic / flow), but the truth may be that the mistake simply isn't as common as the CWE examples led us to believe.

I'm a bit reluctant to increase precision to `high` without more real world evidence (I guess it wouldn't do much harm though).

**Comment by geoffw0** [comment]
DCA shows no significant change in performance.

**Comment by MathiasVP** [comment]
Great! Merging! 🎉

**Pull request merged**
