### PR TITLE
Data flow: No more flow summaries

### PR DESCRIPTION
**Pull request by hvitved**
This PR rewrites how we analyze flow through method calls. Before, we computed flow summaries up-front for (relevant) methods, and restricted such summaries to alter at most the head of the input/output access paths.

This PR proposes to abandon the flow summary approach<sup>*</sup>, and instead compute flow-through using the existing logic for calculating flow in and flow out. The motivation for doing this is:

1. It simplifies and unifies the implementation.
2. It allows for general flow-through, not restricted to alter at most the head of the access paths.

The implementation uses essentially [the same technique](https://github.com/Semmle/ql/pull/2822) as in the first pruning steps (`nodeCandFwd1` and `nodeCand1`), namely to record whether the data-flow node is from an argument `fromArg` (resp. to be returned `toReturn`), and if so, restrict flow back out to calls that also have flow in (resp. restrict flow back in to calls that also have flow out). Additionally, we also record the access path of the argument (resp. the returned value), using the same level of abstraction as for the node itself (a Boolean in the first step, then `AccessPathFront`, and finally `AccessPath`). Lastly, we only record these access paths when the value may potentially flow through, in order to avoid unnecessary duplication.

<sup>*</sup>We still need to compute value-based summaries in `DataFlowImplCommon.qll` for extended return nodes and for reverse store steps through getters, but this can now be simplified as we no longer need to take stores into account.

### Differences jobs
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/1047/
- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/113/
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/704/

Interestingly, even though we now allow for more flow<sup>**</sup>, we see a significant performance improvement on Mono and JDK of 17% and 14%, respectively (performance is mostly the same for C++). Results are unchanged for C++, for C# there are few extra results, and for Java the are also extra results, in particular `java/tainted-arithmetic` now has 52 extra results.

<sup>**</sup>With the exception that the summaries computed in `DataFlowImplCommon.qll` no longer track flow through store-read steps.

### CODE REVIEW

**Comment by hvitved** [comment]
Differences jobs:
- C++: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/976/
- C#: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/49/
- Java: https://jenkins.internal.semmle.com/job/Changes/job/Java-Differences/656/

**Comment by jbj** [comment]
The performance results for C# and Java are fantastic, but I haven't looked at whether the additional flow is good.

Should this PR be aimed at 1.24?

**Comment by hvitved** [comment]
> Should this PR be aimed at 1.24?

I had hoped so, but @aschackmull is on vacation this week and next week.

**Comment by jbj** [comment]
We'll definitely need @aschackmull to review this one, so 1.24 is probably not an option. What a scary-looking diff!

**Comment by hvitved** [comment]
> What a scary-looking diff!

I know ;-) I would still argue that the new code is simpler, and in fact [the diff](https://github.com/Semmle/ql/pull/3110/commits/334b5015a8cc185b8334ec318ed3caf5d67e4292) removes more code than it adds, even though I have also added more elaborate comments to existing predicates (like for example https://github.com/Semmle/ql/pull/3110/commits/334b5015a8cc185b8334ec318ed3caf5d67e4292#diff-3fe62e36050a4be03a57b4a631bb7052R707-R713).

**Comment by hvitved** [comment]
Since there has been no review activity on this PR yet, I am going to rebase and rerun the `Differences` jobs.

**Comment by hvitved** [comment]
> Since there has been no review activity on this PR yet, I am going to rebase and rerun the `Differences` jobs.

I have updated the PR description to link to the new jobs.

**Comment by hvitved** [comment]
> * The ad-hoc flow-restriction from the `fieldFlowBranchLimit` is now also applied to summarized flow.  This is a natural change given the change in the way the code is structured.  This reduces the amount of flow we calculate.

I thought about this again, and isn't the `fieldFlowBranchLimit` very likely to be applied in the final `pathStep` calculation, even before this PR? For example, flow in is restricted to parameters `p` and access paths `ap` that [can be reached in the previous pruning stage](https://github.com/hvitved/ql/blob/42e180d6c47149f4e9595b1dc5e910d559d26f1a/cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll#L2442). A similar restriction is made for [flow out](https://github.com/hvitved/ql/blob/42e180d6c47149f4e9595b1dc5e910d559d26f1a/cpp/ql/src/semmle/code/cpp/dataflow/internal/DataFlowImpl.qll#L2406). This would also explain why we generally don't see a reduction in query results.

**Comment by aschackmull** [comment]
Hmm, yes, that is a good point.

**Pull request merged**
