### PR TITLE
Swift: Accept standardized CSV sink labels

### PR DESCRIPTION
**Pull request by geoffw0**
There's been an effort to standardize the CSV sink labels we use between different languages.  This change adds the standardized labels for Swift (but does not remove the old labels - I'm open to discussion on whether and how we should do that, but personally I don't think they're doing a lot of harm).

@jcogs33

### CODE REVIEW

**Comment by MathiasVP** [comment]
> I'm open to discussion on whether and how we should do that, but personally I don't think they're doing a lot of harm

I think Swift should embrace the fact that we don't have a deprecation period yet and just get rid of the old labels 😃. One way of doing things is better than two in this case, I think!

**Comment by jcogs33** [comment]
> > I'm open to discussion on whether and how we should do that, but personally I don't think they're doing a lot of harm
> 
> I think Swift should embrace the fact that we don't have a deprecation period yet and just get rid of the old labels 😃. One way of doing things is better than two in this case, I think!

FYI, for Java I'm removing rid of the old labels and including a change note on the PR. See https://github.com/github/codeql/pull/12916.

**Comment by geoffw0** [comment]
OK, I've removed the old labels.  I don't think we have any CSV sink models that use these particular labels, and we're not doing change notes yet, so that should be all that's needed.

**Comment by geoffw0** [comment]
>I don't think we have any CSV sink models that use these particular labels
...
> `FAILED: /Users/runner/work/codeql/codeql/swift/ql/test/query-tests/Security/CWE-312/CleartextLoggingTest.ql`

Looks like I was wrong (I searched but my terms were a bit too narrow).  Fixed now.

**Review by MathiasVP — APPROVED** [review]
LGTM once CI is happy!

**Pull request merged**
