### PR TITLE
Go: Fix missing promoted fields due to name clash

### PR DESCRIPTION
**Pull request by owen-mc**
When two embedded fields at different depths have the same name (but are not the same type - they are in different packages and happen to have the same name) then we don't treat the second one correctly and we don't promote any of its fields or methods. This turns out to be because of a condition that was added to avoid non-termination on cyclic structs in https://github.com/github/codeql-go/pull/184 which only checked the name of the embedded field. The fix is to also check the type.

While looking into this I noticed that we have two different predicates for calculating field candidates. This PR includes a refactoring to remove the redundancy and make the code easier to understand.

### CODE REVIEW

**Comment by owen-mc** [comment]
Hmm, the tests pass locally for me. I'll have to look into that more.

**Comment by owen-mc** [comment]
I figured it out. I was using the released CLI, but https://github.com/github/codeql/pull/17941 changes the extractor and hence the test results, so I needed to build and use the go extractor locally.

This is ready to review now.

**Review by smowton — DISMISSED** [review]
Haven't reviewed the tests in detail, but I'm 99% convinced the elimination of getFieldCand vs hasFieldCand is sound. One difference jumps out: `getFieldCand` uses `hasEmbeddedField` which doesn't look through a NamedType before using `.(PointerType).getBaseType()`, `getFieldOfEmbedded` does. This might make a difference if `X` is embedded where X is defined `type X *Y`, in a positive direction. I note `hasMethodCand` uses this embedded-field predicate as well.

Definitely needs DCA.

**Comment by owen-mc** [comment]
Note that `getFieldCand` uses `hasEmbeddedField`, which is defined using `hasFieldCand`. So it seems independent, but actually it isn't.

**Comment by smowton** [comment]
That's true, but for one layer we'll miss named pointer types AFAICT:

```
    exists(Field f | this.hasFieldCand(_, f, depth, true) |
      tp = f.getType() or
      tp = f.getType().(PointerType).getBaseType()
    )
```

That means getFieldCand -> hasEmbeddedField will miss the case where there's an embed of type `Named` which is defined as `*MyEmbeddedStruct`. For deeper embeddings it then uses hasFieldCand -> getFieldOfEmbedded, so this will only affect depth-1 embeddings.

**Comment by smowton** [comment]
OK great. That actually suggests then to simplify `getFieldOfEmbedded` since that does a `getUnderlyingType` jump prior to checking for a pointer type that in fact can't happen.

**Comment by owen-mc** [comment]
The second DCA seems to show a 2% speed up on the two biggest dbs. I should probably run QA in case there are any pathological cases.

**Comment by owen-mc** [comment]
I messed up the QA run by using a nightly base, so the results are dominated by the results for https://github.com/github/codeql/pull/17494. However, I can see that there aren't any alert changes in queries which aren't affected by that PR, and there aren't any noticeable slowdowns. So I am okay with merging this now.

**Comment by owen-mc** [comment]
I ran another QA and the results are completely uneventful. If anything, it sped things up (but it's probably just noise). And no alert changes. @smowton This is ready to re-review.

**Pull request merged**
