### PR TITLE
Ruby/Python: parse anchors in regexes as special characters

### PR DESCRIPTION
**Pull request by nickrolfe**
Fixes https://github.com/github/codeql-team/issues/599

It means the ReDoS query no longer suggests an example input starting with 'G'.

### CODE REVIEW

**Review by alexrford — COMMENTED** [review]
The change looks good - should we have similar special handling for [`\b` and `\B`](https://ruby-doc.org/core-3.0.2/Regexp.html#class-Regexp-label-Anchors)?

**Comment by nickrolfe** [comment]
Yes, probably. I'll check on that once #6561 is merged.

**Comment by nickrolfe** [comment]
I've updated this to handle `\b` and `\B` in Ruby, in addition to `\G`.

I've also changed Python to handle `\b`, `\B`, `\A`, and `\Z` in a similar fashion (`\A` and `\Z` were already handled in Ruby).

These changes should fix ReDoS FPs such as [this one in `ruby/ruby`](https://github.com/ruby/ruby/blob/a53aab1273729c10b7e675ce8fd1a711d22c0cd0/tool/lib/webrick/httputils.rb#L176-L177), but also means we give more accurate alert text for some TPs.

I should probably add that Ruby FP as a test case, but I'm not sure how to handle the licensing.

**Review by yoff — DISMISSED** [review]
Great work, thanks for also fixing the Python side (including tests and all)!

**Comment by nickrolfe** [comment]
Thanks! There were merge conflicts in the Ruby ReDoS test – now resolved.

**Review by alexrford — APPROVED** [review]

**Pull request merged**
