### PR TITLE
C++: Fix data-flow dispatch perf with globals 1.24

### PR DESCRIPTION
**Pull request by jbj**
This is a 1.24 backport of #3637.

**Do not merge** without the approval of the release manager, @alexet.

### CODE REVIEW

**Comment by geoffw0** [comment]
As extra checking, I tested this with two IR queries (`RedundantNullCheckSimple.ql` to warm up, then `CgXss.ql`) on a wxWidgets snapshot.  Performance was similar (249s -> 244s and 250s -> 250s).  `DataFlowDispatch::VirtualDispatch::DataSensitiveCall::flowsFrom` has the same number of tuples (447615) in the latter query.

I've also confirmed the speedup on kamailio with the same setup.  `CgXss.ql` speeds up significantly (2058s -> 1425s) and the `flowsFrom` row count matches (304194).  The number of actual results is also unchanged across all of these runs (in most cases there were 0 results).

:+1:

**Comment by alexet** [comment]
Is it likely that customers will run into this or is this a weird case with a specific database?

**Comment by jbj** [comment]
The problem wasn't visible on our 11 test projects in CPP-Differences.

**Comment by jbj** [comment]
It became visible when deploying to lgtm.com, but even there it didn't cause timeouts.

**Comment by jbj** [comment]
We should perhaps let this PR wait until #3637 has been deployed to lgtm.com in the next dist upgrade. Then we'll better be able to understand the risk.

**Comment by jbj** [comment]
Given that no customer has complained about this performance issue and that 1.25 is getting close, I'll close this PR.

**Pull request closed without merging**
