### PR TITLE
C#: Update DB stats file

### PR DESCRIPTION
**Pull request by tamasvajk**
[C# differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/643/)

### CODE REVIEW

**Comment by hvitved** [comment]
The differences job failed, so I have started a new one: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/645/

**Comment by tamasvajk** [comment]
It failed again, I started it again: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/650/.

If this one fails again, I'll investigate a bit more the reason for the failure.

**Comment by hvitved** [comment]
> If this one fails again, I'll investigate a bit more the reason for the failure.

I also restarted it :-) https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/649/

**Comment by tamasvajk** [comment]
Started a new [differences job](https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/653/) after the nomagic pragmas.

**Comment by tamasvajk** [comment]
I started the differences job again with the extra commit. https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/655/

**Comment by tamasvajk** [comment]
The perf looks better now, but it's still slower than before. `Completion::invalidCastCandidate#f` shows up in `DisposeNotCalledOnException` as a slow predicate, but I don't know what to do about it. Also, `UselessTypeTest.ql-6:#select#cpe#13456#fffff` went from 28ms to 2 minutes in roslyn. @hvitved could you help be with this please?

**Comment by hvitved** [comment]
New diff job: https://jenkins.internal.semmle.com/job/Changes/job/CSharp-Differences/661/.

**Review by hvitved — APPROVED** [review]

**Pull request merged**
