### PR TITLE
C++: Implement the `subpaths` query predicate for `cpp/invalid-pointer-deref`

### PR DESCRIPTION
**Pull request by jketema**
This'll probably need a DCA experiment?

### CODE REVIEW

**Review by MathiasVP — DISMISSED** [review]
Agreed. LGTM once have a DCA run that looks good!

**Comment by jketema** [comment]
@MathiasVP I'd forgotten to update the test results.

**Review by MathiasVP — APPROVED** [review]

**Comment by jketema** [comment]
Still waiting for one DCA result. Mostly looks good, but I'm somewhat confused by the Bochs result. Locally I see similar runtimes for `cpp/invalid-pointer-deref` before and after the change. Could this come from one of the other queries in the suite?

**Comment by MathiasVP** [comment]
> Still waiting for one DCA result. Mostly looks good, but I'm somewhat confused by the Bochs result. Locally I see similar runtimes for cpp/invalid-pointer-deref before and after the change. Could this come from one of the other queries in the suite?

Hm yes, that's odd. If you don't see anything locally I'm not too worried about it. Especially when it's only on 1 project

**Comment by jketema** [comment]
Re-running Bochs to be sure, otherwise DCA looks fine.

**Pull request merged**
