### PR TITLE
Python: No `fieldFlowBranchLimit` for `SummarizedCallable`s

### PR DESCRIPTION
**Pull request by yoff**
We noticed that when
- a function has more than one summary (with different charpred)
- one summary is subsumed by a subpath (or something happens around the function being extracted)
- the function is called multiple times(we needed at least three)

one of the summaries would no longer lead to flow.

Fixed by doing the same as Ruby in https://github.com/github/codeql/pull/15689

### CODE REVIEW

**Comment by yoff** [comment]
> I'm guessing you probably need to implement #15689 for Python.

Thanks! That did indeed solve it.

**Review by RasmusWL — APPROVED** [review]
LGTM (I'll change the title of the PR though, since you're actually fixing the problem as well)

**Comment by RasmusWL** [comment]
Before we merge though: let's do some testing on performance impact! I think that's the main reason we didn't just implement it when Ruby did:

> The change does come with a performance penalty, though, since we are now computing more results, and (hopefully) reducing false negatives.

So we should at least gauge that performance impact

**Comment by yoff** [comment]
No frightening performance cost (less than 1%), so I shall boldly merge this.

**Pull request merged**
