### PR TITLE
Swift: control flow for #available

### PR DESCRIPTION
**Pull request by geoffw0**
Adds control flow for `#available`.  Follows up https://github.com/github/codeql/pull/11876 and https://github.com/github/codeql/pull/12121 and actually gets us the target results around uses of `#available`.

This was considerably more complicated than we expected:
- extensions to `StmtConditionTree` as we had anticipated.
  - we previous noticed `firstElement` appears to be missing a case for patterns, but I was unable to come up with a test case where this matters (do they *always* have an initializer?).  If someone comes up with a non-working test case I will fix it.
  - I don't really understand why `firstElement` is so complicated anyway.  I would expect it to just be `first initializer | first boolean | first availability`.  Can the first element have both an initializer + boolean?
- I also had to create AST tree classes for the `AvailabilityInfo` and `AvailabilitySpec` underneath the `StmtCondition` to get proper flow through those.
- and I had to extend `astInBooleanContext` to recongize a `ConditionElement` containing an `AvailabilityInfo` as boolean.  I believe this was ultimately so that `Completion.qll`s `completionIsValidFor` would recognize the appropriate completions.
  - there was a design choice here as I could have created a new completion type for `AvailabilityInfo`s (along the lines of a matching completion), but I couldn't see any advantages over using the existing boolean completions.  This is my first foray into this stuff, however.
- finally I have added some qldoc and a missing `toString` case.

---

I think @MathiasVP , @d10c and @AlexDenisov may be well suited to reviewing different bits of this PR.

### CODE REVIEW

**Comment by MathiasVP** [comment]
> - and I had to extend `astInBooleanContext` to recongize a `ConditionElement` containing an `AvailabilityInfo` as boolean. I believe this was ultimately so that `Completion.qll`s `completionIsValidFor` would recognize the appropriate completions.
>    - there was a design choice here as I could have created a new completion type for `AvailabilityInfo`s (along the lines of a matching completion), but I couldn't see any advantages over using the existing boolean completions. This is my first foray into this stuff, however.

I think you made the right choice, here. I can't see any advantage to creating a new kind of completion for this either. Generally, we'd create a new kind of completion if we could use it to do clever control-flow splitting, but I don't really think there's anything interesting we can (or should) do here for these checks.

**Review by MathiasVP — APPROVED** [review]
LGTM once DCA is happy 🎉

**Comment by geoffw0** [comment]
Thanks for the quick review!

I do want to give @AlexDenisov chance to take a look as well, as this touches on his recent work.

**Review by AlexDenisov — APPROVED** [review]

**Comment by geoffw0** [comment]
Thanks for the reviews, DCA LGTM so merging!

**Pull request merged**
