### PR TITLE
C++: Add a sanitizer to `cpp/cleartext-storage-buffer`

### PR DESCRIPTION
**Pull request by MathiasVP**
This is the easy part of https://github.com/github/codeql/pull/10117:
> The second performance fix is to block flow through integral typed expressions in the query. We have used similar sanitizers in other queries to fix FPs, so this is a natural thing to do in this query as well, and it seems to dramatically improve the query's performance.

I pulled this out to a separate PR so it's not needlessly delayed by the unrelated `jumpStep` change.

### CODE REVIEW

**Comment by MathiasVP** [comment]
DCA looks fine. Merging 🎉

**Comment by geoffw0** [comment]
I wonder if the same improvement would make sense in the `cpp/cleartext-storage-database` and other `cpp/cleartext-storage-file` queries?

**Comment by MathiasVP** [comment]
> I wonder if the same improvement would make sense in the `cpp/cleartext-storage-database` and other `cpp/cleartext-storage-file` queries?

I would imagine that to be the case, yes.

**Comment by geoffw0** [comment]
I might look into it when I have a spare hour then.

**Pull request merged**
