### PR TITLE
Rust: More test cases for rust/dead-code

### PR DESCRIPTION
**Pull request by geoffw0**
Adds more test cases for `rust/dead-code`.  Like the other unused entities queries, we currently get a lot of spurious results in the wild, and these tests help to characterise some of them.

### CODE REVIEW

**Comment by paldepind** [comment]
Thanks for these great test cases!

For `unreachable_if_2` I don't think the spurious result is caused by the CFG construction. The CFG for the function looks like below. I've labelled the last call to `do_something`. It is visited after the `if` expression.

```mermaid
flowchart TD
1["enter unreachable_if_2"]
10["CallExpr"]
11["ExprStmt"]
12["ReturnExpr"]
13["ExprStmt"]
14["BlockExpr"]
15["PathExpr"]
16["CallExpr"]
17["ExprStmt"]
18["PathExpr"]
19["CallExpr"]
2["exit unreachable_if_2"]
20["ExprStmt (last do_something())"]
3["exit unreachable_if_2 (normal)"]
4["BlockExpr"]
5["ExprStmt"]
6["IfExpr"]
7["PathExpr"]
8["CallExpr"]
9["PathExpr"]

1 --> 5
3 --> 2
4 --> 3
5 --> 7
6 --> 20
7 --> 8
8 -- false --> 17
8 -- true --> 11
9 --> 10
10 --> 13
11 --> 9
12 -- return --> 3
13 --> 12
14 --> 6
15 --> 16
16 --> 14
17 --> 15
18 --> 19
19 --> 4
20 --> 18
```

**Comment by geoffw0** [comment]
Thanks for looking into it, it was a surprising result!  Maybe something is wrong in the query then...

**Comment by geoffw0** [comment]
I've added a couple of extra test cases addressing a point you made elsewhere, that some of the `if let` statements don't actually perform a pattern match that could fail.

I've still to address the issue you describe above, but (since I'm going on holiday) it might be better to merge these tests as they are, and I'll write up an issue to look into a potential problem with the query.

**Review by paldepind — APPROVED** [review]

**Comment by paldepind** [comment]
> I've still to address the issue you describe above, but (since I'm going on holiday) it might be better to merge these tests as they are, and I'll write up an issue to look into a potential problem with the query.

That sounds good! :)

**Comment by geoffw0** [comment]
> I've still to address the issue you describe above

Follow-up work here: https://github.com/github/codeql/pull/17857

**Pull request merged**
