### PR TITLE
C#: Make sure no file is added twice to the compilation

### PR DESCRIPTION
**Pull request by tamasvajk**
This PR is fixing a bug where the same file could be added multiple times to the compilation. This could happen when a source file exists in the `CompilerGeneratedFilesOutputPath` folder.

### CODE REVIEW

**Comment by tamasvajk** [comment]
DCA looks better. 13884 `cs/compilation-error` tuples are removed for `dotnet/roslyn`. Extraction error count is also down.

**Comment by michaelnebel** [comment]
Uh, this is fantastic!
It will be interesting to see, how this affects the nightly DCA run!

**Review by michaelnebel — APPROVED** [review]
LGTM!

**Review by hvitved — APPROVED** [review]

**Comment by tamasvajk** [comment]
> Uh, this is fantastic! It will be interesting to see, how this affects the nightly DCA run!

The second linked DCA issue shows the changes in the nightly-traced source suite.

**Pull request merged**
