### PR TITLE
C#: Delete the CIL extractor.

### PR DESCRIPTION
**Pull request by michaelnebel**
In this PR the CIL extractor is deleted, including all CIL related tests and the extractor option of enabling CIL extraction.
Commit by commit review is encouraged.

### CODE REVIEW

**Comment by michaelnebel** [comment]
DCA experiment: https://github.com/github/codeql-dca-main/issues/19722

**Comment by michaelnebel** [comment]
DCA looks good!

**Review by hvitved — CHANGES_REQUESTED** [review]
Looks like changes are needed in the internal repo as well.

**Comment by michaelnebel** [comment]
The internal PR mentions this PR, but it looks like it drowned in all the other mentions :-)
Tests are passing on the internal PR - I will add you both as reviewers on that one as well.

**Comment by tamasvajk** [comment]
@hvitved Do you know why the standalone tests are failing?

**Review by hvitved — CHANGES_REQUESTED** [review]
We need to remove `"cil"` from
https://github.com/github/codeql/blob/main/csharp/extractor/Semmle.Util/CommandLineOptions.cs#L43

**Comment by hvitved** [comment]
> @hvitved Do you know why the standalone tests are failing?

Now I do :-) See my comment above.

**Review by hvitved — APPROVED** [review]

**Comment by michaelnebel** [comment]
> > @hvitved Do you know why the standalone tests are failing?
> 
> Now I do :-) See my comment above.

OMG - that was important. The standalone extractor would crash in case someone had set the environment variable 😱 
Thank you both!!!

Searched both codeql and semmlecode again for more cil related stuff, but didn't find any.
Is there any workflow that sets the `CIL` environment variable that I have overlooked?

**Pull request merged**
