### PR TITLE
C++: Better caching for IR-based use-use dataflow

### PR DESCRIPTION
**Pull request by MathiasVP**
Turns out the `simpleLocalFlowStep` relation wasn't cached 😱. This PR fixes this.

### CODE REVIEW

**Review by jketema — APPROVED** [review]
That diff was very hard to read, but LGTM.

**Comment by MathiasVP** [comment]
> That diff was very hard to read, but LGTM.

Yeah, sorry :( it's really just moving things into a cached module, but I do see that the diff is making this rather difficult to spot!

**Comment by jketema** [comment]
> it's really just moving things into a cached module

Yup, that was also my conclusion.

**Comment by hvitved** [comment]
Unless you invoke `simpleLocalFlowStep` elsewhere (which I wouldn't expect), caching it should not be needed, since the shared data flow library [makes sure to cache it](https://github.com/github/codeql/blob/d5acd310ce973faf5d7ad778af65f19f9d036381/cpp/ql/lib/semmle/code/cpp/ir/dataflow/internal/DataFlowImplCommon.qll#L858).

**Pull request merged**
