### PR TITLE
C++: Give fewer types to global variables

### PR DESCRIPTION
**Pull request by igfoo**
Follows change in the extractor.

### CODE REVIEW

**Review by nickrolfe — APPROVED** [review]

**Comment by tausbn** [comment]
This was merged with failing tests. Is that intended?

**Comment by nickrolfe** [comment]
The tests on this PR failed because they ran with the extractor from `main`, but they depend on the changes in the linked extractor PR, which was merged at the same time (and was green).

**Comment by tausbn** [comment]
Ah, okay. I guess I just got unlucky with when my tests ran, then? I'll try rerunning them.

**Comment by nickrolfe** [comment]
As I understand it, your PR checks would have had to start in the tiny window between merging this PR and the extractor one. It seems unlikely, but the tests are passing for me, so I'm not sure what happened.

**Comment by tausbn** [comment]
Well, if they keep failing on the global variable tests, I'll be sure to let you know! :slightly_smiling_face:

**Pull request merged**
