### PR TITLE
Python: better models of `open` function

### PR DESCRIPTION
**Pull request by RasmusWL**
Small improvements to `open` modeling, that I spotted while preparing to work in something else.

Would recommend reviewing commit-by-commit.

### CODE REVIEW

**Review by yoff — APPROVED** [review]
Much nicer, thanks. We might consider moving the definition of `OpenCall` below the definition of `io_attr`, but I am not even sure we do that in general. I guess what made me think this is really a desire to keep "providers" (like `io_attr`) and "users" (like `OpenCall) apart; that seems out of scope here..

**Comment by RasmusWL** [comment]
> Much nicer, thanks. We might consider moving the definition of `OpenCall` below the definition of `io_attr`, but I am not even sure we do that in general. I guess what made me think this is really a desire to keep "providers" (like `io_attr`) and "users" (like `OpenCall) apart; that seems out of scope here..

To be completely honest that _did_ feel a bit dirty.

**Comment by RasmusWL** [comment]
Converted to draft, since I'll try to write a new-style changenote for this

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
