### PR TITLE
Java: Add abstract class for fluent methods; use it to propagate taint in StrBuilder, StringBuilder, StringBuffer and Guava Builder

### PR DESCRIPTION
**Pull request by smowton**
Depends on https://github.com/github/codeql/pull/5172 -- only review the last 3 commits

### CODE REVIEW

**Comment by aschackmull** [comment]
I don't think this is quite the way we want to implement this. Instead I think we need two things: 1. Add support for additional value-preserving flow-steps. 2. Make the shared data-flow library handle this sort of aliasing through the use of the additional value-preserving steps.
In particular, this should also work for flow-summaries that are automatically synthesised by the data-flow library, i.e. assuming we had support for flow through byte-code then we want this to work out-of-the-box without any language-specific modelling parts.

**Comment by smowton** [comment]
So for models we specify a dataflow step qualifier -> retval (and for functions we have source/bytecode for we'll know we have localflow*(this, retval)), then a shared-dataflow step that says for the particular case where a qualifier flows to a return value we should also introduce a backward-pointing edge from the return value's post-update node to the qualifier's post-update node?

Sounds doable, so long as "the qualifier" is a sufficiently language-independent concept (would it have to become any-input -> any-output? If so this is getting closer to an alias analysis)

A philosophical question: if we're special-casing return-aliases-qualifier or output-aliases-input, what's special about functions that do this? Using local variables to do `StrBuilder s1 = new StrBuilder(); StrBuilder s2 = s1; s1.append(taint()); sink(s2.toString());` is logically very similar, but I gather we generally take a stance against general alias analysis like this due to excessive false-positives

**Comment by aschackmull** [comment]
The philosophical question is a good one, and indeed this is partial alias analysis. This likely requires some further thinking and tinkering to get to a good tradeoff between precision and risks of time-travel-like data flow paths. In this case I think functions may be different from assignments since that keeps us restricted to intra-statement alias analysis, which I suspect is key to avoid weird effects. We can still get time-travel effects in constructs like this:
```
x.someFluentMethod().anotherFluentMethod(x).addTaint(taint());
```
since in this case taint can travel from `taint()` back to the initial `x` and then forward again to the second occurrence of `x` and into `anotherFluentMethod`, which is a time-travel-like false-positive flow path. But I hope that such flows are rare when we restrict alias analysis to not travel backwards to previous statements.

**Comment by smowton** [comment]
With my implementation at the moment I actually don't think we can get time travel because the backward flow goes via post-update nodes, from result PUN (which equals the next chained call's qualifier's PUN) to our own qualifier's PUN.

In any case this makes sense; my only worry is about introducing edges based on localFlow(qualifier, result) which joins the recursive definition of getASuccessor. Given that, I intend to look syntactically for `return this;` instead (bytecode analysis could do something very similar when it comes along), or a model reporting that the qualifier flows-to the return value (like TaintPreservingCallable but for DataFlow not TaintTracking edges).

**Comment by aschackmull** [comment]
Closing in favour of https://github.com/github/codeql/pull/5219

**Pull request closed without merging**
