### PR TITLE
Python/JS: Make most of the new library private

### PR DESCRIPTION
**Pull request by yoff**
A new library was recently introduced. As much as possible of that should be made private.

### CODE REVIEW

**Comment by aschackmull** [comment]
Much more can be made private.

**Comment by yoff** [comment]
> Much more can be made private.

Do you mean in other files or in the new file? I felt I could not hide previously exposed stuff in the javascript codebase, and I want the python files to be identical.

**Comment by yoff** [comment]
Ah, I guess I could make most classes private also..

**Comment by yoff** [comment]
Oh, and I missed all the typed predicates 🤦

**Review by RasmusWL — APPROVED** [review]
:+1: from the Python side

**Comment by esbena** [comment]
> A new library was recently introduced.

The library is less new for JavaScript (~4-6 months?). Is this privatization a breaking change for JavaScript? Or did we already cross that bridge when the shared RegExp libraries for Python/JavaScript were introduced?

**Comment by aschackmull** [comment]
> Is this privatization a breaking change for JavaScript

I believe this code was recently hidden in a `.ql` file, so therefore implicitly private. But I haven't checked the details - I'm just drive-by commenting.

**Comment by yoff** [comment]
> > Is this privatization a breaking change for JavaScript
> 
> I believe this code was recently hidden in a `.ql` file, so therefore implicitly private. But I haven't checked the details - I'm just drive-by commenting.

That is correct, it was inside `ReDoS.ql` which has to `import javascript`. It defines the relevant `ReDoSConfiguration` and was pulled out so that the files can be identical.

**Review by esbena — APPROVED** [review]
In that case: :+1: from JS

**Pull request merged**
