### PR TITLE
Swift: Update models for better Swift 6 compatibility.

### PR DESCRIPTION
**Pull request by geoffw0**
Update models for better Swift 6 compatibility.

This was aimed and fixing some of the test regressions on the Swift 6 PR.  I've also tried to fix other cases I found where things we model have changed in Swift 6 (or were simply missing) but it's very likely there are other library changes I have missed.

I haven't removed any older models, since (1) I'm not sure if those models still have value for various reasons and (2) even if they don't, it would require somewhat more verification work to be confident.

@redsun82 let me know if you'd like a change note for these changes specifically.  Or will there be a general change note for Swift 6 changes that covers it?

I'll fire off a DCA run as well, though I'm not sure what I expect from it.  Also wait to see if CI shows any further tests impacted.

### CODE REVIEW

**Comment by geoffw0** [comment]
The `BuiltinTypes.ql` test failed, because apparently there is now a `Builtin.Int128` type.  It looks exactly the same on the parent PR, and this is clearly a consequence of the upgrade and not of these changes.

**Comment by geoffw0** [comment]
Nothing to see on the DCA run, apart from analysis time slowdown / wobble.

**Comment by redsun82** [comment]
> @redsun82 let me know if you'd like a change note for these changes specifically. Or will there be a general change note for Swift 6 changes that covers it?

I'd say we can do a general change note once we're ready :+1:

**Review by redsun82 — APPROVED** [review]
Thanks a lot!

**Pull request merged**
