### PR TITLE
Python: Use default `getEnclosingCallable` for `RetrunNode`

### PR DESCRIPTION
**Pull request by yoff**
The override removed some flow, this reinstates it. Differences job suggesting that performance has not suffered: https://jenkins.internal.semmle.com/job/Changes/job/Python-Differences/294/

### CODE REVIEW

**Comment by RasmusWL** [comment]
@yoff do you have conclusions from your performance test yet?

**Comment by yoff** [comment]
Yes, I edited the description. It looks fine as far as I can tell?

**Comment by RasmusWL** [comment]
Oh yes, I overlooked the _suggesting that performance has not suffered_ part. Personally, I would be happy to see a new comment on the PR explaining the results (so I get a notification that something has changed).

probably you only marked it as ready for review after updating the description, but I still didn't notice :sweat_smile:

**Review by RasmusWL — CHANGES_REQUESTED** [review]
Hmm, as I recall you fixed this because it was important for some real code. However, I don't see any of our existing test-cases that now work because you fixed this. Would it be possible to add a new test-case that now works because of this change?

**Comment by yoff** [comment]
> Hmm, as I recall you fixed this because it was important for some real code. However, I don't see any of our existing test-cases that now work because you fixed this. Would it be possible to add a new test-case that now works because of this change?

Yes, I meant to do that. I got caught up in checking that it actually solved the issue. (I agree that the cases in `r_regression.py` do not illustrate the change very clearly.)

**Comment by yoff** [comment]
Since the commit history is so small, I force pushed to get the "add test -> fix test" sequence. I forgot to add the "missing flow" comment, but you can see that nothing changes in the `dataflow` query output until after the fix.

**Review by RasmusWL — APPROVED** [review]
Really happy you _force pushed to get the "add test -> fix test" sequence_.

I would have been even better if you had updated the `.expected` output when adding the test, so  I could see that this didn't work before... but I'll you on this one :wink: 

Good job :+1:

**Pull request merged**
