### PR TITLE
Java: Model java.util.Optional lambda methods

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Adds support for the various lambda-accepting methods on `java.util.Optional`

### CODE REVIEW

**Review by aschackmull — APPROVED** [review]

**Review by smowton — DISMISSED** [review]

**Review by smowton — APPROVED** [review]

**Comment by JLLeitschuh** [comment]
@smowton can you add the `hacktoberfest-accepted` label to this PR for me?

**Comment by smowton** [comment]
AFAIK CodeQL doesn't participate in Hacktoberfest

**Comment by JLLeitschuh** [comment]
@smowton it doesn't matter if you participate or not, I can still get credit if you add the label.
@atorralba did it for me for #6116

**Comment by smowton** [comment]
ok, why not :)

**Pull request merged**
