### PR TITLE
JS: Add JSON Stringify Sanitizer

### PR DESCRIPTION
**Pull request by Kwstubbs**
JSON Stringify accounts for roughly half of all false positives in the reflected xss query and is found in the form res.send(JSON.stringify(malicious_input)). This sanitizer will remove these FPs.

### CODE REVIEW

**Comment by asgerf** [comment]
JSON-encoding does not prevent HTML injection. For example this will execute the script embedded in the JSON value:
```js
res.send(JSON.stringify({x: "<script>alert(1)</script>"}));
```

The real protection comes from setting the content-header to `application/json` (or anything that isn't interpreted as HTML).

We do try to take that into account, but perhaps it's failing to trigger in the cases you've looked at?

**Comment by Kwstubbs** [comment]
@asgerf You are right. I have done a little testing here are the results.


**Default Content Type Returned When Response is passed Through JSON.Stringify**

_Vulnerable_ 
Express - text/html
Hapi - text/html
nest - text/html (uses express)

_Not Vulnerable_
Node HTTP - no content type header - yes alert
micro - no content type header - yes alert
fastify - text/plain - yes alert
koa - text/plain - no alert
restify - application/json - no alert

After looking at how the content type is determined in CodeQL, it seems JSON.stringify can be a good sanitizer for the frameworks that return no content type header since the query considers those to be vulnerable to XSS but the browser will not interpret it as such. Would you like me to add this sanitizer for these frameworks?

**Comment by asgerf** [comment]
@Kwstubbs thanks for looking into this.

There seem to be two slightly different issues at play here:
1. We need to be better at taking into account the default content-type header set by libraries.
2. For libraries that do not set any content-type header (such as raw Node http), we could take content-sniffing into account. If I'm understanding this correctly, when there is no content-type header at all, the first few characters may determine how the document is interpreted.

I'd be happy to see a solution to (1). Though for (2) I'm not sure this is a direction we want to take. In the real world you don't really want your security to be depend on content-sniffing.

**Comment by pwntester** [comment]
> We need to be better at taking into account the default content-type header set by libraries.

In case it helps, I did something similar for Spife and Restify [here](https://github.com/search?q=repo:github/codeql+%22extends+Http::ImplicitHeaderDefinition%22&type=code)

> For libraries that do not set any content-type header (such as raw Node http), we could take content-sniffing into account. If I'm understanding this correctly, when there is no content-type header at all, the first few characters may determine how the document is interpreted.

This is implemented (or not) by the browser and it depends on other headers such as `X-Content-Type-Options=nosniff` so I agree that this is something we should not address in CodeQL. I think all modern browsers will __Not__ do content sniffing, so it may be safe to assume that the lack of content-type header will be treated as `text/plain` (we need to double check that)

**Pull request closed without merging**
