### PR TITLE
JS: make array taint-step better

### PR DESCRIPTION
**Pull request by japroc**
Hello! 👋

I have met a case when taint tacking was broken on expression like: `filter((x) => !!x)`. Actually it's pretty straightforward taint-step as  `filter((x) => x)`. So i made a PR.

There are also 2 moments to discuss:
1. I didnt found test case for current filter taint-step
2. Why you dont consider cases like `filter((x) => x.name)` as correct taint-step? Because of potential false positives? A have some code:
```
call.(DataFlow::MethodCallNode).getMethodName() = "filter" and
    pred = call.getReceiver() and
    succ = call and
    exists(DataFlow::FunctionNode callback, Expr retexpr, DataFlow::Node retnode |
      callback = call.getArgument(0).getAFunctionValue() and
      retexpr =
        [
          callback.getAReturn().asExpr(),
          callback.getAReturn().asExpr().(LogNotExpr).getOperand().(LogNotExpr).getOperand()
        ] and
      DataFlow::exprNode(retexpr) = AccessPath::getAReferenceTo(retnode, _) and
      retnode = callback.getParameter(0).getALocalUse() and
      (retexpr instanceof DotExpr or retexpr instanceof VarRef)
    )
```
It would be interesting to know what you think about this.

I saw in blame that you removed wide taint-step for any filter. https://github.com/github/codeql/commit/4ac21e9f3ffaacd50392fee6bd665c5d2f15989f. And of course, filter like `(x>5)` or `x.Includes(allowlist)` are incorrect taint steps. But i think that cases like `x => x.name`, `x => !!x`, `x => !!x.name` are points for discussion.

Waiting for your thoughts 😊

### CODE REVIEW

**Comment by esbena** [comment]
Yes, the reason for the current behaviour is fear of false positives. We think your `=> !!x`, `=> !!x.p`, `=> x.p` cases are generally fine to have as special case propagation steps.

We are happy to merge your suggestion, could you add a test?
Feel free to attempt to support the suggested property presence check as well, either in this PR or another PR.

**Comment by japroc** [comment]
Hello @esbena.
As i see, currently there is only test for DataFlow::Configuration. But my PR is about TaintTracking. Should i add another test file?

**Comment by esbena** [comment]
>  Should i add another test file?

Ideally, yes. 
In practice we tend to have tests for steps like this scattered throughout the various taint query tests. So if your motivating example is about a false negative for `js/xss`, just add a test in there that uses `filter((x) => !!x)` somewhere to show that we now get a true positive instead.

**Comment by japroc** [comment]
Hello @esbena,

Check out new ql file for taint tracking test and 2 field in test js file.

**Comment by esbena** [comment]
Thanks. I'll do a large performance check of this and report back.

**Comment by kaeluka** [comment]
Is this PR still active, @esbena?

**Comment by esbena** [comment]
@japroc I'm sorry for the very slow response here.

The performance evaluation looks good and the so does the tests in https://github.com/github/codeql/pull/9535 where I fixed the conflicts. 

I'll merge #9535 shortly, let me know if you want to amend this PR further.

**Comment by esbena** [comment]
#9535 has been merged. It contains the rebased changes of this inactive PR.
Thank you for the contribution, and sorry for the slow responses in our end.

**Pull request closed without merging**
