### PR TITLE
C++: Refactor code to use predicate isGuardPhi/4

### PR DESCRIPTION
**Pull request by andersfugmann**
Addressing review comment on #6568: This Pr uses the new predicate for `RangeSSA::isGuardPhi/4`. 
I have not deleted the old predicate `RangeSSA::isGuardPhi/3`, even though its not used anymore to avoid braking of external queries which might rely on `RangeSSA::isGuardPhi/3`

### CODE REVIEW

**Comment by jbj** [comment]
I suggest [marking `RangeSSA::isGuardPhi/3` as `deprecated`](https://github.com/github/codeql/blob/main/docs/qldoc-style-guide.md#deprecated-predicates). It seems there wasn't a single need for it in our own codebase, and we found out it can be a footgun. Then a change note is needed.

As these changes affect the join order, a DCA run would be appropriate.

**Comment by andersfugmann** [comment]
> I suggest [marking `RangeSSA::isGuardPhi/3` as `deprecated`](https://github.com/github/codeql/blob/main/docs/qldoc-style-guide.md#deprecated-predicates). It seems there wasn't a single need for it in our own codebase, and we found out it can be a footgun. Then a change note is needed.
> 
I will deprecate the function. 

> As these changes affect the join order, a DCA run would be appropriate.

[DCA](https://github.com/github/codeql-dca-main/tree/data/andersfugmann/refactor_use_of__Differences__security-extend/reports) timings looks ok.

**Comment by jbj** [comment]
There's an unrelated integration-test failure:
```
Running TRAP import for CodeQL database at /home/runner/work/semmle-code/semmle-code/integration-tests/posix-only/multi_extract/cluster/javascript...
foo.js.trap.gz, 3: com.semmle.util.exception.CatastrophicError: Tried to insert tuple with 2 columns into files which has 5 columns.
```

Maybe merging from `main` will fix it.

**Review by jbj — APPROVED** [review]
Whoops, this PR had fallen off my radar. LGTM.

**Pull request merged**
