### PR TITLE
C++: Make escape analysis less sound and reenable it

### PR DESCRIPTION
**Pull request by rdmarsh2**

### CODE REVIEW

**Comment by rdmarsh2** [comment]
Internal perf test: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/877/

**Comment by jbj** [comment]
Performance and qltest changes look good, but the alert changes at https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/877/ are massive. I'm surprised to see that some queries have many more results after this change; shouldn't they get fewer results?

**Comment by rdmarsh2** [comment]
That's very surprising. I'm looking into it.

**Comment by rdmarsh2** [comment]
Those changes seem to be caused by a bug in IR generation for pointer parameters that escape, which led to the pointer's `InitializeindirectionInstruction` being the root of the aliased vvar's chi chain for the rest of the function. I've fixed that and started a new CPP-Differences: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/896/

**Comment by rdmarsh2** [comment]
Results on the new diff job look good, and I've accepted the test changes.

**Comment by jbj** [comment]
Most of the CPP-Differences changes are hard to judge because they're interprocedural, but I noticed that we lost https://github.com/wireshark/wireshark/blob/505c3187a4fd33803edc55e345ec65a5ebff3754/epan/dissectors/dcerpc/idl2wrs.c#L3252 from `cpp/path-injection`. Can you explain that?

**Comment by rdmarsh2** [comment]
It looks like `idlfile` is considered to escape when it's passed to `FPRINTF`, which is a function that uses the `va_list` macros. The parameter is passed as a macro argument to `va_start`, which we model with a `VarArgsStart` instruction. There's no special handling for that instruction in our alias/escape analysis, so it's assumed to make the parameter's address escape, which I think causes the value of the parameter to also escape.

**Comment by jbj** [comment]
https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/896/ has expired on Jenkins :crying_cat_face:

**Comment by rdmarsh2** [comment]
new job: https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/939/

**Comment by jbj** [comment]
> It looks like `idlfile` is considered to escape when it's passed to `FPRINTF`, which is a function that uses the `va_list` macros. The parameter is passed as a macro argument to `va_start`, which we model with a `VarArgsStart` instruction. There's no special handling for that instruction in our alias/escape analysis, so it's assumed to make the parameter's address escape, which I think causes the value of the parameter to also escape.

That sounds plausible, but fixing that kind of issue could become a whack-a-mole game. That's why we disabled the escape analysis in the first place.

Out of the 38 alerts that disappear in https://jenkins.internal.semmle.com/job/Changes/job/CPP-Differences/939, do you see any that disappear for the right reasons?

**Comment by jbj** [comment]
This is postponed for now. If our use of IR changes before we have a full solution to https://github.com/github/codeql-c-analysis-team/issues/22, we can reconsider this PR.

**Comment by jbj** [comment]
Closing this PR for now.

**Pull request closed without merging**
