### PR TITLE
C++: Use range analysis-based `hasSize` predicate in `cpp/invalid-pointer-deref`

### PR DESCRIPTION
**Pull request by jketema**
This is copied from `cpp/overrun-write`.

Will need DCA experiment.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
LGTM once DCA is happy

**Comment by jketema** [comment]
DCA looks good to me, but has some missing alerts. The git one is an FP. The full alert comparison also shows differences on abseil windows. At first glance those also look like FPs to me, but I need to see the actual dataflow paths to be sure.

**Comment by jketema** [comment]
Abseil alerts that disappeared were FPs. I'm not completely sure why this PR fixes them though, as the allocation expression is of the form:
```cpp
  size_t length = 128 * 1024;
  char* data = new char[length];
```

**Comment by MathiasVP** [comment]
Hm yes, that's odd. I can't see why this PR would change these. At least the FPs are gone now 😅.

**Pull request merged**
