### PR TITLE
C#: Remove local identity flow steps

### PR DESCRIPTION
**Pull request by hvitved**
https://github.com/github/codeql/pull/12959 follow-up.

### CODE REVIEW

**Review by michaelnebel — APPROVED** [review]
Looks plausible to me!
Please note that I removed the consistency check for CIL code on https://github.com/github/codeql/pull/13124 because the reported locations changed (as this seemed to be machine dependent).
Should we consider to include the CIL inconsistencies as a part of the check again (now that we don't have any changes)?

**Comment by hvitved** [comment]
> Should we consider to include the CIL inconsistencies as a part of the check again (now that we don't have any changes)?

Yes, we should simply revert that change to the consistency checks.

**Review by michaelnebel — APPROVED** [review]
Looks good.
You can consider to delete the empty files as well.

**Comment by hvitved** [comment]
> You can consider to delete the empty files as well.

Huh, I am sure those files are deleted. Not sure why the UI says they are empty.

**Pull request merged**
