### PR TITLE
Swift: Remove beta label

### PR DESCRIPTION
**Pull request by MathiasVP**

### CODE REVIEW

**Review by geoffw0 — CHANGES_REQUESTED** [review]
.

**Comment by geoffw0** [comment]
It's time I gave this a proper review:
 - I'm happy that you've removed all the Swift beta references from this repository correctly.
   - there's a discussion going on elsewhere about references that may exist in other repos.
 - I've made a PR onto this PR to add a change note, using the same wording as for Kotlin.

**Review by geoffw0 — APPROVED** [review]
LGTM and can come out of draft.  I'm currently in a conversation about when we want to merge this / what else might need to be merged at the same time.

**Review by felicitymay — APPROVED** [review]
Thanks for this PR. The changes look great 👍🏻

As for the similar PR for Kotlin GA, my only question is whether or not we want to merge into main and publish these changes with the next release of CodeQL CLI, or whether we want to publish the changes sooner (in which case merging into the 2.18.0 branch would make publication simpler).

**Review by geoffw0 — APPROVED** [review]

**Pull request merged**
