### PR TITLE
Generalization of FlowAfterFree

### PR DESCRIPTION
**Pull request by bdrodes**
Updating FlowAfterFree to not enforce dominance of source/sink, now enforced by the instantiations of this module.

### CODE REVIEW

**Comment by bdrodes** [comment]
@MathiasVP , I have some concerns in how I'm doing dominance checks, in that they are not optimized with any special annotations. I wonder if at scale this means dominance would be computed universally before joined with source/sinks.

**Comment by MathiasVP** [comment]
> @MathiasVP , I have some concerns in how I'm doing dominance checks, in that they are not optimized with any special annotations. I wonder if at scale this means dominance would be computed universally before joined with source/sinks.

Yes, I don't the approach you have here is how we should do it. With this approach we're:
1. Probably materializing both `sinkStrictlyPostDominatesSource` and `sourceStrictlyDominatesSink` (unless the compiler inlines them) - and they're both pretty large predicates.
2. Generating a lot of source/sink pairs before restricting it to the sinks that dominate the source.

**Comment by MathiasVP** [comment]
I've opened https://github.com/microsoft/codeql/pull/39 for you to take a look at.

**Comment by bdrodes** [comment]
> I've opened [microsoft#39](https://github.com/microsoft/codeql/pull/39) for you to take a look at.

I've accepted this. Let's role with it!

**Comment by bdrodes** [comment]
Note. I added missing deallocation functions as part of this PR just now, but for some reason it is showing the entire file changed rather than a few of the definitions for deallocation were added to.

**Review by MathiasVP — COMMENTED** [review]
The changes LGTM! Now we just need a happy DCA run and we can merge this 😄

**Comment by MathiasVP** [comment]
I _think_ I've fixed the CI errors here: https://github.com/microsoft/codeql/pull/40. Basically, CI checks that everything "reachable" from a query file has QLDocs added to it. The solution to that CI check failing is always to either:
- Add more QLDoc to public stuff, or
- Make the accidental public stuff private

And in https://github.com/microsoft/codeql/pull/40 I've done a bit of both.

**Review by MathiasVP — APPROVED** [review]

**Pull request merged**
