### PR TITLE
Merge docs updates from codeql-cli-2.11.5 into main

### PR DESCRIPTION
**Pull request by jf205**
This PR merges the codeql-cli-2.11.5 branch into main so that changes from https://github.com/github/codeql/pull/11554 will be present when we create the next CodeQL CLI release branch.

### CODE REVIEW

**Comment by jketema** [comment]
Should the mergeback go via cli-2.11.6?

**Review by felicitymay — APPROVED** [review]
Thanks for opening this pull request to make sure that this docs change is available for the next CodeQL CLI release branch.

Once we've checked on @jketema's question, this looks ready to merge.

**Comment by jf205** [comment]
>Should the mergeback go via cli-2.11.6?

@jketema good question. I guess it should. I'll open some new PRs for that.

**Comment by smowton** [comment]
I'm surprised there were outstanding changes not merged in by https://github.com/github/codeql/pull/11605 followed by https://github.com/github/codeql/pull/11612 ?

**Comment by jf205** [comment]
@smowton https://github.com/github/codeql/pull/11554 was only merged this morning, so isn't covered by either of those mergebacks. I think this makes sense.

**Comment by smowton** [comment]
OK makes sense -- in that case recommend merging -> 2.11.6 -> rc/3.8 -> main

**Pull request closed without merging**
