### PR TITLE
Model summary for `org.springframework.core.io.getInputStream` methods

### PR DESCRIPTION
**Pull request by mbaluda**
Model summary for `getInputStream` methods

#### All query authors

- [x] A change note is added if necessary. See [the documentation](https://github.com/github/codeql/blob/main/docs/change-notes.md) in this repository.
- [x] All new queries have appropriate `.qhelp`. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-help-style-guide.md) in this repository.
- [x] QL tests are added if necessary. See [Testing custom queries](https://docs.github.com/en/code-security/codeql-cli/using-the-advanced-functionality-of-the-codeql-cli/testing-custom-queries) in the GitHub documentation.
- [x] New and changed queries have correct query metadata. See [the documentation](https://github.com/github/codeql/blob/main/docs/query-metadata-style-guide.md) in this repository.

#### Internal query authors only

- [x] Autofixes generated based on these changes are valid, only needed if this PR makes significant changes to `.ql`, `.qll`, or `.qhelp` files. See [the documentation](https://github.com/github/codeql-team/blob/main/docs/best-practices/validating-autofix-for-query-changes.md) (internal access required).
- [ ] Changes are validated [at scale](https://github.com/github/codeql-dca/) (internal access required).
- [x] Adding a new query? Consider also [adding the query to autofix](https://github.com/github/codeml-autofix/blob/main/docs/updating-query-support.md#adding-a-new-query-to-the-query-suite).

### CODE REVIEW

**Review by egregius313 — COMMENTED** [review]
Is there a reason to model individual implementations and not the interface [`InputStreamSource::getInputStream`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/InputStreamSource.html)?

As far as I can tell, the implementations of the interface tend to be other resources where this summary would make sense.

**Comment by egregius313** [comment]
> - [x] A change note is added if necessary. See [the documentation](https://github.com/github/codeql/blob/main/docs/change-notes.md) in this repository.

@mbaluda there's no change note included in the PR. Please either commit it or add https://github.com/github/codeql/labels/no-change-note-required. We usually add change notes for new models.

**Review by smowton — APPROVED** [review]
LGTM!

**Review by egregius313 — APPROVED** [review]
LGTM

**Pull request merged**
