### PR TITLE
JS: add printAst.ql support for regular expressions

### PR DESCRIPTION
**Pull request by erik-krogh**
I think the Python team could use `printAst.ql` support for regular expressions (to debug a regexp parser).  

So I implemented it for JavaScript first.

### CODE REVIEW

**Review by yoff — APPROVED** [review]
LGTM

**Comment by erik-krogh** [comment]
I was a little fast in publishing this PR. 
The filter to determine which regular expression belonged where was missing.

**Comment by korn17122544** [comment]
เมื่อ จ. 10 พ.ค. 2564 เวลา 19:52 Erik Krogh Kristensen <
***@***.***> เขียนว่า:

**Review by yoff — APPROVED** [review]
LGTM

**Pull request merged**
