### PR TITLE
Swift: Models for the String class

### PR DESCRIPTION
**Pull request by geoffw0**
Create tests and models for the Swift `String` class + `StringProtocol` protocol, and partial models of `Collection`, `Sequence` and others where we touch on them.  The aim here is to be quite thorough because `String` is used a lot, and often with tainted data.  Due to time constraints there is not quite a perfect 1:1 correspondence between models and tests, and there are plenty of holes in the actual models - more work/improvements planned as follow-up.

### CODE REVIEW

**Comment by geoffw0** [comment]
DCA:
 - one new alert, for `swift/cleartext-transmission`! :tada:
   - It can be viewed in the DCA run's `alert-comparison.md`.
   - the 'password' looks to be a token of some form rather than an actual password, other than that the result looks good and the taint flow in particular looks excellent.
 - can't see any performance issues.

**Review by jketema — APPROVED** [review]
LGTM (I did not check every MaD row and new test case in detail).

**Comment by geoffw0** [comment]
> LGTM (I did not check every MaD row and new test case in detail).

Thanks for reviewing.  I think not checking every row is reasonable - it would take a long time, and fatigue would make the process quite error prone anyway.

If there is an error somewhere, by far the most likely outcome is that row just doesn't match anything in real world data - so we'd be in the same situation as if that row hadn't been added in the first place.  The mistake would have to have slipped through the test coverage as well.

During development the tests did reveal a number of issues, mainly where a method I thought was in `String` was in fact declared in one of the protocols it inherits from (`StringProtocol`, `Collection` etc).

**Comment by jketema** [comment]
> During development the tests did reveal a number of issues, mainly where a method I thought was in `String` was in fact declared in one of the protocols it inherits from (`StringProtocol`, `Collection` etc).

Yeah, that was indeed the impression I was getting from the PR.

**Comment by geoffw0** [comment]
Right, merging this now.  There are several follow-up tasks, so if anybody has any further comments / suggestions I am listening and happy to address them as part of that follow-up work.

**Pull request merged**
