### PR TITLE
[CSharp] AWS Lambda Modelling

### PR DESCRIPTION
**Pull request by GeekMasher**
I have created some initial modelling and tests for AWS Lambda's using the data extensions.

The stubs of code for AWS Lambda SDK were not auto-generated but pretty much copied from the source code. I would like to in auto generate this like other frameworks but I wasn't sure how this was done.

https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src

This PR requires #13093 as the log injection sinks use the new `log-injection` kind versus `logging`.

### CODE REVIEW

**Comment by GeekMasher** [comment]
This PR seems to be failing due to the models as data validation checks which haven't been merged yet

**Comment by tamasvajk** [comment]
> The stubs of code for AWS Lambda SDK were not auto-generated but pretty much copied from the source code. I would like to in auto generate this like other frameworks but I wasn't sure how this was done.

You can autogenerate the stubs with the scripts in https://github.com/github/codeql/tree/main/csharp/ql/src/Stubs.

For example the below would generate the `Amazon.Lambda.APIGatewayEvents.APIGatewayHttpApiV2ProxyRequest` class and friends:
```
python make_stubs_nuget.py Amazon.Lambda.APIGatewayEvents
```

**Comment by GeekMasher** [comment]
@tamasvajk Ahhh, thanks for sharing this! I will definately be using it going forward

**Comment by michaelnebel** [comment]
@GeekMasher : Is this WIP or are you awaiting review?

**Comment by GeekMasher** [comment]
@michaelnebel Sorry for the delay, yes this was intended for review

**Comment by michaelnebel** [comment]
@GeekMasher : Since the last review, a new stub generator has been implemented. There has also been some changes to the location of framework files. I have taken the liberty to rebase the PR, auto generate the relevant stubs and update the test and options file.
I will review the models tomorrow and if they look good we can start a DCA run as well.
Is that ok with you?

**Comment by michaelnebel** [comment]
The sink models look good to me!
It looks like there are some properties for the class `APIGatewayHttpApiV2ProxyRequest` which are not considered sources - is this considered intentional?

Will start a DCA run.

**Review by michaelnebel — APPROVED** [review]
Looks good to me!
Lets wait and see what DCA says before merging.

**Comment by michaelnebel** [comment]
DCA looks good.

**Review by michaelnebel — APPROVED** [review]
Looks good to me.
@GeekMasher : Merging now to avoid the PR getting stale.

**Pull request merged**
