### PR TITLE
Merge `rc/3.7` into `main`

### PR DESCRIPTION
**Pull request by hvitved**

### CODE REVIEW

**Comment by hvitved** [comment]
@jf205 are you able to resolve the merge conflicts, please?

**Comment by jf205** [comment]
@aeisenberg these look like your docs changes -- please could you take a look at the conflicts?

**Comment by aeisenberg** [comment]
@hvitved and @jf205 Can you look at this PR? https://github.com/github/codeql/pull/10496

I can't resolve the conflicts in the `rc/3.7` branch since it is protected.

**Comment by aeisenberg** [comment]
This PR is superseded by https://github.com/github/codeql/pull/10496.

**Pull request closed without merging**
