### PR TITLE
Swift: Workaround for TypeDecl.getFullName issue.

### PR DESCRIPTION
**Pull request by geoffw0**
Workaround for an issue where databases can contain `ExtensionDecl`s that extend multiple `TypeDecl`s (i.e. a database inconsistency), ultimately sometimes forming an infinite loop in `TypeDecl.getFullName`.  This fix makes the QL more robust, allowing evaluation to complete, though the database inconsistencies are still present.

### CODE REVIEW

**Review by MathiasVP — APPROVED** [review]
The changes LGTM, but I'd like to see a DCA run before we merge!

**Comment by geoffw0** [comment]
Yes, I forgot to start one last week ... running it now.

**Comment by geoffw0** [comment]
Hmm, the DCA run fell over quite badly.  Possibly I didn't update DCA locally first due to some complications.  Retrying... 🤞

**Comment by geoffw0** [comment]
The second DCA run succeeded.  The only wobbles are stage timings (in mixed directions), and overall analysis time is fine.

Merging...

**Pull request merged**
